### ISSUE TITLE
对 map 一顿操作后，旋转会在鼠标松开的那一刻闪回之前的位置

### ISSUE THREAD

**Issue by liuxinqiong** [maptalks/maptalks.js#1000]
**maptalks's version and what browser you use?**
----
v0.45.0

**Issue description**
----
如题

**Please provide a reproduction URL (on any jsfiddle like site)**
----
maptalks.three 的 building 的 demo 就可以玩出来

**Comment by fuzhenn** [comment]
should be also fixed with #1002
