### ISSUE TITLE
maptalks.three  和 three.js 的关系

### ISSUE THREAD

**Issue by luosijie** [maptalks/maptalks.js#1001]
请教一下 maptalks.three 和 three.js 是什么关系：
在 maptalks.ThreeLayer 中，可以使用原生 threejs的完整功能吗？
因为我想修改 threejs 模型的一些样式，比如加上模型边框线什么的。

我发现用推荐的方法可以正常渲染
```
 const geometry = maptalks.GeoJSON.toGeometry(feature);
 const mesh = this.toExtrudeMesh(geometry, extrudeHeight, material, extrudeHeight);
scene.add(mesh);
```

用three.js 的原生方法
1. 根据coordinates 创建 shape
2. 用 shape 挤出ExtrudeGeometry
3. 添加到场景中

模型就没有渲染

**Comment by fuzhenn** [comment]
maptalks.three是只是一个工具图层，帮助你用three.js创建三维可视化，threeLayer上定义的方法都是方便你创建mesh的工具方法，你可以参考他们用自己的方法来实现自己的逻辑也完全没有问题。
