### ISSUE TITLE
geojson 渲染超出视图时会被裁剪

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#1003]
**maptalks's version and what browser you use?**
----
maptalks：1.0.0-alpha.4
**Issue description**
----
![image](https://user-images.githubusercontent.com/19517451/65013984-bc853100-d94f-11e9-9696-04d4f3d32007.png)

![image](https://user-images.githubusercontent.com/19517451/65014013-d32b8800-d94f-11e9-80a3-22cb35501fe8.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
This is an expected behavior, to reduce data to draw and to improve performance.
