### ISSUE TITLE
是否支持geojson-vt

### ISSUE THREAD

**Issue by unclemiki** [maptalks/maptalks.js#1007]
加载大量数据的geojson时是否能和geojson-vt一起使用对geojson进行切片，并且支持自定义的空间参考，我参考了leaflet中使用geojson-vt的例子，在maptalks中geojson-vt对geojson进行切片，在4326和3857空间参考都能很好的工作，但是在baidu地图上无法正常工作，能否给我一些提示？
`function projectX(x, crs) {
    if(crs == 'EPSG:4326'){
        return (x / 180) + 1;
    }else{
        return x / 360 + 0.5;
    }
}

function projectY(y, crs) {
    if(crs == 'EPSG:4326'){
        y = -(y / 180) + 0.5
        y = y < 0 ? 0 : y > 1 ? 1 : y;
        return y;
    }else{
        var sin = Math.sin(y * Math.PI / 180);
        var y2 = 0.5 - 0.25 * Math.log((1 + sin) / (1 - sin)) / Math.PI;
        return y2 < 0 ? 0 : y2 > 1 ? 1 : y2;
    }
}`

**Comment by fuzhenn** [comment]
这个功能需要改写geojson-vt本身来支持baidu投影系统，请尝试联系geojson-vt库的作者。
