### ISSUE TITLE
enhancement: addGeometry添加自适应视图动画

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#1010]
**maptalks's version and what browser you use?**
----
"maptalks": "^1.0.0-alpha.4"

**Issue description**
----
https://maptalks.org/maptalks.js/api/0.x/VectorLayer.html#addGeometry
https://github.com/maptalks/maptalks.js/blob/master/src/layer/OverlayLayer.js#L238

addGeometry添加自适应视图动画；

```js
const extent = getExtent(data);
          const ext = new Extent(...extent);
          const z = this.$map.getFitZoom(ext);
          // map.setCenterAndZoom(extent.getCenter(), z);
          this.$map.animateTo({
            zoom: z,
            center: ext.getCenter(),
          }, {
            duration: 1000,
            easing: 'linear',
          });
```

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
👍 介意提个PR给我吗？可以判断一下fitView参数如果是对象，则认为是animateTo的动画参数，则用动画的方式来移图。

**Comment by sakitam-fdd** [comment]
@fuzhenn OK.
