### ISSUE TITLE
three绘制多边形，地图旋转是多边形出现抖动

### ISSUE THREAD

**Issue by wormAp** [maptalks/maptalks.js#1021]
**maptalks's version and what browser you use?**
----
v0.45.1

**Issue description**
----
结合maptalks.three和three 绘制多边形，地图放大，旋转多边形出现抖动

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
多边形是如何绘制的？
要避免抖动，关键是端点坐标的取值范围不能太大，目前three.js中是通过计算图形中心点，在端点中存储与中心点的相对坐标来解决的。
https://github.com/maptalks/maptalks.three/blob/master/index.js#L137
