### ISSUE TITLE
zoom 不能超过20吗？

### ISSUE THREAD

**Issue by chengdong1995** [maptalks/maptalks.js#1022]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/KKKmjxR?editors=0010

**Comment by lettucebo** [comment]
reference #971

**Comment by fuzhenn** [comment]
Thanks guys!
