### ISSUE TITLE
对polygon使用textPlacement，遮挡 和 选取的几何中心可能不在polygon上

### ISSUE THREAD

**Issue by leecheck** [maptalks/maptalks.js#1023]
**maptalks's version and what browser you use?**
----
0.45.1 chrome

**Issue description**
----
对polygon使用textPlacement，一是会有遮挡问题 二是选取的放置text的位置，取的几何中心，但可能不在polygon上（比如一个中空的polygon）
![image](https://user-images.githubusercontent.com/7836307/67952612-87dfe700-fc28-11e9-9364-5fc9aac71abf.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以用mapbox的[polylabel](https://github.com/mapbox/polylabel) 库来手动计算label的位置
