### ISSUE TITLE
关于maptalks版本问题

### ISSUE THREAD

**Issue by WANGJUEYA** [maptalks/maptalks.js#1025]
请问下vue发布版本大概多久更新一次? 
vue环境下最新版和稳定版有区分么?vue是否只发布稳定版?
期待回复, 谢谢

**Comment by fuzhenn** [comment]
maptalks目前没有区分最新版和稳定版，发布的都是稳定版。

maptalks的稳定版标准：
* 所有的测试用例通过
* 插件也都能正常工作
* api都是向下兼容的
