### ISSUE TITLE
移动端慢慢滑动会卡死

### ISSUE THREAD

**Issue by adevin** [maptalks/maptalks.js#1026]
但用map.animateTo  地图还是会动  但是用手拖动 是不能了。

**Comment by fuzhenn** [comment]
该问题在多个场景下都没有重现，暂时关闭

**Comment by adevin** [comment]
> 该问题在多个场景下都没有重现，暂时关闭

http://39.100.80.211/mobile/#/map 可以试试这个

**Comment by adevin** [comment]
@fuzhenn http://39.100.80.211/mobile/#/map 可以试试这个
