### ISSUE TITLE
加载自定义marker图标会提示no img found for http://localhost:3000/images/icon.png

### ISSUE THREAD

**Issue by guard-wen** [maptalks/maptalks.js#1027]
**maptalks's version and what browser you use?**
----
version:v0.45.1
browser:Chrome

**Issue description**
----
加载自定义marker图标数组，部分图标会提示no img found for http://localhost:3000/images/icon.png,，结果无法显示部分marker图标。再加载一次又全部正常显示了

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
感谢提issue，能否提供一个重现代码？

**Comment by guard-wen** [comment]
你好。十分感谢你的回复。
出现问题的场景是这个样子的。
网页加载，第一次批量创建一百多个marker图标可以正常显示。第二次再批量创建18个图标就会出现部分图标无法显示。
地图中显示18个marker图标。有十七个能显示，一个不能显示。图片保存在本地路径，访问路径是正确的。


测试多次后发现规律是：页面加载后第一批次创建marker就可以正常显示，再第二批次创建marker则部分图标无法显示


下图为打印出marker对象






图标无法显示时控制台会提示no img found for ...
源码：





浏览器版本
Google Chrome&nbsp;
版本 78.0.3904.97（正式版本） （64 位）





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fu Zhen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 晚上6:16
收件人:&nbsp;"maptalks/maptalks.js"<maptalks.js@noreply.github.com&gt;;
抄送:&nbsp;"ｇuard＂"<497823955@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [maptalks/maptalks.js] 加载自定义marker图标会提示no img found for http://localhost:3000/images/icon.png (#1027)




感谢提issue，能否提供一个重现代码？

**Comment by fuzhenn** [comment]
谢谢回复，请问能否用codepen写一个重现代码发给我？
光凭你的描述，我暂时没办法重现出这个问题。

**Comment by ryry886** [comment]
这个问题我也遇到了 ，定位到这个函数
      _proto._getImage = function _getImage(resources) {
        var img = !resources ? null : resources.getImage([this.style['markerFile'], this.style['markerWidth'], this.style['markerHeight']]);
        return img;
      };
返回了null
 我在这里加了个判断，如果找不到图片，就创建一个。暂时解决了这个问题
      _proto._getImage = function _getImage(resources) {
        var img = !resources ? null : resources.getImage([this.style['markerFile'], this.style['markerWidth'], this.style['markerHeight']]);
        if(!img)
        {
          var image = new Image();
          image.src = this.style['markerFile'];
  
          if (resources) {
            resources.addResource(this.style['markerFile'], image);
          }
  
          return image;
        }
        return img;
      };

**Comment by fuzhenn** [comment]
感谢补充 @ryry886 
实现一个重现代码麻不麻烦？我尝试重现过，但目前还是无法重新这个问题。

**Comment by ryry886** [comment]
@fuzhenn    抱歉 ，之前一直在忙项目，把这个事情给耽搁了。 今天闲下来，我重新梳理了一下，发现问题 出现在  之前的视角跳转，如果屏蔽掉这个动画，就不会出现找不到图片的问题。 
整理的测试代码已经写好了。先点击一个marker，是正常的展示其关联的两个marker。但是点击第二个的时候就会 出现 no img found forXXXXXXXXX

https://codepen.io/luckryan/pen/eYpdzvB

**Comment by fuzhenn** [comment]
这个问题应该和 #1129 的成因是相同的，已经解决。
