### ISSUE TITLE
关于 点的沿线动画 平移地图发生偏移的问题

### ISSUE THREAD

**Issue by WANGJUEYA** [maptalks/maptalks.js#1028]
**maptalks's version and what browser you use?**
----
^0.45.1 
chrome

**Issue description**
----
![image](https://user-images.githubusercontent.com/49236180/68766678-41dc4780-065a-11ea-8ae8-37a18c30b6b5.png)
![image](https://user-images.githubusercontent.com/49236180/68766614-296c2d00-065a-11ea-9da6-f7775f3222da.png)
重现方式[在地图有pitch角度时]
1: 在动画执行过程中平移地图底图
2: this.player.pause();this.player.play();两条语句执行后

请问此问题有比较好的解决方案么? 期待您的回复，谢谢
**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://maptalks.org/examples/cn/animation/move-along/#animation_move-along

**Comment by fuzhenn** [comment]
确实有问题，看上去是动画和鼠标同时在移动地图发生了冲突导致的
