### ISSUE TITLE
baidu 的图 maxzoom只能到19

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#1031]
**maptalks's version and what browser you use?**
----

**Issue description**
----

即使设置了maxZoom=20 也只能放大到19
https://codepen.io/deyihu/pen/JjjmJyZ?editors=1010

另外相同层级下，百度地图的缩放比例总比其他图小一圈
https://codepen.io/deyihu/full/MWWPoQo

另外瓦片如果加载不到404，tilelayer有设置默认图片的配置参数吗？类似这样子 
https://codepen.io/deyihu/full/KKKmjxR

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
1. 可以通过修改SpatialReference来支持更大的级别： [示例](https://codepen.io/fuzhenn-the-decoder/pen/ZEEqJzx)，但百度底图最高也就支持到19级
2. 这个是百度地图的问题
3. 有这个设置，叫errorTileUrl

**Comment by deyihu** [comment]
@fuzhenn 
我刚才看了一下

https://github.com/maptalks/maptalks.js/blob/3c201af51153e4645b43814721082f69f46efb2e/src/map/spatial-reference/SpatialReference.js#L41

baidu和4326内部默认都支持到19，而不是像3857默认支持到20，**我觉的他们应该统一，当然我不知道是否其他的考虑因素这样设计的**

另外 百度地图有的图源是支持到20的
https://codepen.io/deyihu/pen/JjjmJyZ?editors=0010


我在使用时，我的图源都是达到20的，切换SpatialReference时，切换到baidu时，突然地图就不能放大到最大了

**Comment by fuzhenn** [comment]
主要是因为百度的默认底图只到19级，所以当初就把baidu的默认最大级别设置到了19
