### ISSUE TITLE
希望有可以在具有atitude的poylgon上贴imaglayer

### ISSUE THREAD

**Issue by houzip** [maptalks/maptalks.js#1036]
https://segmentfault.com/a/1190000017488716
我在这个帖子上面看到这种伪3d效果   希望能在那块灰色的区域上“拔高” 贴个imagelayer
形成立体效果

**Comment by deyihu** [comment]
https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/YEWU/extrudepolygon_topimage.html
