### ISSUE TITLE
请问bing的投影底图如何实现呢？

### ISSUE THREAD

**Issue by Yuwen2019** [maptalks/maptalks.js#1037]
已知bing地图的瓦片投影的实现需要把xy坐标转换为四叉树的字符串QuadKeys。

困惑点在于通过什么样的方式把xy轴转换成quadKeys传入{quadKeys}中
http://r1.tiles.ditu.live.com/tiles/r{quadKeys}.png?g=100&mkt=zh-cn

请问如何通过转换实现显示出Bing地图的底图呢？是否需要通过扩展方法来实现。此问题困扰我已久，万分感谢大神指点迷津。

**Comment by fuzhenn** [comment]
TileLayer的urlTemplate支持用function来实现你的需求。
```js
new TileLayer(id, {
  urlTemplate: (x, y, z, domain) => {
     //通过x,y,z计算quadkey和url
     const quadKey = ?;
     return `http://${domain}.tiles.ditu.live.com/tiles/r${quadKeys}.png?g=100&mkt=zh-cn`;
  }
);
```

**Comment by Yuwen2019** [comment]
非常感谢大神，问题已解决
