### ISSUE TITLE
After limited map's extend, dragging and moving the map quickly several times will make limition loseing it's effectiveness

### ISSUE THREAD

**Issue by CyfforPro** [maptalks/maptalks.js#1038]
**maptalks's version and what browser you use?**
----
maptalks: 0.45.1
chrome: 78.0.3904.108 (64 bit)

**Issue description**
----
First, I limited map's extend as the [demo()](https://maptalks.org/examples/en/map/limit-extent/#map_limit-extent) did, then I draged and moved the map quickly several times, something wrong happened — the map can't go back to it's limited extend unless I zooming it again.

按官网demo设置地图边界，快速拖拽几次会让地图无法回到已设定的边界，奇怪的是，缩放一下后就又好了

![record](https://user-images.githubusercontent.com/19570481/69947890-940ddb80-1529-11ea-942b-5ab3fa8cfaf7.gif)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://maptalks.org/examples/en/map/limit-extent/#map_limit-extent

**Comment by fuzhenn** [comment]
fixed by #1065
