### ISSUE TITLE
enhancement: 图层添加`hitDetect: boolean`禁用或者开启鼠标检测

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#1040]
**maptalks's version and what browser you use?**
----
maptalks: 0.46.0
Chrome: 78.0.3904.108

**Issue description**
----
目前 map 有一个统一参数 `hitDetect` 统一管理 [源码](https://github.com/maptalks/maptalks.js/blob/master/src/renderer/layer/CanvasRenderer.js#L282)，但是没有针对单个图层的参数控制，是否可能在图层配置上增加一个`hitDetect` 去针对具体图层配置（优先级低于全局配置）。

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
有道理，可以在Layer类的options上增加一个默认的hitDetect参数，帮忙提个PR给我吧

**Comment by sakitam-fdd** [comment]
@fuzhenn 好的😄
