### ISSUE TITLE
加载arcgis 切片在没有切片的时候显示没有切片

### ISSUE THREAD

**Issue by tpolong** [maptalks/maptalks.js#1044]
**maptalks's version and what browser **
----
maptalks v0.46.0,chrome

**Issue description**
----
arcgis 切片服务https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer其实没有大于等于12级的切片（虽然服务描述有到0级到15级），但是maptalks加载会有提示没有地图切片，
![image](https://user-images.githubusercontent.com/13393721/70843487-12de0f00-1e6e-11ea-86ea-d8446cffa7f8.png)

可以像arcgis js api那样限制不往没有切片的层级放大
![image](https://user-images.githubusercontent.com/13393721/70843480-fb068b00-1e6d-11ea-92c2-dc0bd82ac47b.png)
** reproduction URL **
----
https://maptalks.org/examples/en/tilelayer-projection/arcgis-tile/raw/index.html

**Comment by fuzhenn** [comment]
谢谢，考虑读取arcgis瓦片的minZoom和maxZoom，用户自己设置到TileLayer上后，就能实现你需要的功能了。

**Comment by tpolong** [comment]
收到，谢谢指导
