### ISSUE TITLE
domready event on infowindow

### ISSUE THREAD

**Issue by smolleyes** [maptalks/maptalks.js#1045]
**maptalks's version and what browser you use?**
----
0.46

**Issue description**
----
miss domready like event on infowindow attached/created

hi!

i try to add some react components to the infowindow thru ReactDOM.render, if i use the "showend" event it works but my component is rerendered every time, on google map we have this "domready" event on the infowindow, possible to add it ? (or mabe it s already possible..?)

thanks !

**Comment by fuzhenn** [comment]
sorry，I'm not familiar with react. 

But maptalks's infowindow's rendering is the same with other libs such as leaflet or openlayers. You may find solutions from their communities.

**Comment by smolleyes** [comment]
hi! ok i ll have a look 👍 

thanks
