### ISSUE TITLE
地图组件在55版本chrome中加大尺寸地图下绘制线严重失帧

### ISSUE THREAD

**Issue by liuxdi** [maptalks/maptalks.js#1046]
**maptalks's version and what browser you use?**
----
chrome:55.0.2883.87
maptalks: v 0.46.0
**Issue description**
----
在chrome55版本里，如果电脑是集显并且地图的尺寸较大（2560*1440）并且地图样式cssfillter传入参数时，绘制线时地图移动时会严重失帧。取消地图滤镜（cssfilter）、移动到线视野外时、换成独显、尺寸缩小使用这四种方法其中一种地图均恢复正常。
以上问题在chrome54-58浏览器环境中均可复现
**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/liudi123/pen/qBERNVY

**Comment by fuzhenn** [comment]
谢谢报issue！

chrome 79上并不明显，cssfilter是直接调用原生接口设置在canvas上的，性能下降应该是chrome本身造成的，很抱歉我对这个问题也没什么好的解决方案。
