### ISSUE TITLE
CancelEdit function

### ISSUE THREAD

**Issue by kibala145** [maptalks/maptalks.js#1047]
**maptalks's version and what browser you use?**
----
0.46.0

**Issue description**
----
It would be great to have "cancelEdit" function to move history pointer to the beginning. For now, we can use "undoEdit" n times to get the cancel edit result, but it doesn't seem to be the right way. Tell me if I'm wrong :)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Thanks for your issue!

Will add this for the next version. 👍
