### ISSUE TITLE
TODO: Remove image address to absolute address 

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#1051]
**maptalks's version and what browser you use?**
----

**Issue description**
----
移除内部ImageMarker的绝对地址转换，这种转换在现代前端框架Vue和React中会出现问题（Hash路由和History路由），对于地址的控制应该交由用户。

To Do List：
  - [ ] Add label and assign to milestone 
  - [x] Coding
  - [x] Test

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
coded by https://github.com/maptalks/maptalks.js/commit/213fc4609e1b525cf8e09c50e00d104586d26557
