### ISSUE TITLE
建议给TileLayer添加extent参数

### ISSUE THREAD

**Issue by Cxyushi** [maptalks/maptalks.js#1056]
**Issue description**
----
建议参照ol, 给TileLayer添加extent参数。超出四至的区域不再绘制，可提升效率。
  1. 小范围自切瓦片场景下，避免加载大量无效url降低绘制效率；
  2. 没必要请求缺省图片；
  3. 特定场景下，不同区域可以方便地绘制不同类型的图层；

![openlayer TileLayer extent 配置截图](https://user-images.githubusercontent.com/4743867/72240401-02f94c80-361f-11ea-972a-d59109bdc972.jpg)

**Comment by fuzhenn** [comment]
感谢提issue。
这个需求已经可以通过layer mask来支持([示例](https://maptalks.org/examples/cn/tilelayer-projection/tile-mask/#tilelayer-projection_tile-mask))，而且功能更强大一些，故先关闭此issue。
