### ISSUE TITLE
如果去拓展图形

### ISSUE THREAD

**Issue by chengdong1995** [maptalks/maptalks.js#1057]
**maptalks's version and what browser you use?**
----

**Issue description**
----
目前可以用自定义图层实现一些自定义图形  但这只是图层  能不能拓展跟点线面这样类似的图形

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
你可以参考曲线类，他们就是扩展了LineString来实现各种曲线的绘制的
* 曲线的抽象类 [Curve](https://github.com/maptalks/maptalks.js/blob/master/src/geometry/Curve.js)
* 圆弧类 [ArcCurve](https://github.com/maptalks/maptalks.js/blob/master/src/geometry/ArcCurve.js)
* 二次贝塞尔曲线 [QuadBezierCurve](https://github.com/maptalks/maptalks.js/blob/master/src/geometry/QuadBezierCurve.js)
