### ISSUE TITLE
绘制出区域位置面之后，不能直接设置区域名，得重新绘制一个文字图层吗？

### ISSUE THREAD

**Issue by dcbase** [maptalks/maptalks.js#1058]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以的，在区域面的symbol里直接设置text相关的属性，会自动在区域的重心按照给定属性绘制text。
