### ISSUE TITLE
'EPSG:4326'与'EPSG:3857'

### ISSUE THREAD

**Issue by luothink** [maptalks/maptalks.js#1060]
'EPSG:4326'是地理坐标系，一般是由经度、纬度来显示；'EPSG:3857'是投影坐标系 ，一般是以米为单位的平面坐标来显示，但是在官方给的例子中，不管是地理坐标系还是投影坐标系，map的center值都是以经、纬度来赋值，鼠标拾取的坐标也是经、纬度值。是否支持平面的投影坐标系？

**Comment by fuzhenn** [comment]
3857坐标(或其他投影坐标) 是没有地理意义的，除了用于投影绘制，并没有任何含义，现实中很少直接存取3857坐标，因此maptalks统一使用经纬度作为输入输出坐标。
maptalks能支持平面坐标系，示例中有用平面坐标绘制的足球场：
https://maptalks.org/examples/cn/tilelayer-projection/identity/#tilelayer-projection_identity




---原始邮件---
发件人: "Thinker-luo"<notifications@github.com&gt;
发送时间: 2020年1月16日(周四) 晚上10:28
收件人: "maptalks/maptalks.js"<maptalks.js@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [maptalks/maptalks.js] 'EPSG:4326'与'EPSG:3857' (#1060)



'EPSG:4326'是地理坐标系，一般是由经度、纬度来显示；'EPSG:3857'是投影坐标系 ，一般是以米为单位的平面坐标来显示，但是在官方给的例子中，不管是地理坐标系还是投影坐标系，map的center值都是以经、纬度来赋值，鼠标拾取的坐标也是经、纬度值。是否支持平面的投影坐标系？

**Comment by luothink** [comment]
其实目前我接触的项目中，大部分使用的都是投影坐标系。请问在加载投影坐标系的地图服务时，相应位置明明是平面坐标（投影坐标），最后输出的是经纬度，请问两坐标之间有无明确的对应关系，是否就是投影坐标对应的地理坐标？

**Comment by fuzhenn** [comment]
嗯是的，投影坐标和经纬度坐标是一一对应的。
他们之间的转换关系可以用如下代码获取：
```js
const projection = map.getProjection();
//经纬度转投影坐标
const prjCoord = projection.project(coord);
//投影坐标转经纬度
const coord = projection.unproject(prjCoord);
```

**Comment by fuzhenn** [comment]
此issue先关闭，如有后续问题可随时打开。
