### ISSUE TITLE
svg格式转换

### ISSUE THREAD

**Issue by chengdong1995** [maptalks/maptalks.js#1062]
**maptalks's version and what browser you use?**
----

**Issue description**
----
svg标注需要的格式是这样的[{transform:"matrix(1,0,0,1,200,200)", path:"M-122.304 84.285C-122.304 84.285 -122.203 86.179 -123.027 86.16C-123.851 86.141 -140.305 38.066 -160.833 40.309C-160.833 40.309 -143.05 32.956 -122.304 84.285z","stroke-width":"0.172",stroke:"#000",fill:"#fff"},{transform:"matrix(1,0,0,1,200,200)", path:"M-118.774 81.262C-118.774 81.262 -119.323 83.078 -120.092 82.779C-120.86 82.481 -119.977 31.675 -140.043 26.801C-140.043 26.801 -120.82 25.937 -118.774 81.262z","stroke-width":"0.172",stroke:"#000",fill:"#fff"}]
怎么将svg转换成这样的格式呢

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这个只能手工转换。
你可以看一下svg的path定义，就知道如何转换了。
另外这个格式是参考的raphaeljs，你也可以参考[它的文档](https://dmitrybaranovskiy.github.io/raphael/reference.html#Element.attr)
