### ISSUE TITLE
限制地图的拖动范围 后拖动频繁会导致灰屏幕

### ISSUE THREAD

**Issue by ghost** [maptalks/maptalks.js#1065]
版本：0.46.0
----

向一个方向连续快速的拖动，地图会显示灰色。
----
https://maptalks.org/examples/cn/map/limit-extent/#map_limit-extent
----

**Comment by fuzhenn** [comment]
谢谢报告issue，确实有这个问题

**Comment by yijiu986** [comment]
> 谢谢报告issue，确实有这个问题
这个大约什么时候可以修复，或者有什么好的办法解决吗?

**Comment by ghost** [comment]
请问一下，有没有其他替换方案吗？
