### ISSUE TITLE
maptalks doc run failed on windows 10

### ISSUE THREAD

**Issue by tpolong** [maptalks/maptalks.js#1066]
**maptalks's version and  browser  use**
----
maptalks@0.46.0
node v12.14.0,
npm  v6.13.4
chrome  79.0.3945.130
**Issue description**
----
maptalks doc run failed
![doc](https://user-images.githubusercontent.com/13393721/73170878-767c7d00-413a-11ea-9c3a-304e8cee0a0a.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by ForeverZhong** [comment]
一样欸

**Comment by deyihu** [comment]
整个工作流已经改了，以后有tsdoc了，所这个问题将不存在了
