### ISSUE TITLE
Events on Markers in repeat world

### ISSUE THREAD

**Issue by Ogator** [maptalks/maptalks.js#1068]
**maptalks's version and what browser you use?**
----

v0.46.0

**Issue description**
----
In the coordinate system that is implemented in maptalks events on geometries and UIMarkers that are drawn after 180 meridian mirror to the other side of the map. So, if we have a marker for example and we want to open up an InfoWindow on it, map will be bounced to the other side of the map. We want to display a ship track along Northern Sea Route with markers on it. Is it possible to do currently and if not, can it be implemented? See the gif attached.

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![maptalks-180](https://user-images.githubusercontent.com/18461123/73828922-25901700-4813-11ea-8a54-4272fb36bdeb.gif)

**Comment by fuzhenn** [comment]
Thanks for reporting. It sounds like a bug, could you kindly provide a reproduction demo on codepen? Thanks.
I'll fix it in days once confirmed.



---Original---

**Comment by Ogator** [comment]
Here is a reproduction [codepen](https://codepen.io/ogator/pen/ZEGEeWd)

**Comment by Ogator** [comment]
I think I have also found an example of this issue on your examples page.
[Distance Tool](https://maptalks.org/examples/en/interaction/distance-tool/#interaction_distance-tool):

![maptalks-distance-tool](https://user-images.githubusercontent.com/18461123/73916115-d22ecf00-48cd-11ea-9b8b-b2c40b88aeba.gif)

**Comment by fuzhenn** [comment]
Thanks for you repro, working on it now.
