### ISSUE TITLE
百度地图投影图层底图与高德地图投影的交通路况图层在同一个底图上无法吻合

### ISSUE THREAD

**Issue by wuhandamowang** [maptalks/maptalks.js#1070]
**maptalks's version and what browser you use?**
----
maptalks版本号：0.46.0
chrome版本号：79.0.3945.130

**Issue description**
----
付老师好：
参考载入不同投影得的TileLayer，
将百度地图瓦片图和高德地图交通路况瓦片图放到同一个图层中会错位，
![image](https://user-images.githubusercontent.com/10433294/74118631-336ce000-4bf7-11ea-9e0c-578bcd92659a.png)

codepen中注释掉的baseLayer为谷歌地图底图，可以与交通路况底图吻合

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/cc8023nn/pen/WNvbVgg

**Comment by fuzhenn** [comment]
这是因为高德与百度采用了两种投影导致的，目前也无法解决这个问题。

印象里百度也提供了交通路况瓦片，可以直接用百度的交通瓦片试试。

因为不是maptalks的bug，暂时先关闭，有问题可以随时再讨论。

**Comment by wuhandamowang** [comment]
是的，百度地图交通路况瓦片图效果不是很好，所以想使用高德地图来代替
谢谢付老师的回答
