### ISSUE TITLE
关于maptalks有时加载瓦片资源造成地图卡死的问题

### ISSUE THREAD

**Issue by SizerHsiung** [maptalks/maptalks.js#1073]
maptalks's version and what browser you use?
0.47.0

Issue description
@fuzhenn 您好，
问题一：我在使用maptalks时发现了一点问题。就是地图缩放层级频繁时会造成一定几率的地图卡死。在您的示例代码中也复现过。请问这个问题怎么解决呢？
问题二：baseLayer（就一个瓦片层）是用tileLayer性能比较好还是用GroupTileLayer性能比较好呢？
谢谢

**Comment by fuzhenn** [comment]
如果TileLayer数量很多，用GroupTileLayer的性能会好一些。如果只有一个图层则没什么区别。

能否更详细说明一下卡死的操作过程，另外请提供一下浏览器与操作系统信息。

**Comment by SizerHsiung** [comment]
初始化地图后，频繁的缩放滚轮（滑动滑鼠）偶现地图卡死状态。 Chrome浏览器（最新的)win7（32bit）

**Comment by SizerHsiung** [comment]
> 如果TileLayer数量很多，用GroupTileLayer的性能会好一些。如果只有一个图层则没什么区别。
> 
> 能否更详细说明一下卡死的操作过程，另外请提供一下浏览器与操作系统信息。

**Comment by fuzhenn** [comment]
我这里是64位的win10，还没有出现过缩放卡死。

你可以先试着初始化地图时，把seamlessZoom设为true，让地图设为无级缩放缩放模式，再测试一下是否还会出现卡死。

如果不会卡死，应该是缩放动画的问题。

**Comment by fuzhenn** [comment]
另外卡死的时候请看一下F12，是否有报错
我晚点也找时间试着重现一下

**Comment by SizerHsiung** [comment]
> 另外卡死的时候请看一下F12，是否有报错
> 我晚点也找时间试着重现一下

@fuzhenn 控制台网络请求会出现瓦片报401的错误，但是未卡死时也会有资源错误的情况

**Comment by fuzhenn** [comment]
我试着重现了一下，win 10 64位 + 32位chrome没有出现卡死，其他用户也暂时没有报告过这个问题。
不知道是不是与环境有关的特殊情况。

**Comment by SizerHsiung** [comment]
但是win7确实会有一定几率卡死。难道会和操作系统环境有关？

**Comment by fuzhenn** [comment]
嗯是的，因为这个问题无法重现，我这里无法对应。
先暂时关闭这个issue，如情况变得更普遍的时再来解决。
