### ISSUE TITLE
ImageLayer 大尺寸图片在ios无法加载正常

### ISSUE THREAD

**Issue by L-fingerprint** [maptalks/maptalks.js#1076]
**maptalks's version and what browser you use?**
----您好，我使用的是最新版本的maptalks 0.47，在ios12.4以上系统测试出这个问题（目前只测试了12.4以上）

**Issue description**
----我这边最开始使用2400 * 1820甚至更小尺寸，图片均加载正常，但是当我使用4800 * 3640的尺寸，图片就变成黑色的了，这个问题只在ios真机上出现这样的问题，但是在浏览器、安卓、微信开发者工具均正常。
 
      
**Please provide a reproduction URL (on any jsfiddle like site)**
----http://fingerprint.binzx.top

**Comment by fuzhenn** [comment]
这个应该是ios对纹理图片尺寸的支持有问题，可以先试试把ImageLayer的renderer改成canvas。
如果还不行，就只能把图片切小以后再载入了。

**Comment by fuzhenn** [comment]
closing as lack of activity

**Comment by L-fingerprint** [comment]
好的，谢谢，我这边采用的是把图片切小。
