### ISSUE TITLE
移动端浏览器拖拽zoomControl控件报错，导致页面假死，无法继续拖拽、放大等操作

### ISSUE THREAD

**Issue by QuietlyChan** [maptalks/maptalks.js#1077]
**maptalks's version and what browser you use?**
maptalks's version: v0.47.0
browser : google chrome
----

**Issue description**
----
手机chrome浏览器、微信浏览器，打开网页，网页已加如下标签
`<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">`

开启zoomControl控件，手指触碰滑块，会报如下错误
`Uncaught Error: Position is NaN`

导致页面无法继续使用手指操作。
另外，目前采取关闭zoomControl控件临时解决，不过在移动端浏览器依然会出现问题，手指旋转、放大、缩小地图依然会小概率出现失效问题，对移动端触摸拖拽很不友好，这个是事件bug嘛

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/QuietlyChan/pen/wvapwRq

**Comment by fuzhenn** [comment]
zoomControl确实没有考虑到移动端的操作。
另移动端小概率失效后，地图会不会冻结掉无法继续操作？

**Comment by QuietlyChan** [comment]
移动端也不是失效问题，就是在移动端正常加载地图后，手触操作会明显感觉卡顿、断断续续，感觉不灵的样子，跟主流地图手触操作相差甚远（双手指上下滑动、旋转滑动、拖拽、缩放），不会冻结掉地图，可以继续操作，不过每次刷新刚开始操作还挺正常，稍微频繁手触操作就有这问题

**Comment by fuzhenn** [comment]
收到，很惭愧我确实没有对移动端的交互认真做过优化，我会找个时间研究一下其他库的实现，对移动端做一下优化。

**Comment by QuietlyChan** [comment]
谢谢，我刚才又看了下，应该是Touch事件没处理好

**Comment by deyihu** [comment]
新版本的zoomControl控件已经删除了slider了，所以这个问题不存在了
