### ISSUE TITLE
markerPathWidth和markerPathHeight属性使用异常

### ISSUE THREAD

**Issue by chaogis** [maptalks/maptalks.js#1078]
**maptalks's version and what browser you use?**
----
version: v0.47.0
browser: chrome 版本 80.0.3987.132（正式版本） （64 位）

**Issue description**
----
使用markerPath定义marker样式（markerType设置为path），在定义markerPathWidth 和 markerPathHeight属性时，发现以下问题：
（1）不设置markerPathWidth markerPathHeight(即使用默认值), svg图标会显示出来
（2）手动设置markerPathWidth markerPathHeight为默认值80, svg图标不显示
（3）手动设置markerPathWidth markerPathHeight为大于100的值, svg图标显示异常

详细情况，请参考以下的复现代码。
**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/chaogis/pen/wvapmMP?editors=0010

**Comment by fuzhenn** [comment]
markerPathWidth和markerPathHeight是设置的svg viewBox里的width和height参数。（viewport的min-x和min-y是固定为0）
MDN上对svg viewBox的介绍：
https://developer.mozilla.org/zh-CN/docs/Web/SVG/Attribute/viewBox

你可以根据需要设置合适的viewport值。

鉴于这不是一个bug，先关闭了。
