### ISSUE TITLE
maptalks加载百度自定义地图，出现切片加载失败现象

### ISSUE THREAD

**Issue by chaogis** [maptalks/maptalks.js#1079]
**maptalks's version and what browser you use?**
----
version: v0.47.0
browser: chrome 版本 80.0.3987.132（正式版本） （64 位）

**Issue description**
----
maptalks加载百度自定义地图，经常出现切片加载失败的现象，在leaflet中不会出现这种问题，具体详见下面的示例。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/chaogis/pen/mdJXWaQ?editable=true

**Comment by fuzhenn** [comment]
这是因为瓦片会偶发性出现CORS验证失败。
把TileLayer的渲染模式从webgl改为canvas即可，canvas对CORS没有要求。
示例：
https://maptalks.org/examples/cn/tilelayer-projection/canvas-renderer/#tilelayer-projection_canvas-renderer
