### ISSUE TITLE
点沿线移动动画可以设置多个点吗

### ISSUE THREAD

**Issue by ljk226280** [maptalks/maptalks.js#1083]
**maptalks's version and what browser you use?**
----

**Issue description**
----
标记点可以沿多条设置好的线移动吗       拐弯     

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
请参考[RoutePlayer](https://github.com/maptalks/maptalks.routeplayer)插件
