### ISSUE TITLE
new extent 为什么会显示Extent未定义

### ISSUE THREAD

**Issue by ljk226280** [maptalks/maptalks.js#1084]
**maptalks's version and what browser you use?**
----
将var extent = new Extent(100, 10, 120, 20);
加入代码中   页面报错显示  Extent未定义

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
因为没有重现代码，不是很清楚你是怎么引用Extent的
如果是直接js方式应用，代码应该是：
```js
var extent = new maptalks.Extent(100, 10, 120, 20);
```
