### ISSUE TITLE
百度投影矢量数据加载问题

### ISSUE THREAD

**Issue by WindyNature** [maptalks/maptalks.js#1085]
使用百度投影，projzh中好像没有对纬度是75-90范围的数据处理，导致加载的矢量数据纬度值超出的范围都按照75°处理，超过这个范围的数据不能正常加载。

**Comment by fuzhenn** [comment]
我没有用过projzh, 方便的话请提供一个重现代码

**Comment by fuzhenn** [comment]
closing as lack of activity
