### ISSUE TITLE
maptalks的地图缩放等级能否更大？

### ISSUE THREAD

**Issue by bonapartecaesa** [maptalks/maptalks.js#1088]
maptalks的地图缩放等级能否更大
 zoom: 20
超过原有的20

**Comment by bonapartecaesa** [comment]
超过原有的20

**Comment by fuzhenn** [comment]
可以的，参考[自定义空间参考的例子](https://maptalks.org/examples/cn/tilelayer-projection/custom-tile/#tilelayer-projection_custom-tile), 为其中resolution增加更多级别就可以了。
