### ISSUE TITLE
点沿线运动  动画是怎样实现的 我需要修改哪里来找到准确的终点

### ISSUE THREAD

**Issue by ljk226280** [maptalks/maptalks.js#1089]
**maptalks's version and what browser you use?**
----

**Issue description**
----
我需要修改哪些参数，使终点到我想要的指定位置。

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以参考routeplayer插件的[源代码](https://github.com/maptalks/maptalks.routeplayer/blob/gh-pages/index.js)

这里主要用来维护bug和feature request，这个issue我就先关闭了，不便之处请谅解。
