### ISSUE TITLE
maptalks利用geojson数据添加新图层，如何使新图层增大缩放等级

### ISSUE THREAD

**Issue by bonapartecaesa** [maptalks/maptalks.js#1090]
**code：**
 var map = new maptalks.Map('map', {
        center: [115.45258640222,38.87145556222],
        zoom: 20,
        centerCross : true,
        baseLayer: new maptalks.TileLayer('base', {
            urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
            subdomains: ['a','b','c','d'],
            attribution: '&copy; <a href="http://osm.org">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/">CARTO</a>'
        }),
    });
 var data =｛.....｝；
 //将获取到的geojosn数据 转换为几何图形后，赋值给collection
      var collection = maptalks.GeoJSON.toGeometry(data);
      console.log(collection);
     //创建一个新的图层，名为vector ， 可使用getLayer获取该图层，或使用removeLayer删除该图层
     //将collection 添加到地图实例中
      var vectorLayer=new maptalks.VectorLayer('vector', collection).addTo(map);
**question：**
如何使vector看起来更大（已是zoom：20）
达到使下图的一个房间占满屏幕
![1](https://user-images.githubusercontent.com/49681435/77526756-0bdf8780-6ec6-11ea-9951-af3369c59773.png)

**Comment by fuzhenn** [comment]
换成用addGeometry方法添加数据，并把第二个参数fitView设成true即可
```js
var vectorLayer=new maptalks.VectorLayer('vector').addTo(map);
vectorLayer.addGeometry(collection, true);
```

**Comment by bonapartecaesa** [comment]
感谢回复

**Comment by bonapartecaesa** [comment]
您好像理解错了，我的意思是突破原有的缩放等级（现在已是20我想要达到更大最好是无限放大）
我使用您提供的方法，发现它的效果是使该图层的缩放等级达到原有的最大即20

**Comment by fuzhenn** [comment]
可以参考这个[自定义空间参考的示例](https://maptalks.org/examples/cn/tilelayer-projection/custom-tile/#tilelayer-projection_custom-tile)

你需要修改源代码里的resolution初始化逻辑，添加更多的resolution就能突破最大的20级限制了

**Comment by bonapartecaesa** [comment]
十分感谢
已解决
![1](https://user-images.githubusercontent.com/49681435/77603452-1abc4d80-6f4b-11ea-91f2-62d44ff336af.png)
