### ISSUE TITLE
能否创建多条等高线，并给上不同颜色；参考了绘制Marker的高度线,但是多条数据遍历时生成多个图层会导致卡顿  不知道有没有好点方法？？？

### ISSUE THREAD

**Issue by dcbase** [maptalks/maptalks.js#1091]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
如果是因为多图层卡顿，尽量把数据集中在一个图层上。
