### ISSUE TITLE
怎么绘制2维的mark

### ISSUE THREAD

**Issue by whlysu** [maptalks/maptalks.js#1092]
**maptalks's version and what browser you use?**
----
maptalks's 0.47.0

**Issue description**
----
我想在地图（VectorLayer）上绘制一个二维的图片（图片平躺在地图上），怎么绘制，现在绘制的都是立起来的

**Comment by deyihu** [comment]
you can use [uimarker](https://maptalks.org/maptalks.js/api/0.x/ui.UIMarker.html)

such as https://codepen.io/deyihu/full/xxGMEoY

**Comment by whlysu** [comment]
> you can use [uimarker](https://maptalks.org/maptalks.js/api/0.x/ui.UIMarker.html)
> 
> such as https://codepen.io/deyihu/full/xxGMEoY

Thank you very much
