### ISSUE TITLE
InfoWindow 高度增加時，以頂部為基準點拉長 InfoWindow，會蓋住 marker 本身

### ISSUE THREAD

**Issue by Wujidadi** [maptalks/maptalks.js#1095]
目前 InfoWindow 高度變化時，是以頂部為基準點變形，隨著高度減少或增加，來縮短或拉長 InfoWindow

但高度增加時，由頂部起拉長 InfoWindow，會導致本來位於 InfoWindow 下方的 marker 本身被蓋住（這裡假定 InfoWindow 相依於 marker，且 dy 設為負，使 InfoWindow 初始顯示在 marker 的上方）

不知道怎麼樣用文字簡單說明清楚，附圖好了

![before](https://user-images.githubusercontent.com/10349431/77993803-6d3aa700-735b-11ea-87ab-9302b61c42c4.png)![after](https://user-images.githubusercontent.com/10349431/77993816-73308800-735b-11ea-9006-78daf5d72417.png)

不知道有什麼方法可以將 InfoWindow 的基準點改為底部，高度增加時由底部向上延伸拉長？

又，InfoWindow 的動畫效果，皆以底部作為起始點，能不能改成以頂部為起始點？（彈出 InfoWindow 時由頂部彈出，隱藏時向頂部收回）

**Comment by fuzhenn** [comment]
创建InfoWindow时，在options里设置一个合适的height值就行了：
https://codepen.io/fuzhenn-the-decoder/pen/ExPNdbW

另外我的工作分支(fixes)上不用设置height也是可以的，虽然不晓得具体原因，等新版本发布后你可以测试一下。

我先关闭issue，有问题欢迎继续讨论。
