### ISSUE TITLE
支持zrerder吗

### ISSUE THREAD

**Issue by chengdong1995** [maptalks/maptalks.js#1096]
**maptalks's version and what browser you use?**
----

**Issue description**
----
支持zrerder吗

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
目前没有直接支持，但因为zrender是一个canvas接口的二次包装，你可以参考教程，基于zrender实现自己基于canvas的绘制逻辑
