### ISSUE TITLE
点击图标出现自定义infowindow出现后，再次点击地图时infowindow位置会发生变动

### ISSUE THREAD

**Issue by liulianfan** [maptalks/maptalks.js#1098]
**maptalks's version and what browser you use?**
----
v0.40.2

**Issue description**
----
如题

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
sorry，因为没有重现代码，我这里无法重现这个问题。
我先关闭这个issue，后续欢迎继续沟通。
