### ISSUE TITLE
百度底图瓦片加载bug

### ISSUE THREAD

**Issue by brucin** [MapTalks/MapTalks.js#11]
在上下拖动地图的时候，瓦片加载会错位。
//定制地图底图(Tile Layer)
        var tileLayer = new Z.TileLayer('tile', //底图id
        {
            /**
            * 坐标系类型：
            * web-mercator：谷歌, 必应,高德, 腾讯等地图服务采用的瓦片系统;
            * baidu: 百度标注。
            */
            tileInfo: 'baidu',
            /**
            * 在线底图服务url
            http://online1.map.bdimg.com/onlinelabel/?qt=tile&x=825&y=222&z=12&styles=pl&udt=20150902&scaler=2
            */
            urlTemplate: 'http://online{s}.map.bdimg.com/onlinelabel/?qt=tile&x={x}&y={y}&z={z}&styles=pl',
            /**
            *urlTemplate中占位符{s}所有数值的数组
            */
            subdomains:[0,1,2,3,4,5,6,7,8,9]
        });
        //设置底图图层
        mapObj.setBaseTileLayer(tileLayer);

**Comment by FuZhenn** [comment]
因为版权的缘故, 只在商业版中提供对百度地图的支持, 程序中没有包含百度地图的投影转换类.
不过我会检查一下这个bug

**Comment by FuZhenn** [comment]
TileConfig中的计算逻辑有问题, 已经修改

**Comment by brucin** [comment]
测试通过。
