### ISSUE TITLE
rotate方法是不是不生效？？我的用法例子是“this.绑定的元素.rotate(角度)”页面客户端不事实更新

### ISSUE THREAD

**Issue by dongshanfei** [maptalks/maptalks.js#1101]
**maptalks's version and what browser you use?**
---
谷歌 V0.47.0
**Issue description**
----rotate方法
我的写法是 this.绑定的当前点的ID.rotate(角度)
例如、我的点id是a、不断变化的角度是b
this.a.rotate(b)
页面不事实刷新

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
没有明白你的问题，能否提供一个重现代码？

**Comment by dongshanfei** [comment]
这个问题解决了 谢谢
但是还有一个问题就是 
我用drawTool在一个道路拓扑（就是一条马路，在页面上显示一条线）
 在这个道路拓扑的这条线上 画了一个长方形的区域
有没有属性可以求出来 这个长方形的区域和道路的交点

**Comment by dongshanfei** [comment]
一个道路（就是在页面上显示一条线）
然后再这个线上画一个长方形的区域
我想获取这个长方形与这个线的两端的两个交点
有没有什么办法 求教

**Comment by fuzhenn** [comment]
duplicate of #1104
