### ISSUE TITLE
如何获取两个图层的交点

### ISSUE THREAD

**Issue by dongshanfei** [maptalks/maptalks.js#1104]
**maptalks's version and what browser you use?**
----谷歌 V0.47

**Issue description**

我用drawTool在一个道路拓扑（就是一条马路，在页面上显示一条线）
在这个道路拓扑的这条线上 画了一个长方形的区域
有没有属性可以求出来 这个长方形的区域和道路的交点

具体的解释：一个道路（就是在页面上显示一条线）
然后再这个线上画一个长方形的区域
我想获取这个长方形与这个线的两端的两个交点
有没有什么办法 求教

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
你需要的是turf.js
https://turfjs.org/docs/#lineIntersect
