### ISSUE TITLE
DrawTool问题、绘制出来一个长方形 有没有属性可以知道四个角的坐标

### ISSUE THREAD

**Issue by dongshanfei** [maptalks/maptalks.js#1105]
**maptalks's version and what browser you use?**
---求解

DrawTool问题、绘制出来一个长方形 有没有属性可以知道四个角的坐标
**Issue description**
----DrawTool问题、绘制出来一个长方形 有没有属性可以知道四个角的坐标

**Please provide a reproduction URL (on any jsfiddle like site)**
----
DrawTool问题、绘制出来一个长方形 有没有属性可以知道四个角的坐标

**Comment by fuzhenn** [comment]
```js
rectangle.getShell()
```
