### ISSUE TITLE
地图用on注册的事件用off无法取消。

### ISSUE THREAD

**Issue by liangxuegang01** [maptalks/maptalks.js#1111]
**maptalks's version and what browser you use?**
----0.47.0

**Issue description**
----地图用on注册的事件用off无法取消

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
on和off的回调函数必须要一致才能取消，也许是因为你on和off时调用了不同的函数。
如果不能确认原因，请提供一个重现代码。

**Comment by Chaunceyctx** [comment]
我看了下源码，用了暴力法😂   直接delete this._eventMap[注册id]

**Comment by fuzhenn** [comment]
.. 这样做会有bug的噢
还是麻烦发个重现代码给我吧，如果有bug我也好修掉
