### ISSUE TITLE
new DrawTool按下按钮的时候 可以设置高亮吗？？

### ISSUE THREAD

**Issue by dongshanfei** [maptalks/maptalks.js#1113]
**maptalks's version and what browser you use?**
----
谷歌
**Issue description**
----new DrawTool按下按钮的时候 可以设置高亮吗？？
就是点击按钮的时候设置一个高亮

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by dongshanfei** [comment]
大哥、求解

**Comment by dongshanfei** [comment]
大哥 求解

**Comment by fuzhenn** [comment]
不是很明白你的需求，是否能提供一个截图？指出是哪里需要高亮？

**Comment by fuzhenn** [comment]
closing as lack of activity
