### ISSUE TITLE
QUESTION: map.setcenter with offset

### ISSUE THREAD

**Issue by smolleyes** [maptalks/maptalks.js#1114]
hi!

everything is in the title... when i click on a marker my map is centered correctly but my infowindow is cutted by half, i can trick the coordinates but don t like that and can t find an offset option.... any other possibility ?

actual result

![2020-05-01 15_56_44-Bâtexpert extranet - accueil - Brave](https://user-images.githubusercontent.com/200256/80810619-8b96fb00-8bc4-11ea-9b1f-c6fa57c773eb.png)

and want that

![2020-05-01 15_56_55-Bâtexpert extranet - accueil - Brave](https://user-images.githubusercontent.com/200256/80810757-c5680180-8bc4-11ea-863a-67f504997245.png)

thanks !

**Comment by fuzhenn** [comment]
you can simply:
```js
//any offset you need
const offset = new Coordinate(0, 0.03);
map.setCenter(center.add(offset));
```

**Comment by smolleyes** [comment]
hi

ok i see thanks but what "center" in center.add represent here? 

https://maptalks.org/maptalks.js/api/0.x/Coordinate.html

thanks

**Comment by smolleyes** [comment]
ok got it sorry

map.setCenter(map.getCenter().add(offset)); ...

thanks !
