### ISSUE TITLE
On map triggering events

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#1116]
**maptalks's version and what browser you use?**
----

**Issue description**
----

When the map is in the process of animation or moving, the mouse will intervene in the map to make it static, and the event such as moveend will not be triggered

当地图处于动画或者移动的过程（moving,animating），用鼠标干预地图使其静止，会不触发moveend,animateend等事件

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
* 我测试了一下，moveend是能正常抛的。
* 没有抛 `animateend` 事件是设计如此，动画中断时会改抛 `animateinterrupted` 事件

先关闭issue，有后续问题我们再继续讨论
