### ISSUE TITLE
Rectangle 当长和宽比较大时，显示出来的矩形歪的

### ISSUE THREAD

**Issue by xiexueze** [maptalks/maptalks.js#1118]
var rectangle = new maptalks.Rectangle([105.9090743,38.1102297], 507819, 401803, {
        symbol: {
          lineColor: '#34495e',
          lineWidth: 2,
          polygonFill: '#34495e',
          polygonOpacity: 0.4
        }
      });
![image](https://user-images.githubusercontent.com/2314196/81053783-39254980-8ef8-11ea-8dbe-eafd38ab96b4.png)

**Comment by fuzhenn** [comment]
这个是正常的，因为投影的缘故，在不同纬度上，相同距离对应的像素长度不一样
