### ISSUE TITLE
animateTo动画结束之前，鼠标缩放滚轴会有异常

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [maptalks/maptalks.js#1119]
**maptalks's version and what browser you use?**
----
v0.47.0

**Issue description**
----
animateTo还没结束的时候，缩放了鼠标，animateTo结束后，鼠标缩放 始终会回到结束的视角

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这个是正常的，地图的状态会以最近的一次animateTo为准

**Comment by Liquid-Zhangliquan** [comment]
> 这个是正常的，地图的状态会以最近的一次animateTo为准

如果用户在animateTo还没结束的途中，就改变了view， 之后再怎么操作 map都会强制回到那个view，这种问题改如何避免
