### ISSUE TITLE
maptalks.plotSymbol插件在最新版本mtk库绘制arrow类等图形报错

### ISSUE THREAD

**Issue by SimpleYong** [maptalks/maptalks.js#1120]
**maptalks's version and what browser you use?**
----version:0.47

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----https://codepen.io/simpleyong/pen/WNQzWGb?editable=true%3Dhttps%3A%2F%2Fmaptalks.org%2Fexamples%2Fcn%2Fmap%2Fload%2F

**Comment by fuzhenn** [comment]
这个是0.47.0为解决跨世界绘制，DrawTool中做的改动导致的。
已经解决，更新到 maptalks.plotsymbol@0.5.0 即可
