### ISSUE TITLE
我想实现一个功能

### ISSUE THREAD

**Issue by dongshanfei** [maptalks/maptalks.js#1123]
**maptalks's version and what browser you use?**
----
谷歌

**Issue description**
----

前端根据后台给的接口，生成一个点的位置、这个接口是实时的、
然后这个后台接口会不定时的带有某种状态
前端生成的点，判断如果这个接口有这个状态了
Marker的这个点会添加某种动态、就类似于报警的那种装置
就这种报警的装置，可以实现吗？
**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by whlysu** [comment]
可以

**Comment by fuzhenn** [comment]
如上楼，可以的，但这个和maptalks.js开发无关，就先关闭了。
