### ISSUE TITLE
maptalks.mapboxgl矢量瓦片调用地图下载图片功能，下载的图片为什么是空白的？

### ISSUE THREAD

**Issue by wuzhenzhen1314** [maptalks/maptalks.js#1124]
**maptalks's version and what browser you use?**
----v0.47

**Issue description**
----
maptalks.mapboxgl矢量瓦片调用地图下载图片功能，下载的图片为什么是空白的？
 var baseLayer = new maptalks.MapboxglLayer('tile',{
        glOptions : {
            'style' : 'mapbox://styles/mapbox/light-v9'
        }
    })
map.toDataURL({
            'mimeType': 'image/png', // or 'image/png'
            'save': true,             // to pop a save dialog
            'fileName': '000'         // file name
        });

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这是因为mapboxgl不是一个canvas图层，它并没有绘制在map的canvas中，而是单独放在了map的dom中。
要实现这个功能，你可以单独调用mapbox的map的截图功能，然后把它和maptalks的canvas在内存中的canvas里组合起来即可。
