### ISSUE TITLE
Smooth the layer

### ISSUE THREAD

**Issue by vladimir-rybalko** [maptalks/maptalks.js#1125]
**maptalks's version and what browser you use?**
----
maptalks v0.47.0 Google Chrome 81.0.4044.138

**Issue description**
----
Hello!

I need help!
I want to smooth the layer, but not on the tiles — the entire canvas. What do I need to do for this?

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/rybalko/full/vYNVxgX

**Comment by fuzhenn** [comment]
Hello, what do you mean of smoothing the layer?

**Comment by vladimir-rybalko** [comment]
I want to get blur effect for canvas map.
![image](https://user-images.githubusercontent.com/3933179/84597769-98736380-ae7f-11ea-9d86-995e0e73bfa2.png)

**Comment by fuzhenn** [comment]
You can create your own layer renderer, and override `getCanvasImage` method and do whatever you need. `getCanvasImage` is the final step before passing layer canvas to map renderer.

There is [an example](https://github.com/maptalks/maptalks.js/blob/master/src/renderer/layer/canvaslayer/CanvasLayerRenderer.js#L41) you can refer to.

Closing for now. Please feel free to comment if you have further question.
