### ISSUE TITLE
使用maptalks.es.js，在ie10浏览器显示不出地图。

### ISSUE THREAD

**Issue by xiexueze** [maptalks/maptalks.js#1126]
使用maptalks.es.js，在ie10浏览器显示不出地图。
控制台提示：SCRIPT438: 对象不支持“mergeOptions”属性或方法 

![image](https://user-images.githubusercontent.com/2314196/82727517-8dfcf880-9d1d-11ea-9479-0a7c29baa138.png)

**Comment by fuzhenn** [comment]
es.js里包含的有es6的语法，ie浏览器都不支持，请改用maptalks.min.js或者maptalks.js
