### ISSUE TITLE
关于ImageLager图层

### ISSUE THREAD

**Issue by dongshanfei** [maptalks/maptalks.js#1127]
**maptalks's version and what browser you use?**
----

new ImageLayer("images", [{
        url : 'http://example.com/foo.png',
        extent: [xmin, ymin, xmax, ymax],
        opacity : 1
    }])
**Issue description**
----现在我的页面插入了这个层，导入了一个图片之后、
项目初始化、图片加载成功之后
就是图片可以滑动 也可以拖动
我在官网找不到 取消滑动 取消拖动的、取消缩放（就是图片多大，按照多大显示）
我想问下 有没有这种 取消拖动 取消缩放 取消拖拽的属性
就是单纯的显示一张图片

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
创建map时，在options中把 draggable 和 zoomable 都设成false就行了
