### ISSUE TITLE
markerFile上插入一个图片

### ISSUE THREAD

**Issue by dongshanfei** [maptalks/maptalks.js#1134]
**maptalks's version and what browser you use?**
----
![Uploading image.png…]()

**Issue description**
this.Alarm_point = new maptalks.Marker([data.x, data.y], {
        id: data.id,
        symbol: {
          markerFile: "../" + img_dengji1,
          markerWidth: 100,
          markerHeight: 100
        },
        properties: {
          foo: "value"
        }
我创建了一个marker
然后markerFile是插入了一个图片
有没有什么办法可以再这个图片上插入一个字体

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
可以将字体转为 text 来做

https://codepen.io/deyihu/pen/XWXWjBL?editors=0010

**Comment by fuzhenn** [comment]
文字和图片的symbol示例：
https://maptalks.org/examples/cn/style/image-text-marker/#style_image-text-marker
