### ISSUE TITLE
maptalks坐标系问题

### ISSUE THREAD

**Issue by jinterry** [maptalks/maptalks.js#1141]
官网的1.0.0版本和0.47.0版本的maptalks坐标系都是躺下的右手坐标系，threejs的坐标系是正统的右手坐标系，我看官网上说了，0.46版本已经是右手坐标系了，但是用0.47开发发现直接放模型，模型是躺下的并不是立起来的。

**Comment by fuzhenn** [comment]
这是因为maptalks的up axis是z轴
你说的一般是因为模型的up axis是y轴，这种模型绕x轴旋转90度即可。
这两种坐标系都是右手坐标系，只是 up axis 不同而已

**Comment by jinterry** [comment]
那么有没有什么办法把up轴变成Y轴？在layer上处理的办法呢？ ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Fu&amp;nbsp;Zhen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月11日(星期四) 凌晨0:53
收件人:&nbsp;&quot;maptalks/maptalks.js&quot;<maptalks.js@noreply.github.com&gt;;
抄送:&nbsp;&quot;jinterry&quot;<624683466@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [maptalks/maptalks.js] maptalks坐标系问题 (#1141)

**Comment by jinterry** [comment]
那么有没有什么办法可以把up轴变成Y轴呢？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Fu&amp;nbsp;Zhen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月11日(星期四) 凌晨0:53
收件人:&nbsp;&quot;maptalks/maptalks.js&quot;<maptalks.js@noreply.github.com&gt;;
抄送:&nbsp;&quot;jinterry&quot;<624683466@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [maptalks/maptalks.js] maptalks坐标系问题 (#1141)
