### ISSUE TITLE
DrawTool 绘制 Point类型的图形 怎么自定义图片？

### ISSUE THREAD

**Issue by yangyang158** [maptalks/maptalks.js#1142]
symbol字段里的配置项 有没有 一个详细的文档说明

**Comment by fuzhenn** [comment]
https://github.com/maptalks/maptalks.js/wiki/Symbol-Reference

初始化DrawTool时，在symbol里指定样式即可。

**Comment by yangyang158** [comment]
var drawTools = new maptalks.DrawTool({
        mode: 'Point',
        symbol :  {
            'XXX属性'   : endMarkerImg,
          }
      }).addTo(map);
是哪个属性呀，试了好几个都不行呀
