### ISSUE TITLE
maptalksLayer在windows缩放文本大于100%的问题

### ISSUE THREAD

**Issue by XiaoLaoDi-x** [maptalks/maptalks.js#1143]
**maptalks's version and what browser you use?**
----
v.0.47.2

**Issue description**
----
mapv.MaptalksLayer在windows显示设置的缩放文本，更改为大于100%时，缩放地图后，地图所有类型热力（除heatmap普通热力外）位置会像右下发生位移。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
codepan.io地址https://codepen.io/XiaoLaoDi/pen/QWyEWKQ?editable=true%3Dhttps%3A%2F%2Fmaptalks.org%2Fexamples%2Fcn%2Fmap%2Fload%2F

**Comment by XiaoLaoDi-x** [comment]
系统是windows10

**Comment by fuzhenn** [comment]
该问题是mapv的maptalks图层dpr处理逻辑的问题
我已经给mapv[提了个pr](https://github.com/huiyan-fe/mapv/pull/229)，mapv合并发版本后，即能解决。

**Comment by fuzhenn** [comment]
mapv的pr已经合并，你可以自己克隆编译mapv后使用。

另外我还发现mapv heatmap在非整数倍devicePixelRatio时绘制会错位，这个问题在[这个commit中](https://github.com/maptalks/maptalks.js/commit/9a09ae1b4653d27f11085d398d447f7c5b830e40)已经解决，过两天会随v0.47.3一起发布

**Comment by XiaoLaoDi-x** [comment]
> mapv的pr已经合并，你可以自己克隆编译mapv后使用。
> 
> 另外我还发现mapv heatmap在非整数倍devicePixelRatio时绘制会错位，这个问题在[这个commit中](https://github.com/maptalks/maptalks.js/commit/9a09ae1b4653d27f11085d398d447f7c5b830e40)已经解决，过两天会随v0.48.0一起发布

好的谢谢大佬，请问mpv会发新版本么？会在几号发布呢？@fuzhenn

**Comment by fuzhenn** [comment]
按照mapv的版本发布频率，估计不会很快发版本的。
推荐你克隆项目后，自己编译使用，或者改个名发布到npm上

**Comment by XiaoLaoDi-x** [comment]
> mapv的pr已经合并，你可以自己克隆编译mapv后使用。
> 
> 另外我还发现mapv heatmap在非整数倍devicePixelRatio时绘制会错位，这个问题在[这个commit中](https://github.com/maptalks/maptalks.js/commit/9a09ae1b4653d27f11085d398d447f7c5b830e40)已经解决，过两天会随v0.47.3一起发布

好的谢谢大佬！这几天比较忙所以没时间看回复。请问您发现的这个问题maptalks什么时候发布最新版呢？我发现浏览器设置缩放小于100%时，也会出现heatmap刷新页面后，向左上错位的情况。不知是不是和您所说的同样的问题。@fuzhenn

**Comment by fuzhenn** [comment]
新版本已经发布了哈
https://github.com/maptalks/maptalks.js/releases

**Comment by XiaoLaoDi-x** [comment]
> 新版本已经发布了哈
> https://github.com/maptalks/maptalks.js/releases

好的，非常感谢您的回复！
