### ISSUE TITLE
在移动端时，快速拖动地图会导致地图卡死（快速拖动/移动3次）

### ISSUE THREAD

**Issue by whiteMelody** [maptalks/maptalks.js#1146]
maptalks's version 0.47.0

手机访问：
https://maptalks.org/examples/en/map/load/

**Comment by fuzhenn** [comment]
这个问题和 #1131 应该是同一个bug。
新版本发布以后，请确认一下是否还存在该问题

**Comment by fuzhenn** [comment]
v0.47.3已经发布，方便的时候请再确认一下卡死问题是否修复

**Comment by fuzhenn** [comment]
新版本中应该已经修复，如再次重现可以随时reopen
