### ISSUE TITLE
polygon有多个面时，只填充了一个面

### ISSUE THREAD

**Issue by whydontyoufly** [maptalks/maptalks.js#1148]
**maptalks's version and what browser you use?**
----
0.47.0

**Issue description**
----
填充多边形时，若多边形有两个面，则只填充了一个面

 
![image](https://user-images.githubusercontent.com/20639638/85242753-7460e500-b472-11ea-9db9-d8eb1e5ba6b7.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/accountli/pen/LYGNeJd

**Comment by fuzhenn** [comment]
```js
"type":"Polygon" //改成MultiPolygon即可
```
Polygon如果有多个ring，会把第二个及之后的环当成是空洞，就出现这个绘制问题。
