### ISSUE TITLE
总是怎么红色的提醒是什么原因

### ISSUE THREAD

**Issue by ZLJ599** [maptalks/maptalks.js#1149]
![截屏2020-06-22 下午5 33 08](https://user-images.githubusercontent.com/9264066/85272482-d0e1f580-b4ae-11ea-8cd7-938f3a0ce9ef.png)
这应的警告是什么原因啊

**Comment by fuzhenn** [comment]
这是因为map接管了容器的鼠标滚轮事件，而这个事件是推荐设为passive的(不preventDefault），但地图必须要preventDefault才能用滚轮缩放地图。

chrome下只是会抛警告，请问你用的是什么浏览器？

**Comment by ZLJ599** [comment]
Google Chrome (Mac)
 版本 83.0.4103.106（正式版本） （64 位）
