### ISSUE TITLE
GeoJSON格式的数据 绘制 出来的线条 如何实现 动画呀

### ISSUE THREAD

**Issue by yangyang158** [maptalks/maptalks.js#1156]
设置 linePatternFile 为一个带动画的图片，但是看不出来效果

**Comment by fuzhenn** [comment]
或许有用的示例：
* [线的动画展现](https://maptalks.org/examples/cn/animation/line-animateshow/#animation_line-animateshow)
* [Geometry通用动画方法](https://maptalks.org/examples/cn/animation/geometry-anim/#animation_geometry-anim)

因为VectorLayer是基于canvas实现的，所以无法支持gif格式的linePatternFile，因为不清楚你的具体需求，无法给出具体建议，请见谅。

**Comment by roshomon** [comment]
那symbol的属性markerFile是不是也不支持gif？
