### ISSUE TITLE
X5内核的浏览器（如qq内的webview）打开无法加载瓦片地图

### ISSUE THREAD

**Issue by Charliecheung2** [maptalks/maptalks.js#1159]
**maptalks's version and what browser you use?**
----
maptalks v0.45.1

**Issue description**
----
在微信或者qq打开maptalks渲染的瓦片地图时，报错
错误信息如下
maptalks.min.js:6 
Uncaught Error: Failed to create the buffer object
    at t.i.createBuffer (maptalks.min.js:6)
    at t.i.createImageBuffer (maptalks.min.js:6)
    at t.i.loadImageBuffer (maptalks.min.js:6)
    at t.i.bufferTileData (maptalks.min.js:6)
    at t.e._bindGLBuffer (maptalks.min.js:6)
    at t.e.drawTile (maptalks.min.js:6)
    at t.e._drawTileOffset (maptalks.min.js:6)
    at t.e._drawTileAndCache (maptalks.min.js:6)
    at maptalks.min.js:6
    at Array.forEach (<anonymous>)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by Charliecheung2** [comment]
看了一下X5是支持webgl 2.0的，所以应该不是webgl的问题，问题出在createBuffer上面。正在阅读源码。

**Comment by fuzhenn** [comment]
感谢提issue。
我刚用[官网demo](https://maptalks.org/examples/cn/map/load/)测试了一下，在qq和微信里都能正常显示。
如果你的错误是基于别的实现方式，帮忙提供一个重现代码。
如果不需要3d功能，可以在创建TileLayer时，[把options里的renderer设成canvas](https://maptalks.org/examples/cn/tilelayer-projection/canvas-renderer/#tilelayer-projection_canvas-renderer)，应该能解决这个问题。

**Comment by Charliecheung2** [comment]
> 感谢提issue。
> 我刚用[官网demo](https://maptalks.org/examples/cn/map/load/)测试了一下，在qq和微信里都能正常显示。
> 如果你的错误是基于别的实现方式，帮忙提供一个重现代码。
> 如果不需要3d功能，可以在创建TileLayer时，[把options里的renderer设成canvas](https://maptalks.org/examples/cn/tilelayer-projection/canvas-renderer/#tilelayer-projection_canvas-renderer)，应该能解决这个问题。

官网的demo应该就是使用的base底图用webgl渲染。然后还有canvas的demo。确实均能访问。我也尝试过切换成canvas但是依旧报相同的错误。所以我正在debug这个createBuffer函数，看到你们的contributing页面已经打不开了。可能与我们的封装代码有关系。
实现的代码为: 先调用GroupTileLayer然后如下
```
new maptalks.TileLayer('百度地图', {
              urlTemplate: 'http://online{s}.map.bdimg.com/onlinelabel/?qt=tile&x={x}&y={y}&z={z}&s=1&styles=pl&scaler=1&p=1&s=1',
              subdomains: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
            }),
```
目前是只有在安卓机型会出现这个问题。iOS端的微信和qq使用的不是X5内核的。检测X5内核可以访问debugx5.qq.com。

**Comment by fuzhenn** [comment]
谢谢回复，帮忙基于[这个demo](https://maptalks.org/examples/cn/map/load/)整理一个重现代码吧。
点击右上角的编辑，在codepen中编辑好后，保存，把url传上来即可

**Comment by Charliecheung2** [comment]
好的，我正在重现，目前全部切换成canvas之后，问题解决。可以的话我想来解决这个issue，OSS 新手。想参与下项目

**Comment by Charliecheung2** [comment]
https://codepen.io/charliecheung2/pen/ZEQRYoR
整理后的代码，但是不知道为什么没有渲染成功，console也没有任何错误提示。但是实现代码是这样的

**Comment by fuzhenn** [comment]
我修改后的代码，能正常显示了：
https://codepen.io/fuzhenn-the-decoder/pen/RwrJNBW

* 因为百度在国外没有数据，调整了中心点坐标
* SpatialReference改为了`baidu`

**Comment by fuzhenn** [comment]
createBuffer失败一般是因为页面上的webgl context数量超过最高限制导致的，而手机端的限制更加严格。
解决方案是尽量减少webgl上下文个数，例如如需载入多个TileLayer，用GroupTileLayer合并为一个图层。

**Comment by Charliecheung2** [comment]
清楚了，我现在知道问题在哪了，因为之前的页面直接用的电脑端，没有做viewport，然后一次性渲染太多webgl了，我现在改成viewport后，一次性渲染的webgl可能没有超出限制，在createBuffer函数里面也能捕捉到t了，不会报failed to create了，问题解决。

**Comment by Charliecheung2** [comment]
webgl超出数量时，会不会抛出异常，如果可以的话，添加一个超出数量的异常提醒，会更方便定位到错误？

**Comment by fuzhenn** [comment]
不会抛错误，新的webgl上下文永远能正常创建，但会导致老的webgl上下文会工作异常，例如createBuffer失败。

**Comment by Charliecheung2** [comment]
明白了，老的被挤出去了，问题复现的关键点在用手机打开电脑端的网页，一次性渲染的webgl过多导致的。而改成viewport后，渲染的页面变小了，webgl数量减少，所以就不会抛出这个错误。谢谢作者。
