### ISSUE TITLE
火星坐标支持

### ISSUE THREAD

**Issue by ssjylsg** [maptalks/maptalks.js#1172]
**maptalks's version and what browser you use?**
----
V:0.47.5
chrome

**Issue description**
----
自动将wgs 84 坐标转为火星坐标，加到高德地图

新建了高德坐标系：
unproject 方法中 将p 转为 火星坐标 再转为84坐标
project 方法中将 输入的84坐标，转为火星坐标 ，再转为3857.

修改之后，高德地图支持了84坐标点位，但是存在点位Marker click 事件不相应。排查了下，是因为84 坐标系和火星坐标 之间互相转换，导致误差越来越大。

请问怎么解决？

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以试试在coordinate对象上加个属性，标识一下它的坐标类型，projection里根据坐标类型来转换。
例如84 => 84就直接输出，只有gcj02 => 84 才转换
