### ISSUE TITLE
initContainer方法默认清空地图dom下的元素

### ISSUE THREAD

**Issue by ok958726** [maptalks/maptalks.js#1175]
initContainer方法中设置containerDOM.innerHTML = '';清空地图dom下的元素。
在使用Vue的时，想在地图dom下挂载组件便无法完成，只好修改源码。
不知是否有其他解决办法？或者从源码上做一些修改？

**Comment by fuzhenn** [comment]
可以通过整理dom层次结构来解决：不要把vue组件放到map的container里，比如可以创建一个和map container同级的vue container，这样既不会被map干扰，也应该能实现同样的功能。
