### ISSUE TITLE
maptalks1.0.0什么时候公布？

### ISSUE THREAD

**Issue by whlysu** [maptalks/maptalks.js#1188]
maptalks1.0.0不再开源了吗？

**Comment by fuzhenn** [comment]
谢谢关心~
1.0版会和正在开发的新三维插件一起发布，顺利的话应该会在10月左右发布。
maptalks.js核心库会一直基于BSD-3开源，但有些插件不排除采用其他开源协议或者闭源。

**Comment by whlysu** [comment]
1.0会支持矢量瓦片吗？正在考虑自己写呢，还是等你们开发完。自己写工作量太大了

**Comment by whlysu** [comment]
> 谢谢关心~
> 1.0版会和正在开发的新三维插件一起发布，顺利的话应该会在10月左右发布。
> maptalks.js核心库会一直基于BSD-3开源，但有些插件不排除采用其他开源协议或者闭源。

1.0会支持矢量瓦片吗？正在考虑自己写呢，还是等你们开发完。自己写工作量太大了

**Comment by fuzhenn** [comment]
矢量瓦片是一定会支持的~
