### ISSUE TITLE
class Geometry method setInfoWindow

### ISSUE THREAD

**Issue by zhao624** [maptalks/maptalks.js#1189]
**maptalks's version and what browser you use?**
----
latest version 

**Issue description**
----
请问怎么将vue组件设置为content内容

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by MaJiaXuan** [comment]
https://github.com/sakitam-gis/map-popup-useage

**Comment by zhao624** [comment]
谢谢
