### ISSUE TITLE
Marker与LineString存在角度差

### ISSUE THREAD

**Issue by huronzhu** [maptalks/maptalks.js#1192]
LineString和Marker（文本，Symbol.textRotation）同时使用，二者存在角度差，代码复现：

https://codepen.io/huronzhu/pen/bGpebyx

**Comment by deyihu** [comment]
@huronzhu https://codepen.io/deyihu/pen/zYqBxBR?editors=1010

**Comment by huronzhu** [comment]
@deyihu 多谢
