### ISSUE TITLE
map.remove 方法中使用 `this._containerDOM.innerHTML = "'';`，导致在同一个 container 内的其他元素被移除

### ISSUE THREAD

**Issue by wang2lang** [maptalks/maptalks.js#1195]
**maptalks's version and what browser you use?**
----
0.48.0

**Issue description**
----
1. 遇到有需要 fullscreen 的场景时，需要将一些 map 之外的自定义组件放在与 map 相同的 DOM 容器里。
2. map 在某些情况下需要被 remove 后重新渲染挂载在 DOM 容器中。
3. map.remove 使用了 `this._containerDOM.innerHTML = "'';`，这会导致与 map 处在相同 DOM 容器里的其他元素都被移除掉。

是否采用 `this._containerDOM. removeChild(document.querySelector('.maptalks-wrapper'))` 会更合适一些？

`this._containerDOM.innerHTML = "'';`真的是太粗暴了！ 

**Please provide a reproduction URL (on any jsfiddle like site)**
----
盼答复！

**Comment by wang2lang** [comment]
或者在地图初始化的时候添加一个 `this._mapDOM`属性，在移除的时候使用 `this._containerDOM.removeChild(this._mapDOM)`

**Comment by fuzhenn** [comment]
你的建议很合理。
但考虑到一个页面中可能有多个map，用querySelector不是很合适。
可以考虑通过遍历container的children，找到class包含maptalks-wrapper的dom然后remove。

有兴趣的话请提个pr给我。

**Comment by fuzhenn** [comment]
fixed by #1208
