### ISSUE TITLE
高速加载marker 图层会消失

### ISSUE THREAD

**Issue by FEJackFly** [maptalks/maptalks.js#1196]
**maptalks's version and what browser you use?**
----
maptalks v0.48.0
chrome

**Issue description**
----
高速加载marker 图层会消失

**Please provide a reproduction URL (on any jsfiddle like site)**
----
[demo.zip](https://github.com/maptalks/maptalks.js/files/5106325/demo.zip)

**Comment by fuzhenn** [comment]
这个问题应该在最新版中解决了，参考 #1222
