### ISSUE TITLE
text-dx, text-dy设置不起作用

### ISSUE THREAD

**Issue by wsw0108** [MapTalks/MapTalks.js#12]
示例见exmaples/geometry/marker/text_marker.html

**Comment by brucin** [comment]
的确不起作用，因为目前有dx、dy已经可以设置偏移，我担心过于复杂。
所以，计算的时候就没有加上text-dx与text-dy。

**Comment by wsw0108** [comment]
shield类型有shield-text-dx与shield-dx，意义明确。
对于text类型来说，应该就只需要text-dx，text-dy。
dx，dy作为对cartocss的自定义扩展，应该只作用于image与vector(circle, triangle, etc)吧？

**Comment by brucin** [comment]
你这个说法我是认可的。我稍后会修改一下。
