### ISSUE TITLE
使用property属性进行批量配置样式时报错

### ISSUE THREAD

**Issue by liulianfan** [maptalks/maptalks.js#1202]
**maptalks's version and what browser you use?**
----
截止发现问题的在线版和此时master编译都可复现问题

**Issue description**
----
使用geojson数据进行图层显示时（maptalks.GeoJSON.toGeometry），样式配置参数无法使用数据中的property信息进行配置

**Please provide a reproduction URL (on any jsfiddle like site)**
[----](url)

`
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>图层 - VectorLayer: 批量设置图形样式</title>
<style type="text/css">
    html,
    body {
        margin: 0px;
        height: 100%;
        width: 100%
    }

    .container {
        width: 100%;
        height: 100%
    }
   
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.min.js"></script>

<body>

    <div id="map" class="container"></div>

    <script>
        var map = new maptalks.Map('map', {
            center: [121.648680349668297, 31.115846723803205],
            zoom: 15,
            baseLayer: new maptalks.TileLayer('base', {
                baseLayerRenderer: 'dom',
                urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
                subdomains: ['a', 'b', 'c', 'd'],
                attribution: '&copy; <a href="http://osm.org">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/">CARTO</a>'
            })
        });

        var layer = new maptalks.VectorLayer('vector')
            .addTo(map);

        var landmarker = {
            "type": "FeatureCollection",
            "features": [{
                    "type": "Feature",
                    "properties": {
                        "markerDy": -8,
                        "icon": 'https://mapapi.qq.com/sdk/overseamap/logo/tencent_color_logo.png',
                        "markerWidth": 19,
                        "markerHeight": 19,
                        "name": "家门口服务中心"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [121.648680349668297, 31.115846723803205]
                    }
                },
                {
                    "type": "Feature",
                    "properties": {
                        "markerDy": -8,
                        "icon": 'https://mapapi.qq.com/sdk/overseamap/logo/tencent_color_logo.png',
                        "markerWidth": 19,
                        "markerHeight": 19,
                        "name": "家门口服务中心"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [121.652565460572418, 31.120836218484975]
                    }
                },

            ]
        }
        const customizedLandmarkSourceGeom = maptalks.GeoJSON.toGeometry(landmarker);
        layer.addGeometry(customizedLandmarkSourceGeom);
        layer.setStyle([{
                    symbol: [{
                        markerFile: {
                            type: 'identity',
                            property: 'icon'
                        },
                        markerWidth: {
                            type: 'identity',
                            property: 'markerWidth'
                        },
                        markerHeight: {
                            type: 'identity',
                            property: 'markerHeight'
                        },
                        markerDy: {
                            type: 'identity',
                            property: 'markerDy'
                        },
                    }, {
                        textName: '{name}',
                        textFill: 'red',
                        textSize: 14
                    }]
                }])
    </script>
</body>

</html>
`

**Comment by liulianfan** [comment]
在线版 https://codepen.io/liulianfan/pen/Vwapqgr

**Comment by fuzhenn** [comment]
设计如此，markerFIle目前不支持function-type，但markerWidth，markerHeight等属性是支持的。
先关闭。
