### ISSUE TITLE
Marker as rounded rectangle

### ISSUE THREAD

**Issue by Gorgchap** [maptalks/maptalks.js#1206]
Hello!
Can you tell, is it possible to realize Marker in form of rounded rectangle (or maybe add new marker's properties for rounding). Thank you in advance

**Comment by fuzhenn** [comment]
Yes, it's possible. You can create a rounded rectangle svg path, and add to marker as `markerPath` property.
The example:
https://maptalks.org/examples/en/style/svg-path-marker/

**Comment by Gorgchap** [comment]
Thanks once again. I've managed to do this)
