### ISSUE TITLE
kml 加载后偏转

### ISSUE THREAD

**Issue by hyoracle** [maptalks/maptalks.js#1207]
我用openlayers和maptalks加载同样的瓦片，和中国境内的kml文件，发现openlayes正常，两者没有错位，而maptalks则有偏移量，两者在坐标系上我都用的是epsg:3857,一时找不到解决方法，希望群主出招解决
[hyoracle@126.com] qq:282603745

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
能否提供一个重现代码？谢谢。

**Comment by hyoracle** [comment]
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Map - Display a map</title>
  <style type="text/css">
    html,body{margin:0px;height:100%;width:100%}
    .container{width:100%;height:100%}
  </style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.css">
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks.formats/dist/maptalks.formats.js"></script>
  <body>

    <div id="map" class="container"></div>

    <script>
      var map = new maptalks.Map('map', {
        center: [116,35],
        zoom: 6,
		spatialReference: {
            projection: 'EPSG:3857',
            resolutions: resolutions,
            fullExtent: {
                'top': 6378137 * Math.PI,
                'left': -6378137 * Math.PI,
                'bottom': -6378137 * Math.PI,
                'right': 6378137 * Math.PI
            }
        },
         baseLayer: new maptalks.TileLayer(type, {
			tileSystem: [1, -1, -20037508.34, 20037508.34],
			crossOrigin: 'anonymous',
			tileSize: [255, 255],
			urlTemplate: (x, y, z) => {
				const _z = z;
				const _x = x;
				const _y = y;

				const urlTemplate = '/mswss/maps/tiles/' + type + '/1000/' + type + '_1000/all_png/3/1/2/1/new/{z}/{y}/{x}';
				const url = urlTemplate.replace('{x}', _x).replace('{y}', _y).replace('{z}', _z);
				return url;
			}
		})
      });
	  
	   maptalks.Formats['kml']('kml/河南省_行政边界.kml', function (err, geojson) { 
        new maptalks.VectorLayer('v', geojson).addTo(map).setStyle({
        symbol: {
            polygonFill: 'rgba(0, 255, 0, 0.3)'
        }
    });
      });

    </script>
  </body>
</html>

**Comment by fuzhenn** [comment]
注意到TileLayer的tileSize被设成了255，这个值一般是256的。
如果不是这个问题，因为这个代码不能实际运行，很难判断是哪里出了错，能否提供一个可以运行的重现demo。

**Comment by hyoracle** [comment]
谢谢，就是你说的问题
