### ISSUE TITLE
drawTool 里选择 polygon 模式的时候，画第二个点双击会触发 drawend，画出一条线

### ISSUE THREAD

**Issue by wang2lang** [maptalks/maptalks.js#1209]
**maptalks's version and what browser you use?**
----
v0.48.0

**Issue description**
----
在 polygon 模式下，不应该画出一条线。双击完成应该在画三个或多于三个点双击时触发，不应该在第二个点双击时触发结束并画出一条线，这就不是 polygon 了。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://maptalks.org/examples/en/interaction/draw-tool/#interaction_draw-tool

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.js/blob/3346c443d15b1538880439fa17e668ed3995a741/src/map/tool/DrawTool.js#L346

双击会触发两次单击

https://github.com/maptalks/maptalks.js/blob/3346c443d15b1538880439fa17e668ed3995a741/src/map/tool/DrawTool.js#L337

自由绘制，鼠标up事件了，应该也要坐下判断，比如 FreePolygon
