### ISSUE TITLE
地图使用不规范

### ISSUE THREAD

**Issue by fishergisdldt** [maptalks/maptalks.js#1210]
**maptalks's version and what browser you use?**
----

**Issue description**
----
看看这个地址：https://maptalks.org/maptalks.three/demo/extrudepolygon-countries.html。印度东北角 藏南 和林芝，换一个国内的行政区划json吧

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
fixed by https://github.com/maptalks/maptalks.three/pull/204
