### ISSUE TITLE
端点沿线自动旋转Marker

### ISSUE THREAD

**Issue by shen198956** [maptalks/maptalks.js#1213]
**maptalks's version and what browser you use?**
----
v0.48.0

**Issue description**
----
绘制线条时，设置每一个节点显示图标，并且自动跟随角度旋转，在地图级别很小的时候绘制图标有问题，中间节点图片不出现，且出现的收尾的角度也不对，只有当默认级别大的时候绘制才会正确出现

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![image](https://user-images.githubusercontent.com/70745811/92212760-0b133e80-eec5-11ea-8b21-ab47a52047a9.png)
![image](https://user-images.githubusercontent.com/70745811/92212809-19615a80-eec5-11ea-949a-6559bdecf070.png)

**Comment by fuzhenn** [comment]
可以试试关闭simplify。
在VectorLayer或者LineString的options中，把enableSimplify设为false即可

**Comment by deyihu** [comment]
可能已经修复，https://maptalks.org/examples/en/style/line-marker/#style_line-marker  如果有问题可以再次打开
