### ISSUE TITLE
`map.animateTo` 方法的代码实现方式导致动画效果不协调

### ISSUE THREAD

**Issue by wang2lang** [maptalks/maptalks.js#1217]
**maptalks's version and what browser you use?**
----
v0.49.0

**Issue description**
----

以下代码实现： [Map.Anim.js#L115](https://github.com/maptalks/maptalks.js/blob/master/src/map/Map.Anim.js#L115)
```
if (frame.styles['center']) {
    const center = frame.styles['center'];
    this._setPrjCenter(projection.project(center));
    this.onMoving(this._parseEventFromCoord(this.getCenter()));
} else if (frame.styles['prjCenter']) {
    const center = frame.styles['prjCenter'];
    this._setPrjCenter(center);
    this.onMoving(this._parseEventFromCoord(this.getCenter()));
}
if (!isNil(frame.styles['zoom'])) {
    this.onZooming(frame.styles['zoom'], zoomOrigin);
}
if (!isNil(frame.styles['pitch'])) {
    this.setPitch(frame.styles['pitch']);
}
if (!isNil(frame.styles['bearing'])) {
    this.setBearing(frame.styles['bearing']);
}
```
如果调用 `map.animateTo({center, zoom}) `，地图执行的 zooming 动画和moving动画是各自割裂的，表现出来的效果就是很明显的一帧地图 zooming，一帧地图 moving。或者很明显的 zooming 和 moving 不一致，不协调，很难受。

理论上，应该是算好 from 和 end 两个状态的形态后，地图所有需要变更的动画一起执行。例如 zooming 和 moving 共同作用后下一帧应该是如何画，应该一起画才能是协调的效果。

mapbox 里的 flyTo 效果就很协调流畅，没有怪异的感觉。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://react-maptalks.stackblitz.io/

**Comment by fuzhenn** [comment]
moving和zooming是一起计算并渲染的，并没有像你说的一帧moving一帧zooming。
你说的停顿感，可能是无法维持帧数的卡顿造成的。
但重现代码现在无法访问(连不上dev server)，能否再重新发一个可以重现问题的代码？

**Comment by wang2lang** [comment]
那问题应该是出现在 fly 这个动作上，假如 start 和 end 两个的 zoom 一样但是 center 距离又较远，那么短时间内横切过去会导致地图底图加载不及时导致整个动画都是白屏，这个很容易复现的。

还有一个动画细节的问题：当 end 的 zoom 较大，需要放大并平移时，如果距离很远，也是需要先缩小地图平移，然后在快结束时再放大的。否则，平移动和放大动作同时执行会很怪异，触发白屏概率很高。

最核心的问题是**动画过程中 zoom 不能太大**，否则地图加载不及时，看起来平移也过快很难受。

mapbox 的 flyTo 有做 zoom 和 center 距离上的判断：如果 zoom 一样， 动画会先缩放地图，再放大，期间做流畅的平移。

leaflet 实现这部分代码是：https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L358

**Comment by fuzhenn** [comment]
谢谢！的确是个很好的建议！

**Comment by wang2lang** [comment]
期待下个版本实现 (*❦ω❦)

**Comment by fuzhenn** [comment]
已经参考了leaflet和mapbox-gl-js新实现了flyTo方法（方法名一样），即按你说的，根据起点和终点动态的调整zoom来获得一个更平滑的动画。

原有的animateTo还是保留（相当于mapbox-gl-js里的eastTo方法）

**Comment by wang2lang** [comment]
请问这个功能准备什么时候发包？
