### ISSUE TITLE
咨询自定义标注UIMarker的高度

### ISSUE THREAD

**Issue by chengang0621** [maptalks/maptalks.js#1220]
地图上会叠加好几层具有高度的面，然后再在上面叠加一些个性化的标注，由于标注内容比较个性化，使用了UIMarker，但是UIMarker没法设置高度

**Comment by fuzhenn** [comment]
目前UIMarker确实不支持高度，不过这是个好建议，会在下个版本实现这个功能

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.three/issues/207
