### ISSUE TITLE
请问 ConnectorLine 的文本能否添加背景

### ISSUE THREAD

**Issue by gee1k** [maptalks/maptalks.js#1221]
这种效果

![image](https://user-images.githubusercontent.com/12059800/92874814-f857b700-f43a-11ea-82fc-b3752d32bd32.png)

![image](https://user-images.githubusercontent.com/12059800/92874859-01488880-f43b-11ea-9ca4-3998e2176ee2.png)

**Comment by gee1k** [comment]
临时重写了 TextMarkerSymbolizer 的 symbolize 实现

![image](https://user-images.githubusercontent.com/12059800/92879774-ea586500-f43f-11ea-99e6-37cde375c426.png)

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/VwaByyj 组合样式就可以了
