### ISSUE TITLE
指定markerFile时，有时请求不到，有时又是好的？

### ISSUE THREAD

**Issue by heyonggis** [maptalks/maptalks.js#1222]
我在做一个场景，做几家飞机飞，汽车动，其中汽车利用LineString的设置markerFile显示，marker File传的是文件，有时请求好好的，有时报错，no img found，很不稳定，不知道如何解决？

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
请问一下你用的版本是？
如果是最新版(0.49.1)， 能否提供一个重现代码？
之前解决过的类似issue: #1211, #1129

**Comment by heyonggis** [comment]
我用的是0.48

**Comment by fuzhenn** [comment]
0.49.1解决了一个markerFile在Geometry动画时消失的bug #1211，可以试试升级到0.49.1，看看是否还有此问题。
如果还有的话，请整理一个重现代码。

**Comment by heyonggis** [comment]
升级之后好了，但是LineString MarkerFile 好像不管用了

**Comment by fuzhenn** [comment]
那帮忙提供一个lineString上markerFile失灵的重现代码吧。

**Comment by fuzhenn** [comment]
先关闭，如果需要，可以随时重新打开
