### ISSUE TITLE
VectorLayer绘制图形会超出TileLayer的远端范围

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1223]
**maptalks's version and what browser you use?**
----
v0.49.1

**Issue description**
----
VectorLayer绘制图形会超出TileLayer的远端范围
![4QZ7SSVSC}S)6(Z2620DTA8](https://user-images.githubusercontent.com/13678919/93159401-a9629800-f740-11ea-82d9-fe809c7d38b3.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
close by https://github.com/maptalks/maptalks.js/pull/1714
