### ISSUE TITLE
旋转地图时多个marker前后位置问题

### ISSUE THREAD

**Issue by wuzhenzhen1314** [maptalks/maptalks.js#1225]
**maptalks's version and what browser you use?**
----
v0.49.1

**Issue description**
----
添加多个marker图形，旋转地图时，有的角度，多个marker前后位置遮挡不正确，应该被遮挡的marker，却在前面。有什么办法可以处理吗？

**Please provide a reproduction URL (on any jsfiddle like site)**
----https://maptalks.org/examples/cn/style/image-marker/#style_image-marker

**Comment by fuzhenn** [comment]
谢谢。
这确实是个bug，应该把marker按相机距离进行排序，再绘制就是正确的了。
下个版本里会修正。

**Comment by wuzhenzhen1314** [comment]
好的，非常期待！
