### ISSUE TITLE
VectorLayer 面数据较多时，地图倾斜视角时，拖放过程中数据不可见。

### ISSUE THREAD

**Issue by gisshare2015** [maptalks/maptalks.js#1226]
VectorLayer 面数据较多时，地图倾斜视角时，拖放过程中数据不可见。
请问是否可以避免这种情况？

**Comment by GGmemeda** [comment]
我也遇到同样的问题，请问有解决方式吗？

**Comment by gisshare2015** [comment]
如下设置即可：
new VectorLayer('v', null, {
            forceRenderOnZooming: true,
            forceRenderOnMoving: true,
            forceRenderOnRotating: true});

**Comment by gisshare2015** [comment]
如下设置即可：
new VectorLayer('v', null, {
forceRenderOnZooming: true,
forceRenderOnMoving: true,
forceRenderOnRotating: true});


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maptalks/maptalks.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 上午10:57
收件人:&nbsp;"maptalks/maptalks.js"<maptalks.js@noreply.github.com&gt;;
抄送:&nbsp;"独孤正鸿"<441856317@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [maptalks/maptalks.js] VectorLayer 面数据较多时，地图倾斜视角时，拖放过程中数据不可见。 (#1226)





 
我也遇到同样的问题，请问有解决方式吗？
