### ISSUE TITLE
marker旋转角度没生效，咋回事

### ISSUE THREAD

**Issue by heyonggis** [maptalks/maptalks.js#1227]
**maptalks's version and what browser you use?**
----
marker.bringToFront().updateSymbol({
     symbol:{
         markerRotation: 40
})

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
你的调用代码写错了，应该是：
```js
marker.updateSymbol({ markerRotation: 40 });
```
