### ISSUE TITLE
可否增加 globe 模式

### ISSUE THREAD

**Issue by wang2lang** [maptalks/maptalks.js#1228]
**maptalks's version and what browser you use?**
----
v0.49.1

**Issue description**
----
当zoom缩放到一定级别的时候显示3D的地球

**Please provide a reproduction URL (on any jsfiddle like site)**
----

<img width="1420" alt="截屏2020-09-17 下午4 25 34" src="https://user-images.githubusercontent.com/4401831/93443089-c646c900-f902-11ea-876b-587803c99f5c.png">

类似于：
[http://examples.webglearth.com/examples/helloworld.html](http://examples.webglearth.com/examples/helloworld.html)

**Comment by fuzhenn** [comment]
谢谢建议，但目前暂时没有这个计划。
因为地球模式对数据格式，投影系统都与平面地图区别比较大，核心库里是不会支持的。
不过未来可以考虑通过插件来提供支持，在某个级别平滑过渡。

**Comment by wang2lang** [comment]
> 谢谢建议，但目前暂时没有这个计划。
> 因为地球模式对数据格式，投影系统都与平面地图区别比较大，核心库里是不会支持的。
> 不过未来可以考虑通过插件来提供支持，在某个级别平滑过渡。

请问一下这个插件实现方面有什么思路和建议吗？
