### ISSUE TITLE
关于maptalk的架构

### ISSUE THREAD

**Issue by fishergisdldt** [maptalks/maptalks.js#1230]
我对比发现，maptalk的主题结构非常类似于leaflet。能否向兼容leaflet插件方向做一些努力。这样maptalk就可以平滑的替换原始的webgis展现方式呢

**Comment by fuzhenn** [comment]
谢谢提issue。
目前没有这个打算，原因如下：
* maptalks是以canvas为map主渲染容器，leaflet是以dom为主渲染容器
* maptalks支持三维，leaflet目前无法支持
* maptalks未来的定位会以webgl技术为主。

**Comment by fishergisdldt** [comment]
也就是说maptalks定位和mapboxGl js一致了。那maptalk有哪些是和他不一致或者说优势的地方呢

**Comment by fuzhenn** [comment]
等webgl插件发布以后，你就知道了，各有特色，共同进步。 😸

**Comment by wefiy** [comment]
@fuzhenn webgl 插件什么时候发布
