### ISSUE TITLE
最近用vue + iframe加载maptalks.js地图网页，发现google浏览器的CPU使用率超过100%，经常死掉，不知咋回事

### ISSUE THREAD

**Issue by heyonggis** [maptalks/maptalks.js#1232]
**maptalks's version and what browser you use?**
----

同题目
**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
我不是很熟悉vue+maptalks，很抱歉无法直接向你提供解决方案。
但之前看网友讨论过，不要把图层加入到vue的状态管理，会造成明显的性能下降，不知道是不是这个原因。
也可以等等看有没有其他人有这方面经验。

**Comment by heyonggis** [comment]
把vue改成生产模式以后，就没有此问题了，有可能开发者模式，有些js是不是形成闭包，或者嵌套造成，个人认为是这样
