### ISSUE TITLE
大量数据绘制问题

### ISSUE THREAD

**Issue by ryry886** [maptalks/maptalks.js#1233]
**maptalks's version and what browser you use?**
----

**Issue description**
----
你好，以前biglayer插件可以实现大量point，line，polygon的绘制，现在maptalks升级 到opengl 坐标系后，biglayer插件就有问题了。如果要用最新的maptalks版本，在海量数据的渲染上面，有什么好的方法吗？

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
过段时间，会发布一些官方webgl插件，可以用他们来实现海量数据的渲染。

**Comment by ryry886** [comment]
期待，希望能尽快看到 ：）
