### ISSUE TITLE
Blank tiles if TileLayer is set with offset

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1237]
**maptalks's version and what browser you use?**
----
v0.49.1

**Issue description**
----
Blank tiles if TileLayer is set with offset

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://jsfiddle.net/fuzhenn/marnpw38/17/

**Comment by sys2007** [comment]
@fuzhenn 更新783d189 后，发现设置offset后底图能正常显示了，但是缩放地图会出现抖动的情况。
