### ISSUE TITLE
 Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by sunkingsss** [maptalks/maptalks.js#1238]
**maptalks's version and what browser you use?**
----
maptalks version: 0.44.2
browser: google

**Issue description**
----
when i leaved the page,it occured a mistake,said that maptalks.es.js?1fc4:30289 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Thanks for reporting.

This error is caused by that the canvas size of a layer is 0.

* You can try to upgrade to the latest version and see if it is resolved.
* If not, please provide a reproduction example on codepen.

Thanks

**Comment by deyihu** [comment]
这种问题一般都是地图大小为0时导致的，比如地图默认display=none,导致地图拿到大小为0，底层的canvas绘制时就出现问题了，
不过现在地图渲染逻辑了，做了离屏控制了，当离屏是不渲染了
https://github.com/maptalks/maptalks.js/blob/034af2467d5b312962dbe65e80ba9fd893a21983/src/renderer/map/MapCanvasRenderer.ts#L89


https://github.com/maptalks/maptalks.js/blob/034af2467d5b312962dbe65e80ba9fd893a21983/src/renderer/map/MapRenderer.ts#L171
