### ISSUE TITLE
ImageLayer images auto set  crossOrigin when Renderer is not canvas

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#1240]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以考虑改一种实现方案：
在[ResourceCache的图片载入逻辑里](https://github.com/maptalks/maptalks.js/blob/master/src/renderer/layer/CanvasRenderer.js#L737)：
如果图层的renderer不是canvas（说明是gl或者gpu），则给个默认的crossOrigin（即空字符串）
