### ISSUE TITLE
maptalks的右键菜单只能一级，不能二级子菜单，这点让人诟病

### ISSUE THREAD

**Issue by heyonggis** [maptalks/maptalks.js#1242]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
二级菜单应该能通过自定义右键菜单来实现。
https://maptalks.org/examples/cn/ui-control/ui-custom-menu/#ui-control_ui-custom-menu
