### ISSUE TITLE
todataurl支持压缩图片

### ISSUE THREAD

**Issue by mankeheaven** [maptalks/maptalks.js#1244]
**maptalks's version and what browser you use?**
----

**Issue description**
----
toDataURL需要添加一个对jpeg允许设置图片质量的参数
目前没有支持图片质量压缩，默认0.92的压缩率

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
增加了quality参数(0 - 1)
```js
map.toDataURL({ quality: 0.5 });
```
