### ISSUE TITLE
maptalks not support geoserver wfs or wmts?

### ISSUE THREAD

**Issue by heyonggis** [maptalks/maptalks.js#1246]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
wmts是支持的, 用法和[加载ArcGIS的瓦片服务](https://maptalks.org/examples/cn/tilelayer-projection/arcgis-tile/#tilelayer-projection_arcgis-tile)差不多。[源代码](https://github.com/maptalks/maptalks.js/blob/master/src/map/spatial-reference/SpatialReference.WMTS.js)
不过还没写example，我会找个时间增加一下示例。

wfs目前还不支持，这个服务用的人多吗？感觉现在大家都喜欢用rest服务来代替了。

**Comment by fuzhenn** [comment]
https://maptalks.org/examples/cn/tilelayer-projection/wmts-tile/#tilelayer-projection_wmts-tile
加载WMTS的示例

WFS暂时不计划实现，需求更多时再考虑
