### ISSUE TITLE
maptalks symbol 'stops' bug

### ISSUE THREAD

**Issue by whiteMelody** [maptalks/maptalks.js#1248]
maptalks version 0.49.1

整体Opacity未生效，markerFill未生效，markerFillOpacity未生效，textSize报错

bug地址
https://codepen.io/whitemelody/pen/WNxvyrG

**Comment by fuzhenn** [comment]
opacity已经在https://github.com/maptalks/maptalks.js/commit/c1f2a71cc8b68c3aae899ca638ccc2da10082f9c 中增加支持。
markerFill，markerFillOpacity等用来生成marker图片的属性目前不支持function-type
