### ISSUE TITLE
2k 4k 大屏下 groupTileLayer 遇到渲染问题

### ISSUE THREAD

**Issue by hey-ksource** [maptalks/maptalks.js#1262]
**maptalks's version and what browser you use?**
---- 0.49.1

**Issue description**
---- 2k 4k 大窗口（2100px+ * 1050px+）下 groupTileLayer 渲染遇到问题，会导致 tile 丢失，tile 图片网络请求正常。

**Please provide a reproduction URL (on any jsfiddle like site)**
---- [codepen](https://codepen.io/ksource-demo/pen/OJXRPeQ) 
---- [复现录屏 ]( https://tile-cdn.terraqt.com/sq-upload/8DCCA90DBB007E35FDE005FC8AF1C111.mp4)

**Comment by fuzhenn** [comment]
这个应该是maxCacheSize的问题，瓦片数量超过了最大缓存数量导致。

可以试试把GroupTileLayer options里的maxCacheSize设为合适的值，例如1024，再看是否解决。

**Comment by wang2lang** [comment]
已解决，感谢！
