### ISSUE TITLE
使用echarts-gl时，infowindow被柱状图遮挡

### ISSUE THREAD

**Issue by Renkosky** [maptalks/maptalks.js#1272]
**maptalks's version and what browser you use?**
----

> v0.49.1

**Issue description**
----
使用echarts-gl时，infowindow被柱状图遮挡

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/renkosky/pen/jOrxVVY
点击柱子后展示infoWindow，我希望infowindow能盖住柱状图，但是通过改zindex好像也没用

**Comment by deyihu** [comment]
@Renkosky  https://github.com/maptalks/maptalks.js/issues/823

**Comment by Renkosky** [comment]
> @Renkosky #823

感谢，我试试这个插件
