### ISSUE TITLE
Loading Geojson from Geoserver

### ISSUE THREAD

**Issue by jose-sanchez-morales** [maptalks/maptalks.js#1273]
**maptalks's version and what browser you use?**
----
maptalks v0.49.1

**Issue description**
----
I'm trying to load a Geojson composed by several polygons from Geoserver by using a WFS request:
https://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html

This will output a JSON file
i.e. {"type":"FeatureCollection","features":[{"type":"Feature","id":"survey_area.1526","geometry":{"type":"MultiPolygon","coordinates":[[[............

How can we ingest these polygons into Maptalks as a Polygon layer?

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@jose-sanchez-morales  https://maptalks.org/maptalks.js/api/0.x/GeoJSON.html

**Comment by ngcccc** [comment]
https://maptalks.org/maptalks.js/api/0.x/GeoJSON.html
这个地址的demo报错啊，如果geojson包含多个Polygon这个格式到底如何？
