### ISSUE TITLE
如何应对带有海拔高度的polygon边缘被截取？

### ISSUE THREAD

**Issue by shmen** [maptalks/maptalks.js#1274]
![QQ截图20201109160059](https://user-images.githubusercontent.com/30108864/98514675-cd57db00-22a4-11eb-991d-43e5009d6dd9.png)

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.js/commit/da78956b6c59fd58a760b11703542c8ba6f993cc @fuzhenn
