### ISSUE TITLE
@fuzhenn 更新783d189 后，发现设置offset后底图能正常显示了，但是缩放地图会出现抖动的情况。

### ISSUE THREAD

**Issue by sys2007** [maptalks/maptalks.js#1278]
@fuzhenn 更新783d189 后，发现设置offset后底图能正常显示了，但是缩放地图会出现抖动的情况。

_Originally posted by @sys2007 in https://github.com/maptalks/maptalks.js/issues/1237#issuecomment-723939618_

**Comment by fuzhenn** [comment]
收到，能否提供一个重现代码？谢谢

**Comment by sys2007** [comment]
https://codepen.io/fuzhenn-the-decoder/pen/KKzEpry

**Comment by sys2007** [comment]
https://codepen.io/fuzhenn-the-decoder/pen/KKzEpry

**Comment by sys2007** [comment]
https://codepen.io/sys2007/pen/pobqydz

**Comment by sys2007** [comment]
https://codepen.io/sys2007/pen/pobqydz
地图进行缩放会抖动。

**Comment by sys2007** [comment]
> 收到，能否提供一个重现代码？谢谢

https://codepen.io/sys2007/pen/pobqydz
地图进行缩放会抖动。
@fuzhenn

**Comment by fuzhenn** [comment]
offset改写一下就行了：
https://codepen.io/fuzhenn-the-decoder/pen/vYgPKeQ
