### ISSUE TITLE
InfoWindow中内容比较多的时候出现滚动条，鼠标中键滚轮滚动时内容不能滚动

### ISSUE THREAD

**Issue by liangxuegang01** [maptalks/maptalks.js#1280]
**maptalks's version and what browser you use?**
----

**Issue description**
----
InfoWindow中内容比较多的时候出现滚动条，鼠标中键滚轮滚动时内容不能滚动，只能拖动滚动条才能显示更多内容。

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by ProgrammingAndersen** [comment]
我也遇到这样的问题，请问有解决办法吗

**Comment by deyihu** [comment]
close by https://github.com/maptalks/maptalks.js/pull/1869
