### ISSUE TITLE
Is it possible to stretch tiles from a lower zoom level to a higher one?

### ISSUE THREAD

**Issue by AnatolyAG** [maptalks/maptalks.js#1281]
Good day
Is it possible to stretch tiles from a lower zoom level to a higher one?

**maptalks's version and what browser you use?**
i am use 
maptalks v0.47.3
maptalks.markercluster v0.8.3
maptalks.formats v0.3.0
maptalks.three v0.12.2

browser
chrome - 86.0.4240.198 64bit
firefox 82.0.3 64bit

**Issue description**
----
I'm using the tile source as my basemap
`'urlTemplate': 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}'`

it has tiles up to zoom level 18

can I somehow limit the output of tiles to this level?
that is, when the map is at 19 - 24 zoom, the tiles of the substrate were taken from the 18 zoom.

in the leaflet there is a possibility to do this using the options maxNativeZoom and minNativeZoom
quote from doc:
> Maximum zoom number the tile source has available. If it is specified, the tiles on all zoom levels higher than maxNativeZoom will be loaded from maxNativeZoom level and auto-scaled.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@AnatolyAG  https://codepen.io/deyihu/pen/bGeZVoP

**Comment by wang2lang** [comment]
maxAvailableZoom

**Comment by AnatolyAG** [comment]
Thank you very much, I missed this property in the description, I'm sorry to bother you, it's my mistake, I didn't look closely.
Thanks again for your prompt reply.
