### ISSUE TITLE
groupTileLayer不能通过修改zIndex显示在Layer上面

### ISSUE THREAD

**Issue by blackOfMelody** [maptalks/maptalks.js#1282]
groupTileLayer不能通过修改zIndex显示在Layer上面

**Comment by deyihu** [comment]
一般都是将图层设置为baseLayer导致的，baseLayer永远都是第一个绘制的，所以想控制层级不要将图层设置为baseLayer即可

https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/DETU/changjianwenti.html#%E5%85%B3%E4%BA%8E%E5%9C%B0%E5%9B%BE%E7%9A%84baselayer
