### ISSUE TITLE
百度瓦片缩放到第5级左右两端没有连起来出现大片空白

### ISSUE THREAD

**Issue by hbliyafei** [maptalks/maptalks.js#1285]
maptalks-0.49.1

百度瓦片缩放到第5级左右两端没有连起来出现大片空白

网站上的示例也有这个问题
https://maptalks.org/examples/cn/tilelayer-projection/baidu/#tilelayer-projection_baidu

**Comment by deyihu** [comment]
同样的问题 https://github.com/maptalks/maptalks.js/issues/2107
