### ISSUE TITLE
Polygon is skewed because common porjection code

### ISSUE THREAD

**Issue by foolseafish** [maptalks/maptalks.js#1286]
First of all, thank you for amazing maptalks. it helps me a lot.

**maptalks's version and what browser you use?**
----
 0.49.1

**Issue description**
---- 
When i get a polygon 'dx >180', it looks quite strange. some coordinates out of the world extent.

`if (Math.abs(dx) > 180) {  
    if (wrapX === undefined) {  
        wrapX = current.x > pre.x;  
    }  
    if (wrapX) {  
        p._add(-circum.x * sign(dx) * sx, 0);  
        current._add(-360 * sign(dx), 0);  
    }  
}  
if (Math.abs(dy) > 90) {  
    if (wrapY === undefined) {  
        wrapY = current.y < pre.y;  
    }  
    if (wrapY) {  
        p._add(0, -circum.y * sign(dy) * sy);  
        current._add(0, -180 * sign(dy));  
    }  
}`  
[Projection.js](https://github.com/maptalks/maptalks.js/blob/master/src/geo/projection/Projection.js) Line 61

I really want to know what the code wrote for.

**Comment by fuzhenn** [comment]
This is to wrap polygon crossing the anti-meridian line to solve the "anti-meridian artifacts" problem.

You can refer to [this stackoverflow question](https://stackoverflow.com/questions/40532496/wrapping-lines-polygons-across-the-antimeridian-in-leaflet-js) for more details.

And you can provide a codepen reproduction, I will have a check if there is anything wrong.

**Comment by foolseafish** [comment]
Thank you for reply.
I have understood.
