### ISSUE TITLE
地图上面天空部分不能响应鼠标事件

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#1287]
**maptalks's version and what browser you use?**
----
v0.49.1

**Issue description**
----
地图上面天空部分不能响应鼠标事件。
![image](https://user-images.githubusercontent.com/5208386/100304622-182e5e00-2fda-11eb-926f-1612bf3a0d29.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
目前是设计如此，因为点击天空没有合法的地理坐标
