### ISSUE TITLE
请问地图框选元素如何实现？

### ISSUE THREAD

**Issue by sinlger** [maptalks/maptalks.js#1288]
**maptalks's version and what browser you use?**
0.49.1

**Comment by deyihu** [comment]
@sinlger  

1. 前台直接计算，利用turf.js/jsts.js

2. 后台计算，前台绘制好图形，将其坐标传到后台，后台利用空间数据库（postgis/mysql/oracle等） 或者空间计算库（geotools等)进行查询

1. 将数据发布成服务(arcgis/geoserver)，利用其空间分析能力

**Comment by sinlger** [comment]
谢谢 可以了
