### ISSUE TITLE
建议使用 TypeScript 对项目进行重写

### ISSUE THREAD

**Issue by wang2lang** [maptalks/maptalks.js#1289]
**maptalks's version and what browser you use?**
----
latest

**Issue description**
----
maptalks 已经是非常复杂的项目了，有精力的话建议使用 TypeScript 进行一次重写，这对未来项目的长期发展绝对是利大于弊的；

目前 TypeScript 已经非常成熟且强大，非常适合用在 maptalks 这类大型复杂的项目中，减少 bug ，保证健壮性；

越来越多前端项目开始使用 TypeScript 来开发，尤其是 GIS 这种天生就比较复杂的项目。使用 TypeScript 开发可以让 maptalks 适应未来；

可以发动社区愿意参与重写的开发者参与进来；

**Comment by fuzhenn** [comment]
谢谢建议。

我和同事们讨论了一下，考虑到maptalks核心库目前已经相对稳定，未来1.0版发布后也不会增加新的功能。

所以用ts重写不是很有必要。未来若开发新的插件时，可以考虑直接用ts来写。
