### ISSUE TITLE
使用瓦片地图缩小到一定程度，如何控制左右循环，上下高度限制，不要留有空白，跟原生地图类似

### ISSUE THREAD

**Issue by freezyh** [maptalks/maptalks.js#1290]
maptalks-0.49.1

使用瓦片地图缩小到一定程度，如何控制左右循环，上下高度限制，不要留有空白，跟原生地图类似

网站上的示例有空白
https://maptalks.org/examples/cn/tilelayer-projection/baidu/#tilelayer-projection_baidu

**Comment by liulianfan** [comment]
地图初始化时设置合理的maxExtent范围就好了

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.js/issues/2107
