### ISSUE TITLE
请问有没有将获取到的Coordinates转换为直角坐标系的方法

### ISSUE THREAD

**Issue by lanny-zhang** [maptalks/maptalks.js#1292]
**maptalks's version and what browser you use?**
----

**Issue description**
----
用了你们的插件去开发画线和选定区域的功能，没有用到地图，但是拿到的坐标好像都是经纬度，能不能提供一个配置使用直角坐标系的选项，或者有没有将经纬度转换为直角坐标系的方法呢

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以采用identity投影，它就是一个简单的直角坐标系，示例：
https://maptalks.org/examples/cn/tilelayer-projection/identity/#tilelayer-projection_identity
