### ISSUE TITLE
同一个图层中的marker 的InfoWindow 有些正常，有些会自动关闭

### ISSUE THREAD

**Issue by tangjuncheng1986** [maptalks/maptalks.js#1295]
marker.setInfoWindow({
                        custom: true,
                        dx: dx,
                        dy: dy,
                        content: el,
                        autoOpenOn:true
                        //single: true,
                      });
                      marker.openInfoWindow();
使用同样的点击方式，有些marker可以弹窗，有些就会自动关闭，样式变成 display: none
![image](https://user-images.githubusercontent.com/19219876/102293427-09f0b380-3f82-11eb-8976-49f614744a2e.png)

![image](https://user-images.githubusercontent.com/19219876/102293269-b7af9280-3f81-11eb-9ec2-3a39a91c612d.png)

**Comment by fuzhenn** [comment]
不是很明白，能否给个重现代码？

**Comment by deyihu** [comment]
一般都是多个infowindow的content引用了同一个dom节点导致的，当新的infowindow打开，content dom节点会被加入新的dom元素，导致老的infowindow content里的dom（dom节点的父节点变更了）被移除导致的，应该多例
