### ISSUE TITLE
 v1.0.0-alpha.14 drawTool enable 之后地图无法拖动

### ISSUE THREAD

**Issue by hey-ksource** [maptalks/maptalks.js#1299]
drawTool.enable() 之后地图无法拖动
disable() 之后可以

是有什么新的配置吗？

**Comment by fuzhenn** [comment]
这是正常的，drawTool启用之后，地图的事件就被drawTool接管了。

**Comment by hey-ksource** [comment]
> 这是正常的，drawTool启用之后，地图的事件就被drawTool接管了。

现在要开启 drawTool 之后也能拖动地图，有办法吗

**Comment by fuzhenn** [comment]
这个不行。。drawTool的事件逻辑就和map的冲突了

**Comment by hey-ksource** [comment]
> 这个不行。。drawTool的事件逻辑就和map的冲突了

v0.49 还是可以的【难受

**Comment by wang2lang** [comment]
drag 这个事件是可以单独拎出来给地图的吧？ 跟 drawTool 里用到的事件不冲突
