### ISSUE TITLE
Marker没有配置markerFile旋转的属性

### ISSUE THREAD

**Issue by freezyh** [maptalks/maptalks.js#1303]
**maptalks's version and what browser you use?**
----
0.49.1"

**Issue description**
----
Marker没有配置旋转的属性，只有配置icon的路径和宽高

**Please provide a reproduction URL (on any jsfiddle like site)**
----
在官文档
var profile = {
            "feature": {
                  "type": "Feature",
                  "id" : "point1",
                  "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
                  "properties": {"prop0": "value0"}
            },
            //construct options.
            "options":{
                "draggable" : true
            },
            //symbol
            "symbol":{
                "markerFile"  : "http://foo.com/icon.png",
                "markerWidth" : 20,
                "markerHeight": 20
            },
            //infowindow info
            "infowindow" : {
                "options" : {
                    "style" : "black"
                },
                "title" : "this is a infowindow title",
                "content" : "this is a infowindow content"
            }
        };

**Comment by fuzhenn** [comment]
可以用 markerRotation 来设置旋转

https://maptalks.org/examples/cn/style/rotate-marker/#style_rotate-marker
