### ISSUE TITLE
在使用map.animateTo同时缩放和旋转时ImageLayer图层有明显bug

### ISSUE THREAD

**Issue by zhaowgit** [maptalks/maptalks.js#1308]
**maptalks's version and what browser you use?**
----
0.49.1

**Issue description**
----
我使用map.animateTo函数是地图同时旋转和缩放，在这个过程中ImageLayer中的图片只做了低分辨率的缩放，不能旋转，在动画结束时突然恢复正常。
我试了单独旋转的时候没有问题，单独缩放的时候是低分辨率的缩放，动画结束才恢复清晰度。
其他图层没有这个问题。

还有我的ImageLayer图层forceRenderOnMoving forceRenderOnZooming forceRenderOnRotating都是true

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
能否提供一个重现代码？

**Comment by zhaowgit** [comment]
初始状态大概是这样
`var map = new maptalks.Map('map', {
        center: BaseGPSExtent.getCenter(),
        zoom: 17,
        bearing: 50,
        maxExtent: BaseGPSExtent,
        dragPitch: false,
        touchPitch: false,
        baseLayer: new maptalks.TileLayer('base', {
            urlTemplate: 'http://mt1.google.cn/vt/lyrs=s&x={x}&y={y}&z={z}',
        })
    });
    map.on('click', function (e) {
        console.log(e)
    });

    var mapLayer = new maptalks.ImageLayer('map',
        [
            {
                url: '@Url.Content("~/image/location/map/map.png")',
                extent: BaseGPSExtent,
                opacity: 1,
            },
        ],
        {
            forceRenderOnMoving: true,
            forceRenderOnZooming: true,
            forceRenderOnRotating: true
        }).addTo(map);

    var personLayer = new maptalks.VectorLayer('person',
        {
            zIndex: 100,
            forceRenderOnMoving: true,
            forceRenderOnZooming: true,
            forceRenderOnRotating: true
        }).addTo(map);

    var railLayer = new maptalks.VectorLayer('rail',
        {
            zIndex: 1,
            visible: true,
            forceRenderOnMoving: true,
            forceRenderOnZooming: true,
            forceRenderOnRotating: true
        }).addTo(map);

    var ibeaconLayer = new maptalks.VectorLayer('ibeacon',
        {
            zIndex: 2,
            visible: true,
            forceRenderOnMoving: true,
            forceRenderOnZooming: true,
            forceRenderOnRotating: true
        }).addTo(map);`


动画代码大概是这样
`map.animateTo({
            zoom: 17,
            bearing: 0
        }, {
            duration: 3000
        });`

**Comment by fuzhenn** [comment]
能否用codepen.io提供一个可以实际运行的例子？谢谢

打开[这个示例](https://maptalks.org/examples/cn/map/load/#map_load)，点右上角的编辑，复现后保存，把url发到这里即可。

**Comment by zhaowgit** [comment]
我研究了下那个网站，js图片跨域报错，怎么在js代码里访问跨域图片

**Comment by fuzhenn** [comment]
可以把图片转成base64后，贴到属性里

**Comment by zhaowgit** [comment]
https://codepen.io/zhaowcode/pen/jOMpKWx

**Comment by zhaowgit** [comment]
整个过程图片的动画明显缺失

**Comment by fuzhenn** [comment]
可以试试创建图层时，在options里添加以下几个属性
```js
const imageLayer = new maptalks.ImageLayer('image', images, { 
  forceRenderOnZooming: true,
  forceRenderOnRotating: true
});
```

**Comment by zhaowgit** [comment]
还是那个地址，我已经加上了，问题依旧。
事实上我在实际项目上一直都有这个设置，一直有问题。
