### ISSUE TITLE
openlayers上能加载的瓦片图层在maltalks上无法加载

### ISSUE THREAD

**Issue by Rain20199** [maptalks/maptalks.js#1309]
**maptalks's version and what browser you use?**
----
chrome

**Issue description**
----
在openlayers上能正常加载显示,maptalks无法加载,图片全是404

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://mcc.daobo-elec.com/tms/370200000000/tiles/{z}/{x}/{y}.png

**Comment by fuzhenn** [comment]
能否提供一个重现代码？谢谢
