### ISSUE TITLE
请问下能否支持拓扑编辑?

### ISSUE THREAD

**Issue by wuqi** [maptalks/maptalks.js#1315]
**maptalks's version and what browser you use?**
V0.49.1

**Issue description**
现在好像没有支持拓扑编辑,比如切割,合并,挖洞等,openlayers是支持使用turf或者jsts之类的库对数据进行处理的,有啥办法进行处理么

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
geometry都能用toGeoJSON方法转成geojson，所以你可以自己用turf，jsts来实现拓扑编辑。

因为实现简单，maptalks就不直接集成了。
