### ISSUE TITLE
使用默认的3857坐标系加载天地图球型墨卡托投影偏差很大

### ISSUE THREAD

**Issue by shmen** [maptalks/maptalks.js#1316]
```
var map = new maptalks.Map("map", {
        center: [119.4079706689, 32.3955292132],
        zoom: 14,
        minZoom: 1,
        maxZoom: 18,
        baseLayer: new maptalks.TileLayer("base", {
            tileSystem: [1,-1,-180,180],
            urlTemplate:
                "http://t{s}.tianditu.com/DataServer?T=vec_w&x={x}&y={y}&l={z}&tk=de0dc270a51aaca3dd4e64d4f8c81ff6",
            subdomains: ["1", "2", "3", "4", "5"],
            attribution: '&copy; <a target="_blank" href="http://www.tianditu.cn">Tianditu</a>'
        })
    });
```
直接使用默认坐标系加载，坐标位置和地图都有错乱，不知道是不是我的写法不对
![image](https://user-images.githubusercontent.com/30108864/105961384-65ea4400-60b9-11eb-8163-e759babf49c4.png)

**Comment by fuzhenn** [comment]
map和底图投影不同时，是不能直接加载的
有两个解决方案：
* 把map的投影改为4326投影 [示例](https://maptalks.org/examples/cn/tilelayer-projection/epsg4326/#tilelayer-projection_epsg4326)
* 给TileLayer指定单独的空间参考 [示例](https://maptalks.org/examples/cn/tilelayer-projection/different-projection/#tilelayer-projection_different-projection)，但因为瓦片缩放问题，在小级别下会存在一些绘制误差。
