### ISSUE TITLE
Replicating the map on the maptalks.org homepage

### ISSUE THREAD

**Issue by scottwvw** [maptalks/maptalks.js#1328]
Hi

I'm trying to replicate the map on [maptalks.org](https://maptalks.org/) (the white outline based on polygon shapes), I've managed to locate the code and get it mostly working, however there are a few points on the map which seem to be aligning badly (see below).

I wondered if there is a quick fix? Or if there is a tutorial I can follow to replicate the style.

![image](https://user-images.githubusercontent.com/7535883/107802312-12ceed00-6d59-11eb-8de3-2b8fc89acfb4.png)

**Comment by fuzhenn** [comment]
this is caused by [anti-meridian problem](https://github.com/rstudio/leaflet/issues/553), you can try to update polygon's orientation from clockwise to counterclockwise (or vice-versa) to see if it can fix the problem.

**Comment by scottwvw** [comment]
Hmm, I'm not sure how to go about that, is there an easy way of changing the orientation?
