### ISSUE TITLE
如何自定义一个比例尺

### ISSUE THREAD

**Issue by hey-ksource** [maptalks/maptalks.js#1329]
![image](https://user-images.githubusercontent.com/63158329/108584969-542a5280-7380-11eb-9830-236162990ae3.png)

就是这个，API 翻了翻好像没有现成的
有没有办法通得到当前地图缩放层级 对应的比例尺长度和数值

**Comment by huronzhu** [comment]
我也在找这个

**Comment by huronzhu** [comment]
我在这里找到了答案 https://www.jianshu.com/p/4ddc870f9528
