### ISSUE TITLE
TileLayer 对象的 setOptions({ tileSystem: '' }) 不生效

### ISSUE THREAD

**Issue by wang2lang** [maptalks/maptalks.js#1330]
**maptalks's version and what browser you use?**
----
最新版本

**Issue description**
----
1. tileLayer.setOptions({ urlTemplate: url }) 设置后，当前已渲染的tile图片不会被替换，当操作地图时会拉新的 url
2. tileLayer.setOptions({ tileSystem: 'tms-global-mercator' }) 设置后，不生效。在1中操作地图，拉的是新的 url，用的是初始化的 tileStystem

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
不用setOptions方法，而是用 tileLayer.config({ urlTemplate: url }) 试试

**Comment by wang2lang** [comment]
还是没有生效，看了源码，config 方法对于 urlTemplate 的变更 跟 setOptions 没啥区别

**Comment by fuzhenn** [comment]
的确，tilelayer中需要增加onConfig处理，来重新绘制瓦片

**Comment by deyihu** [comment]
```
tilelayer.forceReload()
```
