### ISSUE TITLE
Use ImageBitmap to improve Marker render performance

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#1335]
**maptalks's version and what browser you use?**
----

**Issue description**
----

https://developer.mozilla.org/zh-CN/docs/Web/API/ImageBitmap
**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by The-End-Hero** [comment]
![image](https://user-images.githubusercontent.com/19590233/117282349-39ec1500-ae97-11eb-81c6-26fc623ad8aa.png)

**Comment by fuzhenn** [comment]
closed by #1370
