### ISSUE TITLE
测量工具 Distance 或 Area 画出来的线和面会被带 zIndex 的 TileLayer 或 VectorLayer 遮住

### ISSUE THREAD

**Issue by wang2lang** [maptalks/maptalks.js#1336]
**maptalks's version and what browser you use?**
----
最新版

**Issue description**
----
如果在 TileLayer，VectorLayer 使用 zIndex，那么地图工具里的测量如 distance 或 area **画出来的多边形会被隐藏** TileLayer 和 VectorLayer 后面。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://output.jsbin.com/qagaqoyiqi

**Comment by wang2lang** [comment]
目前将所有 TileLayer 的 zIndex 设为负数解决了目前的问题，通过负数大小来控制图层前后的相对位置。
建议给测量工具默认 zIndex 一个极大值，这样就不用通过上面的方法 hack 了

**Comment by fuzhenn** [comment]
正在改写geometry edit和draw tool。
新的实现中，draw tool和edit都会画在最顶层，不受图层影响，应该也能顺便解决这个问题。
