### ISSUE TITLE
MultiPolygon startEdit后无法更新Symbol  （updateSymbol textName不起作用）

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/maptalks.js#1343]
**maptalks's version and what browser you use?**
----
最新版本mtk

**Issue description**
----
MultiPolygon startEdit后无法更新Symbol  （updateSymbol textName不起作用）

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/the-end-hero/pen/VwPPOve

**Comment by deyihu** [comment]
这个不算bug，geometry处于编辑状态时，geometry处于冷冻状态，因为mtk处理编辑时是copy一个新的geometry，真实的geometry被隐藏了，所以如果你想更新symbol的话，
- 需要在编辑之前updateSymbol
- 如果当前geometry处于editing,你可以先关闭edit,然后更新，然后在开启
https://codepen.io/deyihu/pen/mdYKmrx
