### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/maptalks.js#1346]
**maptalks's version and what browser you use?**
----
0.49.2

**Issue description**
----
分批添加marker，之后删除，在layer的geolist上仍然保留引用
内存泄漏

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/the-end-hero/pen/WNRJoxM?editors=1010

**Comment by fuzhenn** [comment]
谢谢提issue。
不过奇怪，我这里运行示例的结果是正确的：
![image](https://user-images.githubusercontent.com/13678919/114807336-d2cbcb00-9dd8-11eb-857e-87de9bc07865.png)

**Comment by The-End-Hero** [comment]
打开控制台，刷新几次，会有比较大的概率出现保留引用的情况。

**Comment by fuzhenn** [comment]
已经重现了，原因是marker设置了zIndex，但因为下一帧才会排序的性能优化，导致removeGeometry时，geometry没有在正确的顺序上，所以折半查找没有找到这个geometry。

已经修改并发布了新版本,0.49.3
