### ISSUE TITLE
GroupTileLayer 增加 setLayers 方法

### ISSUE THREAD

**Issue by wang2lang** [maptalks/maptalks.js#1348]
**maptalks's version and what browser you use?**
----
最新版

**Issue description**
----
需要动态更新 GroupTileLayer 的 layers 

**Please provide a reproduction URL (on any jsfiddle like site)**
----
我现在自己用如下代码实现：
```
class GroupTileLayer extends maptalks.GroupTileLayer {
  setLayers(layers) {
    const map = this.getMap();
    this.onRemove();
    this.layers = layers;
    this.onAdd();
    map.removeLayer(this);
    map.addLayer(this);
  }
}
```

**Comment by fuzhenn** [comment]
收到，下个版本会增加这个接口

**Comment by just-ads** [comment]
> 收到，下个版本会增加这个接口

可以增加addLayers方法吗，向GroupTileLayer中增加新的子TileLayers
