### ISSUE TITLE
maptalks的官网无法打开了

### ISSUE THREAD

**Issue by xby020** [maptalks/maptalks.js#1351]
**maptalks's version and what browser you use?**
----

**Issue description**
----
maptalks的官网无法打开了，是正在改版吗？
**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://maptalks.org/

**Comment by fuzhenn** [comment]
我这里能正常访问（电信直接连接）
网站是托管在cloudflare上的，可能你的所在区域把cloudflare禁了。
可以试试科学上网后能否访问。
