### ISSUE TITLE
如何在地图上显示瓦片的xy坐标用于debug

### ISSUE THREAD

**Issue by hptangxi** [maptalks/maptalks.js#1353]
**请问怎样可以在地图上显示出瓦片的x,y,z坐标，类似于openlayers的TileDebug功能，如下图**

<br />

**或者是否有把瓦片的x、y、z转换成地理坐标的办法呢?**

<br />

![image](https://user-images.githubusercontent.com/30829093/116342086-9b1b4500-a814-11eb-99e6-ba493fdc3fa3.png)

**Comment by fuzhenn** [comment]
创建TileLayer时，options里把debug设成true就行了。
xyz和地理坐标得转换方法在 TileConfig.js 里，tileLayer._getTileConfig() 可以获取到
