### ISSUE TITLE
1.0.0-alpha.15 infoWindow位置显示错误

### ISSUE THREAD

**Issue by sophiewf** [maptalks/maptalks.js#1354]
在marker上面设置了infoWindow，点击的时候，alpha.15不能把顶部的marker的infoWindow的位置置于map的中间。
当marker在左、右、下都是可以的。
在0.49.3就会很好的进行显示

https://user-images.githubusercontent.com/9076905/116345441-affad700-a81a-11eb-8b81-3be31ffe16a6.mp4

这个是alpha.15的效果

https://user-images.githubusercontent.com/9076905/116345465-be48f300-a81a-11eb-8572-79058c1b1adb.mp4

这个是0.49.3的效果

代码是完全一样的。怀疑是不是绑定的layer造成的。

**Comment by fuzhenn** [comment]
因为没有重现代码，暂时无法判定问题在哪里。
该问题可能和今天改好的 #1512 有关。
先关闭此issue，如果在新版本上仍然有问题，欢迎来提新的issue或者重新打开该issue。
