### ISSUE TITLE
如何安全销毁地图对象

### ISSUE THREAD

**Issue by SamuelSue94** [maptalks/maptalks.js#1358]
**maptalks's version and what browser you use?**
0.49.4

**Issue description**
因为业务需要切换多个地图，编写了一个vue组件来做地图，外部父组件通过v-if控制地图组件的销毁和创建，目前通过chrome任务管理器检测标签页所占内存越来越高。想请问一下如何安全的销毁map对象。

**Please provide a reproduction URL (on any jsfiddle like site)**
https://codesandbox.io/s/jovial-microservice-t4y6j?file=/src/components/MTMap.vue

**Comment by mankeheaven** [comment]
map.remove()
map = null
这样就销毁了

另外，由于data会作为响应式数据，其实是不合理的，它更应该是个单例的全局引用，比如ref之类的，但是vue2的ref功能太薄弱了，具体vue2中如何存这个map为单例，你自己根据情况调节一下，比如我会在上方let map = null,然后组件里用map=xxx
```
当你把一个普通的 JavaScript 对象传入 Vue 实例作为 data 选项，Vue 将遍历此对象所有的 property，并使用 Object.defineProperty 把这些 property 全部转为 getter/setter。Object.defineProperty 是 ES5 中一个无法 shim 的特性，这也就是 Vue 不支持 IE8 以及更低版本浏览器的原因。

这些 getter/setter 对用户来说是不可见的，但是在内部它们让 Vue 能够追踪依赖，在 property 被访问和修改时通知变更。这里需要注意的是不同浏览器在控制台打印数据对象时对 getter/setter 的格式化并不同，所以建议安装 vue-devtools 来获取对检查数据更加友好的用户界面。

每个组件实例都对应一个 watcher 实例，它会在组件渲染的过程中把“接触”过的数据 property 记录为依赖。之后当依赖项的 setter 触发时，会通知 watcher，从而使它关联的组件重新渲染。
```
