### ISSUE TITLE
Wheel scroll event

### ISSUE THREAD

**Issue by daumjs** [maptalks/maptalks.js#1359]
I want to scroll from the Map Contact menu, but 'scrollWheelZoom=true' is not enough.
Works when 'scrollWheelZoom = false'.
Is it possible to scroll from the context menu while 'scrollWheelZoom = true'?

**Comment by fuzhenn** [comment]
Hmm.. unfortunately,  it seems to be impossible now.
But maybe it can be solved by not to stop event propagation when event is originated from context menu?

**Comment by daumjs** [comment]
Yes, I think it will be solved if the events in context menu are not blocked.
