### ISSUE TITLE
MaxZoom limited 20?

### ISSUE THREAD

**Issue by AnatolyAG** [maptalks/maptalks.js#1360]
**maptalks's version and what browser you use?**
V0.49.4
Chrome 0.0.4430.212 (Официальная сборка), (64 бит)

**Issue description**

Set maxZoom more than 20 does not work

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
You need to customize a spatial reference, pls refer to this [example](https://maptalks.org/examples/en/tilelayer-projection/custom-tile/)
