### ISSUE TITLE
关于LineString的animateShow占用CPU高的问题

### ISSUE THREAD

**Issue by jerrylyj** [maptalks/maptalks.js#1368]
**maptalks's version and what browser you use?**
----
v0.49.4、Chome、遨游

**Issue description**
----
你好，这边有用到linestring，并且使用animateShow来绘制动画效果。
遇到一个问题是，当线的点比较多时，duration比较长时，浏览器CPU占用有点高，大概在15~20%。
比较消耗资源，应该不是使用问题吧，有优化空间吗:)

https://codepen.io/jerrylyj/pen/gOmjKrG
有在Codepen上基于linestring的动画加了些数据，可以看下效果

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
确实有着这个问题，当节点比较多时：

- 动画函数里要计算当前动画到哪个节点(计算量有点大)
- 动画是要重置线条的坐标集合(计算量比较大)
- 将经纬度坐标转成屏幕坐标(计算量比较大)
- canvas要将所有点进行重绘(渲染量比较大)

平时绘制时，是做了简单的简化的(simplify),所有看不出来这个问题，动画时用的全量坐标

https://github.com/maptalks/maptalks.js/blob/904c54a71f52cb70c37348bea86e66eac55a3dbf/src/geometry/Path.ts#L93
