### ISSUE TITLE
drawAltitude中的polygonFill无法传入数组从而设置不同数据不同样式

### ISSUE THREAD

**Issue by APengragon** [maptalks/maptalks.js#1376]
var map = new maptalks.Map("map", {
        center: [120.132398, 30.18717],
        zoom: 14,
        pitch: 56,
        bearing: 60,
        baseLayer: new maptalks.TileLayer("base", {
          urlTemplate:
            "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
          subdomains: ["a", "b", "c", "d"],
        }),
      });
      var line = new maptalks.LineString(
        [
          [120.132398, 30.18717],
          [120.13316, 30.187342],
        ],
        {
          symbol: {
            lineColor: "#FF69B4",
            lineWidth: 3,
          },
          properties: {
            altitude: [100, 400],
          },
        }
      );
      var line1 = new maptalks.LineString(
        [
          [120.13316, 30.187342],
          [120.13434, 30.187646],
        ],
        {
          symbol: {
            lineColor: "#1bbc9b",
            lineWidth: 3,
          },
          properties: {
            altitude: [400, 500],
          },
        }
      );
      var line2 = new maptalks.LineString(
        [
          [120.13434, 30.187646],
          [120.135492, 30.18796],
        ],
        {
          symbol: {
            lineColor: "#8B008B",
            lineWidth: 3,
          },
          properties: {
            altitude: [500, 600],
          },
        }
      );
      var layer = new maptalks.VectorLayer("vector", [line, line1, line2], {
        enableAltitude: true,
        drawAltitude: {
          polygonFill: ["#FF69B4", "#1bbc9b", "#8B008B"],
          polygonOpacity: 0.3,
          lineWidth: 0,
        },
      });
      layer.addTo(map);

https://codepen.io/apengragon/pen/QWpXjxK
传入数组颜色可以渲染但是无法正确排序，并且缩放会消失

**Comment by gazhay** [comment]
Polygon fills and line colours do not sync up correctly - line colors seems to be correct but polygon fills is offset for some reason

**Comment by gazhay** [comment]
![image](https://github.com/maptalks/maptalks.js/assets/871127/234561c3-58f2-4ad0-80ec-26bd1c39d943)

e.g.

```
polyLines.push(new maptalks.LineString(
                        lines[j],{
                            properties:{
                                'altitude': altitudes[j]
                            },
                            symbol:{
                                'lineColor' : colors[j],
                                'lineWidth' : 3,
                            }
                        }
                    ));
```
```
let Layer = new maptalks.VectorLayer('vector', polyLines, {
                    enableAltitude : true,
                    drawAltitude   : {
                        polygonFill    : colors,
                        polygonOpacity : 0.5,
                        lineWidth      : 0
                    }
                }).addTo(map);
```

lineColor is correct, polyfill is offset by 1

**Comment by fuzhenn** [comment]
cc @deyihu
