### ISSUE TITLE
官网示例疑似错误

### ISSUE THREAD

**Issue by ok958726** [maptalks/maptalks.js#1386]
**maptalks's version and what browser you use?**
----

0.49.4
**Issue description**
----
在细微缩放的示例里，看不到什么效果，是不是应该把是不是应该在map的options里加上seamlessZoom:true

**Please provide a reproduction URL (on any jsfiddle like site)**
----
添加后的效果：
https://codepen.io/ok958726/pen/yLbNxeW

**Comment by fuzhenn** [comment]
噢，当时写这个demo的时候，还不支持seamlessZoom，只是演示了可以把级别设为非整数级别
不过现在确实可以加入seamlessZoom这个参数了。
有兴趣提个pr吗？

**Comment by fuzhenn** [comment]
fixed by https://github.com/maptalks/examples/commit/0384c5d1cb28ec672f0467b53a8c1bc091582c3b
