### ISSUE TITLE
地图移动动画能写成mapbox那种吗，mapbox动画体验要好的多

### ISSUE THREAD

**Issue by just-ads** [maptalks/maptalks.js#1389]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
谢谢提issue，因为不是很清楚你说的动画具体是指哪一项功能，能否提供一个示例链接？谢谢

**Comment by just-ads** [comment]
> 谢谢提issue，因为不是很清楚你说的动画具体是指哪一项功能，能否提供一个示例链接？谢谢

[http://www.mapbox.cn/mapbox-gl-js/example/satellite-map/](url)
mapbox滑动地图的动画要平滑的多，在移动端尤其明显，非常感谢回复

**Comment by xby020** [comment]
我记得以前的maptalks是有这种平滑移动的，但是我在看DEMO的时候看到一些BUG，比如倾斜角度下一些图层（比如3d建筑）只有在平滑结束后才会改变位置

**Comment by just-ads** [comment]
> 我记得以前的maptalks是有这种平滑移动的，但是我在看DEMO的时候看到一些BUG，比如倾斜角度下一些图层（比如3d建筑）只有在平滑结束后才会改变位置

forceRenderOnMoving: true试试

**Comment by fuzhenn** [comment]
收到，我会找时间看一下这个问题
