### ISSUE TITLE
4490自定义坐标系下spatialReference的resolutions加上地图出来一片黑

### ISSUE THREAD

**Issue by wang88633** [maptalks/maptalks.js#1393]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by wang88633** [comment]
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>瓦片图层与地理投影 - WMS瓦片图层</title>
<style type="text/css">
    html,
    body {
        margin: 0px;
        height: 100%;
        width: 100%
    }

    .container {
        width: 100%;
        height: 100%
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.7.4/proj4.js"></script>


<script src='https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.7.4/proj4.js'></script>




<body>
    <div id="map" class="container"></div>

    <script>

        var pro4490 = proj4.defs("EPSG:4490", "+proj=longlat +ellps=GRS80 +no_defs");
        var map = new maptalks.Map('map', {
            center: [106.498568, 36.113049],
            zoom: 6,
            // spatialReference: {
            //     // projection: 'EPSG:4326' 
            //      projection: pro4490
            // },
            spatialReference: {
                projection: pro4490,
                resolutions: [
                    1.4062471860936294,
                    0.7031235930468147,
                    0.35156179652340735,
                    0.17578089826170368,
                    0.08789044913085184,
                    0.04394522456542592,
                    0.02197261228271296,
                    0.01098630614135648,
                    0.00549315307067824,
                    0.0027465765353391312,
                    0.0013732882676695656,
                    6.866441338347828E-4,
                    3.433220669173914E-4,
                    1.716610334586957E-4,
                    8.583051672934777E-5,
                    4.2915258364673987E-5,
                    2.1457629182336993E-5,
                    1.0728814591168486E-5,
                    5.364407295584243E-6],     // geo projection, defined by proj4js

                fullExtent: {         // map's full extent
                    'top': 90.0,
                    'left': -180.0,
                    'bottom': -90.0,
                    'right': 180.0
                }},
            
         baseLayer: new maptalks.WMSTileLayer('wms', {
                    'urlTemplate': 'http://49.232.231.123:8199/iserver/services/map-gsblackgb/wms111/Chinagreen',
                    'crs': pro4490,
                    'layers': 'Chinagreen',
                    'styles': '',
                    'version': '1.1.1',
                    'format': 'image/png',
                    'transparent': true,
                    'uppercase': true
                }),

            });

    </script>
</body>

</html>

**Comment by wang88633** [comment]
![image](https://user-images.githubusercontent.com/22592035/125548195-007e6fa4-e8af-4b3b-9d61-1c73e66aa5d0.png)

**Comment by wang88633** [comment]
对于矢量还可以出来，4490的影像直接不按照自定义投影走，还是3857的  http://49.232.231.123:8199/iserver/services/map-gsblackgb/wms111/chinaL08_1_1%40gsblackbg4490

**Comment by fuzhenn** [comment]
收到，请问一下maptalks的版本是多少？

**Comment by wang88633** [comment]
49.4

**Comment by fuzhenn** [comment]
代码调用方法问题，4490投影可以看作与4326是一样的。
按下面的代码就能正常加载了。
```js
    var map = new maptalks.Map('map', {
        center: [106.498568, 36.113049],
        zoom: 6,
        spatialReference: {
            projection: 'EPSG:4490' //也可以设成 EPSG:4326
        },

     baseLayer: new maptalks.WMSTileLayer('wms', {
                'urlTemplate': 'http://49.232.231.123:8199/iserver/services/map-gsblackgb/wms111/Chinagreen',
                'crs': 'EPSG:4490',
                'layers': 'Chinagreen',
                'styles': '',
                'version': '1.1.1',
                'format': 'image/png',
                'transparent': true,
                'uppercase': true
            }),

        });
```

**Comment by wang88633** [comment]
主要是自定义比例尺一般都要按照固定的resolutions 去请求缓存，4326是可以，但不是固定的比例尺去做的

**Comment by fuzhenn** [comment]
那projection不要改，在空间参考里增加一个resolutions就行了
