### ISSUE TITLE
maptalks加载影像稍微有点倾斜时会出现锯齿

### ISSUE THREAD

**Issue by wang88633** [maptalks/maptalks.js#1396]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by wang88633** [comment]
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>瓦片图层与地理投影 - WMS瓦片图层</title>
<style type="text/css">
    html,
    body {
        margin: 0px;
        height: 100%;
        width: 100%
    }

    .container {
        width: 100%;
        height: 100%
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.min.js"></script>




<script type="text/javascript"
    src="https://cdn.jsdelivr.net/npm/maptalks.wmtstilelayer/dist/maptalks.wmts.min.js"></script>




<body>
    <div id="map" class="container"></div>

    <script>

        var pro4490 = proj4.defs("EPSG:4490", "+proj=longlat +ellps=GRS80 +no_defs");
        var map = new maptalks.Map('map', {
            center: [106.498568, 36.113049],
            zoom: 6,
            spatialReference: {
                projection: 'EPSG:4326'
                //  projection: pro4490
            },
            // spatialReference: {
            //     projection: pro4490,
            //     resolutions: [
            //         1.4062471860936294,
            //         0.7031235930468147,
            //         0.35156179652340735,
            //         0.17578089826170368,
            //         0.08789044913085184,
            //         0.04394522456542592,
            //         0.02197261228271296,
            //         0.01098630614135648,
            //         0.00549315307067824,
            //         0.0027465765353391312,
            //         0.0013732882676695656,
            //         6.866441338347828E-4,
            //         3.433220669173914E-4,
            //         1.716610334586957E-4,
            //         8.583051672934777E-5,
            //         4.2915258364673987E-5,
            //         2.1457629182336993E-5,
            //         1.0728814591168486E-5,
            //         5.364407295584243E-6],     // geo projection, defined by proj4js

            //     fullExtent: {         // map's full extent
            //         'top': 90.0,
            //         'left': -180.0,
            //         'bottom': -90.0,
            //         'right': 180.0
            //     }},


        });
        var wMTSTileLayer = new maptalks.WMTSTileLayer('base', {
            tileSystem: [1, -1, 72.0648193359375, 51.201782226573094],
            layer: 'chinaL08_1@gsblackbg',
            tilematrixset: 'Custom_chinaL08_1@gsblackbg',
            format: 'image/png',
            urlTemplate: 'http://49.232.231.123:8199/iserver/services/map-gsblackgb/wmts100?',

        }).addTo(map);
 

    </script>
</body>

</html>

**Comment by fuzhenn** [comment]
奇怪，按你的代码我这里暂时重现不出来，都是正常的，能给会出现锯齿现象的center，zoom，bearing，pitch参数吗

**Comment by wang88633** [comment]
我这边把地图稍微给一点点倾角，网上移动就重现了，我一会儿写好具体的参数给你发过来

**Comment by wang88633** [comment]
![image](https://user-images.githubusercontent.com/22592035/125621297-ac989839-004f-4a6b-a46c-de67f32d3067.png)

**Comment by deyihu** [comment]
当前版本没有复现这个问题，有问题欢迎再次打开
