### ISSUE TITLE
lineDasharray样式是否可以考虑从"-.."形式换为数组形式?

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/MapTalks.js#14]
我查了一下资料, 除了vml, svg和canvas中dasharray的设置都是用数组形式的.

cartocss的虚线设置也是用的数组:
https://github.com/FuZhenn/carto/blob/master/docs/2.1.1.md#line-dasharray-numbers

所以@brucin 你看是否可以考虑把虚线的"-."形式转换为数组形式, 和大部分标准保持一致.

**Comment by brucin** [comment]
SVG与Canvas本身就需要数组形式去实现。但是VML不行，其定义的是常量：Solid、Dot、Dash、 LongDashDotDot等。从数组形式翻译成对应的这些常量就比较困难了。
所以，支持数组形式我觉得是好的，也应该支持。但是使用起来会有一个学习的过程，提供方便理解的定义线形的样式，可以让大多数人使用起来方便。

**Comment by FuZhenn** [comment]
用数组形式有两个优点:
1. 可扩展性好: 可以定义出无限种虚线样式.
2. "-."风格不符合cartoCSS, 我们的样式定义除了适当扩展, 应和cartoCSS严格保持一致.

如果为了让使用者更友好,这里有个解决方法:
1. dasharray还是用数组定义: 其实dasharray本身就是虚线数组的意思
2. 定义一些常量能方便用户直接引用而不用写dash数组, 类似VML里的Solid、Dot、Dash、 LongDashDotDot

**Comment by brucin** [comment]
dasharray本身含义就是线段数组，的确应该与CartoCss统一。
不过我们不得不解决与VML渲染效果一致的问题。所以我需要好好考虑一下，才能做出修改。

**Comment by FuZhenn** [comment]
vml也支持dash数组定义,参考链接:
https://msdn.microsoft.com/en-us/library/bb264085(v=vs.85).aspx
我试了一下, 除了vml中用0表示dot外, 其它定义和svg基本是一致的, 实际运用时可以以svg为准.

**Comment by brucin** [comment]
可以，我稍后会修改测试一下。
