### ISSUE TITLE
The spatial resolution of the custom tile layer cannot be loaded normally when set   repeatWorld:false

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#1400]
**maptalks's version and what browser you use?**
----

**Issue description**
----

- The spatial resolution of the custom tile layer cannot be loaded normally when set repeatWorld:false

 0.49.4 https://codepen.io/deyihu/pen/RwGBbej?editors=0010

alpha 18  https://codepen.io/deyihu/pen/MWmmebP

- when tilelayer set minZoom cant not  repeatWorld

设置了minzoom后，无法repeatWorld了,一直向左或者向右拖动试试

0.49.4 https://codepen.io/deyihu/pen/LYyyQPm 

alpha 18 https://codepen.io/deyihu/pen/ExmmyqV?editors=1010

- custom tileSize is error

0.49.4 https://maptalks.org/examples/cn/tilelayer-projection/arcgis-tile/#tilelayer-projection_arcgis-tile

alpha https://codepen.io/deyihu/pen/abWWEeL?editors=0010

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.js/pull/1453

**Comment by wang88633** [comment]
你好，麻烦加载超图的自定义投影的这个问题解决了吗，我这不使用wmts格式加载的时候放到一定的比例就乱了，加载的位置就不对了
