### ISSUE TITLE
如何实现半椭圆?

### ISSUE THREAD

**Issue by JianDNA** [maptalks/maptalks.js#1414]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
目前没有直接实现的方式，需要用Polygon来模拟。

**Comment by JianDNA** [comment]
> 目前没有直接实现的方式，需要用Polygon来模拟。

可以直接用椭圆转polygon, 但是不知道如何得到一个半椭圆

**Comment by fuzhenn** [comment]
只取一半的端点就行了，应该蛮简单的。
因为不是bug或feature request，我先关闭此issue了
