### ISSUE TITLE
0.44以上版本加载arcgis瓦片在大于1920的屏幕分辨率下会出现瓦片缺失

### ISSUE THREAD

**Issue by geekljr** [maptalks/maptalks.js#1419]
**0.45版本**
----

**加载arcgis瓦片缺失**
----
我是用0.44版本就不会出现这个问题，我的地图div宽高大小是3964px*2160px，当地图倾角大于56以上时，左下角会出现一片的瓦片缺失，同时我看了下canvas的height是，宽高都不正确，我的猜想是canvas的宽高与样式的宽高不一致导致的
`<canvas height="1080" width="1981" style="width: 3963px; height: 2160px;"></canvas>`
我在再把地图的div设置成1920*1080的大小时，又能正常显示，不会出现瓦片缺失的情况，canvas里面的宽高也与样式的宽高一致，下面是我加载arcgis瓦片服务的代码结构
```js
var arcUrl = config.blackstreetMap;
        maptalks.SpatialReference.loadArcgis(
          arcUrl + "?f=pjson",
          function (err, conf) {
            if (err) {
              throw new Error(err);
            }
            var ref = conf.spatialReference;
            ref.projection = "EPSG:4326";
            _this.map = new maptalks.Map("map", {
              center: [119.6825852313696, 30.63664102701957],
              zoom: 6,
               minZoom: 0,
               maxZoom: 9,
               pitch: 70,
               maxPitch: 70,
             maxVisualPitch: 80,
              spatialReference: ref,
              fog: false,
              // fogColor: [0, 0, 0],
              attribution: false,
              baseLayer: new maptalks.TileLayer("base", {
                tileSystem: conf.tileSystem,
                tileSize: conf.tileSize,
                urlTemplate: arcUrl + "/tile/{z}/{y}/{x}",
                repeatWorld: false,
                maxAvailableZoom: 10,
              }),
            });

            let extent = new maptalks.Extent(
              119.88750099800006,
              30.874656594000044,
              119.23200666900004,
              30.37556102700006
            );
            _this.map.setMaxExtent(extent);
          }
        );
```
详细的情况可以私聊我，因为项目是内网环境，无法公布到外网，效果图我就不贴出来了，还请博主能看看这个bug

**Comment by fuzhenn** [comment]
0.44和0.45都是2年前很古老的版本了，您是否尝试过最新的0.49.5版？
这个版本是否能解决您的问题？

**Comment by geekljr** [comment]
> 0.44和0.45都是2年前很古老的版本了，您是否尝试过最新的0.49.5版？
> 这个版本是否能解决您的问题？

是0.44版本能正常显示不会瓦片缺失，0.44以上到0.49版本我都试了个遍，这之间的版本会出现瓦片缺失

**Comment by fuzhenn** [comment]
收到，那0.44里的哪个版本是正确的？0.44.0， 0.44.1还是0.44.2？

**Comment by geekljr** [comment]
> 收到，那0.44里的哪个版本是正确的？0.44.0， 0.44.1还是0.44.2？

0.44.0

**Comment by fuzhenn** [comment]
那0.44.1和0.44.2是否是正常的？

**Comment by geekljr** [comment]
> 那0.44.1和0.44.2是否是正常的？

刚刚我从npm库每个安装了一遍，可以确定0.47.0开始有问题0.46.0以前的都能正常显示

**Comment by fuzhenn** [comment]
我过了一遍0.46.0 -> 0.47.0的代码，暂时没有发现可能的原因。
虽然可能有点麻烦，能不能请你整理一个重现代码？有重现代码的话，我能很快解决这个问题。

**Comment by geekljr** [comment]
> 我过了一遍0.46.0 -> 0.47.0的代码，暂时没有发现可能的原因。
> 虽然可能有点麻烦，能不能请你整理一个重现代码？有重现代码的话，我能很快解决这个问题。

我临时搭建了一个项目地址，已经私发到您的邮箱

**Comment by geekljr** [comment]
> 我过了一遍0.46.0 -> 0.47.0的代码，暂时没有发现可能的原因。
> 虽然可能有点麻烦，能不能请你整理一个重现代码？有重现代码的话，我能很快解决这个问题。

我临时搭建了一个测试html，已经私发到您的邮箱，直接打开,当地图级别缩放大一些就会出现，地图缩放级别小就不会出现缺失，两个版本的都引入了，您可以切换看一下

**Comment by fuzhenn** [comment]
不好意思，没收到你的邮件呢。
我的邮箱是 fuzhen@maptalks.org

**Comment by geekljr** [comment]
> 不好意思，没收到你的邮件呢。
> 我的邮箱是 [fuzhen@maptalks.org](mailto:fuzhen@maptalks.org)

已经重新发送了，请查收

**Comment by fuzhenn** [comment]
重现代码已经收到，且已经重现。
后发现是因为容器太大，TileLayer的瓦片缓存数量不足导致的，只要在初始化TileLayer时，把options里的maxCacheSize设置得大一些（默认是256，例如设置到1024），就能解决这个问题了。
另外对大屏地图，地图切片的尺寸最好做得更大，例如512，甚至1024都可以，这样应该能显著提升TileLayer的加载性能
