### ISSUE TITLE
Upgrade to Vite build flow

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1426]
Upgrade to Vite build flow, Thanks to @sakitam-fdd 's work.

https://github.com/sakitam-fdd/maptalks.js/tree/vite-bundle

**Comment by deyihu** [comment]
关于vitejs

- 底层还是rollup
- 更适合webapp，而不是lib,mtk是个lib，不存在大量的 hot reload问题,vitejs无法发挥它的价值
- mtk docs，mtk webpage等其他项目适合用vitejs
