### ISSUE TITLE
MarkerClusterLayer is not right on 1.0.0-alpha.20

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1434]
**maptalks's version and what browser you use?**
----
1.0.0-alpha.20@next

**Issue description**
----
MarkerClusterLayer doesn't perform correctly on 1.0.0-alpha.20@next

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
close by https://github.com/maptalks/maptalks.js/commit/713237b3809c21f25fc905a81f1b339b8c21a451
