### ISSUE TITLE
next最新代码在ClusterLayer上的问题

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1443]
**maptalks's version and what browser you use?**
----
v1.0.0-alpha.20

**Issue description**
----
* 缩放地图时性能很差
* 地图放大到18级，图层绘制所有marker时，放大地图过程中marker会消失（这是因为ClusterLayer里，marker._currentView都是false)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
markercluster中的demo/index.html
https://github.com/maptalks/maptalks.markercluster

**Comment by deyihu** [comment]
我明天看看

**Comment by fuzhenn** [comment]
fixed in #1447
