### ISSUE TITLE
如何设置地图全屏？

### ISSUE THREAD

**Issue by ghost** [maptalks/maptalks.js#1444]
可否支持 fullScreen control，增加全屏按钮？

**Comment by ghost** [comment]
how to use requestFullScreen()?

**Comment by guzhongren** [comment]
Hi, @Ruthevil  [maptalks fullScreen](https://codepen.io/guzhongren/pen/wvdYVKJ)


Refs:

- MDN: https://developer.mozilla.org/zh-CN/docs/Web/API/Element/requestFullscreen

**Comment by guzhongren** [comment]
And you can close the issue.

**Comment by ghost** [comment]
> Hi, @Ruthevil [maptalks fullScreen](https://codepen.io/guzhongren/pen/wvdYVKJ)
> 
> Refs:
> 
> * MDN: https://developer.mozilla.org/zh-CN/docs/Web/API/Element/requestFullscreen



> And you can close the issue.

thanks！
