### ISSUE TITLE
大范围加载的时候会出现空白的

### ISSUE THREAD

**Issue by sqzxy** [maptalks/maptalks.js#1466]
**maptalks's version and what browser you use?**
----

**Issue description**
----
大范围加载的时候会出现空白的，加载5000*4000的时候，由于分辨率不够，所以div有部分被隐藏的，这个时候会出现控制灰色的一片缩小放大后也是，会出现同样一片区域空白

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by sqzxy** [comment]
![image](https://user-images.githubusercontent.com/18019985/129197098-3cec7e4d-f302-4f24-b9a2-5197510dd7f6.png)

**Comment by fuzhenn** [comment]
可能和 #1419 原因一样，屏幕范围太大，导致缓存数量不够了。
可以试试把TileLayer.options里的maxCacheSize设置得大一些。

**Comment by sqzxy** [comment]
我在缩放的时候看到图片都请求也加载了，加载完了会在此加载现在这个灰色的情况

**Comment by sqzxy** [comment]
这个情况我验证了下，在0.45版本开始出现的，之前的版本是没有的

**Comment by fuzhenn** [comment]
我刚实现了动态maxCacheSize，应该就能解决这个问题了

**Comment by sqzxy** [comment]
我刚改了这个参数，确实解决了这个问题，但是奇怪我看了之前没问题的版本，这个参数也是默认256的，为什么没有这个问题呢

**Comment by fuzhenn** [comment]
这是因为0.46开始，为了实现无限远的瓦片绘制，所以调整了TileLayer的算法，瓦片数量变多，就造成maxCacheSize不够用的问题了。
不过因为最近遇到两次相关的issue，我刚实现了动态maxCacheSize功能，你可以试试master上的最新代码，就算maxCacheSize不够用，它也能自动调整，应该也能解决这个问题了。

**Comment by sqzxy** [comment]
好的，谢谢。看到master上面更新了，那个在线的版本什么时候可以更新呀？
