### ISSUE TITLE
map 的 off  无法注销 on 事件

### ISSUE THREAD

**Issue by Notcambulist** [maptalks/maptalks.js#1471]
**maptalks's version and what browser you use?**
---v-0.49.5

**Issue description**
---- 
在示例中提供的放大镜功能，实现了之后希望有个取消的功能，原本打算用off去注销里面的鼠标事件和renderend事件

off(eventsOff, handler, context) 地图想要注销里面on的事件，但是无法注销成功，依然继续执行

----
简单写了两个注册和注销函数
在看了其他的issue的时候你好像说handler要一致才能够注销成功？
`removeListen(map) {
		map.off('mousemove', function(e) {
			console.log('hahaha')
		})
	}`
`addListen(map) {
		map.on('mousemove', function(e) {
			console.log('hahaha')
		});
	}`
两个btn分别触发这两个函数时，removeListen()并没有注销成功mousemove事件

------
或者希望能提供一个可以取消放大镜功能的一个可行想法或建议

**Comment by fuzhenn** [comment]
duplicate of #1473

**Comment by fuzhenn** [comment]
感谢提醒，例子里写的确实不够周全，我已经把示例改为预先定义的函数了。
