### ISSUE TITLE
请问地图可以是三维的吗？

### ISSUE THREAD

**Issue by ghost** [maptalks/maptalks.js#1478]
**maptalks's version and what browser you use?**
----
最新版本

**Issue description**
----
请问地图可以是三维的吗，我看了大部分的例子，地图本身貌似都是2d的？

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://maptalks.org/examples/en/3d/marker-altitude/#3d_marker-altitude

**Comment by fuzhenn** [comment]
请参考 [maptalks.three](https://github.com/maptalks/maptalks.three)里的示例，基本都是三维的
