### ISSUE TITLE
 'urlTemplate': arcUrl + '/tile/{z}/{y}/{x}?blankTile=false', 请问加载arcgis底图，y和x不对怎么处理

### ISSUE THREAD

**Issue by dolphinfine** [maptalks/maptalks.js#1482]
**maptalks's version and what browser you use?**
----
maptalks v1.0.0-alpha.20
chrome  v91.0.4472.106

**Issue description**
----
由于y、x计算不对，导致获取瓦片的url有误，arcgis地图加载不出来

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![image](https://user-images.githubusercontent.com/27426130/131100558-636c0f97-efd3-465f-b3f7-89ed13f2646d.png)

`
var arcUrl = 'http://10.190.65.123/arcgis/rest/services/FTKSJ/DLG_ZQ_FT_DB_CGCS2000/MapServer';

      maptalks.SpatialReference.loadArcgis(arcUrl + '?f=json', function (err, conf) {
        if (err) {
          throw new Error(err);
        }
        var ref = conf.spatialReference;
        ref.projection = 'EPSG:4490';

        var map = new maptalks.Map('map', {
          center: [114.060168, 22.603403],
          zoom: 4,
          minZoom: 1,
          maxZoom: 16,
          spatialReference: ref,
          baseLayer: new maptalks.TileLayer('base', {
            'tileSystem': conf.tileSystem,
            'tileSize': conf.tileSize, // [512, 512]
            'urlTemplate': arcUrl + '/tile/{z}/{y}/{x}?blankTile=false',
            'attribution': '&copy; <a target="_blank" href="' + arcUrl + '"">ArcGIS</a>'
          })
        });
`

用arcgis是正常加载的
![image](https://user-images.githubusercontent.com/27426130/131102140-b065f165-2168-4570-a1d2-375487edf5dd.png)

**Comment by fuzhenn** [comment]
这可能是projection没有正确设置造成的。
因为原服务已经无法访问，先关闭issue。如果还有疑问欢迎再来提issue
