### ISSUE TITLE
GroupTileLayer addLayers

### ISSUE THREAD

**Issue by just-ads** [maptalks/maptalks.js#1483]
GroupTileLayer 添加 addLayers方法
```js
addLayers(layers){
        const map = this.getMap();
        if(!Array.isArray(layers)) layers = [layers];
        // this._checkChildren();
        const ids = {};
        layers.forEach(layer => {
            const layerId = layer.getId();
            if (ids[layerId]) {
                throw new Error(`Duplicate child layer id (${layerId}) in the GroupTileLayer (${this.getId()})`);
            } else {
                ids[layerId] = 1;
                this.layerMap[layerId] = layer;
                this.layers.push(layer);
                if (layer.getChildLayer) {
                    this._groupChildren.push(layer);
                }
                layer._bindMap(map);
                layer.on('show hide', this._onLayerShowHide, this);
            }
        });
        // super.onAdd();
    }
```

**Comment by PZD2937** [comment]
`addLayers(layers){
        const map = this.getMap();
        if(!Array.isArray(layers)) layers = [layers];
        // this._checkChildren();
        const ids = {};
        layers.forEach(layer => {
            const layerId = layer.getId();
            if (ids[layerId]) {
                throw new Error(`Duplicate child layer id (${layerId}) in the GroupTileLayer (${this.getId()})`);
            } else {
                ids[layerId] = 1;
                this.layerMap[layerId] = layer;
                this.layers.push(layer);
                if (layer.getChildLayer) {
                    this._groupChildren.push(layer);
                }
                layer._bindMap(map);
                layer.on('show hide', this._onLayerShowHide, this);
            }
        });
        // super.super.onAdd();
    }`

**Comment by fuzhenn** [comment]
sorry，我考虑了一下，感觉暂时没有必要增加该接口。
