### ISSUE TITLE
对于MultiPoint的子几何设置setInfoWindow但无法触发

### ISSUE THREAD

**Issue by Notcambulist** [maptalks/maptalks.js#1491]
**maptalks's version and what browser you use?**
----v0.49.5

**Issue description**
----在使用MultiPoint批量设置几何点时，希望能够动态去设置里面的InfoWindow，所以使用了getGeometries去获取MultiPoint里的各个子几何并分别设置他们的infoWindow，添加之后确实在每个子几何中找到了infowinOptions,但是在点击的时候无法触发窗口的弹出

另外也尝试过getGeometries()的时候给各项子几何绑定 on 事件，也无法成功触发

![image](https://user-images.githubusercontent.com/52956042/131944474-62cbd270-cb95-4737-b83d-f2c0b7a2c48a.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

下面是重现代码
`
var center = new maptalks.Coordinate(-0.113049, 51.498568);
var map = new maptalks.Map('map', {
	center: center,
	zoom: 14,
	baseLayer: new maptalks.TileLayer('base', {
		urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
		subdomains: ['a', 'b', 'c', 'd'],
		attribution: '© <a href="http://osm.org">OpenStreetMap</a>  contributors, © <a href="https://carto.com/">CARTO</a> '
	})
});

var multipoint = new maptalks.MultiPoint([
	[-0.131049, 51.498568],
	[-0.107049, 51.498568],
	[-0.107049, 51.493568],
	[-0.131049, 51.493568],
	[-0.131049, 51.498568]
], {
	visible: true,
	editable: true,
	cursor: 'pointer',
	shadowBlur: 0,
	shadowColor: 'black',
	draggable: false,
	dragShadow: false, // display a shadow during dragging
	drawOnAxis: null, // force dragging stick on a axis, can be: x, y
	symbol: {
		'textFaceName': 'sans-serif',
		'textName': 'point',
		'textFill': '#34495e',
		'textHorizontalAlignment': 'right',
		'textSize': 40
	}
});
multipoint.getGeometries().forEach(i => {
	console.log(i.getCenter())
	var options = {
		title: 'test',
		content: '<div style="color:#f00">' + '坐标：' + JSON.stringify(i.getCenter()) + '</div>',
		autoOpenOn: 'click',
		animation: false
	}
	i.setInfoWindow(options)
})
console.log(multipoint)
new maptalks.VectorLayer('vector', multipoint).addTo(map);
`

**Comment by deyihu** [comment]
这个属于设计范畴，不算bug，multiGeometry属于一个整体，会自动屏蔽器内存的子元素的，MultiGeometry的事件里会给出一个pickGeometryIndex参数的，可以利用其在动态切换InfoWindow的内容

https://codepen.io/deyihu/pen/OJYZBJo
