### ISSUE TITLE
drawTool 修改点样式无法加载点图形

### ISSUE THREAD

**Issue by FEJackFly** [maptalks/maptalks.js#1493]
**maptalks's version and what browser you use?**
----
chorme
"maptalks": "^0.49.5",

**Issue description**
----
drawTool 设置点样式无法绘制 控制台能打出parm.geomety 数据

**Please provide a reproduction URL (on any jsfiddle like site)**
----
drawTool.on('drawend', (param) => {
      if (param.geometry.getType() === 'Point') {
        // param.geometry.setSymbol(this.state.mapStyle.drawStyle.Point);
      } else {
        param.geometry.setSymbol({
          ...this.state.mapStyle.drawStyle.Polygon,
          lineColor: this.state.background,
          polygonFill: this.state.background,
        });
      }
      console.log(param.geometry._symbol);
      drawLayer.addGeometry(param.geometry);
    });

**Comment by deyihu** [comment]
https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/DETU/cursor.html
