### ISSUE TITLE
和cartocss样式的一致性问题

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/MapTalks.js#15]
我们采用了cartoCSS作为图形的样式定义, 但存在少数一些和cartoCSS不一致的地方.

主要是cartoCSS中缺少一些我们需要的样式定义, 所以增加了一些扩展属性,例如shield-type, dx和dy等

但因为cartoCSS本身也是个发展中的标准, 随时会有变化和扩充, 这样定义样式,虽然定义起来方便简单, 用起来也方便, 但会造成未来和cartoCSS的冲突和不一致.

我觉得我们可以研究一个更好的方式来定义这些新的属性. 

cartoDB采用了标准的css扩展语法(例如-webkit-*)作为扩展属性的定义形式, 例如-torque-resolution, 我们也可以研究一下更适合我们的扩展属性定义方式.

@brucin 
@wsw0108

**Comment by brucin** [comment]
这个我觉得可以学习ZUI扩展bootstrap，其扩展的也是样式。并没有定义特殊的形式，而是按照bootstrap的样式定义规则，直接扩展了能准确表达样式含义的新样式，但是bootstrap 本身的样式zui是完全支持的。但是如果你将包含ZUI定义的新的样式，直接copy到只有bootstrap的环境下，则会存在特殊效果的缺失。
我个人的意见是，名称只要能准确表述其定义的含义即可，并不需要求特殊。

**Comment by FuZhenn** [comment]
我很认同你的意见, "名称只要能准确表述其定义的含义即可，并不需要求特殊", 不过ZUI的影响力比较小, 它的处理方式还不足以成为我们借鉴对象.

我觉得我们既然选择了cartoCSS, 就严格和它保持一致, 因为如果任意的对cartoCSS做扩展的话, 以后根据需要扩展的新属性势必越来越多, 就类似IE6对html标准的扩展一样.

这个问题分为3类
1. 属性可用, 但取值不够的, 例如marker-type.
2. 原有属性不够友好的, 定义了新的属性的, 例如dx,dy对应的是原有的marker-transform
3. 需要定义的新的属性, 如shield-type.

鉴于要改的属性并不多, 所以这个问题先不急着下结论, 我们可以参考下其他的软件和平台的做法, 在这一阶段工作结束后回头来调整这个问题.

**Comment by FuZhenn** [comment]
属性基本定稿, 具体参考 #19
