### ISSUE TITLE
keypress 事件失效

### ISSUE THREAD

**Issue by FEJackFly** [maptalks/maptalks.js#1501]
**maptalks's version and what browser you use?**
----
chrome
"maptalks": "^1.0.0-alpha.26",
**Issue description**
----
keypress 事件失效

**Please provide a reproduction URL (on any jsfiddle like site)**
----
 map.on('keypress', (e) => {
            console.log(e);
        });

**Comment by fuzhenn** [comment]
map不会监听keypress事件，你可以调用document上的原生方法来捕捉事件
