### ISSUE TITLE
maptalks

### ISSUE THREAD

**Issue by wang88633** [maptalks/maptalks.js#1502]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by wang88633** [comment]
麻烦问下，能提供一个demo吗，maptalks原生进行矢量瓦片加载的

**Comment by fuzhenn** [comment]
核心库目前还不支持矢量瓦片加载，未来会提供专门的矢量瓦片渲染插件
