### ISSUE TITLE
maptalks.Marker 根据地图缩放

### ISSUE THREAD

**Issue by iiixxxiii** [maptalks/maptalks.js#1503]
现在有个需求需要Marker 根据地图缩放时候也进行缩放,如何设置?

**Comment by deyihu** [comment]
@iiixxxiii https://maptalks.org/examples/cn/style/symbol-by-zoom/#style_symbol-by-zoom

**Comment by iiixxxiii** [comment]
@deyihu 地图缩放是不是有最大限制?我想像是cesium 一样可以放到很大该怎么做?设置maxZoom好像没有用,我maxZoom 设置到50都没效果

**Comment by deyihu** [comment]
@iiixxxiii  https://maptalks.org/examples/en/map/custom-resolutions/#map_custom-resolutions
