### ISSUE TITLE
使用 maptalks.cesium 加载 3DTileset 层时候与其它VectorLayer层上的标签不能融合

### ISSUE THREAD

**Issue by iiixxxiii** [maptalks/maptalks.js#1506]
使用 maptalks.cesium 加载 3DTileset 层时候与其它VectorLayer层上的Marker不能融合
现在问题
1.怎么使 Marker 和 3DTileset 融合?
2.能不能使用cesium 的标签?获取 cesium 的layer?

**Comment by fuzhenn** [comment]
https://github.com/fuzhenn/3dtiles-issues/
可以试试改用我们官方的3dtiles图层。
目前可以用这个图层和[maptalks.three](https://github.com/maptalks/maptalks.three)插件融合绘制。
其他三维图层也马上发不，也都能和3dtiles图层融合绘制。
