### ISSUE TITLE
maptalks.VectorLayer 清除后imagedata没有清空

### ISSUE THREAD

**Issue by tpolong** [maptalks/maptalks.js#1507]
**maptalks's version and what browser you use?**
----
maptalks v1.0.0-alpha.26
94.0.4606.54（
**Issue description**
----

maptalks.VectorLayer 清除后imagedata没有清空，占用内存
**Please provide a reproduction URL (on any jsfiddle like site)**
----
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>图形 - MultiPolygon</title>
  <style type="text/css">
    html,body{margin:0px;height:100%;width:100%}
    .container{width:100%;height:100%}
  </style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.css">

  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.min.js"></script>
    
  
  <body>

    <div id="map" class="container"></div>

    <script>
      var map = new maptalks.Map('map', {
        center: [-0.113049, 51.498568],
        zoom: 14,
        baseLayer: new maptalks.TileLayer('base', {
          urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
          subdomains: ['a','b','c','d'],
          attribution: '&copy; <a href="http://osm.org">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/">CARTO</a>'
        })
      });

      var polygon = new maptalks.Polygon([
        [
          [-0.131049, 51.498568],
          [-0.107049, 51.498568],
          [-0.107049, 51.493568],
          [-0.131049, 51.493568],
          [-0.131049, 51.498568]
        ]
      ], {
        visible : true,
        editable : true,
        cursor : 'pointer',
        shadowBlur : 0,
        shadowColor : 'black',
        draggable : false,
        dragShadow : false, // display a shadow during dragging
        drawOnAxis : null,  // force dragging stick on a axis, can be: x, y
        symbol: {
          'lineColor' : '#34495e',
          'lineWidth' : 2,
          'polygonFill' : 'rgb(135,196,240)',
          'polygonOpacity' : 0.6
        }
      });
      let layers=[]
        for(let i=0;i<100;i++){
            let p=polygon.copy()
            let layer=new maptalks.VectorLayer('vector'+i,p).addTo(map);    
            layers.push(layer)
        }
      function clear(){
        layers.forEach(function(layer){
          layer.clear()
        })
      }
        
       

    </script>
  </body>

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.js/pull/1508
