### ISSUE TITLE
e.target.identify事件在调用时候函数执行次数一直在增加

### ISSUE THREAD

**Issue by liyu022** [maptalks/maptalks.js#1513]
**maptalks's version and what browser you use?**
----

![1634022475(1)](https://user-images.githubusercontent.com/19968327/136908465-056cf6a4-ea64-4467-9de7-6714bd838184.png)

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
我还不是很明白问题在哪里，能否提供一个简单的重现代码？谢谢

**Comment by deyihu** [comment]
not find problem https://maptalks.org/examples/en/interaction/mouse-identify/#interaction_mouse-identify
