### ISSUE TITLE
maptalks.cesium 如何获取  viewer.entities

### ISSUE THREAD

**Issue by iiixxxiii** [maptalks/maptalks.js#1516]
maptalks.cesium 如何获取  viewer.entities ?

看 maptalks.cesium 的demo 可以获取  CesiumScene 但是如何获取  viewer.entities?

**Comment by iiixxxiii** [comment]
@deyihu  这个怎么获取

**Comment by deyihu** [comment]
@iiixxxiii  scene上没有entities的，有 scene.primitives
