### ISSUE TITLE
地图滑动动画优化

### ISSUE THREAD

**Issue by just-ads** [maptalks/maptalks.js#1525]
重写Map.Drag.js的_moveEnd()
`_moveEnd(param) {
        if (!this.startDragTime) {
            return;
        }
        const map = this.target;
        let t = now() - this.startDragTime;
        const mx = param['mousePos'].x,
            my = param['mousePos'].y;
        const dx = mx - this.startX;
        const dy = my - this.startY;

        const _this$momentum = this.momentum(dx, dy, t),
            targetX = _this$momentum.targetX,
            targetY = _this$momentum.targetY,
            duration = _this$momentum.duration,
            absXY = _this$momentum.absXY;

        this._clear();

        if (map.options['panAnimation'] && !param.interupted && t < 280 && map._verifyExtent(map._getPrjCenter()) && absXY > 15 && duration > 450) {
            if (duration > 600) {
                map.panBy(new Point(targetX, targetY), {
                    'duration': duration
                });
            } else {
                t = 5 * t * (Math.abs(dx) + Math.abs(dy)) / 500;
                map.panBy(new Point(dx, dy), {
                    'duration': t
                });
            }
        } else {
            map.onMoveEnd(param);
        }
    }`

动量函数： `momentum(disx, disy, duration) {
        //减速
        const deceleration = 0.003;
        const absX = Math.abs(disx);
        const absY = Math.abs(disy);
        const absXY = Math.sqrt(Math.pow(absX, 2) + Math.pow(absY, 2));
        const speed = absXY / duration;
        const targetX = disx + speed * absX / absXY / deceleration * (disx < 0 ? -1 : 1);
        const targetY = disy + speed * absY / absXY / deceleration * (disy < 0 ? -1 : 1);
        const targetXY = Math.sqrt(Math.pow(targetX, 2) + Math.pow(targetY, 2));
        const sqrt = targetXY * 2 / deceleration;
        const t = Math.round(Math.sqrt(sqrt));
        return {
            duration: t,
            targetX: targetX,
            targetY: targetY,
            absXY: absXY
        };
    }`

**Comment by PZD2937** [comment]
`    momentum(disx, disy, duration) {
        //减速
        const deceleration = 0.003;
        const absX = Math.abs(disx);
        const absY = Math.abs(disy);
        const absXY = Math.sqrt(Math.pow(absX, 2) + Math.pow(absY, 2));
        const speed = absXY / duration;
        const targetX = disx + speed * absX / absXY / deceleration * (disx < 0 ? -1 : 1);
        const targetY = disy + speed * absY / absXY / deceleration * (disy < 0 ? -1 : 1);
        const targetXY = Math.sqrt(Math.pow(targetX, 2) + Math.pow(targetY, 2));
        const sqrt = targetXY * 2 / deceleration;
        const t = Math.round(Math.sqrt(sqrt));
        return {
            duration: t,
            targetX: targetX,
            targetY: targetY,
            absXY: absXY
        };
    }`

**Comment by PZD2937** [comment]
core/Animation.js   

`in(t) {
        return Math.pow(t, 3);
    },`

**Comment by fuzhenn** [comment]
已经参考上面的代码做了优化
