### ISSUE TITLE
About GL Plugins Suggestions

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#1527]
**maptalks's version and what browser you use?**
----

**Issue description**
----

- umd包重复打包工具包（feature-flter等工具包）的问题，如果核心库里有了，插件里直接引用，核心库里么有的可以将工具包放到gl npm包里供其他的插件（vt,3dtile等）来引用
 类似于

```js
 import {featureFilter,rbush} from 'maptalks';
 import {glmatrix,.......} from '@maptalks/gl';
 import {PointLayer,.........} from '@maptalks/gllayer';
```

- 整个插件的架构和依赖体系

![2021-11-13_233916](https://user-images.githubusercontent.com/25998927/141650044-46c040d2-fb7f-4ab2-acbd-bb157c443293.png)

- GroupGLLayer的功能移动到核心库的MapRender里，Map上的图层只要是gl图层并实现相关方法或者配置，一律收集到GroupGLLayer实例里，除非用户手动配置要单独的类似于VectorLayer一样的渲染，不满足条件的
gl图层按照老的方式处理,当然不知道这样做会让核心库体积膨胀多少

      理由： (1) 用户使用起来是无感知的，无需  const groupGLLayer=new GroupGLLayer(layer1,layer2);
             (2) 开放出来给用户自己去创建，会发生滥用的情况，比如多次创建

```js
       const groupGLLayer1=new GroupGLLayer(layer,layer);
       const groupGLLayer2=new GroupGLLayer(layer,layer);
       const groupGLLayer3=new GroupGLLayer(layer,layer);
       const groupGLLayer4=new GroupGLLayer(layer,layer);
       const groupGLLayer5=new GroupGLLayer(layer,layer);
```
**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
* 关于第一个直接引用maptalks中featurefilter以及rbush的问题，目前还暂时无法实现。因为gl插件中的feature-filter和rbush等需要在worker中加载，而worker是无法加载maptalks中的逻辑的，所以目前只能先单独加载。
* 关于GroupGLLayer是否要挪到核心库中，目前暂时感觉收益不如增加的复杂度
   * GroupGLLayer里除了gl融合逻辑，还包含了后处理，而后处理是需要依赖gl库的。如果把后处理剥离出来，则必须要增加GroupGLLayer的子类，会增加接口复杂度
   * 除了ThreeLayer插件，其他webgl插件都需要依赖gl库，所以用GroupGLLayer但不用gl库的情况不多
   * 考虑到gl库本身的大小只有600k左右，所以把GroupGLLayer挪到核心库的收益感觉并不是很大。
