### ISSUE TITLE
markerFile引用http图片地址报错

### ISSUE THREAD

**Issue by SimpleYong** [maptalks/maptalks.js#1528]
mtk  v1.0.0-beta.5
test :  https://codepen.io/simpleyong/pen/xxLyoVR

**Comment by fuzhenn** [comment]
图片跨域造成的，引用的图片没有返回有效的cors

**Comment by SimpleYong** [comment]
个人感觉不太友好耶，图片加载出来了但是接下来地图直接无法操作了，先暂时改源码‘解决’报错了(PS:0.49.5及以前的版本没这个问题)
