### ISSUE TITLE
按照自定义瓦片图层添加超图服务的自定义比例尺还是有点问题，不请求地图服务

### ISSUE THREAD

**Issue by wang88633** [maptalks/maptalks.js#1529]
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title data-i18n="resources.title_tiledMapLayerProj4"></title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.css">
    <script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/maptalks@1.0.0-alpha.20/dist/maptalks.min.js"></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.7.4/proj4.js'></script>
    <style>
        html,
        body {
            margin: 0px;
            height: 100%;
            width: 100%
        }

        .container {
            width: 100%;
            height: 100%
        }
    </style>

</head>

<body style=" margin: 0;overflow: hidden;background: #fff;width: 100%;height:100%;position: absolute;top: 0;">

    <div id="map" class="container"></div>

    <script type="text/javascript">
  
    var pro4490 = proj4.defs("EPSG:4490", "+proj=longlat +ellps=GRS80 +no_defs");
        var Unit = {
            /**  米 */
            METER: "METER",
            /**  千米 */
            KILOMETER: "KILOMETER",
            /**  英里 */
            MILE: "MILE",
            /**  码 */
            YARD: "YARD",
            /**  度 */
            DEGREE: "DEGREE",
            /**  毫米 */
            MILLIMETER: "MILLIMETER",
            /**  厘米 */
            CENTIMETER: "CENTIMETER",
            /**  英寸 */
            INCH: "INCH",
            /**  分米 */
            DECIMETER: "DECIMETER",
            /**  英尺 */
            FOOT: "FOOT",
            /**  秒 */
            SECOND: "SECOND",
            /**  分 */
            MINUTE: "MINUTE",
            /**  弧度 */
            RADIAN: "RADIAN"
        };
    var earchRadiusInMeters = 6378137;
    var inchPerMeter = 1 / 0.0254;
    var meterPerMapUnit = (Math.PI * 2 * earchRadiusInMeters) / 360;
    function replaceURL(url, x, y, scale) {
        var str = ['x', x, 'y', y, 'scale', scale];
        for (var i = 0, len = str.length; i < len; i += 2) {
            url = url.replace('{' + str[i] + '}', str[i + 1]);
        }
        return url;
    }
   function resolutionToScale(resolution, dpi) {
        var scale = resolution * dpi * inchPerMeter * meterPerMapUnit;
        scale = 1 / scale;
        return scale;
    }
        const parmas = {
            zooms: 20,
            firstRes:0.000000004573,
            origin: [-180, 85.05],
            maxBounds: [
                [-180, -85.05],
                [180, 85.05]
            ]
        };
     
        const url ="https://iserver.supermap.io/iserver/services/map-china400/rest/maps/China_4326/tileImage.png?width=256&height=256&redirect=false&transparent=true&cacheEnabled=true&origin=%7B%22x%22%3A-180%2C%22y%22%3A85.05112877980648%7D&overlapDisplayed=false&scale={scale}&x={x}&y={y}"
     
        const res = [];
          
    for (let i = 0; i <= parmas.zooms; i++) {
            res.push(parmas.firstRes / Math.pow(2, i));
        }
        console.log(res)
        const crs = {
            projection: "EPSG:4326",
            // projection: pro4490,
            resolutions: res,
            fullExtent: {
                // map's full extent
                top: 85.05,
                left: -180,
                bottom: -85.05,
                right: 180
            }
        };
  
        const tileLayer = new maptalks.TileLayer("base", {
            urlTemplate: url,
            repeatWorld: false,
            spatialReference: crs,
            // subdomains: ["a", "b", "c", "d"],
            // attribution:
            //     '&copy; <a href="https://www.supermap.com/cn/">supermap</a> contributors',
            tileSystem: [1, -1].concat(parmas.origin) // tile system
        });

        tileLayer.getTileUrl = function (x, y, z) {
                this.scales = this.scales || {};
                if (this.scales[z]) {
                    return replaceURL(this.options.urlTemplate, x, y, this.scales[z]);
                }
                var crs = this.getMap().getSpatialReference().getProjection();
                var bounds = this._getTileExtent(x, y, z);
                var min = bounds.getMin(),
                    max = bounds.getMax();
                var ne = crs.project(max);
                var sw = crs.project(min);
                var tileSize = this.options.tileSize[0];
                var resolution = Math.max(
                    Math.abs(ne.x - sw.x) / tileSize,
                    Math.abs(ne.y - sw.y) / tileSize
                );
                var scale = resolutionToScale(resolution, 96);
                this.scales[z] = scale;
                return replaceURL(this.options.urlTemplate, x, y, this.scales[z]);
            };

            tileLayer._getTileExtent = function (x, y, z) {
                var map = this.getMap(),
                    res = map._getResolution(z),
                    tileConfig = this._getTileConfig(),
                    tileExtent = tileConfig.getTilePrjExtent(x, y, res);
                return tileExtent;
            };
        var map = new maptalks.Map("map", {
            center: [116.2, 36.5],
            // pitch:40,
            // overviewControl: true,
            zoom: 1,
            spatialReference: crs,
            baseLayer: tileLayer
        });

    </script>

</body>

</html>

**Comment by deyihu** [comment]
https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUCENG/tilelayer.html#%E5%8A%A0%E8%BD%BDsupermap%E5%8F%91%E5%B8%83%E7%9A%84%E7%93%A6%E7%89%87%E6%9C%8D%E5%8A%A1
