### ISSUE TITLE
GeoJSONVectorTileLayer 在使用 stops 分级设置元素尺寸时，渲染出现模糊

### ISSUE THREAD

**Issue by ydfzgyj** [maptalks/maptalks.js#1530]
**maptalks's version and what browser you use?**
----
Edge 95
maptalks@1.0.0-beta.5
@maptalks/gl@0.56.2
@maptalks/vt@0.54.0
@maptalks/vt.basic@0.54.0

**Issue description**
----
使用 GeoJSONVectorTileLayer 加载点元素时，symbol 中的 markerWidth 和 marketHeight 设置为固定值时，点元素显示清晰；当使用 stops 分级设置大小时，点元素显示模糊，有明显阴影

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/ydfzgyj/pen/porQYzG

**Comment by fuzhenn** [comment]
已经发布，vt和vt.basic都是 v0..59.0

**Comment by ydfzgyj** [comment]
升级以后 stops 分级不生效了，在所有分级都显示为最大值……
把 demo 改了一下，麻烦 zhen 神再看看，谢谢

**Comment by fuzhenn** [comment]
收到

**Comment by fuzhenn** [comment]
已经修改并发布
vt升级到 0.60.1
vt.basic 升级到 v0.60.2
