### ISSUE TITLE
在draw绘制图形时，mode为point，能否在绘制时自定义set节点坐标

### ISSUE THREAD

**Issue by IIIzz** [maptalks/maptalks.js#1536]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以考虑不要用drawTool，改成自己监听map的click事件来实现，这样代码的灵活性比较强。
你根据条件选择用点击位置的坐标，或者自己设置坐标
```js
map.on('click', e => {
  if (useOwnCoord) {
     new Marker(ownCoord).addTo(layer);
  } else {
     new Marker(e.coordinate).addTo(layer);
 }
});
```
