### ISSUE TITLE
百度地图作为底图，在缩放不变的情况下，平移地图，出现不连续的情况

### ISSUE THREAD

**Issue by daolanfler** [maptalks/maptalks.js#1540]
**maptalks's version and what browser you use?**
----
"maptalks v1.0.0-beta.7"

**Issue description**
----
在缩放到小数级别的时候，地图中心的缩放等级和边缘的不一致。 如图是在 13.7 
![image](https://user-images.githubusercontent.com/29777079/146105903-0e36f852-43a2-4bbe-8b0f-00de6e8c3224.png)

![image](https://user-images.githubusercontent.com/29777079/146105937-ec518410-9c49-44c9-a7f4-ce8205ac77ed.png)

在整数的时候没有这个问题。不知道这是不是bug？有什么方法让鼠标滚轮缩放限制为在整数上变化吗？

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/daolanfler/pen/poWRNKQ

**Comment by fuzhenn** [comment]
确实是个bug。
要关闭小数点级别，创建map时，options里把seamlessZoom设成false就行了

**Comment by fuzhenn** [comment]
还有一个解决方案是创建TileLayer时，在TileLayer的options里把 pyramidMode 设成false，用老的瓦片遍历算法来加载瓦片。
