### ISSUE TITLE
关于shift+鼠标左键/右键会触发地图上特定事件问题

### ISSUE THREAD

**Issue by IIIzz** [maptalks/maptalks.js#1542]
**maptalks's version and what browser you use?**
----
屏蔽地图自带的快捷键

**Issue description**
----
shift+鼠标左键/右键会触发地图的事件，但是我需要使用shift作为自定义的快捷键，请问怎么屏蔽掉地图自带的快捷键？

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以在创建map时，options中把boxZoom设置为false，关闭这个功能，或者调用下面的方法关闭：
```js
map.config('boxZoom', false);
```
