### ISSUE TITLE
Map旋转缓动没有禁止配置，拖拽缓动效果比较怪异

### ISSUE THREAD

**Issue by shmen** [maptalks/maptalks.js#1547]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
增加了`map.options.rotateAnimation` 用于控制是否开启旋转缓动
`rotateAnimationDuration` 用于控制缓动的持续时间

**Comment by fuzhenn** [comment]
https://github.com/maptalks/maptalks.js/commit/6f64725db7b93a9a5a38d86ff9fd356cfe1153f4 中调整了缓动参数，增加了两个新的缓动函数，优化了体验。
缓动函数库：
https://github.com/fuzhenn/animation-easings
