### ISSUE TITLE
fitExtent doesn't work at the second time

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1554]
**maptalks's version and what browser you use?**
----
v1.0.0-beta.7

**Issue description**
----
fitExtent doesn't work at the second time

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by just-ads** [comment]
`var map = new maptalks.Map('map', {
  center: [-0.113049, 51.498568],
  zoom: 14,
  baseLayer: new maptalks.TileLayer('base', {
    urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
    subdomains: ['a', 'b', 'c', 'd'],
    attribution: '© <a href="http://osm.org">OpenStreetMap</a>  contributors, © <a href="https://carto.com/">CARTO</a> '
  }),
  layers: [
    new maptalks.VectorLayer('v')
  ]
});

var center = map.getCenter();
var polygon = new maptalks.Polygon([
  center.add(-0.005, 0.005),
  center.add(0.005, 0.005),
  center.add(0.005, -0.005),
  center.add(-0.005, -0.005)
], {
  symbol: {
    polygonFill: '#fff',
    polygonOpacity: 0.5
  }
});
map.getLayer('v').addGeometry(polygon);

function fitExtent() {
  // fit map's extent to polygon's
  // 0 is the zoom offset
  map.fitExtent(polygon.getExtent(), 0);
  map.setZoom(15);
}`

**Comment by just-ads** [comment]
https://user-images.githubusercontent.com/50706050/147749831-7e163c43-6aef-4496-918f-563dc8942873.mp4

**Comment by just-ads** [comment]
https://codepen.io/pzd2937/pen/abLqaBj

**Comment by deyihu** [comment]
这个不是bug，**fitExtent和setZoom方法都是动画方法,**
- **fixExtent里面可能包含zoom动画的，取决于fitExtent计算出的zoom是否等于当前zoom，如果不等于就会有zoom动画**
- 第一次，当fitExtent时，处于动画zooming（14-16的过程）,这时setZoom会被阻止  https://github.com/maptalks/maptalks.js/blob/d5ac56b0f1250b367d41ea3ecac1cc3313d5e0fe/src/map/Map.Zoom.ts#L35
- 第二次 fitExent时，这时zoom=16,这时fitExtent里面没有包含zoom动画，setZoom动画执行，会把fitExtent的动画给停掉，其实如果第二次zoom不等于16，你会发现fitExtent仍然可以正常工作



https://github.com/maptalks/maptalks.js/assets/25998927/5fc58502-0f8e-40bc-adea-f1ff582d531e


总结：动画函数会冲突
- 要么关闭动画，要么在动画函数结束时在调用另一个动画函数

```js
   //关闭动画
   map.fitExtent(polygon.getExtent(), 0, { animation: false });
   map.setZoom(15);
```


```js
   //动画结束后再调用另一个动画
    map.fitExtent(polygon.getExtent(), 0, { animation: true }, (frame) => {
                if (frame.state.playState === 'finished') {
                    map.setZoom(15);
                }
            });
```
