### ISSUE TITLE
如何实现匀速的水流动画？

### ISSUE THREAD

**Issue by kokonatsuli** [maptalks/maptalks.js#1559]
绘制了lineString之后，想在线上叠加动画，却找不到好的方法，想利用虚线实现，却没有头序。

后来用Marker来实现，定时器不断创建Marker，在线的每两个点之间做移动动画，执行时间则通过两点之间的距离计算得出，到达终点时销毁Marker，不断重复。这个方式还是有些繁琐，而且会有轨迹点之间如果过近，导致流动不顺畅的问题。

有没有更好的方式实现这个需求呢？

**Comment by fuzhenn** [comment]
这个需求在马上要发布的矢量瓦片图层插件中很容易实现。
图层的线渲染样式可以给线设置填充纹理和填充动画。

**Comment by kokonatsuli** [comment]
> 这个需求在马上要发布的矢量瓦片图层插件中很容易实现。 图层的线渲染样式可以给线设置填充纹理和填充动画。

感谢。那么矢量瓦片图层插件什么时候发布呢？

**Comment by fuzhenn** [comment]
顺利的话这个月就会发布了，现在开发已经结束，正在编写文档和示例中。

**Comment by kokonatsuli** [comment]
> 顺利的话这个月就会发布了，现在开发已经结束，正在编写文档和示例中。

好的，感谢
