### ISSUE TITLE
如何给Geometry添加自己的数据?

### ISSUE THREAD

**Issue by c20000c** [maptalks/maptalks.js#1560]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
不知道你是不是指的自定义属性：
```js
goemetry.setProperties({ foo: 'bar' });
```
对应的geojson中feature.properties

**Comment by c20000c** [comment]
测试ok 多谢
