### ISSUE TITLE
刚初始化生成Map instance后  fitExtent  symbol失效

### ISSUE THREAD

**Issue by nijiayu0914** [maptalks/maptalks.js#1568]
刚初始化生成Map instance后，使用fitExtent，在移动端（主要是android各浏览器）会发生fitExtent失败，需要加上一些延时才能成功，且地图自适应后，会造成symbol颜色丢失，同样需要增加延时然后重新setSymbol     @fuzhenn 

/**
     * 解决移动端移动地图，symbol失效问题
     */
    const setSymbol = () => {
        setTimeout(() => {
            polygon.setSymbol(symbol)
        }, 300)
        setTimeout(() => {
            polygon.setSymbol(symbol)
        }, 350)
        setTimeout(() => {
            polygon.setSymbol(symbol)
        }, 400)
        setTimeout(() => {
            polygon.setSymbol(symbol)
        }, 500)
        setTimeout(() => {
            polygon.setSymbol(symbol)
        }, 1500)
    }

map.current = new maptalks.Map('showmap_map_container', {
                center: wgs84tobd09(center[0], center[1]),
                draggable : false,
                dragPan : false,
                dragPitch : false,
                dragRotate : false,
                scrollWheelZoom : false,
                touchZoom : false,
                zoom: 13,
                spatialReference:{
                    projection : 'baidu'
                },
                baseLayer: new maptalks.TileLayer('base', {
                    urlTemplate: API.BaseMap + token,
                    subdomains: [0],
                    tileRetryCount: 3,
                }),
                layers: [polygonVec.current],
            })
            setTimeout(() => {
                map.current && map.current.fitExtent(polygon.getExtent(), 0); // 问题在这里这里
                setSymbol() // 问题在这里这里
            }, 500)

**Comment by fuzhenn** [comment]
谢谢！能否用codepen或者直接提供一个能运行的重新代码？
我用你的代码片段自己尝试重现了一下，没有重现出这个问题
