### ISSUE TITLE
1.0.0-beta.8至beta.10版本，无法获取国家天地图切片

### ISSUE THREAD

**Issue by ok958726** [maptalks/maptalks.js#1570]
**maptalks's version and what browser you use?**
----
1.0.0-beta.7 至1.0.0-beta.10

**Issue description**
----
在1.0.0-beta.7及之前，设置浏览器端tk后，可以正常获取国家天地图切片。但是在1.0.0-beta.8及之后，改用fetch(url)获取切片，请求返回错误403，{"msg":"权限类型错误","resolve":"不支持的key类型！","code":18}

测试发现，好像是天地图切片服务的请求头中不增加Accept属性，就会报此错误。
把TileLayer.js中的：fetch(url) 修改成：fetch(url,{'headers':{'Accept':'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8'}})，
甚至：fetch(url,{'headers':{'Accept': ''}}) 就可以正常获取切片。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/ok958726/pen/BamaBgB
切换到maptalks版本可重现

**Comment by fuzhenn** [comment]
收到，问题确实存在，但如果默认设置了headers，又怕会影响别的瓦片服务。
需要先确认原因，制定一个周全的解决方案。
有兴趣做一下研究然后发个pr给我妈？

**Comment by ok958726** [comment]
> 收到，问题确实存在，但如果默认设置了headers，又怕会影响别的瓦片服务。 需要先确认原因，制定一个周全的解决方案。 有兴趣做一下研究然后发个pr给我妈？

那我尝试一下。
今天还发现一个问题，就是mark设置几何样子的symbol后，拖拽绘制发生错误的问题。
示例：
https://codepen.io/ok958726/pen/NWwWOeQ

**Comment by fuzhenn** [comment]
收到，上面说的拖拽问题已经解决且补充了测试用例

**Comment by deyihu** [comment]
@ok958726 @fuzhenn  我也遇到这个问题了，我来解决下

**Comment by fuzhenn** [comment]
我感觉按照 #1574 里通过公开一个extraParams参数，让用户来根据不同图源设置不同的参数，不是一个很好的解决方案。
感觉更合适的方案是找到一个普适性的fetch参数，能适用到所有的底图服务。这样用户就不需要自己来设置fetch参数了。

上面说的思路应该是可行的，因为目前所有底图服务都支持用Image来请求，可以参考一下Image方式的参数是什么，设置给fetch应该就可以了。

**Comment by deyihu** [comment]
@fuzhenn 有道理，不过有些服务的token是藏在header里验证的，所以……

**Comment by fuzhenn** [comment]
噢，有道理，那把参数名extraParams换一下吧，就直接点叫 fetchOptions 吧，我在其他子图层插件里也读取一下这个设置
