### ISSUE TITLE
Chrome 49以下的版本地图随鼠标移动而移动

### ISSUE THREAD

**Issue by mrdonkey3** [maptalks/maptalks.js#1572]
**maptalks's version and what browser you use?**
----
chrome_48.0.2564.109(mac)、chrome_47.0.256.106(64位)、maptalks V0.49.5 Released

**Issue description**
----
在v0.47.5版本的提交点里 c1b9eb8f03953645dc6af6baee3f9ace691fbd93 59009d5704703327d4cea306e0a395c8884e0a77
做了如下改动
之前：
```js
  //firefox
        if (type === 'mousewheel' && Browser.gecko) {
            type = 'DOMMouseScroll';
        }
         obj.addEventListener(type, eventHandler, false);
```

之后：
```js
 // https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
        if (Browser.ie) {
            // ie doesn't support options as the third parameter
            obj.addEventListener(type, eventHandler, false);
        } else {
            obj.addEventListener(type, eventHandler, { capture: false, passive: false });
        }
```
如果不是ie，addEventListener 第三个参数是 options，但是在chrome 49以下的版本，第三个参数不支持options的写法
[mdn-api_eventtarget_addeventlistener_options_parameter](https://caniuse.com/mdn-api_eventtarget_addeventlistener_options_parameter)

这导致了在chrome 49以下的版本使用出现了异常，点击地图后地图随鼠标移动而移动，根本无法使用。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://maptalks.org/examples/en/map/load/#map_load

**Comment by fuzhenn** [comment]
收到~
看上去改起来不难，而且我这里没有这么低版本的chrome，能否提个pr给我？谢谢啦！

**Comment by mrdonkey3** [comment]
> 收到~
> 看上去改起来不难，而且我这里没有这么低版本的chrome，能否提个pr给我？谢谢啦！

我之前没提过pr，我尝试一下😶
