### ISSUE TITLE
use layer's identify and clear function at the same time will cause an error

### ISSUE THREAD

**Issue by Wincy94** [maptalks/maptalks.js#1587]
**maptalks's version and what browser you use?**
----
maptalks version : ^1.0.0-beta.7
browser: chrome

**Issue description**
----
I call the identify function on a layer , and then I call the layer's clear function. It will throw out an error:
![image](https://user-images.githubusercontent.com/26516358/153530574-b772f8e9-1195-4379-b105-d0b40fafa215.png)

It seems like the clear function will destroy the layer's renderCanvas directly.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Thanks for submiting this issue!
Could you provide a reproduction on codepen? I'm afraid I may have any misunderstanding if I reproduce by myself.

**Comment by deyihu** [comment]
No issues found in the current version
https://codepen.io/deyihu/pen/RwmJQXq?editors=1010
