### ISSUE TITLE
加载WMTS瓦片图层出错

### ISSUE THREAD

**Issue by kokonatsuli** [maptalks/maptalks.js#1588]
**maptalks's version and what browser you use?**
----
1.0.0-beta.8及以上版本

**Issue description**
----
加载WMTS瓦片图层（天地图）出错了，直到1.0.0-beta.7版本是正常的。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
这个问题在官网的 [示例](https://maptalks.org/examples/en/tilelayer-projection/wmts-tile/#tilelayer-projection_wmts-tile) 中可以看到
![image](https://user-images.githubusercontent.com/40257376/153898873-b05fa12e-6e51-4bd3-b210-532998869dbd.png)

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.js/commit/f9d0940bf04c9e4b14eacb26083c88786bc8537b
