### ISSUE TITLE
maptalks的微信小程序适配

### ISSUE THREAD

**Issue by zsunpl** [maptalks/maptalks.js#1589]
微信小程序有大量的2d地图展示应用需求，很多时候又不想仅限于一家地图平台（例如百度、腾讯、高德啥的）。我们现在想把maptalks适配到微信小程序环境，想要利用 https://github.com/yannliao/miniapp-adapter 来实现。但是看了下源码，好多maptalks很依赖H5的div标签、以及H5的各个对象。感觉适配工作量会很大。请问你们有没有maptalks微信小程序版的开发计划？或者微信小程序适配方面有什么建议，能够降低工作量？如果能够适配成功，我们打算把代码开源放到github。

**Comment by fuzhenn** [comment]
有这个开发计划的，不过目前暂时还不晓得啥时候会开始开发。
我们最近的开发计划是地形数据的加载，如果没有特别的安排的，可能地形开发完后，就会来做微信小程序的适配。

**Comment by HogwartsRico** [comment]
> 有这个开发计划的，不过目前暂时还不晓得啥时候会开始开发。 我们最近的开发计划是地形数据的加载，如果没有特别的安排的，可能地形开发完后，就会来做微信小程序的适配。

期待

**Comment by wucangeo** [comment]
> 有这个开发计划的，不过目前暂时还不晓得啥时候会开始开发。
> 我们最近的开发计划是地形数据的加载，如果没有特别的安排的，可能地形开发完后，就会来做微信小程序的适配。

大佬，地形功能发布了吗？
