### ISSUE TITLE
1.0.0-beta.8及以上加载tilelayer的问题

### ISSUE THREAD

**Issue by RyfiLucy** [maptalks/maptalks.js#1591]
**maptalks's version and what browser you use?**
----
1.0.0-beta.8及以上

**Issue description**
----
TileLayer的urlTemplate无法通过关键字做反向代理，请求响应地址的切图服务

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![image](https://user-images.githubusercontent.com/22829619/154206963-25372541-0dcb-4681-a544-137505ff6fe9.png)
beta.8之前的版本这个地址是可以做代理请求的，但升级之后浏览器旧不进行请求了

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.js/pull/1581
