### ISSUE TITLE
Error when loading tile

### ISSUE THREAD

**Issue by shashidhar568** [maptalks/maptalks.js#1619]
Hi , 
    I am using maptalks  version "^1.0.0-beta.10". I tried loading the tile that was created from maptiler but getting 'error when loading tile'. Please help me with the solution. Thanks in advance. 

https://codepen.io/shashidhar568/pen/qBVgpNO

**Comment by fuzhenn** [comment]
TileLayer only supports image format tile like png/jpg etc, maptiler's tile is a json format vector tile, so this is expected.
