### ISSUE TITLE
矩形会强制垂直于坐标轴，且无法手动旋转

### ISSUE THREAD

**Issue by dev-kxy** [maptalks/maptalks.js#1625]
如题

**Comment by fuzhenn** [comment]
不是很明白您的意思，能否提供一个重现代码？

**Comment by dev-kxy** [comment]
https://codepen.io/dev-kxy/pen/JjOQdmK
这里提供了一个旋转矩形的重现代码。
实际上我发现任何图形都不能旋转，包括imageLayer

**Comment by dev-kxy** [comment]
因为我的地图采用的utm坐标系，坐标轴自带地理倾角。所以我的矩形和imageLayer都是偏的。
![image](https://user-images.githubusercontent.com/38744990/157358928-1e6dbed4-eef5-47c3-8b99-b30f4af6d1d7.png)
