### ISSUE TITLE
使用3857的坐标系投影，mouseover事件会强行将repeat的瓦片部分的坐标重置到4326坐标

### ISSUE THREAD

**Issue by wgsheng06** [maptalks/maptalks.js#1634]
**maptalks's version and what browser you use?**
----

**Issue description**
----
使用3857的坐标系投影，mouseover事件会强行将repeat的瓦片部分的坐标重置到4326坐标，这样的话无法识别是否已经在地图外了，已经设置瓦片repeatWorld为false
使用的here瓦片，
 设置 spatialReference: {
        projection: 'EPSG:3857'
      },

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by wgsheng06** [comment]
maptalks's version and what browser you use?

^0.47.2

**Comment by fuzhenn** [comment]
不好意思刚看到这个issue，能否提供一个重现代码？谢谢，我还没有准确的明白您的意思

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.js/pull/2341
