### ISSUE TITLE
setZIndex 导致绑定事件错乱

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/maptalks.js#1635]
**maptalks's version and what browser you use?**
----
latest

**Issue description**
----
setZIndex 导致绑定事件错乱

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/the-end-hero/pen/BaJNNXj

**Comment by The-End-Hero** [comment]
猜测setZIndex 导致绑定顺序变化？事件使用下标寻找？

**Comment by The-End-Hero** [comment]
连续点击同一个图形。回调函数中target，会发生变化

**Comment by The-End-Hero** [comment]
@fuzhenn

**Comment by fuzhenn** [comment]
该问题已经解决，新的vt版本发布后解决

**Comment by fuzhenn** [comment]
新的vt版本已经发布
