### ISSUE TITLE
distanceTool AreaTool

### ISSUE THREAD

**Issue by stateless8289** [maptalks/maptalks.js#1636]
**maptalks's version and what browser you use?**
v1.0.0.0-rc2

**Issue description**
distanceTool AreaTool    绘制第二个图形的时候 使用 undo 方法，会删除上一个图形的点标注。

**Please provide a reproduction URL (on any jsfiddle like site)**
https://codepen.io/114714267/pen/ExoVaLj

**Comment by fuzhenn** [comment]
请麻烦提供一个重现代码
