### ISSUE TITLE
低层级，渲染几何，设置样式markerPlacement为verter时，由于路径被简化了，有一些顶点没有样式

### ISSUE THREAD

**Issue by just-ads** [maptalks/maptalks.js#1639]
https://codepen.io/pzd2937/pen/QWayZLV?editors=1010

**Comment by fuzhenn** [comment]
这个不算bug，需要在VectorLayer中关闭图形简化，enableSImplify:false
```js
var layer = new maptalks.VectorLayer('vector', {crossOrigin: 'anonymous', enableSimplify: false}).addTo(map);
```

或者改用[LineStringLayer](https://doc.maptalks.com/docs/api/vt/linestring-layer/)，它也是不会简化的

**Comment by just-ads** [comment]
> 这个不算bug，需要在VectorLayer中关闭图形简化，enableSImplify:false
> 
> ```js
> var layer = new maptalks.VectorLayer('vector', {crossOrigin: 'anonymous', enableSimplify: false}).addTo(map);
> ```
> 
> 或者改用[LineStringLayer](https://doc.maptalks.com/docs/api/vt/linestring-layer/)，它也是不会简化的

低层级渲染，放大到高层级，顶点也没有样式也不算bug吗
