### ISSUE TITLE
无法加载openstreetmap的底图

### ISSUE THREAD

**Issue by ShenWeiQun** [maptalks/maptalks.js#1643]
**maptalks's version and what browser you use?**
----
maptalks v1.0.0-beta.10
chrome 98.0.4758.80

**Issue description**
----
```js
var map = new maptalks.Map("map",{
     center:     [180,0],
     zoom:  4,
     baseLayer : new maptalks.TileLayer("base",{
         urlTemplate:'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
         subdomains:['a','b','c']
     }),
     layers : [
         new maptalks.VectorLayer('v', [new maptalks.Marker([180, 0])])
     ]
});

```
当按照官网的[map api](https://maptalks.org/maptalks.js/api/1.x/Map.html)使用`http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`路径作为底图时会出错，报错如下

```
Access to fetch at 'https://b.tile.openstreetmap.org/2/2/2.png' from origin 'http://127.0.0.1:5501' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
我测试下使用`openlayers`是可以正常加载的，而且`openstreetmap`也设置了跨域
```
access-control-allow-origin: *
```

**Please provide a reproduction URL (on any jsfiddle like site)**
----

[openstreetmap底图错误](https://codepen.io/shenweiqun/pen/LYexXXZ)

**Comment by fuzhenn** [comment]
为了提高性能，TileLayer在1.0.0-rc.1中默认在worker中用fetch加载瓦片并解码，但osm的瓦片服务并不支持在localhost域名(或127.0.0.1上）这样请求瓦片（但用其他域名是可以的）。
1.0.0-rc.3为了兼容性，默认关闭了在worker中加载瓦片解码的功能，本问题也随之解决。
目前其他瓦片服务都能在worker中加载，如果你想开启该特性，可以在创建TileLayer时，把options中的decodeImageInWorker设成true即可。
```js
    new maptalks.TileLayer("base",{
         urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',,
         subdomains:['a','b','c'],
         decodeImageInWorker: true
     })
```
