### ISSUE TITLE
maptalks.plotsymbol编辑报错，导致移动地图时编辑节点也跟随移动

### ISSUE THREAD

**Issue by SimpleYong** [maptalks/maptalks.js#1645]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
---- https://codepen.io/simpleyong/pen/KKZaYEV

**Comment by fuzhenn** [comment]
已解决，并发布了 maptalks.ploysymbol 0.6.0版。
另外还发现了另外一个问题，开始startEdit后，应该隐藏掉的创建新端点的handle是可见的，核心库1.0.0-rc.4解决了该问题。
