### ISSUE TITLE
macbookpro 16款 15寸polygonLayer性能低于vectorLayer

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/maptalks.js#1646]
**maptalks's version and what browser you use?**
----
1.0.0-rc3

**Issue description**
----
macbookpro 16款 15寸 i7 6700hq cpu / radeon pro 450 gpu: polygonLayer性能低于vectorLayer

**Please provide a reproduction URL (on any jsfiddle like site)**
----

https://codepen.io/the-end-hero/pen/WNdpNYK
https://codepen.io/the-end-hero/pen/jOYyoga

**Comment by fuzhenn** [comment]
这个现象应该是正常的，因为地图没有倾斜时，且VectorLayer默认没有开启forceRenderOnMoving时，VectorLayer图层在移动地图时不会绘制，只涉及到了canvas的复制而已。

但PolygonLayer因为是webgl图层，默认开启了forceRenderOnMoving的，移动地图时默认会绘制。

要公平比较两者性能，应该开启VectorLayer的forceRenderOnMoving，或者把地图都设置一个倾斜角度，就会明显发现PolygonLayer性能好很多了。
