### ISSUE TITLE
如何使用碰撞检测

### ISSUE THREAD

**Issue by QJvic** [maptalks/maptalks.js#1650]
**maptalks's version and what browser you use?**
----

1.0.0-rc.4
**Issue description**
----
注意到最新的release中提到了碰撞检测，且查看文档layer的collisionScope默认为layer，但如何使用以进行点的碰撞隐藏？

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by QJvic** [comment]
已开启 collision: true

**Comment by fuzhenn** [comment]
碰撞检测是在PointLayer和VectorTileLayer中开启的，具体可以参考：
examples.maptalks.com 中碰撞检测的相关示例

**Comment by QJvic** [comment]
@fuzhenn Thanks a lot！例子似乎比官网的更丰富更详细，如果不是您告诉我有这个地址，根本找不到入口进入。
