### ISSUE TITLE
自己的arcgis瓦片服务,在一些缩放等级下地图倾斜的时候,瓦片不显示

### ISSUE THREAD

**Issue by wenner** [maptalks/maptalks.js#1656]
v0.47.0 ~ v1.0.0-rc.4
----
情况说明: 
**使用自己的arcgis瓦片服务，pitch = 0 一切正常， pitch > 0 的话，在一些分辨率下，瓦片显示不正常**

基于官方例子  [ArcGIS瓦片图层](https://maptalks.org/examples/cn/tilelayer-projection/arcgis-tile/) ，官方例子没有任何问题，只是换成自己的 arcgis 服务（maxZoom=7），一度以为自己发布的地图服务有问题 🤣
这个情况挺久了, 但是最开始使用maptalks的时候肯定没有异常（当时用也是喜欢倾斜的功能）, 这次仔细试了一下, 发现 <= 0.46.0  的版本都是正常的, 之后都有问题，几乎 所有支持的浏览器，所有分辨率(1080p, 2k , 4k) 都试过，问题基本一致

具体测试如下：
以下是对官方例子简单修改进行测试的，只是修改了 地图服务地址

### 测试1：版本 = v1.0.0-rc.4，固定pitch = 45
1. zoom=0开始，显示正常
2. 滚动滚轮，放大地图，只有在一些zoom（0，4，5，7）下显示正常，其他的显示都不正常

![1](https://user-images.githubusercontent.com/157351/163543823-fb5f57bd-db89-4f9b-9100-ac066d3897fd.gif)

### 测试2：版本 = v1.0.0-rc.4，pitch = 0
1. zoom=0且pitch=0开始，显示正常
2. 拖动让地图倾斜（pitch>0)，在一些zoom(0，4，5，7）下显示正常，其他的显示不正常
3. 还原pitch = 0，放大地图，所有显示正常
因为只让上传10M内容，所以截屏速度稍快😒

![录制_2022_04_15_16_27_37_174](https://user-images.githubusercontent.com/157351/163546417-13d542af-74e3-4234-88da-721db04a130b.gif)

### 测试3：版本= v0.46.0，重复测试1
✔所有显示都正常
本来发这个问题的时候，还没测到0.46.0，最后多试了一些，就发现这个版本可以使用
![3](https://user-images.githubusercontent.com/157351/163546812-c49b5262-7f3d-4953-8742-1e425c13e520.gif)

### 测试4：版本= v0.46.0，重复测试2
✔所有显示都正常
![录制_2022_04_15_16_31_27_988](https://user-images.githubusercontent.com/157351/163547158-1db8f43e-807b-4f23-a1b0-943e3858e6ca.gif)

---
@fuzhenn 已经把测试的html发到您邮箱 (fuzhen AT maptalks.org），如果需要，可以看一下

**Comment by fuzhenn** [comment]
虽然还未解决，但有个临时的解决方案是创建TileLayer时，把options里的cascadeTiles设为false即可。
```js
          const baseLayer = new maptalks.TileLayer('base', {
            'cascadeTiles': false,
            'tileSystem' : conf.tileSystem,
            'tileSize' : conf.tileSize, // [512, 512]
            'urlTemplate' : arcUrl + '/tile/{z}/{y}/{x}',
            'attribution' : '&copy; <a target="_blank" href="' + arcUrl + '"">ArcGIS</a>'
          })
```

**Comment by fuzhenn** [comment]
cascadeTiles的作用是把地图分成三个级别来加载，假设当前级别是z，最远处加载z-5级瓦片，中间加载z-1级瓦片，近处加载z级的瓦片。
这样可以显著减少加载的瓦片数量，提高图层渲染性能。
但如果z-5级不存在，则远处原本显示z-5级瓦片的位置会显示空白。
因为你的arcgis底图级别很少，可以根据实际的性能表现，酌情考虑是否开启cascadeTiles。

**Comment by wenner** [comment]
好的，了解了，我试一下。
再次感谢！
