### ISSUE TITLE
关于线的填充动画（Line patttern animation）的性能问题

### ISSUE THREAD

**Issue by kokonatsuli** [maptalks/maptalks.js#1661]
**maptalks's version and what browser you use?**
----
1.0.0-beta.7  （1.0.0-rc.4也尝试过，现象是一致的）
Chrome 100.0.4896.127
系统：Windows 11 21H2

**Issue description**
----
用LineString绘制多条路径，参照示例（[线的模式填充动画](https://maptalks.org/examples/cn/style/line-pattern-animation/#style_line-pattern-animation)）给LineString加上动画，发生了奇怪的现象：
一开始动画运行流畅，但**只要鼠标在浏览器窗口范围内移动**，不需要任何交互，就会发生GPU占用迅速降低，然后动画严重卡顿的现象。
如果像示例中，只有一条线，只有起止两个坐标时，没有发生这种现象，需要有一定量的路径数据；
在Firefox浏览器中没有发现这种问题。
关于这个问题，有没有好的解决方法？

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![image](https://user-images.githubusercontent.com/40257376/164203859-44ed4c2a-3845-44be-a9ef-36d002ee4efb.png)

**Comment by fuzhenn** [comment]
这个线的动画实现本身是有点半吊子，可以改用[LineStringLayer](https://doc.maptalks.com/docs/api/vt/linestring-layer/)用symbol里的[linePatternAnimSpeed属性](https://doc.maptalks.com/docs/style/symbols/#linepatternanimspeed)试试
