### ISSUE TITLE
Event Sensibility Setting

### ISSUE THREAD

**Issue by korhanozbek44** [maptalks/maptalks.js#1663]
**maptalks's version and what browser you use?**
----
browser version (1.0.0-rc.1)

**Issue description**
----
I'm using maptalks.threejs plugin with maptalks. When i drag map a little bit fast, click event triggering. Actually in mobile, triggering much more wrongly. I search code and i didn't find solution like sensivity value precision. How can solve this problem ?

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
The click event will be fired when timespan of mousedown and mouseup is smaller than CLICK_TIME_THRESHOLD (default is 300ms) defined in Map.DomEvents.js.

You can reduce sensibility of click event by setting a smaller value of CLICK_TIME_THRESHOLD.

For convinience, I'm considering to change CLICK_TIME_THRESHOLD from a global constant to a map's configurable option.

**Comment by korhanozbek44** [comment]
Thanks for reply. I check already the code and I thought CLICK_TIME_THRESHOLD is solving my problem. But i have to do without fork. If it can be in map's option, it will be great.

**Comment by korhanozbek44** [comment]
@fuzhenn When will you publish next release with this feature ?

**Comment by fuzhenn** [comment]
it's already published in 1.0.0-rc.5 (now is 1.0.0-rc.10)

**Comment by korhanozbek44** [comment]
oww ok. Thank you.
