### ISSUE TITLE
什么时候可以支持terrain 数据（url引入）加载

### ISSUE THREAD

**Issue by PoreyTaken** [maptalks/maptalks.js#1671]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
地形正在开发中，目前大概进度60%吧，我们支持的一些特性：
* 支持cesium的terrain格式，天地图地形格式，mapbox的png地形格式
* 可以用参数调整地形的绘制精度，提升性能
* 支持把矢量瓦片用作地形贴图

**Comment by giswrok** [comment]
@fuzhenn 太棒了，期待

**Comment by giswrok** [comment]
@fuzhenn 当地图的pitch 大于0以后（比如80），this.getTiles().tileGrids  this._renderer.tilesInView 这里的切片的数量感觉存在问题，如果pitch等于0，纯二维平面是没问题，但是pitch大于0以后，三维视图下地图的视野范围应该是被增大的，现在的renderer.tilesInView会造成靠近相机部分有地形切片，但是远离相机部分就没有了。
![1678857724684](https://user-images.githubusercontent.com/4919052/225215112-6cde41f4-63f4-4dab-8df4-9ee53411e733.jpg)
