### ISSUE TITLE
一个页面不能同时显示两个地图，如何解决

### ISSUE THREAD

**Issue by CendyceChen** [maptalks/maptalks.js#1675]
**maptalks's version and what browser you use?**
----
一个页面不能同时显示两个地图，如何解决

**Issue description**
----
一个地图做主页面，另一个弹窗用来回放轨迹，但不能同时正常显示两个地图，请问有没有小伙伴遇到类似的问题呢

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这应该不是引擎的问题，需要检查你的代码逻辑，如果仍然有问题，请发个重现代码。
载入多个地图实例的示例：
https://maptalks.org/examples/cn/json/layer-json/#json_layer-json

**Comment by CendyceChen** [comment]
我尝试了，在一个页面用不同的div初始化正常。当我做成组件的时候，就不行了，为了区分，我还特地写了两个组件，分布注册不同的div

**Comment by CendyceChen** [comment]
> 这应该不是引擎的问题，需要检查你的代码逻辑，如果仍然有问题，请发个重现代码。 载入多个地图实例的示例： https://maptalks.org/examples/cn/json/layer-json/#json_layer-json

我尝试了，在一个页面用不同的div初始化正常。当我做成组件的时候，就不行了，为了区分，我还特地写了两个组件，分布注册不同的div

**Comment by deyihu** [comment]
@CendyceChen  这个是你的代码有问题，组件应该使用动态容器，而不是domId

[code sandbox demo](https://codesandbox.io/s/funny-bardeen-d1s7nf?file=/src/components/Map.vue)

**Comment by CendyceChen** [comment]
> @CendyceChen 这个是你的代码有问题，组件应该使用动态容器，而不是domId
> 
> [code sandbox demo](https://codesandbox.io/s/funny-bardeen-d1s7nf?file=/src/components/Map.vue)

好的好的，我去试试看

**Comment by fuzhenn** [comment]
先关闭

**Comment by CendyceChen** [comment]
> 先关闭

可分享具体的思路吗，封装了组件来分别显示实时、回放的数据

**Comment by bartimos** [comment]
遇到同样的问题，首先需要保证不同的dom，其次在maptalks初始化的时候，options中的baseLayer 属性必须保证每次都是全新的。我的项目由于把options抽离封装导致，即便两个maptalks对象，也会有问题
