### ISSUE TITLE
是否支持初始化是一个地球仪的效果，如cesium那种

### ISSUE THREAD

**Issue by sqzxy** [maptalks/maptalks.js#1681]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
目前还不支持，未来考虑用插件的形式单独实现球体效果，然后在某个级别和现在的地图无感切换，但这个功能不在近期的开发计划内。

**Comment by roshomon** [comment]
请问，今年有这样的球体插件计划？

**Comment by fuzhenn** [comment]
请参考 https://github.com/maptalks/issues/issues/400

**Comment by sqzxy** [comment]
发现最新版本的使用 maptalks.webgl.min.js,使用里面的BigPointLayer层加载海量数据后，存在bug,绘制的点位数据会跟着地图拖动而跳动，缩小就不见了，用下面的demo测试发现的：



***@***.***
 
发件人： Fu Zhen
发送时间： 2023-08-11 11:05
收件人： maptalks/maptalks.js
抄送： sqzxy; Author
主题： Re: [maptalks/maptalks.js] 是否支持初始化是一个地球仪的效果，如cesium那种 (Issue #1681)
请参考 maptalks/issues#400

**Comment by fuzhenn** [comment]
sorry，maptalks.webgl插件是个早期的实验插件，已经废弃不用且不再维护了

> 发现最新版本的使用 maptalks.webgl.min.js,使用里面的BigPointLayer层加载海量数据后，存在bug,绘制的点位数据会跟着地图拖动而跳动，缩小就不见了，用下面的demo测试发现的： ***@***.*** 发件人： Fu Zhen 发送时间： 2023-08-11 11:05 收件人： maptalks/maptalks.js 抄送： sqzxy; Author 主题： Re: [maptalks/maptalks.js] 是否支持初始化是一个地球仪的效果，如cesium那种 (Issue #1681) 请参考 [maptalks/issues#400](https://github.com/maptalks/issues/issues/400) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sqzxy** [comment]
哦哦，好得，那现在新版本的支持之前那个截图的效果的api吗？



***@***.***
 
发件人： Fu Zhen
发送时间： 2023-08-11 16:56
收件人： maptalks/maptalks.js
抄送： sqzxy; Author
主题： Re: [maptalks/maptalks.js] 是否支持初始化是一个地球仪的效果，如cesium那种 (Issue #1681)
sorry，maptalks.webgl插件是个早期的实验插件，已经废弃不用且不再维护了
发现最新版本的使用 maptalks.webgl.min.js,使用里面的BigPointLayer层加载海量数据后，存在bug,绘制的点位数据会跟着地图拖动而跳动，缩小就不见了，用下面的demo测试发现的： @.*** 发件人： Fu Zhen 发送时间： 2023-08-11 11:05 收件人： maptalks/maptalks.js 抄送： sqzxy; Author 主题： Re: [maptalks/maptalks.js] 是否支持初始化是一个地球仪的效果，如cesium那种 (Issue #1681) 请参考 maptalks/issues#400 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>
