### ISSUE TITLE
建议使用别的方式解决LineString的centerHandle和newVertexHandle重叠的问题

### ISSUE THREAD

**Issue by cXiaof** [maptalks/maptalks.js#1689]
在编辑面图形的时候centerHandle会显示在图形center上，而在编辑线图形的时候centerHandle会偏移5个像素。翻看源代码后发现是为了避免和newVertexHandle重叠。
但是这个真的会产生误导，在一些场景中想要将中心点移动到某个位置时，肉眼看见的centerHandle的位置却并不在center上。
我也想过一些办法比如把centerHandle的Symbol设置为数组，一个Symbol标明中心点 另一个Symbol显示为Handle的样式并作Handle使用。但是失败了，因为centerHandleSymbol不支持数组。

https://github.com/maptalks/maptalks.js/blob/76c5d0ef9d2f6b5c5aabf338dd793932095f217a/src/geometry/editor/GeometryEditor.js#L282-L285

目前这个问题还是产生了一些困扰，希望能有其他方式来解决LineString的centerHandle和newVertexHandle重叠的问题

**Comment by fuzhenn** [comment]
可以考虑反过来，centerHandle不变，把newVertexHandle往右移动5个像素，应该就能解决这个问题了。

**Comment by cXiaof** [comment]
补充：
现在这个方式还有一个小问题。一旦编辑一个LineString后，无论后续再编辑的是线还是面，centerHandle都会偏移5像素

问题重现：https://codepen.io/cxiaof/pen/QWQdeJM
1. 点击1编辑Polygon，此时centerHandle在Polygon中心
2. 点击2编辑线，此时centerHandle偏移了5像素
3. 点击3再次编辑Polygon，此时centerHandle依然保持偏移5像素

应该是默认的centerHandleSymbol对象被修改了

**Comment by fuzhenn** [comment]
这个问题用上面说的方法应该也能一起解决，那我找个时间把newVertexHandle往右移动5个像素。
