### ISSUE TITLE
How to extend click tolerance with feature3d（如何扩展 feature3d 的鼠标可点范围？）

### ISSUE THREAD

**Issue by haelue** [maptalks/maptalks.js#1695]
https://maptalks.org/examples/en/3d/line-altitude/#3d_line-altitude
我希望鼠标在一定tolerance内靠近3D线，就能变成手指，就能点中
leaflet(2D) 有类似的 tolerance，在 map 中配置的：
```
L.map("map_root", { maxZoom: core_max_zoom, zoom:23, renderer: L.canvas({ tolerance: 15 }), editable: true, editOptions: {} }).setView(startPoint, 19)
```
其实最好是在 layer 中配置，或者在元素的 style 中加一个 clickWidth，区别于 lineWidth

**Comment by fuzhenn** [comment]
应该是可以的，但我不是很确定你说的feature3d是指的哪个图层，请说明一下

**Comment by haelue** [comment]
leaflet 有类似的 tolerance，在 map 中配置的：
`
L.map("map_root", { maxZoom: core_max_zoom, zoom:23, renderer: L.canvas({ tolerance: 15 }), editable: true, editOptions: {} }).setView(startPoint, 19)
`
其实最好是分图层，比如点云就不需要点击。

**Comment by haelue** [comment]
有个办法是给 style 加一个 linePatternFile，然后 png图片 中间填充，两边透明。加宽可选区。
但感得不太优雅，要是 style 里面能有个 clickWidth 就好了。

**Comment by haelue** [comment]
https://maptalks.org/examples/en/3d/line-altitude/#3d_line-altitude
示例中的线 lineWidth 设为 1，则难以用鼠标点中。希望能有一个 clickWidth（或其它机制），拓宽鼠标可选区，使容易点中。

**Comment by haelue** [comment]
我们作业的时候，经常需要用鼠标点击图元显示/修改属性。polygon / circle 都好点，但对于狭长的 polyline，不把可点区域拓宽一点会很让人抓狂的

**Comment by fuzhenn** [comment]
VectorLayer上增加了 geometryEventTolerance 设置，用来设置触发事件的tolerance，单位是像素

**Comment by haelue** [comment]
太好了！谢谢！！
