### ISSUE TITLE
TileLayer 倾斜问题

### ISSUE THREAD

**Issue by Simon-wu** [maptalks/maptalks.js#1698]
在使用中发现，当底图的仰角到30 度左右，屏幕显示比较窄的情况下，上下贴图层级不一致的问题，文字拼接就出现了问题，请问是否有参数设置，或者是设计如此，

<a href="https://imgtu.com/i/OOZh01"><img src="https://s1.ax1x.com/2022/05/20/OOZh01.png" alt="OOZh01.png" border="0" /></a>

**Comment by fuzhenn** [comment]
设计如此，为了避免一屏瓦片数量太大，造成性能下降。
可以通过设置TileLayer的如下options来关闭:
* cascadeTiles设为false
* pyramidMode设为0

**Comment by Simon-wu** [comment]
> 

3Q
