### ISSUE TITLE
LineString两个端点距离很近，同时给线条颜色设置渐变，线条的颜色会消失

### ISSUE THREAD

**Issue by just-ads** [maptalks/maptalks.js#1712]
https://codepen.io/pzd2937/pen/oNEpEzW?editors=0010

**Comment by OnePunchManGhy** [comment]
我也遇到这个问题了，真的无语，进来大的不显示，放大点大的又显示了，还有设置cursor:'pointer'也没效果
![image](https://user-images.githubusercontent.com/52189562/170967866-83dabb9e-9bf9-47ea-8072-275e92329ed1.png)
![image](https://user-images.githubusercontent.com/52189562/170967947-b3182753-6f0c-4cff-b016-9b8e883acccb.png)

**Comment by just-ads** [comment]
> 我也遇到这个问题了，真的无语，进来大的不显示，放大点大的又显示了，还有设置cursor:'pointer'也没效果 ![image](https://user-images.githubusercontent.com/52189562/170967866-83dabb9e-9bf9-47ea-8072-275e92329ed1.png) ![image](https://user-images.githubusercontent.com/52189562/170967947-b3182753-6f0c-4cff-b016-9b8e883acccb.png)

显示是因为线条被裁剪了

**Comment by fuzhenn** [comment]
那把VectorLayer options里的enableSimplify设成false试试看

**Comment by just-ads** [comment]
> 

刚刚试了，不行，codepen 更新了

**Comment by OnePunchManGhy** [comment]
marker和lineString设置cursor:'pointer'没效果，不知道为什么，就很奇怪，同时作者大大要是看到这个问题的话，能不能加个动态蚂蚁线的功能，用现在的模式填充，图片填充线段，线段长了很卡，附上代码，同时 也加上这个了，没效果
![image](https://user-images.githubusercontent.com/52189562/170969785-a6c54eb8-d185-44d9-b3d0-e23894baa5e1.png)

**Comment by fuzhenn** [comment]
收到，我晚点会解决一下这个问题

**Comment by OnePunchManGhy** [comment]
好的，感谢大佬
