### ISSUE TITLE
GroupTileLayer isn't aware of childLayer.remove()

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1719]
**maptalks's version and what browser you use?**
----
1.0.0-rc.6

**Issue description**
----
调用childLayer的remove方法后，GroupTileLayer没有接收到子图层的remove事件，导致了一些绘制问题。
相关pr #1718 能暂时解决被remove的childLayer的获取瓦片逻辑的错误，但上述问题依然存在

**Please provide a reproduction URL (on any jsfiddle like site)**
----
```js
const tileLayer = new TileLayer(...);
const groupLayer = new GroupTileLayer('group', [tileLayer]).addTo(map);

tileLayer.remove();
```

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.js/pull/1673
