### ISSUE TITLE
在移动端编辑矩形/圆形/椭圆等  会报一个bug，maptalks.min.js:6 Uncaught Error: Position is NaN

### ISSUE THREAD

**Issue by xp002** [maptalks/maptalks.js#1720]
在移动端编辑矩形/圆形/椭圆等  会报一个错误，Uncaught Error: Position is NaN，这个怎么解决呢？

**Comment by xp002** [comment]
已解决，我把版本从maptalks v1.0.0-rc.6  降至 maptalks v0.49.1  解决了此问题

**Comment by fuzhenn** [comment]
收到，我还没来得及看这个问题，回头我会重现解决一下的

**Comment by xp002** [comment]
@fuzhenn 膜拜大佬

**Comment by The-End-Hero** [comment]
> 收到，我还没来得及看这个问题，回头我会重现解决一下的

目前移动端无法编辑图形
