### ISSUE TITLE
pixijs game engine support

### ISSUE THREAD

**Issue by someall2003** [maptalks/maptalks.js#1721]
**maptalks's version and what browser you use?**
----
i am new for using maptalks i used to use leaflet 

**Issue description**
----
can you provide plugin for pixijs game engine because it will give us wide range of ability to do in map.
i want to move from leaflet developer to maptalks but still no support for game engine.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
Thank you for your question. Due to limited energy, I don't have time to develop this feature. You can go to the community to find if there is a corresponding plugin, otherwise you will have to develop it yourself
