### ISSUE TITLE
能否提供一个在react脚手架中使用mapbox矢量瓦片的demo

### ISSUE THREAD

**Issue by nijiayu0914** [maptalks/maptalks.js#1722]
**Issue description**
能否提供一个在react脚手架中使用mapbox矢量瓦片的demo，包括package.json相关依赖和一个demo page  hook function

**Comment by deyihu** [comment]
谢谢提问，由于精力有限，没有时间来开发这个功能，可以去社区找找有没有对应的插件，否则只能你自己来开发了
