### ISSUE TITLE
测距工具 标签点击，会清除图形，应该是点击“X” 才会清除的吧

### ISSUE THREAD

**Issue by Gweidong** [maptalks/maptalks.js#1737]
**maptalks's version and what browser you use?**
----
last

**Issue description**
----
测距工具 最后的一个节点标签点击，会清除图形，应该是点击“X” 才会清除的吧

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/gwdzZZ/pen/dymoKPp

**Comment by deyihu** [comment]
marker的包围盒计算错误导致的
