### ISSUE TITLE
Cannot read properties of null (reading 'options')

### ISSUE THREAD

**Issue by RyfiLucy** [maptalks/maptalks.js#1738]
**maptalks's version and what browser you use?**
----
1.0.0-rc.6

**Issue description**
----
i use arcgis tilelayer in my vue project,when i close my dialog,the console log always report the same error---cannot read properties of null (reading 'options').
And when i open the dialog again, the map cannot move. These are the problem pic:
![image](https://user-images.githubusercontent.com/22829619/177103906-84e00a29-6b69-483c-ac7e-8d8bc6c39294.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.js/commit/1a03d7d648c3bfa7f97f4b1f0c4ac7cd541712bf

**Comment by RyfiLucy** [comment]
which version can i update?

**Comment by deyihu** [comment]
@fuzhenn

**Comment by fuzhenn** [comment]
thank @deyihu , I plan to publish a new version at the end of this week.
