### ISSUE TITLE
使用three.js创建的geometry添加到threeLayer上，在地图旋转和倾斜时，网格物体相对地图位置产生偏移

### ISSUE THREAD

**Issue by lixin131** [maptalks/maptalks.js#1746]
通过BaseObject创建的立方体

class Box extends BaseObject {
  constructor(coordinate: any, options: any, material: any, layer: any) {
    options = Util.extend({}, options, { layer, coordinate });
    super();
    this._initOptions(options);
    const geometry = new BoxBufferGeometry(0.5, 0.5, 0.5);
    this._createMesh(geometry, material);
    const position = layer.coordinateToVector3(coordinate, 0);
    this.getObject3d().position.copy(position);
  }
}

添加自定义立方体的代码

threeLayer.prepareToDraw = (gl: any, scene: Scene, camera: PerspectiveCamera) => {
    const material = new MeshBasicMaterial({
      color: 0xff0000
    });
    const box = new Box([115.88542981657292, 28.691307013823035], undefined, material, threeLayer);
    threeLayer.addMesh(box);
  };
  
  初始化时，立方体相对地图而言位置正常。但是一旦地图旋转和倾斜的时候，立方体相对地图位置就会产生偏移。

three.js 是 0.142.0

**Comment by deyihu** [comment]
@lixin131  给个完整的代码

**Comment by lixin131** [comment]
@deyihu   您好，这是代码。

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script type="text/javascript" src="https://unpkg.com/maptalks/dist/maptalks.js"></script>
  <script type="text/javascript" src="https://unpkg.com/@maptalks/gl/dist/maptalksgl.js"></script>
  <script type="text/javascript" src="https://unpkg.com/three@0.142.0/build/three.min.js"></script>
  <script type="text/javascript" src="https://unpkg.com/maptalks.three@latest/dist/maptalks.three.js"></script>
  <style>
    * { margin: 0; padding: 0; }
    #con { width: 100vw; height: 100vh; }
  </style>
</head>
<body>
  <div id="con"></div>
  <script>
    const map = new maptalks.Map('con', {
      center: [ 115.88545277764888, 28.690837011301966 ],
      zoom: 17,
      pitch: 45,
      baseLayer: new maptalks.TileLayer('base', {
        urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
        subdomains: [ 'a', 'b', 'c', 'd' ]
      }),
      attribution: false
    });

    const threeLayer = new maptalks.ThreeLayer('t', {
      forceRenderOnMoving: true,
      forceRenderOnRotating: true
    });

    threeLayer.prepareToDraw = (gl, scene, camera) => {
      const material = new THREE.MeshBasicMaterial({
        color: 0xff0000
      });
      const box = new Box([115.88542981657292, 28.691307013823035], undefined, material, threeLayer);
      threeLayer.addMesh(box);
    };

    threeLayer.addTo(map);

    class Box extends maptalks.BaseObject {
      constructor(coordinate, options, material, layer) {
        options = maptalks.Util.extend({}, options, { layer, coordinate });
        super();
        this._initOptions(options);
        const geometry = new THREE.BoxBufferGeometry(1, 1, 1);
        this._createMesh(geometry, material);
        const position = layer.coordinateToVector3(coordinate, 0);
        this.getObject3d().position.copy(position);
      }
    }
  </script>
</body>
</html>

**Comment by lixin131** [comment]
@deyihu  您好，这是完整代码。

    const map = new maptalks.Map('con', {
      center: [ 115.88545277764888, 28.690837011301966 ],
      zoom: 17,
      pitch: 45,
      baseLayer: new maptalks.TileLayer('base', {
        urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
        subdomains: [ 'a', 'b', 'c', 'd' ]
      }),
      attribution: false
    });

    const threeLayer = new maptalks.ThreeLayer('t', {
      forceRenderOnMoving: true,
      forceRenderOnRotating: true
    });

    threeLayer.prepareToDraw = (gl, scene, camera) => {
      const material = new THREE.MeshBasicMaterial({
        color: 0xff0000
      });
      const box = new Box([115.88542981657292, 28.691307013823035], undefined, material, threeLayer);
      threeLayer.addMesh(box);
    };

    threeLayer.addTo(map);

    class Box extends maptalks.BaseObject {
      constructor(coordinate, options, material, layer) {
        options = maptalks.Util.extend({}, options, { layer, coordinate });
        super();
        this._initOptions(options);
        const geometry = new THREE.BoxBufferGeometry(1, 1, 1);
        this._createMesh(geometry, material);
        const position = layer.coordinateToVector3(coordinate, 0);
        this.getObject3d().position.copy(position);
      }
    }

**Comment by deyihu** [comment]
@lixin131  这个不是bug,boxgeometry的原点不是在底部的，所以你加的box有一般在地图地底下


```js
  class Box extends maptalks.BaseObject {
            constructor(coordinate, options, material, layer) {
                options = maptalks.Util.extend({}, options, { layer, coordinate });
                super();
                this._initOptions(options);
                const geometry = new THREE.BoxBufferGeometry(1, 1, 1);
                geometry.translate(0, 0, 0.5);
                this._createMesh(geometry, material);
                const position = layer.coordinateToVector3(coordinate, 0);
                this.getObject3d().position.copy(position);
            }
        }
```

可以这样试试

**Comment by lixin131** [comment]
@deyihu 

非常感谢您，可以了。
