### ISSUE TITLE
画图工具生成图形放入gl内，开启拖拽，操作卡顿

### ISSUE THREAD

**Issue by FEJackFly** [maptalks/maptalks.js#1749]
**maptalks's version and what browser you use?**
----
设备：macbookpro 16
系统：macos 12.4
硬件：i7 16 + 512 AMD5300m 4g
浏览器：chrome 102.0.5005.115
显示器：4k

**Issue description**
----
<img width="1946" alt="image" src="https://user-images.githubusercontent.com/24688308/179953745-6c9e6bfc-0961-4380-bb49-68090f5cb9b3.png">

```
// gl图层打开
"hitDetect": true,
"geometryEvents": true,
```
滑动时CPU暴涨

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这个是geometryEvents和hitDetect导致的不停读取像素导致的
关掉geometryEvents和hitDetect后应该能解决

**Comment by FEJackFly** [comment]
都关了还有picking  可能还是 电脑的问题 linux 和mac都出现了这个问题

**Comment by FEJackFly** [comment]
geometryEvents 关闭拖拽事件就不能触发了吧，我一会再测一下

**Comment by deyihu** [comment]
当前版本不存在这个问题了
