### ISSUE TITLE
IOS设备中设置线的模式填充linePatternFile报错

### ISSUE THREAD

**Issue by cXiaof** [maptalks/maptalks.js#1761]
设置linePatternFile，PC和安卓设备正常，IOS设备地图崩溃

#### 重现方式
Example中《线的模式填充》，在IOS设备打开，在图片加载完成后做任意操作触发（需要将图片地址先换成绝对路径）
也可以直接看这个CodePen：[https://codepen.io/cxiaof/pen/OJvxgPQ](https://codepen.io/cxiaof/pen/OJvxgPQ)

**Comment by cXiaof** [comment]
IOS下微信小程序内打开H5，还是有这个报错
> TypeError: Type error
> createPattern@[native code]
> _setStrkoePattern
> prepareCanvas

IOS普通浏览器，安卓浏览器，安卓小程序，都不会报错。仅IOS下小程序会有这个错误

**Comment by mjixiang** [comment]
刚才也碰到这个问题了，确实在iphone的微信环境依然存在报错。看上面@fuzhenn 修复的内容加上了safari判断，但是微信的ua字符串不包含"safari"。@cXiaof 在源码没修复的情况下，可以临时这样处理：
```js
import { Browser } from 'maptalks'

const ua = navigator.userAgent
// 覆盖maptalks内safari判断逻辑，包含iphone微信环境
Browser.safari = Browser.safari || (/iphone/i.test(ua) && /micromessenger/i.test(ua))
```

**Comment by fuzhenn** [comment]
谢谢 @mjixiang ，已经在 https://github.com/maptalks/maptalks.js/commit/d1ec8d3d14e02a6cd7ac8084e02d20a865b90f6a 加入了对 ios weixin的判断
