### ISSUE TITLE
绘制单个图形坐标点太多(1350个)，vertexHandleSymbol更改图形激活样式导致面卡死

### ISSUE THREAD

**Issue by IIIzz** [maptalks/maptalks.js#1767]
**maptalks's version and what browser you use?**
----
"^0.49.3",
**Issue description**
----
绘制单个图形坐标点太多(1350个)，vertexHandleSymbol更改图形激活样式导致面卡死

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@noobzzzz  can you provice a demo?

**Comment by IIIzz** [comment]
我是通过kml文件解析出来的图形，但是github上传不了kml文件

**Comment by noobzzzz** [comment]
我通过邮箱把kml文件发你吧，能给我个邮箱么

**Comment by IIIzz** [comment]
我把kml文件发到你邮箱了

**Comment by deyihu** [comment]
@noobzzzz  这个是我写的例子，请基于这个例子，把你的出现问题的代码完善下

https://codepen.io/deyihu/pen/oNqypBv?editors=1010

**Comment by IIIzz** [comment]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/29473782/183543897-211b44ba-6ed3-48f6-951d-d2bd01fae820.png">
在1350多个坐标点的图形，调用startEdit方法 会导致浏览器卡死

**Comment by deyihu** [comment]
@noobzzzz  这个例子就是用你的数据，并未出现你说的卡死情况，另外如果用vue要注意，不要把复杂的对象（map,layer,geometry等）往data里放，vue会对data 建立watcher，导致性能急剧下降  

QQ群:237726126
