### ISSUE TITLE
marker 在执行 remove 或 removeInfoWindow 操作时其绑定的 infoWindow 的 DOM 没有被删除

### ISSUE THREAD

**Issue by shmen** [maptalks/maptalks.js#1768]
![image](https://user-images.githubusercontent.com/30108864/182772405-be67f921-1101-423c-bff8-0b87759a4a49.png)
![image](https://user-images.githubusercontent.com/30108864/182772534-0ffaf4cb-c23a-442b-8a6d-a4e5ece64059.png)

**Comment by fuzhenn** [comment]
设计如此，并不是bug
