### ISSUE TITLE
希望多变形编辑，增加点位吸附功能。

### ISSUE THREAD

**Issue by coloz** [maptalks/maptalks.js#1770]
主要用于地块编辑，高德在这块的体验较好，希望能增加类似功能。
https://lbs.amap.com/demo/jsapi-v2/example/overlay-editor/polygon-editor-avoidpolygon/

**Comment by deyihu** [comment]
developing by https://github.com/maptalks/maptalks.snap

**Comment by coloz** [comment]
nice!
我正在开发一个gis编辑器，下一步改成maptalks版本
https://github.com/coloz/GisEditor

> developing by https://github.com/maptalks/maptalks.snap

**Comment by deyihu** [comment]
close by https://github.com/maptalks/maptalks.snap
