### ISSUE TITLE
定位中心点时，如何设置以像素为单位的偏移量

### ISSUE THREAD

**Issue by hotchicken1996** [maptalks/maptalks.js#1777]
目前遇到的问题：
  项目中地图右侧会有弹窗，此时定位点或面到地图中心时会被遮挡。如何在设置地图中心时（animateTo、flyTo、fitExtent等方法）设置以像素为单位的偏移量？类似leaflet的padding参数。

**Comment by fuzhenn** [comment]
目前没有这个设置，不过可以考虑添加一个

**Comment by deyihu** [comment]
@hotchicken1996  最简单的方法就是改变地图容器左边的位置，比如往左缩进一定距离
https://codepen.io/deyihu/pen/dymjovN

如果右侧的弹窗关掉了，那么就把地图容器位置改回来

**Comment by hotchicken1996** [comment]
@deyihu 很巧妙的点子，目前我的问题解决了。感谢

**Comment by hotchicken1996** [comment]
当修改地图容器位置和设置地图中心点同时进行的时候会出现问题，希望添加设置像素偏移量的方法.....((/- -)/

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/WNBWJxJ
