### ISSUE TITLE
点线重复删除添加，样式不更新

### ISSUE THREAD

**Issue by FEJackFly** [maptalks/maptalks.js#1785]
**maptalks's version and what browser you use?**
----

**Issue description**
----
点线重复删除添加，样式不更新，最后一帧显示。希望添加一个实时更新的选项

**Please provide a reproduction URL (on any jsfiddle like site)**
----
`{
                                "symbol": {
                                    "lineColor": "red",
                                    "markerFill": "red",
                                    "lineWidth": 1,
                                    "lineOpacity": 1,
                                    "markerType": "ellipse",
                                    "markerWidth": {
                                        "stops": [
                                            [0, 10],
                                            [20, 10]
                                        ]
                                    },
                                    "markerHeight": {
                                        "stops": [
                                            [0, 10],
                                            [20, 10]
                                        ]
                                    },
                                    "markerPlacement": "vertex",
                                    "markerVerticalAlignment": "middle",
                                    "markerRotationAlignment": "map",
                                    "markerPitchAlignment": "map"
                                }
                            }`

**Comment by deyihu** [comment]
设计如此，整个地图的渲染是放在动画函数里的，单位时间内你就是对样式操作一万次，也是只有最后一次生效，你应该从动画角度入手
