### ISSUE TITLE
identify在地图drag后无法拾取面图形

### ISSUE THREAD

**Issue by brucin** [MapTalks/MapTalks.js#18]
在canvas上的面图形，在地图drag后，就无法拾取了。应该是对应的_containsPoint没有计算上map的偏移。

**Comment by brucin** [comment]
polygon的我已经修复，原因的确是没有加上map.offsetPlatform()。polygon的外接矩形，以及polygon._getPrjPoints()都需要，这样地图移动以后，鼠标点击在图形上才能找到该图形。
你看看其它图形的判断是否也存在同样的问题。

**Comment by FuZhenn** [comment]
是因为用了屏幕坐标, 没有用容器坐标做判断, 所以要加上map.offsetPlatform().

 不过不用这么麻烦,直接用transformToOffset代替coordinateToScreenPoint, 直接返回的容器坐标

**Comment by wsw0108** [comment]
@FuZhenn 
map.coordinateToScreenPoint是直接调用了map._transformToOffset；
geometry.poly的_transformToOffset也是直接调用了map._transformToOffset；
