### ISSUE TITLE
载入不同投影的TileLayer很卡，且缩放地图会完全清空缓存的瓦片，一片白，体验很差

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#1802]
**maptalks's version and what browser you use?**
----

**Issue description**
----
https://maptalks.org/examples/cn/tilelayer-projection/different-projection/#tilelayer-projection_different-projection

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
https://github.com/maptalks/maptalks.js/commit/7ea656f2ff6ff76c0ea18dd69a41af6bd185cd70 解决了拖动卡顿的问题

https://github.com/maptalks/maptalks.js/commit/210f393b450dd331a693a780a017869e78a7b662 解决了在小数级别时瓦片绘制不正确的问题

**Comment by deyihu** [comment]
@fuzhenn  白屏的问题还是存在,不过可以先发个版本了
