### ISSUE TITLE
高分屏下，TileLayer的瓦片之间出现裂缝

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1812]
**maptalks's version and what browser you use?**
----
1.0.0-rc.11

**Issue description**
----
高分屏下，TileLayer的瓦片之间会出现裂缝
![image](https://user-images.githubusercontent.com/13678919/188774910-3d131691-8f95-47da-9408-ea748e56f6ef.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
```js
const layer=new maptalks.TileLayer('id',{
bufferPixel:0
});

```
