### ISSUE TITLE
maptalks中tileLayer设置独立投影问题（EPSG3857、EPSG4326）

### ISSUE THREAD

**Issue by ytblackTea** [maptalks/maptalks.js#1816]
**maptalks's version and what browser you use?**
----
chrome版本 93.0.4577.63
maptalks版本 v0.49.5

**Issue description**
----
原有底图是通过EPSG3857的方式进行贴图，现在瓦片图是通过EPSG4326的方式。为了不影响其他图层，在tileLayer里面独立设置spatialReference:{
          projection:'EPSG:4326'
        },
发现引入的底图拼接有问题，会出现断开的现象。
请问这是什么原因

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![1663640733227](https://user-images.githubusercontent.com/27613376/191153629-71b367f7-454e-44de-8345-ec15c1833ce8.jpg)

**Comment by deyihu** [comment]
@ytblackTea  请提供个可以复现这个bug的代码
ps：从你的截图中看，你这个切片是3857的，不是4326的

**Comment by ytblackTea** [comment]
> @ytblackTea 请提供个可以复现这个bug的代码 ps：从你的截图中看，你这个切片是3857的，不是4326的

嗯嗯，是的，这个是一个示例。
![image](https://user-images.githubusercontent.com/27613376/191158482-4e79ccc2-8a4b-4042-bbdd-72b77faf82da.png)
因为使用的是内网，没办法从外网链接到切片，他们那边提供的切片是4326，我使用的是3857
大体效果
![image](https://user-images.githubusercontent.com/27613376/191158658-b3afc4d9-2e94-4a17-a379-f7a9148a4650.png)
