### ISSUE TITLE
maptalks.mapboxgl示例中使用最新的maptalks版本导致 窗口缩放的时候，地图会不停的闪屏

### ISSUE THREAD

**Issue by 286208466** [maptalks/maptalks.js#1818]
直接用maptalks.mapboxgl 官方上的demo，把引入的maptalks.min.js的替换成最新版，在窗口不断缩放的时候，地图容器中的图层会不断闪烁，容易导致眼睛疲劳，在V0.49.5的版本以前不会有该问题

**Comment by deyihu** [comment]
最新版本里应该没有这个问题了，如果有问题欢迎再次打开
