### ISSUE TITLE
TypeError: Class constructor BaseObject cannot be invoked without 'new'

### ISSUE THREAD

**Issue by lzshenpan** [maptalks/maptalks.js#1831]
**maptalks's version and what browser you use?**
----v1.0.0-rc.14

**Issue description**
  14 | class Circle extends maptalks.BaseObject{
  15 | 
> 16 |     constructor(coordinate, options, material, layer) {
  17 |         super();
  18 |         options = maptalks.Util.extend({}, OPTIONS, options, { layer, coordinate });
  19 |         // super();

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@lzshenpan 

 https://github.com/maptalks/maptalks.three/issues/547
