### ISSUE TITLE
tileLayer 加入到gllayer之后 cssFilter 失效

### ISSUE THREAD

**Issue by Xyyue221** [maptalks/maptalks.js#1837]
tileLayer 加入到gllayer之后 cssFilter 失效

**Comment by deyihu** [comment]
cssFilter是个canvas效果https://github.com/maptalks/maptalks.js/blob/a16df0c347dc89d3a40487c9bf0b63792c352aa9/src/renderer/map/MapCanvasRenderer.js?_pjax=%23js-repo-pjax-container#L659

加入到gllayer了就是webgl render了（canvas filter失效），如果需要对底图的图片做自定义,可以自己对底图图片做任何图像处理

such as :https://codepen.io/deyihu/pen/poKJaXG

**Comment by Xyyue221** [comment]
> cssFilter是个canvas效果
> 
> https://github.com/maptalks/maptalks.js/blob/a16df0c347dc89d3a40487c9bf0b63792c352aa9/src/renderer/map/MapCanvasRenderer.js?_pjax=%23js-repo-pjax-container#L659
> 
> 加入到gllayer了就是webgl render了（canvas filter失效），如果需要对底图的图片做自定义,可以自己对底图图片做任何图像处理
> 
> such as :https://codepen.io/deyihu/pen/poKJaXG

感谢大佬！

**Comment by deyihu** [comment]
close by https://maptalks.org/examples/en/tilelayer-projection/tile-image-custom/#tilelayer-projection_tile-image-custom
