### ISSUE TITLE
使用报错：Error: Container is already loaded with another map instance, use map.remove() to clear it.

### ISSUE THREAD

**Issue by EKIKOUKA** [maptalks/maptalks.js#1842]
## vue3项目中引入vue2写法的maptalks地图，项目在本地预览没问题，但部署到线上后访问报错

vendor.fde442c2.js:5 Error: Container is already loaded with another map instance, use map.remove() to clear it.
    at i._initContainer (maptalks.es-bundler.9b01299e.js:75:61713)
    at new a (maptalks.es-bundler.9b01299e.js:75:47024)
    at Proxy.mapInit (map.1bb6b77e.js:1:1518)
    at Proxy.mounted (map.1bb6b77e.js:1:603)
    at callWithErrorHandling (vendor.fde442c2.js:5:789)
    at callWithAsyncErrorHandling (vendor.fde442c2.js:5:911)
    at U.__weh.U.__weh (vendor.fde442c2.js:2:44632)
    at flushPostFlushCbs (vendor.fde442c2.js:5:3487)
    at flushJobs (vendor.fde442c2.js:5:3864)
logError$1 @ vendor.fde442c2.js:5
handleError @ vendor.fde442c2.js:5
callWithErrorHandling @ vendor.fde442c2.js:5
callWithAsyncErrorHandling @ vendor.fde442c2.js:5
U.__weh.U.__weh @ vendor.fde442c2.js:2
flushPostFlushCbs @ vendor.fde442c2.js:5
flushJobs @ vendor.fde442c2.js:5
Promise.then (async)
queueFlush @ vendor.fde442c2.js:5
queueJob @ vendor.fde442c2.js:5
(anonymous) @ vendor.fde442c2.js:2
triggerEffects @ vendor.fde442c2.js:2
triggerRefValue @ vendor.fde442c2.js:2
set value @ vendor.fde442c2.js:2
(anonymous) @ index.8ccfcac8.js:1
Promise.then (async)
W @ index.8ccfcac8.js:1
callWithErrorHandling @ vendor.fde442c2.js:5
callWithAsyncErrorHandling @ vendor.fde442c2.js:5
emit$1 @ vendor.fde442c2.js:2
T @ WhInfoLeftTree.fbb6592c.js:1
se @ WhInfoLeftTree.fbb6592c.js:1
callWithErrorHandling @ vendor.fde442c2.js:5
callWithAsyncErrorHandling @ vendor.fde442c2.js:5
emit$1 @ vendor.fde442c2.js:2
handleSelect @ vendor.fde442c2.js:114
__emit @ vendor.fde442c2.js:40
onNodeSelect @ vendor.fde442c2.js:114
onSelect @ vendor.fde442c2.js:114
onSelectorClick @ vendor.fde442c2.js:114
callWithErrorHandling @ vendor.fde442c2.js:5
callWithAsyncErrorHandling @ vendor.fde442c2.js:5
H @ vendor.fde442c2.js:5

**Comment by fuzhenn** [comment]
这个是因为对同一个容器重复创建了多个地图示例，需要检查一下vue逻辑里，对map的初始化逻辑，排除掉重复创建应该就能解决了

**Comment by EKIKOUKA** [comment]
> 

我看代码好像只创建了一个实例，另一个在某个事件之后才会再创建一个实例

页面加载的时候发现地图渲染函数执行了两遍，改成只加载一遍就没问题了
