### ISSUE TITLE
编辑 Polygon时，区分一部分点不允许编辑，应该怎么写

### ISSUE THREAD

**Issue by lsguang0** [maptalks/maptalks.js#1857]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
目前不支持这个功能，这个设置不太常见而且设置起来会有点复杂。

**Comment by lsguang0** [comment]
好吧
