### ISSUE TITLE
获取baselayer后，setOptions设置cssfilter不生效

### ISSUE THREAD

**Issue by Wuli-Zhang** [maptalks/maptalks.js#1872]
**maptalks's version and what browser you use?**
----
最新版本

**Issue description**
----
以滑块设置cssfilter不生效，必须滚动一下或者放大缩小，重绘瓦片才会变化。如何重绘layer？

**Please provide a reproduction URL (on any jsfiddle like site)**
----
褐色:{{sepia}}<el-slider v-model="sepia" :min="0" :max="1" :step="0.01" @change="setCssFilterConfig"></el-slider>
透明度:{{opacity}}<el-slider v-model="opacity" :min="0" :max="1" :step="0.01" @change="setCssFilterConfig"></el-slider>

setCssFilterConfig(){
      const a = this.map.getBaseLayer()
      a.setOptions({cssFilter: `sepia(${this.sepia}) opacity(${this.opacity})`})
    }

**Comment by deyihu** [comment]
the method is config
```js
layer.config({....})

```

**Comment by Wuli-Zhang** [comment]
用`layer.config({....})`问题已解决，什么情况下用setOptions呢？
