### ISSUE TITLE
使用天地图的最佳实践？

### ISSUE THREAD

**Issue by kokonatsuli** [maptalks/maptalks.js#1895]
天地图的底图和注记是分开的，当使用天地图时需要在底图图层之上叠加注记的图层（参考了官网的demo，创建两个TileLayer）。
但当放大地图的时候，下一层级的注记图片还未加载完全，此时上一层级的注记则被放大得很夸张，如下图所示。
请问有没有更好的做法呢？
![image](https://user-images.githubusercontent.com/40257376/220582661-6f21a61b-cf29-44a7-9c87-294df7ca947e.png)

**Comment by deyihu** [comment]
@kokonatsuli  确实存在这个问题，但是我也没有是么好的方式来解决这个问题

实现逻辑

- 当用户缩放地图时，会用缓存的低级别的瓦片来填充高级别的
- 如果不这么做，那么用户放大是就是一片白了，这样也是不行的

原因：

- 因为天地图的服务很慢，所以这个现象将特别明显
- 意思就是如果服务特别快，这个现象将好很多

解决方式
-  更换服务快的地图服务
- 可以自己搭建个代理缓存中间层，前端直接请求自己的这个中间层，在自己的中间层进行缓存等来加快出图速度
- 用矢量切片来解决这个（道路和各种标注做成一个矢量切片）

**Comment by kokonatsuli** [comment]
@deyihu 是的……天地图服务较慢，而且注记图片都是透明的，所以低级别的瓦片会看得到。而天地图的标注矢量数据好像并不对外开放（https://map.tianditu.gov.cn/ 他自己的官网明明是有的），但尝试请求会报错。
而解决方法如果只能自己缓存天地图的数据，对我们而言又不那么有可行性了🤣

**Comment by ryry886** [comment]
不明白，为什么直接请求天地图服务，浏览器不缓存瓦片，每次请求都是重新请求瓦片？是不是天地图服务端有限制？
