### ISSUE TITLE
how to calculate the length of lineString？(ps: the result is in meters or kilometers)

### ISSUE THREAD

**Issue by Jackyclearliu** [maptalks/maptalks.js#1899]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@Jackyclearliu 
You can use some third-party libraries to solve your needs 

such as [turfjs](https://github.com/Turfjs/turf),[jsts](https://github.com/bjornharrtell/jsts) etc

```js
const geojson=line.toGeoJSON();

const distance=turf.length(turf.linestring(geojson))
```
