### ISSUE TITLE
Material Design Icons as Marker

### ISSUE THREAD

**Issue by eviltik** [maptalks/maptalks.js#1901]
Hi,

Is it possible to use Material Design icons as marker ?

i didn't found in the doc. textContent is text, not html.

Thanks

**Comment by deyihu** [comment]
- you can use UIMarker for display html content  https://maptalks.org/examples/en/style/html-marker/#style_html-marker
- or you can use custom textName font https://codepen.io/deyihu/pen/XWXWjBL
