### ISSUE TITLE
ArcConnecctionLine不能定义事件，mouseover mouseout不管用

### ISSUE THREAD

**Issue by hyoracle** [maptalks/maptalks.js#1913]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by hyoracle** [comment]
ArcConnecctionLine.on('mouseover',(e)=>{
console.log(e)
})

ArcConnecctionLine.on('mouseout',(e)=>{
})

**Comment by hyoracle** [comment]
maptalks version is 1.0.0-rc.4
var src = maptalks.Marker(...)
var dst = maptalks.Marker(...)
var line = maptalks.ArcConnectionLine（src, dst, ...）
line.on('mouseover',(e)=>{
console.log(e)
})

line.on('mouseout',(e)=>{
})

**Comment by deyihu** [comment]
No issues found in the current version

https://codepen.io/deyihu/pen/jOogKGe
