### ISSUE TITLE
本地瓦片刷新

### ISSUE THREAD

**Issue by 1051099961** [maptalks/maptalks.js#1924]
我想频繁的刷新某一张或某几张瓦片，用本地的png瓦片进行替换更新，请问有demo吗？

**Comment by fuzhenn** [comment]
https://maptalks.org/examples/cn/tilelayer-projection/wms-reload/#tilelayer-projection_wms-reload

**Comment by 1051099961** [comment]
用forcereload会造成闪烁情况，有没有方法不闪烁或者指定行列号层级这种形式去刷新?
