### ISSUE TITLE
multiLineString在v1.0.0-rc.18里是否设置不了高度？

### ISSUE THREAD

**Issue by mashubin** [maptalks/maptalks.js#1925]
**maptalks's version and what browser you use?**
----
v1.0.0-rc.18

**Issue description**
----
因为为了引入3d倾斜摄影，从v0.49.5s升级到v1.0.0-rc.18，以前的multiLineString是可以设置高度形成阴影。更新后不能
新版的线高度是使用那个？除了LineString，我这使用LineString，很多报错

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![image](https://user-images.githubusercontent.com/32285084/229470520-b3d04765-80dc-4081-b504-412c91b19526.png)
![image](https://user-images.githubusercontent.com/32285084/229470667-daafa6f3-b46a-4243-a2be-b72b24480813.png)

有点急，需要帮忙下

**Comment by deyihu** [comment]
麻烦提供下复现代码

**Comment by mashubin** [comment]
[EZUIKit_js_v6.5_build20221102.zip](https://github.com/maptalks/maptalks.js/files/11137558/EZUIKit_js_v6.5_build20221102.zip)
这是我本地代码，有个地区点的数据。下载下来可以查看。~~

**Comment by mashubin** [comment]
![image](https://user-images.githubusercontent.com/32285084/229491144-cf23e600-a7fe-4fbe-8aed-fcff14b76048.png)
![image](https://user-images.githubusercontent.com/32285084/229491268-4d3a890f-b4ca-48b4-ac80-c7e8997c5577.png)

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/rNgKJQW?editors=1010

当前版本没有发现问题
