### ISSUE TITLE
Can I watch the layer visibility change 

### ISSUE THREAD

**Issue by Wincy94** [maptalks/maptalks.js#1928]
**maptalks's version and what browser you use?**
----
maptalks's version: ^1.0.0-rc.6
browser: chrome 

**Issue description**
----
Can I watch the layer visibility change ? I notice the layer has the show or hide event. But It doesn't emit when zoomChange or opacity change. 

**Please provide a reproduction URL (on any jsfiddle like site)**
----
none

**Comment by fuzhenn** [comment]
you can try layerload event if it meets your needs

**Comment by deyihu** [comment]
@Wincy94  you can 

```js

const layer=.....;
// map render end event
map.on('frameend',()=>{
  const visible=layer.isVisible();
});

```
