### ISSUE TITLE
集成mapbox gl后，无法使用ToDataUrl 导出图片

### ISSUE THREAD

**Issue by sqzxy** [maptalks/maptalks.js#1932]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by sqzxy** [comment]
mapbox 加载的矢量pbf瓦片，单独用box的可以导出，用talks自己的ToDataUrl导出是空白的，这个有什么办法吗？

**Comment by deyihu** [comment]
maptalks是以dom等方式将mapbox插入到maptalks的容器的，需要你自己合并mapbox的canvas和maptalks的canvas
