### ISSUE TITLE
希望显示了InfoWindow的marker在碰撞检测中避免被隐藏

### ISSUE THREAD

**Issue by zhouzhili** [maptalks/maptalks.js#1934]
**maptalks's version and what browser you use?**
----
maptalks v1.0.0-rc.18
@maptalks/gl v0.81.3

**Issue description**
----
使用了pointLayer的碰撞检测功能，当marker显示了infowindow，平移的时候marker被隐藏了，是否有地方能设置显示了infowindow的marker在碰撞检测的时候不被隐藏，或者能在碰撞检测的时候配置某个marker的权重，
如下图，黄色圈处的marker被隐藏了
![image](https://user-images.githubusercontent.com/14259932/231971695-f149662c-2e2e-4cc7-8926-4e0769574507.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/zhili124/pen/KKGVpOr

**Comment by deyihu** [comment]
1.Marker添加 collision 配置选项
2.核心库已经实现该功能
3.PointLayer也需要实现该配置选项

**Comment by fuzhenn** [comment]
symbol里定义 markerAllowOverlap: true 就行
