### ISSUE TITLE
WebGL context lost when updating ImageLayer frequently

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#1955]
**maptalks's version and what browser you use?**
----
v1.0.0-rc.20

**Issue description**
----
WebGL context lost when updating ImageLayer frequently, need to check memory management of ImageLayer.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
imagebitmap close not dipose imagebitmap object when in chrominum

**Comment by deyihu** [comment]
最后定位到是因为 fetch blob导致的，需要fetch arraybuffer，然后手动new Blob([arraybuffer]),来绕过chrome浏览器的内存暴涨的问题
