### ISSUE TITLE
1.0版本，鼠标滚到废了，地图才从全国缩放到街道，有点废手呀

### ISSUE THREAD

**Issue by 156370005** [maptalks/maptalks.js#1969]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by Beats0** [comment]
我是改的 seamlessZoom: false, 每次缩放级别为1, 缩放可以快一点

**Comment by deyihu** [comment]
暂时没有其他同学报告这个问题，可能鼠标速度有关，或者可能特殊环境导致的，我这边也没法子复现这个问题，如果有问题的话欢迎再次打开这个主题
