### ISSUE TITLE
当Map对象为Vue3 的ref包裹时，DrawTool的disable方法不生效

### ISSUE THREAD

**Issue by zhouzhili** [maptalks/maptalks.js#1971]
**maptalks's version and what browser you use?**
----
maptalks v1.0.0-rc.20

**Issue description**
----
drawTool初始化时设置为
```js
var refMap = Vue.ref(map)
var drawTool = new maptalks.DrawTool({
  mode: 'Point'
}).addTo(refMap.value).disable();
```
disable方法没生效，依然可以画点

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/zhili124/pen/ZEqPQaP

**Comment by deyihu** [comment]
因为ref本质是Proxy，地图被代理后地图上挂载的变量就不是原来的值了

前置知识：

1.地图是个非常复杂的对象，对象嵌套对象
2.ref会递归遍历map对象，把map对象上的属性构造成新的proxy

问题原因：
1.地图上的挂载的事件缓存方式：
```js
 click:{hanlder:function ,context:drawtool}
```
2.地图ref后，事件里的context会变成 proxy,注意其本来的值为 drawtool，导致地图内部处理事件时 context不相等
3.证明方法：
```js
drawTool === Vue.ref(drawTool).value
```
看看这个结果就知道了

总结：
1.ref会递归遍历，对象上的对象属性构造成proxy，导致和原来的值不等
2.这个问题我们修复不了
3.不要这么使用地图，性能差不说，会发生一些乱七八糟的问题

**Comment by zhouzhili** [comment]
已解决，改为shallowRef就可以了
```js
var refMap = Vue.shallowRef(map)
```
