### ISSUE TITLE
可以在三维模型中实现定位以及绘制轨迹吗？

### ISSUE THREAD

**Issue by Raina-mtn** [maptalks/maptalks.js#1979]
例如这样
![image](https://github.com/maptalks/maptalks.js/assets/100856995/3093eb69-f939-4a39-8816-6b4fe0c1198e)
![image](https://github.com/maptalks/maptalks.js/assets/100856995/18a81af2-685a-4fd1-a911-d8423812016a)

**Comment by deyihu** [comment]
https://maptalks.org/maptalks.routeplayer/demo/map-animation.html  可以的

1.定位取决于你的设备了，目前mtk只能在浏览器里跑，浏览器里定位停难得，怎么做需要你研究
2.mtk支撑加载模型
3.mtk支撑加载3d的线条
4.mtk也支持轨迹的数据的播放等
