### ISSUE TITLE
coordinatesToContainerPoints函数计算固定层级下的像素距离得到的结果不正确

### ISSUE THREAD

**Issue by Janexr** [maptalks/maptalks.js#1983]
**maptalks's version and what browser you use?**
----
1.0.0-rc.20

**Issue description**
----
无论地图当前是多少层级，想要计算两个坐标点在18级的像素距离。使用了coordinatesToContainerPoints函数，但是得到的结果还是当前层级下的像素距离

**Please provide a reproduction URL (on any jsfiddle like site)**
----
function getPixelDisBetweenCoordinates(mapIns, source, target, zoom) {
    if(Array.isArray(source)) source = new maptalks.Coordinate(source);
    if(Array.isArray(target)) target = new maptalks.Coordinate(target);
    const pixelList = mapIns.coordinatesToContainerPoints([source, target], zoom);
    return [pixelList[1].x-pixelList[0].x, pixelList[1].y-pixelList[0].y];
}

**Comment by fuzhenn** [comment]
改用 `coordToPointAtRes` 方法
```js
const res = map.getResolution(zoom);
map.coordToPointAtRes(coord, res);
```
