### ISSUE TITLE
当版本在rc21时，tilelayer首次加载会拉伸的非常夸张，版本倒退到rc18，则没有该问题

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/maptalks.js#1984]
**maptalks's version and what browser you use?**
----
rc21

**Issue description**
----
当版本在rc21时，tilelayer首次加载会拉伸的非常夸张，版本倒退到rc18，则没有该问题

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
设计如此，是提前加载了父级瓦片导致的现象，主要是为了地形服务，如果不需要这个特性，可以在图层options里把 tileStackDepth设成0即可
