### ISSUE TITLE
请问支持terriain服务加载吗？

### ISSUE THREAD

**Issue by giswrok** [maptalks/maptalks.js#1996]
**maptalks's version and what browser you use?**
----

1.0-rc.22
**Issue description**
----
请问这个版本支持加载地形服务吗？接入maobox的地形服务或者是cesium的地形服务

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@giswrok  http://examples.maptalks.com/examples/cn/3d/terrain/load

**Comment by mahalo777** [comment]
@deyihu  http://examples.maptalks.com/examples/cn/3d/terrain/load

你好， 请问最新版本都支持哪些地形呢？ 示例只能看见Mapbox的地形
