### ISSUE TITLE
希望支持pbf字体库

### ISSUE THREAD

**Issue by luothink** [maptalks/maptalks.js#2001]
希望在mtk的矢量切片样式中，可以支持读取类似于mapbox中的  "glyphs": "http://....../{fontstack}/{range}.pbf"，pbf字体资源，用于点类型图标样式的展示

**Comment by deyihu** [comment]
进一步的了解用户的需求后发现：用户是把图标等做进pbf的，这个不是个好的方法：

- 每次更新数据都要重制pbf
- 不支持彩色图标
- 后续我会添加sprite等支持，svg集合支持的来解决图标集合的问题
