### ISSUE TITLE
请教一下制作内部地图的方案

### ISSUE THREAD

**Issue by zhongbiran** [maptalks/maptalks.js#2005]
1. 我是个GIS的新手，我要做的地图源于CAD或者PNG，为了方便管理我统一转换成SVG格式。
2. 如何在 new maptalks.TileLayer加载svg图片作为底图呢？我看下文档和案例实在没搞懂，请求帮助。
3. 我还有在地图上添加自定义图标、自定义轨迹播放的需求，请问该参考那些文档呢？

**Comment by deyihu** [comment]
2. 可以使用ImageLayer
3. 具体参考示例和文档
4. 轨迹播放参考 https://[github.com/maptalks/maptalks.routeplayer](https://github.com/maptalks/maptalks.routeplayer)
