### ISSUE TITLE
invalid symbol for geometry(Point) to draw

### ISSUE THREAD

**Issue by gezonthenet** [maptalks/maptalks.js#2013]
**maptalks's version and what browser you use?**
----
[v1.0.0-rc.23](https://github.com/maptalks/maptalks.js/tree/v1.0.0-rc.23)
Chrome: Version 114.0.5735.199 (Official Build) (64-bit)

**Issue description**
----
(maptalks.es-bundler.js:8076 invalid symbol for geometry(Point) to draw :){"textFaceName":"monospace","textSize":12,"textLineSpacing":8,"textWrapCharacter":"\n","textHorizontalAlignment":"middle","textVerticalAlignment":"middle"}

This default symbol code seems to becoming directly from maptalks defaults.
https://github.com/maptalks/maptalks.js/blob/b42a3c0fff9bf6eba7e93e72a3c525b2e398f29b/src/geometry/TextMarker.js#L6

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
looks like you missed symbol.textName property, set a textName will fix this.

**Comment by gezonthenet** [comment]
Correct. My symbol.textName was in some cases "undefined". Fixing this removed the errors.
