### ISSUE TITLE
地图快速缩放时  元素模糊

### ISSUE THREAD

**Issue by luosijie** [maptalks/maptalks.js#2018]
如图所示
当用【animateTo】和【快速缩放】时
地图元素会模糊
缩放停止后才恢复正常

请问有办法改善吗

![image](https://github.com/maptalks/maptalks.js/assets/16912206/b38ddcc9-97ea-47b5-97f7-88da29cd65ea)

**Comment by fuzhenn** [comment]
试试创建图层的时候在options里把 forceRenderOnZooming 设成true
