### ISSUE TITLE
如何将倾斜旋转操作改为鼠标左键

### ISSUE THREAD

**Issue by hotchicken1996** [maptalks/maptalks.js#2022]
因为项目需求只查看固定位置，所以我禁用了地图拖动，有什么办法能把倾斜与旋转（原鼠标右键）操作转为左键，因为移动端右键事件需要双指操作，比较麻烦

**Comment by deyihu** [comment]
@hotchicken1996  https://maptalks.org/examples/en/map/drag-pitch-rotate/#map_drag-pitch-rotate

可以看看这个例子，Ctrl+鼠标左键也是可以的

**Comment by fuzhenn** [comment]
移动端上目前暂时无法实现这个需求，需要增加配置，例如在map的options里增加一个 swithDragButton 配置项，然后在Map.Drag.js的_onMouseDown方法里，切换一下鼠标按键的判断就行了

**Comment by fuzhenn** [comment]
创建map时，可以通过把 options.swithDragButton 设成 true 来实现这个功能了。
