### ISSUE TITLE
geometry_linestring onclick事件无法触发

### ISSUE THREAD

**Issue by shaokeke** [maptalks/maptalks.js#2027]
**maptalks's version and what browser you use?**
----
最新版本，EDGE 谷歌浏览器

**Issue description**
----
https://maptalks.org/examples/cn/geometry/linestring/#geometry_linestring
加上
line.on('click', e => {
  console.log("e",e)
})
80%概率无法触发click,
只有ctrl+左键调整下视角才可以100%触发

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://maptalks.org/examples/cn/geometry/linestring/#geometry_linestring
![image](https://github.com/maptalks/maptalks.js/assets/37448773/968ae403-7c81-4e77-b4f9-7b20163399c0)

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.js/commit/ce989771feeb20c56b6732c05e0d140ee605402d
