### ISSUE TITLE
1.0.0-rc18版本开始，Imagelayer 出现上层image的alpha图层会把下面的image也透明掉

### ISSUE THREAD

**Issue by wangshen5962** [maptalks/maptalks.js#2029]
**maptalks's version and what browser you use?**
---- >=1.0.0-rc18

**Issue description**
----从1.0.0-rc18版本开始，当ImageLayer对象中加载多个png图片，且其中的图片有alpha部分，会将它下面的图片一起变透明

**Please provide a reproduction URL (on any jsfiddle like site)**
---- 下面是测试链接
 https://codepen.io/jondeifn-the-bold/pen/XWyYOBg

![Snipaste_2023-06-26_08-50-26](https://github.com/maptalks/maptalks.js/assets/6285062/576a8dca-7a81-4397-be2e-d81aa7c1a853)

**Comment by fuzhenn** [comment]
收到
