### ISSUE TITLE
Custom image for markerFile - Dont understand how it works

### ISSUE THREAD

**Issue by Sunny-Sol** [maptalks/maptalks.js#2035]
**maptalks's version and what browser you use?**
----
chrome

**Issue description**
----
im trying to use a custom image for the markerFile, i have tried both local path and http path
It doesnt show up

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://masterarms.tech/liberation/

**Comment by fuzhenn** [comment]
Confirmed it's a bug which is caused by orders of resources loading.

If you need a quick fix, you can have a try:
* move the outlined Marker and Circle into the VectorLayer's geometries array (after THEATRE), as the images shown below:

![image](https://github.com/maptalks/maptalks.js/assets/13678919/8e91684c-4480-4368-9bd7-bd86fdff229b)

**Comment by Sunny-Sol** [comment]
Hi, i tried and still cant make sense of it...
Please see these two examples, one with an image file linked from maptalks and one from my own web-adress

Image Not working
```
var arcUrl = 'https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer';
      maptalks.SpatialReference.loadArcgis(arcUrl + '?f=pjson', function (err, conf) {
        if (err) {
          throw new Error(err);
        }
        var ref = conf.spatialReference;
        ref.projection = 'EPSG:3857';
        ref.fullExtent = null;
        var map = new maptalks.Map('map', {
          center: [33.510414,34.278336],
          zoom: 6.5,
          pitch : 11,
          rotate: -5,
          minZoom: 1,
          maxZoom : 16,
          spatialReference : ref,
          baseLayer: new maptalks.TileLayer('base', {
            'tileSystem' : conf.tileSystem,
            'tileSize' : conf.tileSize,
            'urlTemplate' : arcUrl + '/tile/{z}/{y}/{x}',
            'attribution' : '&copy; <a target="_blank" href="' + arcUrl + '"">ArcGIS</a>',
            cssFilter : 'sepia(15%) invert(5%)',
            
            
          }),
          
        });
        
      var center = map.getCenter();

      var layer = new maptalks.VectorLayer('vector').addTo(map);

      var marker1 = new maptalks.Marker(
        center.sub(0.009, 0),
        {
          'symbol' : {
            'markerFile'   : 'https://masterarms.tech/liberation/IMAGES/MARKERS/image026.png',
            'markerWidth'  : 28,
            'markerHeight' : 40,
            'markerDx'     : 0,
            'markerDy'     : 0,
            'markerOpacity': 1
          }
        }
      ).addTo(layer);})

```
--------------------------------------

Image Is working
```
var arcUrl = 'https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer';
      maptalks.SpatialReference.loadArcgis(arcUrl + '?f=pjson', function (err, conf) {
        if (err) {
          throw new Error(err);
        }
        var ref = conf.spatialReference;
        ref.projection = 'EPSG:3857';
        ref.fullExtent = null;
        var map = new maptalks.Map('map', {
          center: [33.510414,34.278336],
          zoom: 6.5,
          pitch : 11,
          rotate: -5,
          minZoom: 1,
          maxZoom : 16,
          spatialReference : ref,
          baseLayer: new maptalks.TileLayer('base', {
            'tileSystem' : conf.tileSystem,
            'tileSize' : conf.tileSize,
            'urlTemplate' : arcUrl + '/tile/{z}/{y}/{x}',
            'attribution' : '&copy; <a target="_blank" href="' + arcUrl + '"">ArcGIS</a>',
            cssFilter : 'sepia(15%) invert(5%)',
            
            
          }),
          
        });
        
      var center = map.getCenter();

      var layer = new maptalks.VectorLayer('vector').addTo(map);

      var marker1 = new maptalks.Marker(
        center.sub(0.009, 0),
        {
          'symbol' : {
            'markerFile'   : 'https://raw.githubusercontent.com/maptalks/examples/master/src/style/line-marker/plane.png',
            'markerWidth'  : 28,
            'markerHeight' : 40,
            'markerDx'     : 0,
            'markerDy'     : 0,
            'markerOpacity': 1
          }
        }
      ).addTo(layer);})

```

**Comment by Sunny-Sol** [comment]
![Skärmbild 2023-08-02 085852](https://github.com/maptalks/maptalks.js/assets/45478387/8387cb10-851b-4c0a-9cbc-35371215fba7)
![Skärmbild 2023-08-02 085901](https://github.com/maptalks/maptalks.js/assets/45478387/a26e9192-5e26-41b9-bb6a-2efcd7be1735)

**Comment by fuzhenn** [comment]
Thanks for reporting.

This is caused by 2 reasons:
*  `image026.png` is blocked by [server's CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), but `plane.png` is not.
* we changed to fetch image in worker in previous version for performance but it strictly requires CORS permits.

We are changing back to load image by Image object, and it should resolve this bug.

**Comment by Sunny-Sol** [comment]
Thanks alot for your quick replies! 
So if i understand you correctly, there is a new build somewhere where the CORS issue does not affect your local images?
If so, can you please link it? Or instruct where in the code i can change it?

*edit*
Got it to work with the plugin "Live Server" for VB code and your latest code for maptalks
Have not tested it online yet
