### ISSUE TITLE
图片mark标记添加旋转角度，点击事件无法触发

### ISSUE THREAD

**Issue by JGS12** [maptalks/maptalks.js#2047]
**maptalks's version and what browser you use?**
----

**Issue description**
----
图片mark标记添加旋转角度，点击事件无法触发

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
- renderbbox 没有考虑canvas translate的情况
- 原来的markerRotation后其 FixedExtent计算不正确
- 需要重新设计 markerRotation的FixedExtent计算逻辑

**Comment by JGS12** [comment]
那这种怎么处理呢，我不太懂，有没有啥解决方案呀，谢谢啦



---原始邮件---
发件人: "hu de ***@***.***&gt;
发送时间: 2023年8月13日(周日) 上午10:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [maptalks/maptalks.js] 图片mark标记添加旋转角度，点击事件无法触发 (Issue #2047)




  
renderbbox 没有考虑canvas translate的情况
 
原来的markerRotation后其 FixedExtent计算不正确
 
需要重新设计 markerRotation的FixedExtent计算逻辑

**Comment by deyihu** [comment]
@JGS12  我们会拉解决这个问题的，代码已经好了，还需要写一些测试用例

**Comment by JGS12** [comment]
好滴，辛苦啦，解决啦，麻烦可以告知一下吗，谢谢啦！



---原始邮件---
发件人: "hu de ***@***.***&gt;
发送时间: 2023年8月13日(周日) 上午10:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [maptalks/maptalks.js] 图片mark标记添加旋转角度，点击事件无法触发 (Issue #2047)




 
@JGS12  我们会拉解决这个问题的，代码已经好了，还需要写一些测试用例

**Comment by JGS12** [comment]
这是修复好了嘛，可以直接用了吗





---原始邮件---
发件人: "Fu ***@***.***&gt;
发送时间: 2023年8月13日(周日) 中午11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [maptalks/maptalks.js] 图片mark标记添加旋转角度，点击事件无法触发 (Issue #2047)




 
Closed #2047 as completed via #2050.

**Comment by JGS12** [comment]
现在修复过后我怎么用啊，怎么更新啊

**Comment by JGS12** [comment]
我看现在都修复了，我这边怎么更新啊



---原始邮件---
发件人: "hu de ***@***.***&gt;
发送时间: 2023年8月13日(周日) 上午10:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [maptalks/maptalks.js] 图片mark标记添加旋转角度，点击事件无法触发 (Issue #2047)




 
@JGS12  我们会拉解决这个问题的，代码已经好了，还需要写一些测试用例

**Comment by JGS12** [comment]
npm包也更新了吗



---原始邮件---
发件人: "hu de ***@***.***&gt;
发送时间: 2023年8月13日(周日) 上午10:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [maptalks/maptalks.js] 图片mark标记添加旋转角度，点击事件无法触发 (Issue #2047)




 
@JGS12  我们会拉解决这个问题的，代码已经好了，还需要写一些测试用例

**Comment by deyihu** [comment]
@JGS12 

release rc.25
