### ISSUE TITLE
marker加上气泡框后，infoWindow的autoPan开启时会发生偏移错误

### ISSUE THREAD

**Issue by OnePunchManGhy** [maptalks/maptalks.js#2056]
版本rc24，edge浏览器，如下图：
![20230817193845_rec_](https://github.com/maptalks/maptalks.js/assets/52189562/caa7a1de-15b4-41b6-a518-b563dfb2f415)

**Comment by OnePunchManGhy** [comment]
换了好多版本都有这个问题，系统里的都不对了。之前用的rc4版本是好的。一点气泡框就会偏移错误，不该偏移的瞎偏，该偏移的不偏。估计是autoPan的逻辑问题，计算的位置不对，为false时正常。

**Comment by OnePunchManGhy** [comment]
![20230817200423_rec_](https://github.com/maptalks/maptalks.js/assets/52189562/dc8c3f12-aa9a-4565-a80e-28d0c16d3749)
直接用官网的例子放到系统里也是不正常

**Comment by fuzhenn** [comment]
收到，这个功能的测试用例确实还不够完善，我们刚好趁这个机会完善一下相关测试

**Comment by OnePunchManGhy** [comment]
好的，谢谢大佬，麻烦尽快解决一下这个问题

**Comment by deyihu** [comment]
@OnePunchManGhy  https://maptalks.org/examples/en/ui-control/ui-geo-infownd/#ui-control_ui-geo-infownd 这个例子我们这边复现不出来，麻烦给个复现代码出来

**Comment by deyihu** [comment]
通过和作者确认，是因为作者修改了样式导致的，但是用户没有给出其代码，故暂时无法确实是否有bug

**Comment by z-xiangqi** [comment]
遇到过同样问题，使用在地图没有占满整个屏幕时会出现，首页地图占满整个屏幕，infowindow点击正常，在需要显示小地图或者半屏显示时，点击infowindow会向左偏移，当我换成uiMarker后就不偏移了

**Comment by deyihu** [comment]
maybe fixed by https://github.com/maptalks/maptalks.js/commit/360adfae060a7f3c5935d8ca7ee00c7eb1bb6d68

**Comment by z-xiangqi** [comment]
牛，大佬，升级到最新版本确实修复了
