### ISSUE TITLE
瓦片边缘1px重叠

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/maptalks.js#2066]
**maptalks's version and what browser you use?**
----
1.0.0-rc.25

**Issue description**
----
当瓦片是半透明时，边缘1px会有重叠

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![image](https://github.com/maptalks/maptalks.js/assets/19590233/0b0bb051-28c2-43aa-9d1c-48c028189b47)

**Comment by QQ853695231** [comment]
我也遇到这个问题了，每次缩放地图级别的时候，屏幕上都是这种小方框，不知道怎么解决

**Comment by deyihu** [comment]
这个是因为瓦片自动buffer了0.5像素导致的

- 两个相邻的瓦片叠盖了，因为是透明的导致透明度叠加了从而导致边界处颜色加深了
- 之所以当时这么做是因为有的高分屏上瓦片之间会出现缝隙，所以当时自动buffer了0.5像素
- 新的版本将解决这个问题,将瓦片的buffer像素大小完全交给用户自己设置（bufferPixel），默认值还是0.5,如果出现这个情况把其值设置为0即可

```js
   var map = new maptalks.Map('map', {
            center: [121.53480274771175, 31.24033597897349],
            zoom: 9,
            pitch: 0,
            baseLayer: new maptalks.TileLayer('base', {
                bufferPixel: 0,
                repeatWorld: false,
                urlTemplate: 'xxxxxxxxxxxxxxxxxx’,
                subdomains: ["a", "b", "c", "d"],
                attribution: '© <a href="http://osm.org">OpenStreetMap</a>  contributors, © <a href="https://carto.com/">CARTO</a> '
            })
        });



```

@fuzhenn
