### ISSUE TITLE
请问开启天空盒后可以显示瓦片图层吗

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#2071]
打开天空盒后地图瓦片图层被遮挡了，请问有办法可以实现同时存在吗？

**Comment by wordgold** [comment]
搞定了，把 TileLayer 放到 GroupGLLayer 里，设置下 zIndex 就可以了

**Comment by deyihu** [comment]
@wordgold  https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/DETU/changjianwenti.html
