### ISSUE TITLE
请问高德图层瓦片纠偏有可能实现吗？

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#2076]
现在我们使用的坐标全都是 wgs84，使用高德的图层的话，坐标和地图位置对不上，看 [链接](https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/KAISHI/introduce.html) 介绍有瓦片纠偏，但是搜了好多也没有查到相关资料，只有把坐标 wgs84 转 火星的
请问有把瓦片 火星 转 wgs84 的介绍吗？
使用的瓦片图层是
`        new maptalks.TileLayer('gaode', {`
`          urlTemplate: 'http://webrd{s}.is.autonavi.com/appmaptile?lang=zh_cn&style=8&x={x}&y={y}&z={z}',`
`          subdomains: ['01', '02', '03', '04']`
`        })`

**Comment by deyihu** [comment]
@wordgold 

https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUCENG/tilelayer.html#%E6%80%8E%E6%A0%B7%E7%93%A6%E7%89%87%E7%BA%A0%E5%81%8F

**Comment by wordgold** [comment]
@deyihu 谢谢指导，其实我尝试了 ctrl + k 在这个网站上搜索没找到。。。
