### ISSUE TITLE
crossorigin error on map.toDataURL

### ISSUE THREAD

**Issue by abolfazl-esmaeeli** [maptalks/maptalks.js#2077]
I loaded the Google tiles on the map. With the following code, everything works very well
map.toDataURL({
           'mimeType' : 'image/jpeg', // or 'image/png'
           'save' : true, // to pop a save dialog
           'fileName' : 'map' // file name
         });
But when I use the function, there is an error
crossorigin
Gives

**Comment by deyihu** [comment]
Your image resources need to allow cross domain, including icons, base images, etc
