### ISSUE TITLE
使用发布的arcgis地图服务(投影是4326）加载的地图，坐标偏移明显，不是map的center的位置

### ISSUE THREAD

**Issue by Zhpfffff** [maptalks/maptalks.js#2084]
**maptalks's version and what browser you use?**
----

**Issue description**
----您好，在使用使用发布的arcgis地图服务(投影是4326）加载的地图，坐标偏移明显，不是map的center的位置，不清楚是啥原因，因为服务地址需要内网访问，图片为arcgis地图服务的具体信息和写的代码。

**Please provide a reproduction URL (on any jsfiddle like site)**
----<img width="483" alt="iShot_2023-09-14_11 11 56" src="https://github.com/maptalks/maptalks.js/assets/57903742/1a9738ea-dc05-4190-9e0f-7f2c09f1b9e8">
<img width="587" alt="iShot_2023-09-14_11 14 38" src="https://github.com/maptalks/maptalks.js/assets/57903742/9fbd3498-4302-4ca6-aae2-fef6df274b31">
<img width="515" alt="iShot_2023-09-14_11 14 51" src="https://github.com/maptalks/maptalks.js/assets/57903742/fe3eb611-50f4-4dad-a431-8b47a445fec1">

**Comment by Zhpfffff** [comment]
地图可以加载出来，就是和我想要的中心点的位置相差很大

**Comment by deyihu** [comment]
你这个瓦片服务不是全球标准的切图，标准的切图分辨率是这样的：
```json
[1.40625,0.703125,0.3515625,0.17578125,0.087890625,0.0439453125,0.02197265625,0.010986328125,0.0054931640625,0.00274658203125,0.001373291015625,0.0006866455078125,0.00034332275390625,0.000171661376953125,0.0000858306884765625,0.00004291534423828125,0.000021457672119140625,0.000010728836059570312,0.000005364418029785156,0.000002682209014892578,0.000001341104507446289,6.705522537231445e-7,3.3527612686157227e-7]

```

**注意第一个切图参数和你的服务明显有误差的**

- 怎样查看标准的4326切图参数
  打开这个例子（天地图）https://maptalks.org/examples/en/tilelayer-projection/epsg4326/raw/index.html ,调试窗口执行
```js
JSON.stringify(map.getSpatialReference()._resolutions)
```
你会发现切图的第一个参数和你的明显不一样

- 你的服务加载需要自定义切图参数 `resolutions`,具体的参考 https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUCENG/tilelayer.html#%E6%80%8E%E6%A0%B7%E5%8A%A0%E8%BD%BD%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%87%E5%9B%BE%E5%8F%82%E6%95%B0%E7%9A%84%E7%93%A6%E7%89%87

**Comment by Zhpfffff** [comment]
@deyihu 非常感谢您的答复，谢谢！

**Comment by Zhpfffff** [comment]
@deyihu 您好，采用了您的方法，只自定义的切图的resolutions参数，地图现在只能出现部分展示，加载Arcgis地图服务是不是地图的spatialReference也要设置？期待得到您的回复。代码更改如下图<img width="1004" alt="image" src="https://github.com/maptalks/maptalks.js/assets/57903742/2723f69c-1f0c-4172-b04c-8e03bee216b8">

**Comment by deyihu** [comment]
@Zhpfffff QQ:971657972

**Comment by Zhpfffff** [comment]
@deyihu 已解决，原因是地图分辨率与切图分辨率不一致导致，非常感谢您的解答！
