### ISSUE TITLE
UIMarker's mouse event always propogated to map

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#2091]
**maptalks's version and what browser you use?**
----
v1.0.0-rc.26

**Issue description**
----
Even `return false` in event callback, UIMarker's mouse event still propogated to map.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
设计如此 https://github.com/maptalks/maptalks.js/issues/619
