### ISSUE TITLE
百度底图 往左或右滑动一段距离后 底图加载不出来

### ISSUE THREAD

**Issue by 410739452** [maptalks/maptalks.js#2107]
![1](https://github.com/maptalks/maptalks.js/assets/8285719/c924a085-89a7-4cae-b6c6-93b7f93ecf2f)

![2](https://github.com/maptalks/maptalks.js/assets/8285719/9b7099e5-948e-4d26-9f41-76b61c917a9b)

**Comment by deyihu** [comment]
这是由百度地图的特性决定
另外：
![AX(ENBMNVGO_C2MFZU {OS6](https://github.com/maptalks/maptalks.js/assets/25998927/b32dea7b-110c-417c-9256-42dc02a4a492)
