### ISSUE TITLE
Newbie Question: Maptalks vs Mapbox-gl-js

### ISSUE THREAD

**Issue by iamjagan** [maptalks/maptalks.js#2109]
**maptalks's version and what browser you use?**
----
Latest Version, Chrome

**Issue description**
----
What does Maptalks offer over and above Mapbox-gl-js. I am trying to build a map animation product and I am confused on which way to go. 

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
Mapbox is biased towards the Internet
Maptalks. js leans towards projects and is generally used for government, industry, and similar to arcgis.js
