### ISSUE TITLE
为绘制工具增加提示信息，当前绘制工具启用后无法分辨是否是激活状态

### ISSUE THREAD

**Issue by aliothor** [maptalks/maptalks.js#2113]
**maptalks's version and what browser you use?**
----
"maptalks": "1.0.0-rc.27",

**Issue description**
----
希望在激活绘制多边形或绘制线模式时，鼠标位置有提示标记正在绘制要素，类型openlayers的绘制功能
[openlayers draw](https://openlayers.org/en/latest/examples/draw-and-modify-features.html)
![image](https://github.com/maptalks/maptalks.js/assets/60435548/cf409f8a-cf2e-43a8-a03b-3a2c42795f63)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://examples.maptalks.com/examples/cn/basic/interaction/draw-tool

**Comment by deyihu** [comment]
@aliothor  https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/DETU/cursor.html

**Comment by aliothor** [comment]
@deyihu 感谢您的回复
