### ISSUE TITLE
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0

### ISSUE THREAD

**Issue by 410739452** [maptalks/maptalks.js#2117]
**maptalks's version and what browser you use?**
v1.0.0-rc.27

**Issue description**
![111](https://github.com/maptalks/maptalks.js/assets/8285719/9bb7d3fa-7906-46f6-8ed4-d4cac5df2876)

地图有时会加载不出来，会报这个错误

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@410739452 

这种一般都是地图容器大小为0导致的,可能原因:

1.地图容器默认隐藏导致地图容器为0
2.vue等组件开发时，组件还没有挂载就开始new地图了,应该在组件挂载后在new map
