### ISSUE TITLE
infoWindow的autoPan开启时会发生偏移错误

### ISSUE THREAD

**Issue by QQ853695231** [maptalks/maptalks.js#2119]
**1.0.0-rc.27**
----

**infoWindow的autoPan开启时会发生偏移错误**
问题同#2056
----

**用vue封装的maptalks使用**
开源仓库地址： https://gitee.com/Devil666/vue-maptalks.git
分支： maptalk-v1.0.0
运行起来后
![issues](https://github.com/maptalks/maptalks.js/assets/22435948/a9302e1c-fa70-4afc-b9a7-dbc65cd78dce)
@deyihu
----

**Comment by deyihu** [comment]
this is bug

**Comment by QQ853695231** [comment]
will be resolved in next version?

**Comment by deyihu** [comment]
> will be resolved in next version?

yes

**Comment by deyihu** [comment]
@QQ853695231  fix by https://github.com/maptalks/maptalks.js/pull/2120/files

**Comment by QQ853695231** [comment]
Ok,牛逼
