### ISSUE TITLE
分辨率小的情况下，使用DrawTool画出的圆会变形

### ISSUE THREAD

**Issue by 410739452** [maptalks/maptalks.js#2122]
**maptalks's version and what browser you use?**
"maptalks": "1.0.0-rc.25"

**Issue description**

![11111](https://github.com/maptalks/maptalks.js/assets/8285719/62accad9-4bd2-4870-b956-d66ecff8f687)

zoom小的情况下，使用DrawTool画出的圆会变形

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
这是正常的，墨卡托投影下，圆形确实会变形
