### ISSUE TITLE
2k分辨率及以上测距、测面工具有很高的延迟

### ISSUE THREAD

**Issue by liyang9331** [maptalks/maptalks.js#2136]
**maptalks's version and what browser you use?**
----

**Issue description**
[----]()

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
请提供一个重现代码，我这里有2k和4k分辨率的屏幕，没有重现这个问题。
应该不是测量本身的问题，而是别的因素造成的。

**Comment by liyang9331** [comment]
> 请提供一个重现代码，我这里有2k和4k分辨率的屏幕，没有重现这个问题。 应该不是测量本身的问题，而是别的因素造成的。

我们的工程代码很重，模块高耦合，没办法提供重现代码
