### ISSUE TITLE
drawtool绘制矩形会受地图pitch的影响，不是正常的矩形，而是一个梯形

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#2156]
**maptalks's version and what browser you use?**
----
![image](https://github.com/maptalks/maptalks.js/assets/5208386/bd913277-21a8-4546-8b09-7a11ed280cd3)

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
not a bug
