### ISSUE TITLE
样式规则通过filter in方式高亮不了最上面的面的颜色，点击广州市的面可复现

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.js#2174]
**maptalks's version and what browser you use?**
----
谷歌 120.0.6099.110

**Issue description**
----
样式规则通过filter in方式高亮不了最上面的面的颜色，点击广州市的面可复现

**Please provide a reproduction URL (on any jsfiddle like site)**
----
[样式规则通过filter in方式高亮不了最上面的面的颜色，点击广州市的面可复现.zip](https://github.com/maptalks/maptalks.js/files/13792044/filter.in.zip)

**Comment by fuzhenn** [comment]
duplicate of maptalks/issues#566
