### ISSUE TITLE
关于环中环状的polygon的展示bug

### ISSUE THREAD

**Issue by roshomon** [maptalks/maptalks.js#2194]
**maptalks's version and what browser you use?**
----1.0.0-rc.25

**Issue description**
----
对于环嵌套在一个外环的polygon图形，leaflet展示正常，mtk的外环内部展示为空，数据见jsfiddle=>polygonData
PS:GeoJSON格式验证网[GeoJSONLint](https://geojsonlint.com/)验证过是有效GeoJSON数据，网站用leaflet展示

**Please provide a reproduction URL (on any jsfiddle like site)**
----
[mtk demo](https://jsfiddle.net/roshomon/uv1o34ah/1/)
[leaflet  demo](https://jsfiddle.net/roshomon/nd3z1j8w/14/)

**Comment by deyihu** [comment]
@roshomon 你的数据我用JTS和GQIS验证过了，其是不符合GeoJSON规范的，你可以自己验证下

- 能被渲染不代表正确，因为渲染利用的奇偶填充，是平面几何里的知识，而GeoJSON是平面几何的子集，是有严格的定义的，可以类比，一个对象可以符合JSON的定义，但是不一定符合GeoJSON的定义
- GeoJSON规范里，一个polygon里holes是不可以相交的，即所有的内环，任何两个都不可相交，更不要说你的数据这种套娃了

**Comment by roshomon** [comment]
@deyihu 
多谢，试了QGIS的check validity工具，确实数据有错；
示例数据是简化后的，实际生产是从turf.isobands输出的“套娃”， 请问有更好的isobands方法吗，或是分离套娃的方法？

**Comment by roshomon** [comment]
> @deyihu 多谢，试了QGIS的check validity工具，确实数据有错； 示例数据是简化后的，实际生产是从turf.isobands输出的“套娃”， 请问有更好的isobands方法吗，或是分离套娃的方法？

log下：重写了turf.isobands源码中的groupNestedRings方法，将套环拆分输出到多个多边形
