### ISSUE TITLE
【BUG】InfoWindow 内的元素无法使用滚轮触发滚动条

### ISSUE THREAD

**Issue by shenxianhui** [maptalks/maptalks.js#2200]
**maptalks's version and what browser you use?**
----
^1.0.0-rc.28

**Issue description**
----
InfoWindow 内的元素设置 overflow: auto; 后, 无法使用滚轮滚动, 只能鼠标拖动, 应该是外层元素禁用了滚动事件

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@shenxianhui   

请在这个例子的基础上复现下，给个代码  https://maptalks.org/examples/en/ui-control/infowindow-scroll/#ui-control_infowindow-scroll

**Comment by The-End-Hero** [comment]
> @shenxianhui
> 
> 请在这个例子的基础上复现下，给个代码 https://maptalks.org/examples/en/ui-control/infowindow-scroll/#ui-control_infowindow-scroll

应该说的是ui.infowindow. 不是marker上的infowindow

**Comment by The-End-Hero** [comment]
> @shenxianhui
> 
> 请在这个例子的基础上复现下，给个代码 https://maptalks.org/examples/en/ui-control/infowindow-scroll/#ui-control_infowindow-scroll

custom为true时，滚动失效
https://codepen.io/the-end-hero/pen/vYPpZRa
