### ISSUE TITLE
PolygonLayer渲染MultiPolygon图像失真

### ISSUE THREAD

**Issue by wxia5** [maptalks/maptalks.js#2226]
**maptalks's version and what browser you use?**
----
![image](https://github.com/maptalks/maptalks.js/assets/11541946/636c8e46-cb62-4bfc-beea-431f970224ce)

**Issue description**
----渲染顶点较多的多边形出现失真情况
![JK`V6LNN%1H%F~5~6SFC6P3](https://github.com/maptalks/maptalks.js/assets/11541946/77a8ada4-bd33-42dd-9258-130eae459587)

----这个是vectorLayer的正常表现
![JK`V6LNN%1H%F~5~6SFC6P3](https://github.com/maptalks/maptalks.js/assets/11541946/f1c56f46-838f-4c1e-9e1e-f3f3360eb7cf)
**Please provide a reproduction URL (on any jsfiddle like site)**
----
[demo.zip](https://github.com/maptalks/maptalks.js/files/14611856/demo.zip)

**Comment by deyihu** [comment]
@wxia5  https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUXING/problem.html#%E6%B8%B2%E6%9F%93polygon%E6%95%B0%E6%8D%AE%E5%87%BA%E7%8E%B0%E6%BC%8F%E6%B4%9E
