### ISSUE TITLE
ts改造任务

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#2235]
以下所有任务只包括该文件夹下文件，不包括子文件夹里的文件
- [x] ~src/core/ & src/core/worker~ (江湖夜雨十年灯)
- [x] src/core/util & src/core/mapbox(江湖夜雨十年灯)
- [x] src/geo & src/geo/measurer/ & src/geo/projection & src/geo/transformation（我是鱼）
- [x] src/geometry/Geometry.js 和 CenterMixin.js(Liquid)
- [x] src/geometry/下首字母A到L的类
- [x] src/geometry/下首字母M到T的所有类
- [x] src/geometry/editor (Liquid)
- [x] src/geometry/ext (Liquid)
- [ ] src/control & src/handler
- [ ] src/lang & src/ui
- [x] src/map/Map.js（胡佬）
- [x] src/map/下除 Map.js 以外的文件 （胡佬）
- [x] ~src/map/handler & src/map/spatial-reference~ (江湖夜雨十年灯)
- [x] src/map/tool （也）
- [x] src/layer （也）
- [x] src/layer/tile & src/layer/tile/tileinfo (L)
- [x] src/renderer/ & src/renderer/map（我是鱼）
- [x] src/renderer/layer & src/renderer/cavanslayer(我是鱼）
- [x] src/renderer/layer/tilelayer (我是鱼）
- [x] src/renderer/layer/vectorlayer (我是鱼）
- [x] src/renderer/geometry & src/renderer/geometry/edit(我是鱼）
- [x] src/renderer/geometry/symbolizers（空白）

**Comment by deyihu** [comment]
ts改造的整体计划

1.大家一起把js改成ts，在改造的过程中，能标注多少就标注多少，不好搞的就any或者ts-ignore，不要不好意思

2.完成第一个步骤后，镇会进行全局的审查下，并标注，注意里可能涉及到源码的修改，这个步骤下来基本做到整个项目的50%左右的标注，这时已经可以发布版本了

3.后续的标注就看大家使用的体验和感受了，在项目里使用时，如果你发现哪里标注不够给力，可以随手就是一个pr，随着时间的推移，无限趋近于100%即可，不要求百分之百，因为有些方法都是私有，大家在项目里根本用不到，只要大家用起来满足需求即可

**Comment by ipcjs** [comment]
迁移完成了？什么时候会发布新版本？

**Comment by deyihu** [comment]
Already completed
