### ISSUE TITLE
Node环境渲染地图后使用导出图片方法报错

### ISSUE THREAD

**Issue by aliothor** [maptalks/maptalks.js#2250]
**maptalks's version and what browser you use?**
----
    "maptalks": "1.0.0-rc.33"

**Issue description**
----
Node环境渲染地图后使用导出图片方法报错，解决无法访问window对象问题后，导出的图片为null

**Please provide a reproduction URL (on any jsfiddle like site)**
----
[问题复现仓库](https://github.com/aliothor/maptalks.js-issue)

**Comment by deyihu** [comment]
maptalks专注于web端，在node里渲可能会有遇到一些问题：
- canvas适配问题(不是所有的node canvas库都mock了所有的canvas api)
- webgl环境
- dom支持问题

这方面不是我们的核心重点，如果你有这方面的需求，欢迎你给提pr来做适配
