### ISSUE TITLE
在加载3dtiles后测量工具点击的位置和鼠标位置有偏差

### ISSUE THREAD

**Issue by zhouzhili** [maptalks/maptalks.js#2271]
**maptalks's version and what browser you use?**
----
@maptalks/gl v0.97.4
@maptalks/vt v0.95.0
@maptalks/3dtiles v0.97.4
@maptalks/gltf-layer v0.97.4
@maptalks/transform-control v0.97.4
@maptalks/video-layer v0.97.4
@maptalks/analysis v0.97.4
@maptalks/transcoders.draco v0.97.4

**Issue description**
----
![1742be11c1625ad32fad2f4b7c5385cb](https://github.com/maptalks/maptalks.js/assets/14259932/e20e4713-fd15-4281-9859-6d041126dfe3)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by liubgithub** [comment]
没有重现此问题，看截图那个cursor是自定义的，需要确保cursor的图标中心点在鼠标的位置

**Comment by zhouzhili** [comment]
> 没有重现此问题，看截图那个cursor是自定义的，需要确保cursor的图标中心点在鼠标的位置

鼠标样式是 `map.setCursor('crosshair')`

**Comment by liubgithub** [comment]
不改变鼠标样式，用默认鼠标样式会出现这个问题吗？

**Comment by zhouzhili** [comment]
复现出来了，一种情况是加载的模型比较大，电脑卡的时候；另外一种是模型有一部分在地平线下面的时候。
官网测量示例里，设置 `heightOffset: -430` 的时候就能复现

![image](https://github.com/maptalks/maptalks.js/assets/14259932/895add45-1aab-40a9-b0d6-53eca2f46acc)

**Comment by deyihu** [comment]
https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/DETU/huizhiyuansu.html#_3d%E6%B5%8B%E9%87%8F
