### ISSUE TITLE
如何在加载地图的时候增加自定义header内容

### ISSUE THREAD

**Issue by liangxuegang01** [maptalks/maptalks.js#2292]
**maptalks's version and what browser you use?**
----

**Issue description**
----
使用TileLayer加载地图的时候，地图url要求带自定义header值，比如header是token，请问如何添加此header值呢？

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@liangxuegang01  https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUCENG/tilelayer.html#%E7%93%A6%E7%89%87%E5%8A%A0%E8%BD%BD%E6%97%B6%E8%87%AA%E5%AE%9A%E4%B9%89headers
