### ISSUE TITLE
label的boxTextAlign功能问题

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#23]
该功能应该是label中的文字相对label居左、居中、居右。
目前的效果是label的box针对center居左、居中、居右。

**Comment by FuZhenn** [comment]
以前固定box, 移动文字的对齐在table里确实用起来更方便, 可以考虑增加新的option属性来解决?

在现有对齐方式下的解决方法, 供参考, *不建议照此修改*:
* table.js中, 初始化label时, 将boxTextAlign设为null
* table.toolbox.js里_setStyleToCell函数改为:
```javascript
    _setStyleToCell: function(cell, attr, value) {
        var symbol = cell.getSymbol();
        if(attr==='textAlign') {
            var mapping = {
              'left'   : ['right', -1],
              'center' : ['middle', 0],
              'right'  : ['left', 1]  
            };
            symbol['textHorizontalAlignment'] = mapping[value][0];
            symbol['textDx'] = symbol['markerDx']+mapping[value][1]*cell.options['boxMinWidth']/2;
//             cell.config('boxTextAlign',value);
            cell.setSymbol(symbol);
        } else {
            var symbol = cell.getSymbol();
            symbol[attr] = value;
            cell.setSymbol(symbol);
        }
    },
```

**Comment by brucin** [comment]
这个问题不是局限在table中，label本身的使用场景也是需要这个功能。应该说只要label需要动态调整文本对齐方式都需要。
如果只是展现，默认对齐方式，展现的位置不对，通过拖动到目标位置即可。如果还有改变对齐方式的功能，那么就需要用户每次改变后都去调整位置，这个不太合理。
![snip20160325_1](https://cloud.githubusercontent.com/assets/11517403/14036807/ce8d6efc-f277-11e5-9323-f9e64d8142e6.png)

**Comment by FuZhenn** [comment]
假设在一个marker下加一个label, boxTextAlign有两种对齐方式:

* box相对marker的位置固定不变, 改变文字位置
* text相对marker的位置固定不变, 改变box位置

感觉两种对齐方式都有适宜的使用场景
可以考虑增加一个options属性, 是固定box还是固定text

例如:
```javascript
boxTextAlign : middle,
boxTextAlignAnchor: text (default) | box 
```

**Comment by fuzhenn** [comment]
分为TextBox和Label分开实现
