### ISSUE TITLE
CanvasContext.createPattern() failed on firefox

### ISSUE THREAD

**Issue by wsw0108** [MapTalks/maptalks.js#23]
![createpattern-failed-on-firefox](https://cloud.githubusercontent.com/assets/4977975/9807339/564695fa-5884-11e5-94e1-201c627395e2.png)

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern
```
var canvas = document.getElementById("canvas");
var ctx = canvas.getContext("2d");

var img = new Image();
img.src = 'https://mdn.mozillademos.org/files/222/Canvas_createpattern.png';
img.onload = function() {
  var pattern = ctx.createPattern(img, 'repeat');
  ctx.fillStyle = pattern;
  ctx.fillRect(0,0,400,400);
};
```

createPattern() should be called after img's onload event...

**Comment by FuZhenn** [comment]
already fixed in new Painter

**Comment by FuZhenn** [comment]
pls verify
