### ISSUE TITLE
底图加载经常空白

### ISSUE THREAD

**Issue by shixiayu13** [maptalks/maptalks.js#2305]
![image](https://github.com/maptalks/maptalks.js/assets/92137880/bec77655-37f0-4036-8d73-1e526940c936)
这种底图加载经常空白的有什么好的优化方式吗

**Comment by deyihu** [comment]
@shixiayu13 https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUCENG/tilelayer.html#%E5%9C%B0%E5%9B%BE%E6%94%BE%E5%A4%A7%E5%90%8Etilelayer%E5%8A%A0%E8%BD%BD%E4%B8%8D%E5%88%B0%E6%95%B0%E6%8D%AE%E4%B8%80%E7%89%87%E7%99%BD%E6%80%8E%E4%B9%88%E5%8A%9E

**Comment by shixiayu13** [comment]
> @shixiayu13 https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUCENG/tilelayer.html#%E5%9C%B0%E5%9B%BE%E6%94%BE%E5%A4%A7%E5%90%8Etilelayer%E5%8A%A0%E8%BD%BD%E4%B8%8D%E5%88%B0%E6%95%B0%E6%8D%AE%E4%B8%80%E7%89%87%E7%99%BD%E6%80%8E%E4%B9%88%E5%8A%9E

没有用

**Comment by sakitam-fdd** [comment]
这种应该是由于并发问题造成的瓦片失败，不知道是服务端问题还是瓦片请求队列控制的问题

**Comment by Kelina-WangQiang** [comment]
这是老版本会缓存加载错误的瓦片，下次会继续读取错误的瓦片，作者新版本已经解决这个问题，在tilelayer上新加了瓦片错误处理方法，可以再重新请求一次，类似以下截图代码：
![aaaa](https://github.com/user-attachments/assets/a7d7f082-ae0b-4385-bd6f-35f0a1502926)
