### ISSUE TITLE
地图边缘zoom计算问题导致图层拼接不上

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#2306]
"maptalks": "^1.0.0-rc.33"
----

使用高德瓦片，使用 gcoord 转换为 wgs84
```
new maptalks.TileLayer('base', {
    urlTemplate: 'http://webrd{s}.is.autonavi.com/appmaptile?lang=zh_cn&style=8&x={x}&y={y}&z={z}',
    subdomains: ['01', '02', '03', '04'],
    offset (z) {
      const map = this.getMap()
      const center = map.getCenter()
      return map.coordToPoint(center, z)
        .sub(map.coordToPoint(
          new maptalks.Coordinate(
            gcoord.transform(center.toArray(), gcoord.AMap, gcoord.WGS84)
          ), z
        ))._round().toArray()
    }
  })
```

在地图边缘会出现有的瓦片zoom计算错误问题，往中心挪动就正常，到边缘表现为层级缩小，瓦片加载错误
----
![image](https://github.com/maptalks/maptalks.js/assets/3621846/97046134-bd2d-461c-919a-38d4332446a6)
边缘时瓦片上的文字明显较大
![image](https://github.com/maptalks/maptalks.js/assets/3621846/474b2b2d-2a89-4f89-b0c4-7361d6298614)
往中心稍微挪动一下后变小
![image](https://github.com/maptalks/maptalks.js/assets/3621846/ab17d086-4cdf-485d-9493-932956afc908)
往中心稍微挪动一下后变小

----

**Comment by wordgold** [comment]
请问大佬地图没有倾斜，没有旋转，为什么会出现各瓦片 zoom 层级不一致的问题呢？

**Comment by fuzhenn** [comment]
直觉上感觉和offset有关

**Comment by deyihu** [comment]
maybe same proble https://github.com/maptalks/maptalks.js/issues/2008

**Comment by wordgold** [comment]
@fuzhenn @deyihu 设置 map option： seamlessZoom: false 后规避了这个问题

**Comment by wordgold** [comment]
https://github.com/maptalks/maptalks.js/issues/1540
