### ISSUE TITLE
版本："maptalks": "^1.0.0-rc.33", 问题：The old listener function will be removed

### ISSUE THREAD

**Issue by is-Joe** [maptalks/maptalks.js#2308]
**maptalks's version and what browser you use?**
----
"maptalks": "^1.0.0-rc.33

**Issue description**
----

我是用天地图底图，可以正常渲染，但是渲染完成之后约三五秒钟，控制台有警告
![image](https://github.com/maptalks/maptalks.js/assets/47885917/646202d0-8b64-4ee7-9468-f1e67fe43f40)
我代码中是没有绑定mouseout事件的，以下是我的代码，前端框架使用的是Vue2

![code](https://github.com/maptalks/maptalks.js/assets/47885917/1fb0219d-a7c8-4690-9996-ca5d6d7c61d9)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by hackers267** [comment]
当使用map.setMenu 和 map.setMenuItems 时，"The old listener function will be removed" 警告还是存在

**Comment by deyihu** [comment]
@hackers267  more detail https://github.com/maptalks/maptalks.js/pull/2661
