### ISSUE TITLE
三维模式下infoWindow 显示位置不准确

### ISSUE THREAD

**Issue by zhouzhili** [maptalks/maptalks.js#2313]
**maptalks's version and what browser you use?**
----
maptalks v1.0.0-rc.33
maptalks-gl-layers.js:51 @maptalks/gl v0.97.4
maptalks-gl-layers.js:119 @maptalks/vt v0.95.0
maptalks-gl-layers.js:135 @maptalks/3dtiles v0.97.4
maptalks-gl-layers.js:146 @maptalks/gltf-layer v0.97.4
maptalks-gl-layers.js:152 @maptalks/transform-control v0.97.4
maptalks-gl-layers.js:168 @maptalks/video-layer v0.97.4
maptalks-gl-layers.js:174 @maptalks/analysis v0.97.4
maptalks-gl-layers.js:174 @maptalks/gl-layers v0.34.1
transcoders.draco.js:6 @maptalks/transcoders.draco v0.86.0

**Issue description**
----
![image](https://github.com/maptalks/maptalks.js/assets/14259932/720b78bb-d357-4386-a593-3a619023d420)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
官网示例：http://examples.maptalks.com/examples/raw/cn/3d/3dtiles/view-monomer

**Comment by deyihu** [comment]
![W08(O`6Z @_1F}%I(2 G4X1](https://github.com/maptalks/maptalks.js/assets/25998927/3a80f4d7-ce60-4765-ab0d-2b596b53c090)

没有发现是么问题，
