### ISSUE TITLE
Possibility of drawing LineStrings drawAltitude floating?

### ISSUE THREAD

**Issue by rrickfox** [maptalks/maptalks.js#2320]
**maptalks's version and what browser you use?**
----
Maptalks: 1.0.0-rc.33
Chrome: Version 124.0.6367.119 (64 Bit)

**Issue description**
----
Hi,
I was wondering whether the functionality exists to give LineStrings drawAltitude a lower shape. The examples show the LineString being used as a wall of sorts, my usecase would be to draw a floating wall.
When looking through the source code I found a reference to "groundPoints" inside the DrawAltitudeSymbolizer, although I was unable to understand how one would be able to set the groundPoint for each coordinate in the lineStrings array.
Any insight into that is greatly appreciated, the framework is great so far!

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by joric** [comment]
@rrickfox I think it's just a confusing naming, groundPoint is merely a name for the line start. I managed to draw lower shapes in a separate layer.

**Comment by deyihu** [comment]
Sorry, this feature is not supported
