### ISSUE TITLE
flyTo Method: Animation Zooms Without Panning and Flickers to Target Location on End

### ISSUE THREAD

**Issue by Gazentia** [maptalks/maptalks.js#2321]
**maptalks's version and what browser you use?**
----
- maptalks@1.0.0-rc.33
- Chrome: Version 124.0.6367.119 (64-bit)

**Issue description**
----
- When attempting to utilize the flyTo method, I encountered incorrect behavior: initially, the animation simply zoomed in and out without panning, but then it flickered to the target location once the animation ended.

**Please provide a reproduction URL (on any jsfiddle like site)**
----
- https://github.com/maptalks/maptalks.js/assets/63592674/e669106e-47bc-4db6-a067-0742ed304a70

- https://github.com/maptalks/maptalks.js/assets/63592674/6586ddc7-fa56-4933-9e2c-8670059f411d

**Comment by deyihu** [comment]
fixed by https://github.com/maptalks/maptalks.js/pull/2335/files
