### ISSUE TITLE
Marker 3D Altitude

### ISSUE THREAD

**Issue by ShafSpecs** [maptalks/maptalks.js#2324]
**maptalks's version and what browser you use?**
----
Chrome & Latest Maptalk (as of 9th of May, 2024)

**Issue description**
----
- One thing I noticed about vector layer with altitude is that they remove some marker past some height, after about 500, markers seem to disappear. How do I set altitude height for vector layers?
- My second question is what is the altitude unit? Is it meters or pixels or something else?
- How do I also update altitude? I tested a layer with an altitude of 20, updated it to 15 and it didnt get rendered anymore till I refresh. The code referenced a `setAltitude` here:
https://github.com/maptalks/maptalks.js/blob/2a4ab207619543237a2943bbb1c293863c6a98bd/src/geometry/Geometry.ts#L1748-L1783
but I can't seem to access it even though marker extends geometry. 

Would this be updated anytime soon too? https://maptalks.org/maptalks.js/api/1.x

**Comment by ShafSpecs** [comment]
And thank you @fuzhenn for this package ❤️

**Comment by deyihu** [comment]
@ShafSpecs 

1. this is bug,has fixed,The next version will fix this issue
2. meter
3. https://codepen.io/deyihu/pen/qBGBbWb?editors=1010

**Comment by ShafSpecs** [comment]
> @ShafSpecs
> 
> 1. this is bug,has fixed,The next version will fix this issue

🎉 

> 2. meter

Ok, thanks

> 3. https://codepen.io/deyihu/pen/qBGBbWb?editors=1010

Ah, thank you. This is missing in TypeScript too. Would ignore error for now till a fix is made

Thanks

**Comment by ShafSpecs** [comment]
@deyihu Quick question from an issue I am facing:
![image](https://github.com/maptalks/maptalks.js/assets/69679506/9a54c202-898a-48c2-9a3c-35e948b6c411)
I have this simple UI that gets marker altitude and sets them on the map. When I place a marker down, they have a default height of 20m. But placing them down looks like they are 1m instead of 20 (I did not change the first one). I changed the second one to 21 and back to 20 and it is higher than the first one

This is my code:
```ts
const _coords$$$ = Array.isArray(coordinates) ? [coordinates[0], coordinates[1]] : [coordinates.x, coordinates.y]

const mk = new MaptalkMarker(_coords$$$, {
      draggable,
      symbol,
      id,
      // properties: {
      //   altitude,
      // },
})

if (altitude) {
      // @ts-ignore - Super-wrong typing
      // mk.setAltitude(altitude)
      mk.setProperties({
        altitude,
      })
}
```
I tried changing it different ways but it doesnt work. I have to change it in my table, before correct height is shown

**Comment by ShafSpecs** [comment]
Fixed it :tada:. Seemed like the issue was because of ids? And my altitude wasn't passed in correctly. Thank you very much
