### ISSUE TITLE
cdn 引入 maptalks 没有Geo3DTilesLayer 这个属性，cdn 引入如何创建Geo3DTilesLayer这个呢

### ISSUE THREAD

**Issue by hellofancycn** [maptalks/maptalks.js#2330]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Geo3DTilesLayer 在[这个包里](https://github.com/maptalks/maptalks-gl-layers/)，不过未来会和maptalks.js合并

**Comment by hellofancycn** [comment]
maptalks-gl-layers 有文档手册吗？我们现在有一个2D的底图， 还有一个3D的部分区域图Geo3DTilesLayer，这俩个要叠加，这俩会互相覆盖，二者只显示其一
