### ISSUE TITLE
enableSimplify does not work

### ISSUE THREAD

**Issue by joric** [maptalks/maptalks.js#2331]
Looks like enableSimplify never works, tried to find it in code and It's a placeholder, there is no implementation, is there?
Code in question (I tried to use it for LineString): [index.html](https://github.com/joric/supraland/blob/main/3d/index.html), [live demo](https://joric.github.io/supraland/3d).

I had to use a 3rd-party `simplify` library, https://github.com/mourner/simplify-js/tree/3d

```js
points = simplify(points, 20); // WORKS HERE (3rd-party library), back to million points if commented out

new maptalks.LineString(points, {
  enableSimplify: true, simplifyTolerance: 20, // DOES NOT WORK HERE, no effect at all
  symbol:{lineColor: color, lineWidth: lineWidth}
}).addTo(lineLayer);
```

I'd rather had it built in, than a dependency. It's less than a page of code.

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/YzbLMgQ

Perhaps your data is too sparse, please note that the simplifyTolerance value is for projection coordinates, not screen pixel coordinates

https://github.com/maptalks/maptalks.js/blob/d5ac56b0f1250b367d41ea3ecac1cc3313d5e0fe/src/geometry/Path.ts#L292

**Comment by joric** [comment]
@deyihu debugged a little. The real reason is that it works only for 2d data and layers where enableAltitude is `false`.
There's an early termination here Path.prototype._shouldSimplify, condition `!hasAltitude`.
Your example does not have enableAltitude enabled and polygons don't have z-coordinate.

Figures maptalks simplify code, namely getSqSegDist doesn't support 3d simplify at all.
When I try to skip conditions, everything 3d degrades to start and end points.

The actual code is essentially copied from the same source, `maptalks.js` has comments like:

```js
  /*
   (c) 2017, Vladimir Agafonkin
   Simplify.js, a high-performance JS polyline simplification library
   mourner.github.io/simplify-js
  */

  (function (module) {
    (function () {
    // to suit your point format, run search/replace for '.x' and '.y';
    // for 3D version, see 3d branch (configurability would draw significant performance overhead)

    // square distance between 2 points
    function getSqDist(p1, p2) {

        var dx = p1.x - p2.x,
            dy = p1.y - p2.y;

        return dx * dx + dy * dy;
    }

    // square distance from a point to a segment
    function getSqSegDist(p, p1, p2) {

        var x = p1.x,
            y = p1.y,
            dx = p2.x - x,
            dy = p2.y - y;
```
So it would need updating this part using code from https://github.com/mourner/simplify-js/tree/3d but only where .z exists.

Could not reopen this one, created a new issue #2362
