### ISSUE TITLE
Question: Providing Sky/Horizon fade

### ISSUE THREAD

**Issue by ShafSpecs** [maptalks/maptalks.js#2338]
**maptalks's version and what browser you use?**
----
Latest (March 14 release)

**Issue description**
----
I want to ask about adding a sky-like feeling (instead of the background color) - similar to mapbox:
![image](https://github.com/maptalks/maptalks.js/assets/69679506/1ccca0f3-c646-469a-a8bb-4fee77151f3b)

Thank you for the package, I have also seen a lot of fixes. Please, any idea when the next release would happen?

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/QWpmxzE?editors=1010
