### ISSUE TITLE
LineString arrow placement, scalable markers

### ISSUE THREAD

**Issue by joric** [maptalks/maptalks.js#2339]
I'm using big round icons as markers. How to make a LineString to draw the arrow not in the end but with a little offset (marker radius)? Basically I need endOffset for arrows, preferably as a function (akin to D3) because icon size may change on zoom.

![image](https://github.com/maptalks/maptalks.js/assets/852547/7b58dce9-d5b2-4535-b139-93080e1283b9)

I tried to reproject the line segment using `coordinateToContainerPoint`, fix the length in screen space and recalculate it back as 3d coordinates when creating the layer, but it breaks on zoom so lines would have to be recalculated each time.

It should be done in screen space by the engine, maybe there's a way to do it already? Using D3 layer maybe?

---

Also (sorry for digress) how to do scalable markers properly? I'm currently doing it like this, but maybe there's an easier way?

```js
  // need all 3 events because of animation
  map.on('zooming zoomstart zoomend', function(e) {
    let s = getIconSize(e.to ? e.to : e.from);
    [].forEach.call(vectorLayer._geoList, function(g) {
      if (g._jsonType=='Marker') {
        g.updateSymbol([{markerWidth:s, markerHeight: s, markerDy: s/2}]);
      }
    });
  });
```

Also how to do outline (stroke) for the LineString?

**Comment by deyihu** [comment]
@joric  symbol value support function-type

https://codepen.io/deyihu/pen/BaeYrWZ?editors=0010
https://maptalks.org/examples/en/style/symbol-by-zoom/#style_symbol-by-zoom
https://github.com/maptalks/maptalks.js/wiki/Symbol-Reference
