### ISSUE TITLE
Can't change heightFactor for the existing map

### ISSUE THREAD

**Issue by joric** [maptalks/maptalks.js#2358]
I want to change heightFactor dynamically (for various reasons, e.g. I have a slider in user settings), how can I do that? Both `map.setOptions({heightFactor: 0.25})` and `map.config('heightFactor', 0.25)` don't work, the map doesn't change. Do I need to update geometry cache somehow or something?

**Comment by deyihu** [comment]
This parameter is not intended to update the altitude of the geometry. It is designed to solve the problem of scaling heights at different latitudes. If you want to update the altitude of the graph, you need geometry. setAltitude()

https://maptalks.org/examples/en/3d/set-altitude/#3d_set-altitude

**Comment by joric** [comment]
It would be great to change height multiplier dynamically though, for the entire map...
