### ISSUE TITLE
官网例子中，画的线会模糊，很多地方都是这样

### ISSUE THREAD

**Issue by 156370005** [maptalks/maptalks.js#2361]
![aa](https://github.com/maptalks/maptalks.js/assets/102794997/b24c6ff1-bb5a-4ad5-a653-3beaa223e0f2)

**Comment by deyihu** [comment]
从截图上并没有发现你说的问题，不知道你说的模糊指的是？如果说的颜色拾取工具，那是正常的，颜色拾取工具会放大当前位置的像素点

**Comment by 156370005** [comment]
这应该很明显，中间的线，比上下两条线都模糊，我截图放大看，这条模糊的线，上下各有半透明的边

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/dyEeEje

这个是我原生的canvas画的效果，你说的问题仍然存在，所以：
- 我不知道你的说的这个是不是bug
- 即使是bug也是浏览器的bug
-  经过我测试是线的宽度是奇数导致的，应该是浏览器的问题，如果你把lineWidth=4你说的问题就不存在了
