### ISSUE TITLE
关于 drawTool dblclick触发drawend是否可以修改？

### ISSUE THREAD

**Issue by zhangweixun0207** [maptalks/maptalks.js#2372]
**maptalks's version and what browser you use?**
----
1.0.0-rc.27  Chrome

**Issue description**
----
项目中需要将drawTool中绘制结束的双击保存触发drawend，更改为某个键盘按键触发，是否可以实现？

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
You can use the drawEnd method to actively end drawing

https://codepen.io/deyihu/pen/KKLOxXv

**Comment by zhangweixun0207** [comment]
十分感谢，已解决
