### ISSUE TITLE
有高度的元素，在相机拉近时会消失

### ISSUE THREAD

**Issue by pigHeadnotBald** [maptalks/maptalks.js#2377]
**maptalks's version and what browser you use?**
---- "maptalks": "^1.0.0-rc.33",

**Issue description**
---- 您好，我在底图上添加了一些有高度的线段，LineString中的数据都是（lng, lat, alt）的格式，相机一旦拉近时会出现线段消失的问题

这是视角没有拉近的时候，线段可以正常显示：
![1720167672151](https://github.com/maptalks/maptalks.js/assets/125938035/ec497d5e-8511-49ba-b5f4-a38332ac18cb)
当视角拉近线段会消失：
![1720167704241](https://github.com/maptalks/maptalks.js/assets/125938035/669f157b-723e-4cc6-b722-5ecfa523a367)

**Comment by deyihu** [comment]
fixed by https://github.com/maptalks/maptalks.js/commit/251f0212679c74ac2eac7c11c3b08f11520795d0

**Comment by pigHeadnotBald** [comment]
> fixed by [251f021](https://github.com/maptalks/maptalks.js/commit/251f0212679c74ac2eac7c11c3b08f11520795d0)

问一下您 新版本什么时候会发布出来呢？现在下载的版本似乎并没有fix这个bug

**Comment by deyihu** [comment]
> > fixed by [251f021](https://github.com/maptalks/maptalks.js/commit/251f0212679c74ac2eac7c11c3b08f11520795d0)
> 
> 问一下您 新版本什么时候会发布出来呢？现在下载的版本似乎并没有fix这个bug

@fuzhenn
