### ISSUE TITLE
使用 QGIS和MapTiler desktop 对TIFF文件进行切片，加载到Maptalks里出现拼接错误

### ISSUE THREAD

**Issue by zhangweixun0207** [maptalks/maptalks.js#2379]
**maptalks's version and what browser you use?**
----
chrome   maptalks：^1.0.0-rc.27

**Issue description**
----
对TIFF切图出的瓦片，在Openlayers和leaflet上加载都是正常的，在Maptalks上加载出现拼接位置错乱，瓦片丢失的问题
问题显示
![Snipaste_2024-07-12_09-03-42](https://github.com/user-attachments/assets/5532ef8f-e348-45ee-940d-78620db31d83)
代码粘贴
![Snipaste_2024-07-12_09-08-02](https://github.com/user-attachments/assets/08729d60-8e6e-4d85-87b0-85bd00265963)
openlayers加载
![openlayers_2024-07-12_09-04-12](https://github.com/user-attachments/assets/8edc462c-6afc-4f1a-ab0a-500184186ae6)
leaflet加载
![leaflet_2024-07-12_09-05-20](https://github.com/user-attachments/assets/b94188de-c60d-4b65-8bec-59cfc1ab4007)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
当地图切斜时，mtk里会：
- 远处会加载低级别的瓦片，近处会加载当前网片
- 如果全部加载当前瓦片，当前视野捏会大量的瓦片，会导致性能急剧下降，故而这么设计
- leaflet/ol 里因为没有地图倾斜这个功能所以没有这种机制而已

你可以关闭这个功能：

```js
  const layer = new maptalks.TileLayer('base', {
            cascadeTiles: false,
            pyramidMode: false,
            urlTemplate: "https://webst01.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}",
            subdomains: ["a", "b", "c", "d"],

        });

```

注意关闭这个功能后，地图倾斜时因为都会加载当前瓦片(瓦片非常多),性能会下降

@zhangweixun0207 如还有问题，欢迎再次打开改issue
