### ISSUE TITLE
map实例对象放到vue3的reactive对象属性中，map.on('viewchange')事件会失效

### ISSUE THREAD

**Issue by yangjh168** [maptalks/maptalks.js#2408]
**maptalks's version and what browser you use?**
^1.0.0-rc.37

**Issue description**
初始化地图实例后，将得到的实例放到vue3的reactive对象中的属性中，添加地图viewchange事件监听，调用zoomIn，zoomOut改变地图层级，map.on('viewchange')的监听会失效

**Please provide a reproduction URL (on any jsfiddle like site)**
----
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>test</title>
  <style type="text/css">
    html,body{margin:0px;height:100%;width:100%}
    .container{width:100%;height:50%}
  </style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.min.css">
  <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.min.js"></script>
  <body>
    <div id="map" class="container"></div>
    <button onclick="onZoomIn()">-</button>
    <button onclick="onZoomOut()">+</button>

    <script>
      const { reactive } = Vue

      const state = reactive({
        map: null
      })

      state.map = new maptalks.Map('map', {
        center: [112.4399345,30.1517875],
        zoom: 14,
        baseLayer: new maptalks.TileLayer('base', {
          urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
          subdomains: ['a','b','c','d'],
          attribution: '&copy; <a href="http://osm.org">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/">CARTO</a>'
        })
      });

      state.map.on('viewchange', (event) => {
        console.log(event)
      })

      function onZoomIn() {
        state.map.zoomIn()
      }
      function onZoomOut() {
        state.map.zoomOut()
      }
    </script>
  </body>
</html>

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.js/issues/1971
