### ISSUE TITLE
绘制多个连续扇形时有明显边框

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#2416]
**maptalks's version and what browser you use?**
----
1.0.0-rc.33

**Issue description**
----
![image](https://github.com/user-attachments/assets/3476097e-700d-438f-a3f6-fcbcd8cf4258)
尝试绘制如图的台风范围示意图，使用 Sector 绘制后扇形边缘有明显边框
![image](https://github.com/user-attachments/assets/cbc6d924-2ad3-4cb9-9729-81c95c3540ca)

```
[200,250,200,200].map((v, i) => new maptalks.Sector([lng, lat], v * 1000, i * 90 - 90, i * 90, {
    symbol: {
      lineWidth: 0,
      polygonFill: '#ff0',
      polygonOpacity: 0.4
    }
  }))
```

请问有什么办法可以实现第一张图的台风示例吗？

**Comment by deyihu** [comment]
https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/YEWU/typhoom.html

**Comment by wordgold** [comment]
@deyihu 谢谢！
