### ISSUE TITLE
Marker无法identify点中图片中的透明部分

### ISSUE THREAD

**Issue by luothink** [maptalks/maptalks.js#2424]
Marker的markerFile的图片包含透明部分，当鼠标点击透明部分时，identify返回结果为空；
调试源码发现，实现逻辑中只查询透明度不为0的部分；
![image](https://github.com/user-attachments/assets/672c6d75-202b-4347-854c-e2fbc7e637bb)

**Comment by deyihu** [comment]
https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUXING/problem.html#%E5%9B%BE%E5%BD%A2%E9%80%8F%E6%98%8E%E7%9A%84%E5%9C%B0%E6%96%B9%E4%B8%8D%E5%8F%AF%E4%BA%A4%E4%BA%92
