### ISSUE TITLE
maptalks如何加载SuperMap iServer发布的rest地图服务

### ISSUE THREAD

**Issue by gaohuijuan** [maptalks/maptalks.js#2430]
maptalks如何加载SuperMap iServer发布的rest地图服务

**Comment by deyihu** [comment]
https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/TUCENG/tilelayer.html#%E5%8A%A0%E8%BD%BDsupermap%E5%8F%91%E5%B8%83%E7%9A%84%E7%93%A6%E7%89%87%E6%9C%8D%E5%8A%A1
