### ISSUE TITLE
MultiLineString flash问题

### ISSUE THREAD

**Issue by QQ853695231** [maptalks/maptalks.js#2439]
地图上添加了多个 MultiLineString ，右侧表格里面也可以和地图联动，点击表格里面的行，可以定位到对应的线，同时调用flash方法让线闪烁，现在发现有的线能闪，有的线不闪，不知道为啥。

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/eYqWpRd

暂时没有发现这个问题，如果有问题请给个复现的代码
