### ISSUE TITLE
Geometry.startEdit() 方法右键删除面要素内环点报错

### ISSUE THREAD

**Issue by xiaoin6515** [maptalks/maptalks.js#2458]
**maptalks's version and what browser you use?**
maptalks v1.0.0-rc.35

**Issue description**
geometry是polygon且polygon有内环，调用startEdit()方法，右键删除内环上的点时报错

**Please provide a reproduction URL (on any jsfiddle like site)**
----
[edit.txt](https://github.com/user-attachments/files/17640389/edit.txt)

**Comment by deyihu** [comment]
核心库rc.38已经修复这个bug了，
https://github.com/maptalks/maptalks.js/commit/d9926d64b672451618fb9107f2760887efcfda71

示例网站的版本太老了，需要你使用最新版本
