### ISSUE TITLE
核心库解决鼠标在地图范围外空指针问题

### ISSUE THREAD

**Issue by Kelina-WangQiang** [maptalks/maptalks.js#2460]
除了drawtool还有snap也有问题，不排除其他插件有问题，所以需要从核心库解决问题
![ddd](https://github.com/user-attachments/assets/489156f0-6488-4aaf-8c9b-72b8be6c450d)

**Comment by deyihu** [comment]
![Z08ATD6S9Z7@3MYZX$3VY17](https://github.com/user-attachments/assets/d60dd38d-af6f-43a3-ab99-bb89f0d4add2)

@Kelina-WangQiang  麻烦提个pr
