### ISSUE TITLE
DrawTool 能否支持在激活状态下显示 vertex marker

### ISSUE THREAD

**Issue by hellocreep** [maptalks/maptalks.js#2462]
**maptalks's version and what browser you use?**
----
maptalks@1.0.0-rc.17
maptalks.snap@0.4.2

**Issue description**
----
当 DrawTool 结合角点捕捉([maptalks.snap](https://github.com/maptalks/maptalks.snap))一起使用，在绘制工具激活状态绘制第一个点位时，无法得知是否捕捉到角点。
能否在绘制工具(LineString, Polygon...)激活状态下，显示一个跟随鼠标移动的 marker，并且支持角点捕捉。

同时发现 maptalks.snap@0.4.3 在调用绘制工具时报错
可复现链接：https://maptalks.org/maptalks.snap/test/draw.html

**Please provide a reproduction URL (on any jsfiddle like site)**
----

现在使用绘制工具的效果：

https://codepen.io/hellocreep/pen/BaXgBjR

期望的效果：

https://github.com/user-attachments/assets/b6ae527f-3c4f-4c8d-b5df-40ebb485859e

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.snap/commit/03423234fdbdeea8a977c600bf41462ddd4b0803

the draw demo updated https://maptalks.org/maptalks.snap/test/draw.html
