### ISSUE TITLE
symbol 的 polygonFill 能支持 conic-gradient 渐变吗

### ISSUE THREAD

**Issue by DimplesY** [maptalks/maptalks.js#2467]
polygonFill 里面的渐变类型只支持 linear | radial ，有办法能够支持 conic-gradient 吗

**Comment by deyihu** [comment]
不支持的，因为VectorLayer底层渲染是canvas，canvas默认好像没有提供这个功能，这些功能都需要人工去模拟，性能很差的

另外VectorLayer图层我们不打算在加入一些新的功能，维护现有的功能，目前精力在webgl这块

**Comment by DimplesY** [comment]
> 不支持的，因为VectorLayer底层渲染是canvas，canvas默认好像没有提供这个功能，这些功能都需要人工去模拟，性能很差的
> 
> 另外VectorLayer图层我们不打算在加入一些新的功能，维护现有的功能，目前精力在webgl这块

能够支持 
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createConicGradient
