### ISSUE TITLE
Canvas图层坐标有偏移

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#28]
geometry在Canvas上位置有偏移。在YUM上数据偏移更加明显。不能确定是数据问题，还是与Canvas上数据位置偏移问题一致。

**Comment by FuZhenn** [comment]
已经在主工程maptalks中解决了此问题.
请验证:
https://github.com/MapTalks/maptalks/commit/904e25fd86cc6d129654d43574e100a1870dc6e1

**Comment by FuZhenn** [comment]
问题已经解决,请验证 @brucin
