### ISSUE TITLE
控件的换肤功能

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/MapTalks.js#3]
是否需要提供控件的换肤.

在提供默认的皮肤基础上, 通过加载新的js或者新的css等方式简单的实现换肤.

**Comment by brucin** [comment]
哦，这个功能，我之前就考虑过。
对于，系统自带的多套皮肤模板，在options，增加一个style: grey（white/black)这样的参数，可以让用户简单设置系统控件风格。

**Comment by FuZhenn** [comment]
ok, 关闭问题
