### ISSUE TITLE
layer.clear()与geometry.remove()

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#31]
1、layer.clear()会引起：Maximum call stack size exceeded；
2、geometry.remove()  无效。在canvas上绘制图形会出现两个图形原因也是在绘制后删除绘制的临时图形失败造成的。

**Comment by FuZhenn** [comment]
无法重现, 请给出重现代码

**Comment by brucin** [comment]
edit_polygon.html，测试layer.clear()无法删除图形；
draw_polygon.html，绘制后，在_endDraw()中无法清除临时的图形。

**Comment by FuZhenn** [comment]
fixed, pls verify
