### ISSUE TITLE
鼠标悬停事件支持

### ISSUE THREAD

**Issue by xiaoguxg** [maptalks/maptalks.js#318]
是否支持鼠标悬停事件，比如，鼠标移动到相应的polygon上，能够获取当前polygon的信息
![image](https://cloud.githubusercontent.com/assets/8435230/21674752/1ed59244-d36a-11e6-899b-d49e735a8487.png)

**Comment by fuzhenn** [comment]
可以试试
polygon.on('mouseover', e => console.log(e.target));
