### ISSUE TITLE
symbol属性名命名规范

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/maptalks.js#32]
根据谷歌json代码指南里关于属性名的规范, json属性属性名应该都是camel的, 但第一个字母可以是_或者$
所以我觉得应该:

* 把symbol属性名都改成camel:myName的, 而不是现在的dash:my-name方式
* cartoCSS样式里用dash-style, 但程序里都用camelCase, 和DOM属性保持一致
* cartoCSS样式应用到程序里时, 就做一下属性转化

maptalks的内部属性名以__(两个下划线)开头, 例如__maptalksSymbol

修改后的symbol示例:

{

    "markerPlacement":"point", //point | line | interior

    "markerFile"   : "bus.png",
    //设定markerFile后, 只有下面的属性起作用
    "markerWidth"  : 20,
    "markerHeight" : 20,
    "markerOpacity": 1,

    //两个cartocss里没有的扩展属性, 用来标注相对中心点的像素距离
    "markerDx"     : 0, //<-------
    "markerDy"     : 0  //<-------

};

参考资料:
http://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml#Property_Name_Format
http://stackoverflow.com/questions/5543490/json-naming-convention
第一个网址需要翻墙

**Comment by brucin** [comment]
你的意思是除了外部的cartoCSS定义文件，js中的样式全部用camel的样式吗？

**Comment by FuZhenn** [comment]
对的, 因为在程序语境中, symbol是个json格式数据, 所以我查了一下, 基本上目前主流都是用camel形式定义json属性名的.
而dash形式只在外部的cartoCSS定义中使用, 因为cartoCSS不是json, 遵循的类CSS命名规范.

**Comment by brucin** [comment]
ok。同意。

**Comment by FuZhenn** [comment]
@wsw0108 有没有什么意见

**Comment by wsw0108** [comment]
可以，程序中使用camelCase没什么问题。
也就是所有marker/polyline/sector之类的Symbol，全部用cartoCSS风格的属性名，但是是camelCase的。

另有一个情况，在绘制之前，把cartoCSS风格的属性名转换成stroke/strokeWidth之类的名字，好像没什么必要？

**Comment by FuZhenn** [comment]
转换成stroke, stroke-width等主要是方便向生成的svg对象直接设置属性, 省略名字转换.

**Comment by wsw0108** [comment]
但是对于canvas，又没什么直接对应关系。
可以考虑使用一个或多个映射表的方式统一管理。

**Comment by FuZhenn** [comment]
对canvas是没有对应关系, 同理对vml也没有.当初考虑的是总归要转换, 少转换一个是一个

**Comment by wsw0108** [comment]
可以。少转换一个是一个。

顺便贴几个规范地址。

SVG property index:
http://www.w3.org/TR/SVG/propidx.html

VML spec:
http://www.w3.org/TR/NOTE-VML

CartoCSS spec:
https://github.com/mapbox/carto/blob/master/docs/latest.md
