### ISSUE TITLE
polygon-fill/polygon-pattern-file has no effection when draw polygon(exactly)

### ISSUE THREAD

**Issue by wsw0108** [MapTalks/maptalks.js#33]
it's ok when drawing circle/ellipse/rectangle with polygon-fill/polygon-pattern-file

**Comment by FuZhenn** [comment]
fixed, pls verify

**Comment by wsw0108** [comment]
其实我说的问题是，对于polygon，在画的过程中，达到3个点足以形成一个面时，样式没有体现出来。
不知道这个算不算问题？

**Comment by FuZhenn** [comment]
这个不算是bug.
我们以前在3点形成面后, 就马上形成多边形并形成填充, 类似百度地图的示例:
http://developer.baidu.com/map/jsdemo/demo/f0_7.htm

但后来yum客户觉得这种方式不好用, 更喜欢用画线的形式来画多边形, 在双击结束绘制后才封闭图形并填充, 就是我们现在的方式.

谷歌地图也和我们一样的(要翻墙):
https://developers.google.com/maps/documentation/javascript/examples/drawing-tools

**Comment by brucin** [comment]
的确是这样，因为三点成面之后的点得绘制会很受动态移动的那个面的影响，在实际操作过程中不少人提出来过问题。
百度的面绘制也类似我们的方案。

**Comment by wsw0108** [comment]
问题在于，画circle/rect的过程中，polygon-fill/polygon-pattern-file是起作用的，唯独画polygon的过程中不起作用。

leatlet.draw的例子：
http://leaflet.github.io/Leaflet.draw/

**Comment by FuZhenn** [comment]
leaflet的draw挺好, 要不我们按它的来

**Comment by FuZhenn** [comment]
@wsw0108 该问题已经修改好
http://localhost:20000/examples/geometry/polygon/draw_polygon.html

![image](https://cloud.githubusercontent.com/assets/13678919/11893907/dba1169a-a5ae-11e5-8d9d-d3b7c07c6d93.png)
