### ISSUE TITLE
maptalks.clusterLayer.js插件，可否设置成，在最大级别时全部散开，不以聚集状态呈现

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#341]
因为需要点某个要素查看信息，如果仍然以聚集状态呈现的话，不能点开查看

**Comment by fuzhenn** [comment]
可以设置maxClusterZoom, 参考示例:
https://github.com/maptalks/maptalks.markercluster/blob/gh-pages/demo/index.html#L51

**Comment by liubgithub** [comment]
亲测，可以。
