### ISSUE TITLE
uimarker的mouseout事件在调用setContent()方法后，不能被监听，且mouseover事件会变为mousemove事件的效果

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#354]
map.on('click', function (e) {
                var m = new maptalks.ui.UIMarker(e.coordinate, {
                    'draggable': true,
                    'single': false,
                    'content': '<div id="uimarker"><img src="../images/marker-icon.png"/></div>',
                    'dy':-20.5
                }).addTo(map).show();
                m.on("mouseover", function (e) {
                    m.setContent('<div id="uimarker"><img src="../images/marker-change.png"/></div>');
                    console.log("ui marker mouse type is" + e.type);
                });
                m.on("mouseout", function (e) {
                    m.setContent('<div id="uimarker"><img src="../images/marker-icon.png"/></div>');
                    console.log("ui marker mouse type is" + e.type);
                });
            });
以上为测试代码

**Comment by fuzhenn** [comment]
测试并重现了, 不过这并不是引擎的bug, 而是实现方法不当造成的.
**原因:**
mouseover会被频繁调用, UIMarker的content随之被频繁设置, UIMarker的dom元素也频繁的重新生成, 造成mouseout事件无法正常响应.
**修改:**
注释中的数字为修改处
```javascript
map.on('click', function (e) {
      // 1
      var changed = false;
      var m = new maptalks.ui.UIMarker(e.coordinate, {
          'draggable': true,
          'single': false,
          'content': '<div id="uimarker"><img src="../images/marker-icon.png"/></div>',
          'dy':-20.5
      }).addTo(map).show();
      m.on("mouseover", function (e) {
          // 2
          if (changed) {
            return;
          }
          m.setContent('<div id="uimarker"><img src="../images/marker-change.png"/></div>');
          // 3
          changed = true;
          console.log("ui marker mouse type is" + e.type);
      });
      m.on("mouseout", function (e) {
          m.setContent('<div id="uimarker"><img src="../images/marker-icon.png"/></div>');
          console.log("ui marker mouse type is" + e.type);
          // 4
          changed = false;
      });
  });
```

**Comment by liubgithub** [comment]
mouseover事件和mousemove事件啥区别呢？

**Comment by fuzhenn** [comment]
hmm, 感觉区别不大

查了一下资料, 给UIMarker增加了一个mouseenter事件, 相当于只调用一次的mouseover

**Comment by fuzhenn** [comment]
相关的commit:

https://github.com/maptalks/maptalks.js/pull/356/commits/f9a7db2fed0b7a25bf50d5b03555f6d5f1a64173

题目的程序里可以把mouseover直接替换成mouseenter, 就不用设置changed标志位了
