### ISSUE TITLE
地图on,off方法监听和注销事件的问题

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#355]
测试代码如下:
     $("#clickEvent").click(function () {
                var clickHandle=function (e) {
                    console.log("地图被点击!");
                    //点击地图后注销事件
                    map.off("click", clickHandle);
                }
                //希望在重复点击多次按钮后把以前监听的事件注销掉，避免重复多次点击按钮造成回调函数多次调用
                map.off("click", clickHandle);
                map.on('click', clickHandle);
            });
发现注销事件无效，仍然会多次调用clickHandle方法

**Comment by fuzhenn** [comment]
无法重现, 帮忙给在codepen上一个重现代码

**Comment by liubgithub** [comment]
http://codepen.io/liubing1989/pen/WpevoV

**Comment by liubgithub** [comment]
单击按钮，然后点击地图，我在代码里面alert()了点击事件

**Comment by fuzhenn** [comment]
clickHandler的函数重复注册造成的, 并非引擎bug
