### ISSUE TITLE
服务查询

### ISSUE THREAD

**Issue by SimpleYong** [maptalks/maptalks.js#357]
你好：
比如查询一个数据上千的featurelayer服务，其中服务的数据包含了面的样式以及面上显示的label，MapTalks需要先去查询服务所包含的样式然后再查数据去匹配样式，花的时间过长；
我之前是做flex开发的，flex加载这样的地图只需要几行代码就可以解决(ArcGISDynamicMapServiceLayer)，不需要去做那么复杂的查询(本人是刚开始学习MapTalks的，可能有这样的方法我还没发现)。
Flex 加载图层代码示例：
```
var layer:ArcGISDynamicMapServiceLayer = new ArcGISDynamicMapServiceLayer();
layer.url=url;
layer.visibleLayers=new ArrayCollection([0]);
map.addLayer(layer);
```

**Comment by fuzhenn** [comment]
ArcGISDynamicMapServiceLayer 动态图层需要ArcGIS的Arc Server服务支撑, 但它的协议是闭源的, 所以maptalks或其他非ArcGIS前端库都不能直接调用.

有两个替代解决方案:

1. 因为数据只有上千, 量不大, 如果数据不会经常变化, 可以把它下载下来, 设置样式后以本地数据的形式直接用VectorLayer加载
2. 用我们的服务端产品mapresty, 也提供了同样的动态图层服务, 也只需要很少代码就可以实现ArcGISDynamicMapServiceLayer的功能

maptalks的mapresty客户端sdk:

https://github.com/maptalks/maptalks.mapresty.js/blob/master/src/layer/DynamicLayer.js

调用示例:
```javascript
var layer = maptalks.DynamicLayer('d', {
   mapdb : 'foo',
  layer : 'bar',
  style : ...
}).addTo(map);
```

**Comment by fuzhenn** [comment]
> 务支撑, 但它的协议是闭源的, 所以

看了一下[Leaflet-ESRI](https://github.com/Esri/esri-leaflet/)的源代码, ArcGISDynamicLayer并不是闭源的, 他们提供了ArcGISDynamicLayer的访问方法, 可以参考Leaflet-ESRI的实现给maptalks.js写一个插件来访问ArcGISDynamicLayer动态图层服务.

[DynamicMapLayer.js](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/DynamicMapLayer.js)

有兴趣试一下吗?
@SimpleYong @liubgithub
