### ISSUE TITLE
vector marker 增加编辑功能

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#37]
可以考虑为vector类型的marker增加真实的编辑功能。
进入编辑状态，在marker四周套个外接矩形，矩形四条边中点放置热点，拖动可以调整vector大小；
另：image类型的marker也可以考虑增加上述的功能。

**Comment by brucin** [comment]
vector marker已经验证通过。
不过image marker能否也增加一个拖动调整大小呢？

**Comment by FuZhenn** [comment]
我也考虑过, 但图片标注不像是矢量标注, 调整图片大小会带来图片不清晰的问题, 所以我觉得更应该鼓励直接修改图片本身大小来调整图表大小

**Comment by FuZhenn** [comment]
又想了想, 图片是否清晰应该是客户自己判断的问题. 那我把这个功能也加到image类型marke上
