### ISSUE TITLE
地图滑动过程中图形异常

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#39]
1、在svg绘制的情况下，如果地图滑动，图形会向滑动的方向移动；（拖动地图不会）
2、在canvas绘制的情况下，zoomIn/zoomOut 点图标会消失。
测试地址：
http://localhost:20000/examples/guide/tip_event.html

**Comment by brucin** [comment]
补充：问题2的也是在先滑动地图后，zoom才会触发。

**Comment by FuZhenn** [comment]
已经解决, 请验证

**Comment by brucin** [comment]
问题2依然存在，canvas中滑动地图，然后zoom，marker会消失，然后再次zoom才会出现。
测试地址：
http://localhost:20000/examples/editor.html?html=guide/geometry.html&title=Add%20Geometries
备注：代码中默认是render为svg。

**Comment by FuZhenn** [comment]
奇怪, 现在已经禁止滑动过程中zoom地图了

**Comment by brucin** [comment]
出现频率大概5次出现3次左右。

**Comment by FuZhenn** [comment]
重现了, 是vectorlayer读取图片资源的机制有问题, 有时候找不到marker 图片, 就画不出来了

**Comment by FuZhenn** [comment]
问题已经解决, 请验证
