### ISSUE TITLE
当map的container设置了padding-top属性时，mark的显示位置与click事件触发位置存在位移

### ISSUE THREAD

**Issue by gyd19940708** [maptalks/maptalks.js#398]
map的container<div id="Map">，设置了padding-top为100px；在map中加mark，显示位置正确，但是mark的click事件触发位置与显示位置相差了100px。

**Comment by fuzhenn** [comment]
这个bug已经在0.25.0中解决,可以从unpkg上下载
https://unpkg.com/maptalks/dist/

0.25.0有一些不兼容修改, 如果你用了插件的话, 插件也需要更新
