### ISSUE TITLE
control的id都注册在Control类上是否合理

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/MapTalks.js#4]
control通过id将引用注册在Control类上, 会造成页面有多个地图时, 相同id的control会覆盖彼此.

建议将control的注册放在Map对象中, 刚好control的addTo方法能获得Map对象引用

例如在Map对象中增加一个controls对象, 用同样的方法在controls上进行注册

**Comment by brucin** [comment]
解决了上述bug。
拓展了controls的结构，按map分开存放control。觉得增加control这样的插件就要污染map的代码不太好，所以control的事情都在control里面做，只是将map或者geometry作为可以创建control的参数来传递。

**Comment by FuZhenn** [comment]
是否可以考虑取消Z.Control上的getControl方法?直接在map上弄个object来管理应该就行了.

**Comment by brucin** [comment]
我觉得不好。

**Comment by brucin** [comment]
虽然我目前去掉了control的id，但是我还是觉得id是很有必要的。
因为拥有id最终用户将会省略掉很多遍历的代码。比如，用我们toolbar创建上下左右多侧的工具栏区域，在页面上增加数据区域（可利用panel），用户自然会在面板或者工具条上增加，打开关闭响应面板的按钮，在每次这样按钮事件背后，用户都需要去用map获取所有的controls，然后遍历找到对应的工具栏与面板，然后再调用show或者hide操作。这些代码相当的没有意义。
或许其它的GIS库没有这些工具，但是我所接触的工具组件都会为用户维护一个唯一标识，这样用户在使用组件的过程中，随时找到之前定义的组件，进行属性设置或者隐藏与关闭。

**Comment by brucin** [comment]
"control通过id将引用注册在Control类上, 会造成页面有多个地图时, 相同id的control会覆盖彼此."
而且我仔细测试了一下，我的id其实只是一个标签，并不会互相覆盖，即使是你构造了两个参数一模一样的control。你如果在真实的测试中发现互相覆盖的原因只是location设置的一模一样，然后两个control重合了而已。

**Comment by FuZhenn** [comment]
我觉得map上也不用提供control的遍历方法, 都留给用户自己来管理就好, 因为控件数量肯定不会太多, 这个维护不会复杂, 相信不会有技术人员会为这个问题感到困扰的.

**Comment by brucin** [comment]
你这个观点我只能持保留意见。
因为我参与的项目中控件的管理是一件挺麻烦的事情，所以如果可能越简单越好。
其实，大多数项目从后台取得数据很简单，大量工作都集中在控件的编写与控制上。

**Comment by FuZhenn** [comment]
因为地图库的控件不是重点, 大多数时候用户不会用我们的控件系统来做, 因为我们提供的控件样式和功能很难满足各种系统的要求.

所以一般来说用户都会用自己的控件来做, 只是让控件悬浮到地图上就ok.

地图库的控件永远不会, 也不应该做成很重量的东西, 也不应给用户这种印象.

类似yum里, 用到的各种悬浮控件面板都不适用地图库做的

**Comment by FuZhenn** [comment]
其实如果要做出一套功能很强大, 很好用的地图控件库, 现在这个Control类是远远不能满足的. 要好好的重新规划才可以

**Comment by brucin** [comment]
我会关闭这个问题。目前的就按照你的做，panel与toolbar我都会移除掉。
然后另外做一套插件。你可能不太清楚，项目开发中这些东西。市面上各种grid组件与tree的确有很多，但是自己做套件不是不可以，但是会花费很多时间。
