### ISSUE TITLE
关于两个或者多个polygon相交，去除相交的部分形成一个polygon

### ISSUE THREAD

**Issue by SimpleYong** [maptalks/maptalks.js#410]
之前请教过刘兵，他给了一个插件turf.js，有个方法可以去除相交的部分，但是好像只能去除两个polygon相交的部分(不知道是不是我使用有误)，但是如果有更多的polygon要去计算，就不是很方便了，大哥你有什么好方法发吗(〃'▽'〃)

**Comment by fuzhenn** [comment]
一般多个多边形的相交, 应能通过循环, 转化为多次的两个多边形相交来解决吧.

虽然麻烦, 但多个多边形相互关系一般也没什么简单的办法.

**Comment by SimpleYong** [comment]
嗯呢，蟹蟹~~
