### ISSUE TITLE
给tile加一个天地图的经纬度平面投影坐标系的配置吧

### ISSUE THREAD

**Issue by signhuwei** [maptalks/maptalks.js#447]
https://github.com/maptalks/maptalks.js/blob/master/src/layer/tile/tileinfo/TileSystem.js#L93

//天地图经纬度投影采用的瓦片系统
'tdt-w' : new TileSystem([1, -1, -180, 90])

**Comment by fuzhenn** [comment]
可以这么定义
```javascript
maptalks.TileSystem['tdt-w'] = [1, -1, -180, 90];
```
之后tileLayer就能用'tdt-w'了
```
new maptalks.TileLayer('t', {
    tileSystem : 'tdt-w',
   urlTemplate : ...
});
```

天地图不是标准TileSystem, 所以就不加入maptalks.js核心了
