### ISSUE TITLE
ie9 下canvas中文本标签拖动问题

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#45]
如题，无法激活拖动状态。
测试地址：
http://localhost:20000/examples/geometry/marker/label_marker.html

**Comment by brucin** [comment]
补充：线与面在ie9下canvas中也无法拖动。

**Comment by FuZhenn** [comment]
因为canvas图形的事件机制问题, 拖动经常出现响应不到图形的mouseup事件的问题, 所以需要把Geometry.Drag再做一下研究.
以下问题也都和此有关.
#44 
#42

**Comment by brucin** [comment]
问题同#50，而后者包含更广泛，先关闭这个。
