### ISSUE TITLE
关于CurveLine的一些bug

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#46]
1，arrow方向不太正确；
2，截图中arrow没有出现。

**Comment by FuZhenn** [comment]
arrow方向问题目前还无法解决, 因为arrow方向都是由连线方向计算得出, 而曲线需要计算曲线切线方向才会比较准确, 

我有时间的话看看有没有比较简单的方法

**Comment by fuzhenn** [comment]
曲线自动计算角度难度较大, 不再实现.
marker中增加了markerRotation, 可通过markerRotation来手动设置旋转角度
