### ISSUE TITLE
updates TextBox and Label

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#462]
@brucin 
根据之前的讨论, 以下是我对TextBox和Label初步的调整方案, 有什么我考虑不周全的地方, 随时讨论:
## TextBox 和 Label 的区别
* TextBox中文字以box为文字对齐基准, label以坐标为文字对齐基准
* TextBox必须有box, 而label可选
* (?)TextBox没有autoSizeBox, 反而可以考虑自动缩减文字以适应TextBox
* Label需要提供autoSizeBox方法, 并自动更新symbol

### TextBox
* 取消options中的box相关设置
* 构造方法增加TextBox高和宽
```javascript
new maptalks.TextBox(content, width, height, options):
```
* 增加设置文字对齐方法
```javascript
textBox.setTextVerticalAlignment('top') // top, middle, bottom
    .setTextHorizontalAlignment('right'); // left, middle, right
```
* 增加设置高宽的方法
```javascript
var width = textBox.getWidth(),
    height = textBox.getHeight();
textBox.setWidth(width + 10)
    .setHeight(height - 2);
```
* 增加缩减字符串的方法
```javascript
textBox.trimText('..'); //将超长的字符串用..代替
```

### Label
* Label取消options中的box相关设置
* 增加autoSizeBox方法
```js
//动态调整markerWidth, markerHeight, markerDx和markerDy, 以自动适应文字
label.autoSizeBox({
   'minHeight' : 20,
   'minWidth' : 100
});
```

**Comment by brucin** [comment]
1、在将textBox的文本对齐方式变为：textBox.setTextVerticalAlignment(...)以后，Label与TextBox可以统一了，根据坐标调整的通过symbol去设置，针对文本的对齐通过上面的方法去调整；

2、autoSizeBox是针对box的设定，对于text与box的高与宽的变化，其实存在两种场景：其一，文本变化（编辑或赋值）；其二，box变化。这两种场景下，存在另一方是否去适配对方新的大小的情况。
目前boxAutoSize属性实现了，box跟随text变化而变化，box编辑过程中的重置textWrapWidth并不能影响到text的重新布局，但是这两者不能共存，所以是否通过设置一个属性比如{'autoSize':'text/box'}，来决定调整以谁为主导；

3、在box编辑的情况下，需要fitSize以适配新的box的width与height，可以统一一autoSizeBox(...)，这个方法是根据文本来调整box的大小，在box存在的场景下，背景比文字区域小的场景都意义都是不大的，但是针对box的缩小调整，其实应该影响到text的textWrapWidth，这个应该可以通过上面textBox.setWidth/setHeight来实现，不过这个设置与textWrapWidth的是否需要配合就与上面第二点有些关联了；

4、自动缩减文字这个方法很有价值，它的使用场景是希望文本不要超出box，在实际场景中更应该是根据box的高宽自动去截取，这个方法应该可以配合autoSize:'box'来用；

5、box的padding的作用还是有的，所以如果取消了，势必需要一个类似的设置；

6、textMarker、Label、textBox的旋转功能。

**Comment by fuzhenn** [comment]
我觉得TextBox和Label还是需要分开
* Label可以取消编辑(box的高宽是根据text的高宽自适应的, 编辑无意义)
* TextBox和普通marker一样可以编辑

可以考虑给Label和TextBox添加auto option, 用来自动设置box和文字
*  Label.options.auto: 调整content或symbol时, 根据文字自动调整box
* TextBox.options.auto : 调整TextBox的width/height时, 根据box自动调整文字, 包括自动调整TextWrapWidth和缩减字符

最后, 旋转功能已经有了, symbol中:
```javascript
{
  textRotation :  60
}
```

**Comment by fuzhenn** [comment]
# Label

```javascript
//自动调整markerWidth与markerHeight以适应文字高宽
let label = new Label('hello label', {
  padding : [2, 3],
  boxVerticalAlignment : 'middle',
  boxHorizontalAlignment : 'middle',
  symbol : {
  ...
  }
});

label.setBoxVerticalAlignment('top');
label.setBoxHorizontalAlignment('left');

// 自动调整textWrapWidth和缩减文字, 以自动适应box
let textBox = new TextBox('hello textbox', 100, 50, {
  padding : [2, 3],
  textVerticalAlignment : 'middle',       // 默认垂直居中
  textHorizontalAlignment : 'middle',  // 默认水平居中
  symbol : {
  }
});

textBox.getWidth()/setWidth()/getHeight()/setHeight()

textBox.setTextVerticalAlignment('top'); //默认是middle
textBox.setTextHorizontalAlignment('left'); //默认是middle

textBox.getPadding()/setPadding([3, 4]);
```

**Comment by fuzhenn** [comment]
具体实现的时候发现, 方法分的太细还是太累赘, 所以改成了下面的形式.

API方案:

# Label

```javascript
//自动调整markerWidth与markerHeight以适应文字高宽
let label = new Label('hello label', coord, {
  boxStyle : {
      padding : [2, 3],
      verticalAlignment : 'middle',
      horizontalAlignment : 'middle',
      symbol : { .. }
  },
  textSymbol : {
   //文字样式
   ...
  }
});

label.setBoxStyle({
  padding : [12, 8],
  verticalAlignment : 'top',
  horizontalAlignment : 'middle',
  symbol : { .. }
});
```

# TextBox
```javascript
// 自动调整textWrapWidth和缩减文字, 以自动适应box
let textBox = new TextBox('hello textbox', 100, 50, {
  textStyle :  {
     padding : [2, 3],
     verticalAlignment : 'middle',       // 默认垂直居中
     horizontalAlignment : 'middle',  // 默认水平居中
     symbol : { .. }
  },
  boxSymbol : {...}
});

textBox.setTextStyle({
     padding : [12, 8],
     verticalAlignment : 'middle',       // 默认垂直居中
     horizontalAlignment : 'middle',  // 默认水平居中
     symbol : { .. }
});

textBox.startEdit();
```

**Comment by gee1k** [comment]
ConnectorLine 连接线的文字内容能否添加背景框
