### ISSUE TITLE
Auto-fit drop menu to the edge of toolbar control

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#470]
Current:

![tim 20170725155704](https://user-images.githubusercontent.com/13678919/28561700-f9a43f9e-7151-11e7-880b-78064a35db9b.png)

Expected:

![tim 20170725155658](https://user-images.githubusercontent.com/13678919/28561710-034d9b94-7152-11e7-9671-a39ca431540e.png)

**Comment by 1dent1ty** [comment]
下一步还应该实现对二级菜单的支持

**Comment by fuzhenn** [comment]
close via 
#473
