### ISSUE TITLE
盾标若干问题

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#49]
1、canvas中盾标不显示；
2、svg中盾标无法拖动。
测试地址：
http://localhost:20000/examples/editor.html?html=geometry/marker/shield_marker.html&title=Add%20Shield%20To%20Geometry

**Comment by FuZhenn** [comment]
该问题已经重现, 是因为本次更新增加了Point内坐标不能为NaN的判断, 而以前的计算是错误的, 所以会抛出异常中止绘制.
