### ISSUE TITLE
关于Polygon的getCenter()方法获取的中心点坐标超出多边形区域

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [maptalks/maptalks.js#490]
我们在做项目的时候时常要用过获取多边形的中心点，然而当多边形是凹凸状或者分散状的话，获取的中心点就会超出几何边界

**Comment by fuzhenn** [comment]
绘制时的中心点意义与几何中心点(重心)是不一样的

**Comment by Liquid-Zhangliquan** [comment]
感谢镇哥提醒，后面引用了第三方插件库turf.js取几何的质心点作为中心点效果还不错[http://turfjs.org/docs/#centerofmass](url)；
