### ISSUE TITLE
ie9下canvas中图形无法拖动

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#50]
如题，测试地址：
http://10.211.55.2:20000/examples/editor.html?html=geometry/polygon/polygon.html&title=Add Polyline

**Comment by brucin** [comment]
IE9下canvas中拖动的确正常了，但是chrome中canvas绘制的图形无法拖动了。

**Comment by FuZhenn** [comment]
已经改好, ie9和其他的浏览器对事件监听机制不同造成的, 对ie9做了一下特殊处理, 分别监听不同的容器.

**Comment by FuZhenn** [comment]
ie9监听不同的容器可能会导致其他的bug, 例如有svg图形存在的时候, ie9可能就无法响应到其他事件.

所以建议那个全图形测试demo里, 把svg和canvas图层都加上去, 这样测试的全面一些.
@brucin
