### ISSUE TITLE
InfoWindow在mouseover和mouseout鼠标事件下，无法正常显示/隐藏的问题

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#503]
如题：
BUG重现如下：http://139.159.219.234/maptalksdemo/dist/geo_examples/infowindow.html

**Comment by fuzhenn** [comment]
哪里不正常? 我这里显示是正常的呢

**Comment by fuzhenn** [comment]
infowindow显示无动画是正常的
因为mouseover事件会不停的被调用, 所以infowindow会不停的调用show方法, 此时就没有动画了

我在0.30中新增了mouseenter事件, 这个事件只在第一次进入geometry时才会调用
改为监听mouseenter事件即可
