### ISSUE TITLE
地图tile出现大概一个像素的错位

### ISSUE THREAD

**Issue by signhuwei** [maptalks/maptalks.js#511]
在tile加载完成后底图上的文字可以看到明显的虚影，
并且似乎就在天地图tile上表现的特别明显

var mapObj = new maptalks.Map('tdtmap',{
                center:{x:121.433184,y:28.670308},
                zoom: 17,
                minZoom: 5,
                maxZoom: 19,
                view:{  projection: 'EPSG:4326'  },
            });
mapObj.setBaseLayer(new maptalks.TileLayer('tdt-w', {
                        tileSystem: [1, -1, -180, 90],
                        urlTemplate:'http://tmap.tzsjs.gov.cn/services/wmts/tzemap?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=tzemap&STYLE=default&TILEMATRIXSET=esritilematirx&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image%2Fpng'                        }));
mapObj.addLayer(new maptalks.TileLayer('zjtdt',{
                        tileSystem: [1, -1, -180, 90],
                        urlTemplate:'http://ditu.zj.cn/services/wmts/zjemap?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=UNTMZJEMAP&STYLE=default&TILEMATRIXSET=nativeTileMatrixSet&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image%2Fpng'
}));

**Comment by fuzhenn** [comment]
之前的版本确实有这个问题, 是因为绘制瓦片时, 像素坐标没有取整造成的.

0.30把这个问题解决了(目前master上的版本, 还没有发布)

有没有截图? 我确认一下

**Comment by signhuwei** [comment]
![image](https://user-images.githubusercontent.com/9034260/31001901-adc71758-a519-11e7-9e2f-81d46bf49146.png)

**Comment by fuzhenn** [comment]
0.30上的文字:
![image](https://user-images.githubusercontent.com/13678919/31003505-a0f8c6a8-a522-11e7-989e-1c6c3ff8f2d4.png)

天地图官网:
![image](https://user-images.githubusercontent.com/13678919/31003553-e832ad9a-a522-11e7-930d-a31b15f5b264.png)

应该是一致的
如果0.30更新了还是有问题, 那就是天地图本身文字渲染的问题了

**Comment by fuzhenn** [comment]
v0.30.0已经发布
另外上线了新版的demo
http://maptalks.github.io/examples/cn/map/load/#map_load

**Comment by signhuwei** [comment]
嗯，更新后就👌了
