### ISSUE TITLE
MultiPoint会将放入其中的Marker symbol变成默认样式

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#52]
如图。

**Comment by FuZhenn** [comment]
你提的这个问题和我们的设计有关, 按照GeoJSON规范, GeometryCollection中的Geometry只是单纯的Geometry(GeoJSON中的Geometry, maptalks的Geometry对应的是GeoJSON中的feature).

所以加入到GeometryCollection中的Geometry不应该再有样式和其他属性的, 都应以Collection的为准.按照这一原则, 我们目前的实现是子Geometry的symbol会被父collection的symbol覆盖(用来构造painter), 输出json的时候, 子Geometry的symbol不会被输出. 

如果需要子Geometry的symbol也保持独立, 有一个比较麻烦的问题是GeometryCollection的GeoJson表达需要把子Geometry的symbol也都包含进去, 这个会影响snap和dynmiac等模块功能.

如果觉得symbol保持独立很重要, 可以研究下有没有更好的实现方案.

参考:

http://geojson.org/geojson-spec.html#geometrycollection

**Comment by brucin** [comment]
我赞同GeoJSON中规范的定义。Multi-Geometry的确应该有一致的symbol。
不过，你目前的实现中MultiPoint的确会采用父的symbol，但GeometryCollection并不会覆盖子Geometry的symbol。所以，label我又换回了GeometryCollection，其保留了vector与text 的symbol。

**Comment by FuZhenn** [comment]
现在如果对GeometryCollection做setSymbol操作, 子Geometry的symbol都会被覆盖, 但构造函数里确实没有.

这个问题之前没有认真对待过, 所以各种混乱.

不过对Label来说, 每个Marker都必须有自己的symbol才能实现, 这个得想想看怎么处理比较恰当.
