### ISSUE TITLE
有两个地图div的情况下，地图的显示需要鼠标交互下才能显示

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#520]
> maptalks's version and what browser you use?

0.31.0-alpha.1

> Description

有两个地图div容器,mapA,mapB,通过display样式来做显隐，当隐藏mapA,显示mapB的时候，mapB需要拖动下地图或者缩放一下才能显示，以前版本没这个问题

> Please provide a reproduction Url (on any jsfiddle like site)

http://139.159.219.234/maptalksdemo/dist/geo_examples/%E4%B8%A4%E4%B8%AA%E5%9C%B0%E5%9B%BE%E7%9A%84%E6%83%85%E5%86%B5.html

**Comment by fuzhenn** [comment]
seems it's fixed in 0.31.0
