### ISSUE TITLE
图像信息框可否不需要绑定点击事件 才能打开信息框 比如像leaflet 那样 设置气泡框之后 点击图标可以直接打开

### ISSUE THREAD

**Issue by shanyipeng** [maptalks/maptalks.js#525]
**maptalks's version and what browser you use?**

**Issue description**

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
目前还不行, 但你的建议可以考虑

如果点击图标能自动打开信息框, 可能会与图标本身的click事件冲突

所以我想可以仿照之前的`autoCloseOn`, 增加一个`openOn` options, 默认值是click

如果不需要自动打开, 把`openOn`设置成null

你看如何?

**Comment by shanyipeng** [comment]
可以这样！！

**Comment by fuzhenn** [comment]
👍 会在0.33中实现

**Comment by fuzhenn** [comment]
@shanyipeng 
已经完成并发布(v0.33.0)

相关示例:
https://maptalks.org/examples/cn/ui-control/ui-map-infownd/#ui-control_ui-map-infownd
https://maptalks.org/examples/cn/ui-control/ui-geo-infownd/#ui-control_ui-geo-infownd

**Comment by liubgithub** [comment]
提个建议，点击点类型要素的时候，信息框的锚点仍然是点的坐标，线和面的话锚点用鼠标点坐标

**Comment by fuzhenn** [comment]
@liubgithub 有道理, 我会改一下

**Comment by fuzhenn** [comment]
@liubgithub 已经改好发布了, v0.33.1
