### ISSUE TITLE
fpsOnInteracting = 0 导致的流畅问题

### ISSUE THREAD

**Issue by zzcyrus** [maptalks/maptalks.js#526]
因为是国人开发，就用中文啦，希望作者别介意 ：）

0.32版本中 b2f775c

设置 fpsOnInteracting = 0 ，（不是很清楚这里的目的）

但是这会导致一些继承CanvasRenderer的图层，缩放时多次刷新，严重影响了绘制的效率。

可以在插件heatmap中重现，所以就不放jsfiddle了。

**Comment by fuzhenn** [comment]
之前fps设得比较高, 一些example会出现空白问题,  当时想着用户自己把`fpsOnInteracting`设置为合适的值, 就没有做限制了
你这么一说, 确实还是应该设置一个适用于80%情况的值, 不应该让用户来动这个脑筋.

我来改一下, 等会发个fix版

**Comment by fuzhenn** [comment]
fpsOnInteracting重新改为了25
已经发布为0.32.4
