### ISSUE TITLE
IS_NODE的判断还不充分啊

### ISSUE THREAD

**Issue by signhuwei** [maptalks/maptalks.js#529]
[nw](https://nwjs.io)跟electron一样也是一个rich node client collection

**maptalks's version and what browser you use?**

**Issue description**

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
yes!

有兴趣提个pull request吗?

**Comment by signhuwei** [comment]
ok

**Comment by fuzhenn** [comment]
fixed in #530
