### ISSUE TITLE
MultiPoint相关问题

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#53]
1、MultiPoint中的marker在svg中会绘制在同一个点上；
2、拖动的时候，有时候激活多个点一起移动，有时只有一个点移动。
测试地址：
http://localhost:20000/examples/geometry/geometry.html

**Comment by FuZhenn** [comment]
geometry.html没有提交, 请提交一下

**Comment by brucin** [comment]
问题补充：在multi-geometry中设置的symbol只有最后一个geometry生效。
