### ISSUE TITLE
multiple bindings in forEach

### ISSUE THREAD

**Issue by Henry-xiaofengChen** [maptalks/maptalks.js#533]
在使用forEach时，如果有多个元素做forEach，如
在layer里画若干个点
```js
layer.forEach(function(g) {
    g.on('click', function(e) {
        console.log('test')
    }).
});
```

预期的结果应该是layer里的每一个点都被绑定了一个点击事件，点击一下打印test。
而在编写中发现有时会出现多重绑定的时间，比如layer里有三个对象，那forEach之后点击一下其中一个元素会打印三次。
**并非每次都会出现这个问题，但是出现的次数不少**

**Comment by fuzhenn** [comment]
收到, 我会试着重现一下

**Comment by fuzhenn** [comment]
@Henry-xiaofengChen 这个bug我这里重现不出来, 我审核了一下代码, 也没看出可能的原因. 

能不能麻烦你帮忙试着重现一下?

我写的重现代码(你可以在此基础上修改):
https://jsfiddle.net/75bsnqar/1/

forEach方法的源代码:
https://github.com/maptalks/maptalks.js/blob/master/src/layer/OverlayLayer.js#L137

**Comment by Henry-xiaofengChen** [comment]
我也暂时重现不了，尝试着玩没做版本管理回不去了，那就先关了吧再遇到了再说

**Comment by Henry-xiaofengChen** [comment]
@fuzhenn 我知道了是右键的问题 就你的重现代码改成on contextmenu试试
（写到这里我在怀疑是我的鼠标坏了）

**Comment by fuzhenn** [comment]
重现了 👌 
感谢发现一个新的bug, 很开心, 哈哈
