### ISSUE TITLE
capricious InfoWindow

### ISSUE THREAD

**Issue by Henry-xiaofengChen** [maptalks/maptalks.js#534]
参照examples里的《9.6自定义信息框》
>map.on('click', function (e) {
    infoWindow.show(e.coordinate);
})

我发现即使不绑定点击事件（也就是说我不想通过点击的方式唤出信息框），InfoWindow也会随click出现
>map.on('click', function (e) {
    //infoWindow.show(e.coordinate);
})

或者我绑定其他的方法，InfoWindow依然会随click出现
>//map.on('click', function (e) {
    //infoWindow.show(e.coordinate);
//})
map.on('contextmenu', function (e) {
    infoWindow.show(e.coordinate);
})

**Comment by fuzhenn** [comment]
这不是个bug, 是个feature

具体可以参考 #525 中的讨论

如果要取消默认的事件绑定, 创建InfoWindow时把autoOpenOn设成null就行了

**Comment by fuzhenn** [comment]
[9.6示例](http://maptalks.org/examples/cn/ui-control/ui-custom-infownd/)里还是老代码, 刚改了一下, 去掉了事件响应逻辑

**Comment by fuzhenn** [comment]
如果要绑定多个事件来打开信息框, 可以这么写
```js
var options = {
        'autoOpenOn' : 'click contextmenu',
        'title'     : 'Map\' InfoWindow',
        'content'   : 'Click on map to reopen'

        // 'autoPan': true,
        // 'width': 300,
        // 'minHeight': 120,
        // 'custom': false,
        //'autoCloseOn' : 'click'
      };
      var infoWindow = new maptalks.ui.InfoWindow(options);
```

**Comment by Henry-xiaofengChen** [comment]
谢谢，顺便一提，examples在上周通过https访问正常，在这周https访问地图加载不到，http正常
