### ISSUE TITLE
Label-symbol will be reset after label.startEditText()

### ISSUE THREAD

**Issue by Henry-xiaofengChen** [maptalks/maptalks.js#535]
在新建一个label的时候预设了颜色和文字大小等值，通过某些操作触发updateSymbol，然后再触发startEditText后，Symbol会回到初始预设值
>var label = new maptalks.Label('label with box',
		map.getCenter().add(0, 0.01), {
			'textSymbol': {
				'textFill': '#999',
				'textSize': 20
			}
		}).on('click', function(e) {
		e.target.startEditText();
	}).on('mouseenter', function(e) {
		e.target.updateSymbol({
			'textSize': e.target.getSymbol().textSize + 1,
			'textFill': '#304050'
		})
	}).addTo(layer)

当然这个好解决，就是想问下这是BUG还是怎么考虑的

**Comment by fuzhenn** [comment]
这个不是bug，label和textbox这两个Geometry比较特殊, 它们的symbol是根据options里的设置自动生成的, 所以不应该用updateSymbol/setSymbol来更新样式(更新后只是暂时的)

为什么symbol会自动生成? 例如在options中自动设置或更新textVerticalAlignment后, label/textbox会自动计算textDx, textDy等相关属性, 并更新到symbol, 来对齐文字.

具体可以看一下[example里地图下方的文字说明](http://maptalks.org/examples/cn/geometry/label/#geometry_label)

在你的代码里把`updateSymbol`改成`setTextSymbol`应该就可以了.
