### ISSUE TITLE
在IE下，map.setCursor方法只支持.cur，不支持.png文件嘛

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#537]
**maptalks's version and what browser you use?**
0.33.1

**Issue description**
在IE下，map.setCursor方法对.png文件设置鼠标样式无效，chrome下没问题

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
It looks like an IE bug..

**Comment by liubgithub** [comment]
OK
