### ISSUE TITLE
InfoWindow's position not changing while hovering multiple polygons

### ISSUE THREAD

**Issue by s9eenk** [maptalks/maptalks.js#538]
Using version 0.33.1 . 

I have created multiple polygons and set an (on mouseover and mouseout) events.
The issue is that when hovering on another polygon, the InfoWindow position stays on the first polygon only.

**Comment by fuzhenn** [comment]
Thanks for reporting issue!

I have tried to reproduce the issue but failed.   Could you provide one for me?

The jsfiddle I created is as bellow, you can write your own upon it.

http://jsfiddle.net/c4nyoLjz/

**Comment by fuzhenn** [comment]
closing.

will reopen if necessary.

**Comment by s9eenk** [comment]
Thanks Fuzhenn . One more thing, want to close the infoWindow while dragging the map. How to make it ?. The problem persists when the mouse jumps over the infoWindow while dragging. Is there like "map.on('dragend',func(){})"

**Comment by fuzhenn** [comment]
Hi again

You can try to set a option 'autoCloseOn' in infoWindow's options. InfoWindow will close itself when map throws events set in 'autoCloseOn'

```javascript
p.setInfoWindow({
  'autoCloseOn' : 'mousedown movestart zoomstart',
  'title'     : 'Marker\'s InfoWindow',
  'content'   : 'Click on marker to open.'
});
```
jsfiddle:
http://jsfiddle.net/c4nyoLjz/1/

and map doesn't have 'dragstart' event, but have 'movestart' event

**Comment by s9eenk** [comment]
Does this API have layer list control ?. If not please provide an example for switching layers in layer list control.

**Comment by fuzhenn** [comment]
no.. it doesn't have layer control in default. 
Another maptalker @1dent1ty implemented one, I'll ask him whether he can share it with us.
If he can, I'll add an example in [examples](http://maptalks.org/examples/en/map/load/)

**Comment by fuzhenn** [comment]
@s9eenk , there is a same request in #544 , we decide to bring layer list (layer switcher) control on board. Scheduled for v0.35.0 (should be released in the next week)

cc @1dent1ty

**Comment by fuzhenn** [comment]
@s9eenk  v0.35.1 is published with LayerSwitcher, example:
http://maptalks.org/examples/en/ui-control/control-layer-switcher/#ui-control_control-layer-switcher

**Comment by s9eenk** [comment]
@fuzhenn  . It would be a nice addition if you could develop an example on the aspect of 3D terrain. Please find the figure as attached.
![3d terrrain](https://user-images.githubusercontent.com/23517231/33255268-c58d68ba-d372-11e7-82b5-e97ea11d6d8c.png)

**Comment by fuzhenn** [comment]
3D terran is on the plan, please just keep track of us. 🤓
