### ISSUE TITLE
Tiles blinks when pitching or rotating at large zoom

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#540]
**maptalks's version and what browser you use?**
v0.34.0

**Issue description**
reported by @char-ten, tiles blink when pitching or rotating at large zoom. Some tiles go blank at certain bearing/pitch.

When zooming out to smaller zooms, the blinks disappeared. It should be related with map's perspective camera's near/far parameters.

**Please provide a reproduction URL (on any jsfiddle like site)**
https://char-ten.github.io/demo/maptalk/

open it in mobile browsers

**Comment by Char-Ten** [comment]
thanks.

**Comment by fuzhenn** [comment]
resolved, will be released with v0.35.0
