### ISSUE TITLE
IE's background color  always are black

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#541]
**maptalks's version and what browser you use?**
0.33.1
**Issue description**
IE's background color  always are black

**Please provide a reproduction URL (on any jsfiddle like site)**
http://139.159.219.234/maptalksdemo/dist/geo_examples/%E6%8A%95%E5%BD%B1%E5%9D%90%E6%A0%87%E5%9C%B0%E5%9B%BE.html

**Comment by liubgithub** [comment]
There are still problems, map's background color is still black.

**Comment by fuzhenn** [comment]
version? @liubgithub
