### ISSUE TITLE
Marker锚点位置默认在中下方，希望可以有参数设置为中心点

### ISSUE THREAD

**Issue by 520ph** [maptalks/maptalks.js#542]
maptalks.js版本：`0.34.0  `       Chrome浏览器版本：`62.0.3202.94`

Marker锚点位置默认在中下方，希望可以有参数设置为中心点。

重现地址：
[Marker锚点位置](http://jsfiddle.net/520ph/1dbcexax/)

**Comment by fuzhenn** [comment]
可以考虑和text统一， 增加两个新的symbol属性：
```javascript
'markerHorizontalAlignment' : 'middle', //left | middle | right
'markerVerticalAlignment' : 'bottom'     // top | middle | bottom
```

你觉得如何？

**Comment by 520ph** [comment]
这个可以有

**Comment by fuzhenn** [comment]
🆗  scheduled for v0.35.0

**Comment by fuzhenn** [comment]
resolved in commit mentioned above，will be released with v0.35.0

**Comment by fuzhenn** [comment]
@520ph, 0.35.1版已经发布，这两个symbol属性已经添加，参考示例：
http://maptalks.org/examples/cn/style/marker-alignment/
