### ISSUE TITLE
SVG marker doesn't show when loaded on FireFox

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#543]
**maptalks's version and what browser you use?**
v0.34.0, Firefox v58

**Issue description**
SVG marker doesn't show when loaded on FireFox. But it will show once map is redrawed (dragged or zoomed).

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by Wujidadi** [comment]
2020-03-28 當前最新版的的 Firefox（74.0）仍有此問題
因為個人最近才重新開始用 Firefox，不知道這問題是從哪一個版本開始又出現的
