### ISSUE TITLE
Is there control to switch base layers?

### ISSUE THREAD

**Issue by aleung** [maptalks/maptalks.js#544]
It's common to provide more then one base maps and let user to choose.

Like Leaflet's layers control:
http://leafletjs.com/reference-1.2.0.html#control-layers

**Comment by fuzhenn** [comment]
HI!
No now, but since many ppl have requested this feature, I would like to implement one in the next release v0.35.0.

**Comment by fuzhenn** [comment]
close by #547 and https://github.com/maptalks/maptalks.js/commit/3a4905f9edda2e225ca4d687e88ee764b4aa273e, thanks @1dent1ty

**Comment by fuzhenn** [comment]
@aleung v0.35.1 is published with LayerSwitcher, example:
http://maptalks.org/examples/en/ui-control/control-layer-switcher/#ui-control_control-layer-switcher
