### ISSUE TITLE
Label存在的若干问题

### ISSUE THREAD

**Issue by brucin** [MapTalks/maptalks.js#55]
1、仅仅是需要标注一段说明文字，用户能直接获取的就是坐标，为了构造label需要构造marker，并设置为透明，不合理；
2、当用户利用label做信息说明（与任何geometry无关），在觉得label位置不合适的时候，拖动label，因为之前需要构造marker，连线的存在也是不合理的；
3、label上需要事件，以便于用户进行交互设置。
事件交互测试地址：
http://localhost:20000/examples/toolbox/label/label.html

**Comment by FuZhenn** [comment]
to 1&2: 这个问题我也考虑过, 但发现如果只是需要在地图上标注文字并可以拖动, 不需要用label, 一个普通的marker就够了, 
而用label实现, label必须要像个marker一样addTo到map上或者layer上, 而功能和文字类型marker一模一样, 感觉会不会精简一点更好些?

**Comment by brucin** [comment]
因为在用户在利用我们接口开发label功能的时候，我们已经提供了label，却需要用户去实现两种不同的方式去实现label，而你目前实现的方式也就是一个marker。用户需要实现的代码逻辑与我们也是一致，这也是典型的我们实现一次，永久造福用户的行为。所以，我认为这个应该我们来统一。

**Comment by brucin** [comment]
补充一个例子：就以我之前实现的那个example来说明，我那个例子中是需要对label进行编辑的，例子中可以直接标注与绑定geometry标注label，如果要两种方式实现label，编辑的绑定方式与触发都需要分别来写，而且，修改以后，设置新的参数的方式也是不同的。

**Comment by FuZhenn** [comment]
我以前理解错了, 以为label只是geometry的一个属性, 这样看起来, 其实label是一个加强版的marker.

我仔细想了想, 查了一下其他库的类似实现, 我觉得label其实是个不好的设计:
1. 在geojson中不被支持
2. 在cartoCSS中不被支持
3. 为profile增加复杂度: 需要增加label的处理和事件响应.
4. snap和dynamic都需要单独处理

我有个想法, 你看看是否合理, 我们可以考虑取消label, 在marker上增加新的API接口来代替现有的label功能.

而总结下对label的设计:
1. 如果target是一个坐标, label就完完全全是一个marker
2. 如果target是geometry, 其实是把geometry的center当成了label的target
label实质上只是一个能绑定某个位置, 编辑dx和dy时出现linker线的加强版marker.

不知道以上看法有没有哪里漏掉的.

**Comment by brucin** [comment]
你最终的结构形式我是赞同的。其实在重构svg与canvas之前与第一版本来也是将label作为一个marker去实现的。而且，在之前那版label中，label.addTo(layer)也是将其作为geometry的表现，其实我更加愿意的是layer.addGeometry(label)来统一这个行为，但是考虑这样会破坏整个结构，所以才等而下之。就目前的实现来说，将label直接放在与其关联的geometry的layer也是不合理的，这两者的显示与隐藏，以及层级都是需要单独处理的。

下面将我能考虑到的关于geometry与label（我暂时还将其叫做label）相关的增强以及marker本身应该可能存在的使用都罗列一下，可以讨论是作为插件，还是在原有的类上增加api.
1、label是需要编辑的，除了setSymbol与setContent以外，最符合操作习惯的是目前marker的拉动调整；
2、label的形式，目前是vector + text，但是这明显不能完整表达label对形状的需求，这里有两种扩展方式：
     A、增加更多的vector形式；
     B、image+text。我个人是倾向于后者的，但是如果是后者是否就更加接近shield marker呢？
3、label的方向调整；
4、其它不规则的矢量图形的标注，同时在这些矢量图形中的文本标注（2.B），比如行军路线的箭头图形；
5、polyline的端点图形，是类似之前label一样利用geometryCollection包装多个geometry作为pulgin存在，还是扩展polyline 增加api。

**Comment by FuZhenn** [comment]
这些功能都很必要！
不过有些功能现在已经能实现，比如线上的各种文字标注;在线的端点加载图片标注。有些有点超出label范畴了，比如线的末端箭头。
我觉得这些功能同样可以考虑通过增强各geometry来实现。
我查了一下各个地图库，label只有百度地图有，leaflet有个插件，本身确实不是个标准的东东，所以大部分开源库都不支持。所以去掉的话在用户体验和设计上不会有太大问题

**Comment by FuZhenn** [comment]
上述功能的实现方案:
1、label是需要编辑的，除了setSymbol与setContent以外，最符合操作习惯的是目前marker的拉动调整；
**marker本身功能**
2、label的形式，目前是vector + text，但是这明显不能完整表达label对形状的需求，这里有两种扩展方式：
A、增加更多的vector形式；
**扩展VectorMarkerSymbolizer上的markerType实现**
B、image+text。我个人是倾向于后者的，但是如果是后者是否就更加接近shield marker呢？
**用Shield Marker就能实现**
3、label的方向调整；
**可以拓展marker, 实现marker的旋转**
4、其它不规则的矢量图形的标注，同时在这些矢量图形中的文本标注（2.B），比如行军路线的箭头图形；
**同2.A**
5、polyline的端点图形，是类似之前label一样利用geometryCollection包装多个geometry作为pulgin存在，还是扩展polyline 增加api。
**该功能已经实现,在polyline的symbol中定义marker样式, 然后把placement设成vertex即可**

**Comment by brucin** [comment]
以上的实现方案，我觉得可以。不过需要写demo去验证。
关于2.A：为何不能使用2.B 中vector image+text的方式？这样不是就可以让用户自行配置vector图形库了嘛。而且这里的需求是不固定的。
关于5：对于加了端点的polyline的编辑，比如调整lineWidth或者color，端点的图形会否一起refresh？
