### ISSUE TITLE
插件打包问题

### ISSUE THREAD

**Issue by axmand** [maptalks/maptalks.js#550]
-maptalks v0.3.4
-arcgis javascript api v4.5.0

[maptalks.arcgis插件](https://github.com/axmand/maptalks.arcgis/blob/43dd63b7b95a67a1cd84ade642ac1cb71c4c5e15/index.js#L8) 使用require后，打包文件[编译后](https://github.com/axmand/maptalks.arcgis/blob/43dd63b7b95a67a1cd84ade642ac1cb71c4c5e15/dist/maptalks.arcgis.js#L11)不执行后文factory的操作

**Comment by fuzhenn** [comment]
ok, I think it's not related with maptalks
