### ISSUE TITLE
Geometry对象绑定"click"事件后，双击Geometry对象导致对象id异常变更

### ISSUE THREAD

**Issue by DragonEmperorG** [maptalks/maptalks.js#562]
**maptalks's version and what browser you use?**
"maptalks": "^0.35.1", Chrome

**Issue description**
如示例（以circle对象为例）所示，从控制台的输出可以看到，单击选中任意一点（假设a点）高亮，然后双击除a点外任意一点b，a的id会被修改为和b点一致。。。

**Please provide a reproduction URL (on any jsfiddle like site)**
http://jsfiddle.net/uhon5Lhs/3/

**Comment by fuzhenn** [comment]
这个不是bug， 代码的38行有个错误：
```js
if (clickedObj[i]._id = target._id) {
```
应该为
```js
if (clickedObj[i]._id === target._id) {
```

另外maptalks中带'_'的属性和方法都是内部属性和方法，是不能使用的，未来不保证不会发生变化

id和jsontype可以用`getId`和`getJSONType`方法获取

get/set方法是一种设计模式，虽然繁琐，但更严谨，例如上述bug，用get/set模式是不会发生的

**Comment by DragonEmperorG** [comment]
谢谢，已经解决这个问题啦！
