### ISSUE TITLE
WMS请求BBOX顺序错误

### ISSUE THREAD

**Issue by boythl** [maptalks/maptalks.js#568]
src/layer/tile/WMSTileLayer.js文件第88行计算BBOX的参数有问题，不需要做1.3和1.1.1的区分
      const bbox = (this._wmsVersion >= 1.3  && this.wmsParams.crs === 'EPSG:4326' ?
            [min.y, min.x, max.y, max.x] :
            [min.x, min.y, max.x, max.y]).join(',');

我翻了下OGC标准，
在1.3的《7.3.2 GetMap request overview》章节，表格里有如下说明：
BBOX=minx,miny,maxx,maxy M Bounding box corners (lower left, upper right) in CRS units.

在1.1.1的《7.2.3.6 BBOX》有
The value of the BBOX parameter in a GetMap request is a list of comma-separated numbers of the form
"minx,miny,maxx,maxy".

===========================
综上，不需要min.y,min.x,max.y,max.x这种形式

**Comment by fuzhenn** [comment]
@boythl 感谢你提的issue！
我刚才翻了一下WMS 1.3的[官方标准](http://portal.opengeospatial.org/files/?artifact_id=14416)

里面确实提到如果CRS是EPSG:4326时，需要设为min.y,min.x,max.y,max.x(`18页 example 2`)，  原因是EPSG:4326参考系里x表示纬度，y表示经度 (`16页最后`)， 你可以自行查阅。

我也用boundlessgeo的wms服务写了一个EPSG:4326 WMS图层的调用示例，看上去是能正常调用的：
http://jsfiddle.net/uLe1Loxa/

我先关闭该问题，如果你确认问题仍然存在的话，我会再打开。

再次感谢！

**Comment by boythl** [comment]
很抱歉，我没有通篇研究OGC文档；我验证了下你提到的第16页，你说的是对的。
