### ISSUE TITLE
coordinateToContainerPoint

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#574]
经纬度转屏幕坐标时有问题？

当我使用 
  const projection = map.getProjection();
  var xy= projection.project(new maptalks.Coordinate(h[0], h[1]));
  xy= map._prjToContainerPoint(xy);
(当map的pitch大于0时)转换的结果不对;
-----------------------------------------------------------------
如果是在maptalks.renderer.CanvasRenderer的canvas上绘制线段就会发现问题，
我怀疑是自己的问题；
后来我切换到 map.coordinateToContainerPoint(coord);
也是不对
----------------------------------------------------------------
当地图zoom小的时候不会发现该问题,绘制结果是这样的：
[image1](http://58.210.98.62:7080/image/2018-01-05_135537.png)
当我放大地图后就是这个样子的：
[image2](http://58.210.98.62:7080/image/2018-01-05_135719.png)
当pitch调节到为0时，不管缩放的层级都是对的，结果是这个样子的：
[image3](http://58.210.98.62:7080/image/2018-01-05_135744.png)
---------------------------------------------------------------
然后我看了一下
maptalks.e3 [这个插件也是有问题的](http://maptalks.org/maptalks.e3/demo/fly.html)
（zoom调节到大一点时查看）
当pitch为0，是对的，效果是这样的：
[image4](http://58.210.98.62:7080/image/2018-01-05_140822.png)

当ptich>0时，效果就是这个样子了：
[image5](http://58.210.98.62:7080/image/2018-01-05_141100.png)

当ptich调整到 80时，效果是这个样子的：
[image6](http://58.210.98.62:7080/image/2018-01-05_141442.png)

然后我限制了   maxPitch:60,还是有问题的；
--------------------------------------------------------------------------------

我基于heatLayer插件做了一些改动做的一个列子：
[exmaple](http://58.210.98.62:7080/maptalks-gmvi/examples/)

-------------------------------------------------------------------------------
不知是我使用的方式不对，还是这是有问题的呢？

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
感谢提出issue，你写的逻辑没什么问题，`projection =》 _prjToContainerPoint`和`coordToContainerPoint`都可以。

飞线是因为在三维坐标 -> 二维坐标时，因为三维相机的摆放位置，点的投影角度造成飞线，那些飞线在三维坐标系中其实是正确的，但绘制在二维坐标系中不正确，需要的话我晚点会画个示意图来解释一下。

同样的面数据在VectorLayer里绘制没有问题，是因为我预先用地图的可视范围对图形做了[剪切]（https://github.com/maptalks/maptalks.js/blob/master/src/renderer/geometry/Painter.js#L243），只保留了图形的可见部分，保证点是从正确的角度投影的，所以就没有飞线了。

如果能在三维转换时，有数学方法得到正确的二维投影，这个问题就能解决了，我会来研究一下这个问题。（得复习下立体几何）

**Comment by deyihu** [comment]
好的，谢谢

**Comment by fuzhenn** [comment]
@deyihu 这个问题已经[初步改好](https://github.com/maptalks/maptalks.js/pull/575)

我发布了一个alpha版: v0.37.0-alpha.0

你可以先用这个版本来测试验证。

```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks@0.37.0-alpha.0/dist/maptalks.min.js"></script>
```

**Comment by fuzhenn** [comment]
另外前几天@pissang 和我看到了你在echarts-gl的gallery里分享的[maptalks插件](http://gallery.echartsjs.com/editor.html?c=xByh-kvLmf)，我们对它都很感兴趣，有兴趣以开源的形式贡献出来，与大家分享吗？ @deyihu

**Comment by fuzhenn** [comment]
@deyihu v0.37.0已经发布

**Comment by deyihu** [comment]
@fuzhenn  会开源的，等我周末整理一下代码
