### ISSUE TITLE
官方Demo，圆、椭圆、扇形，在倾斜情况下会消失

### ISSUE THREAD

**Issue by gee1k** [maptalks/maptalks.js#578]
**maptalks's version and what browser you use?**
官方最新版，maptalks v0.36.2

**Issue description**
官方Demo，圆、椭圆、扇形，在倾斜情况下会消失

**Please provide a reproduction URL (on any jsfiddle like site)**
[http://maptalks.org/examples/cn/geometry/rectangle-circle-ellipse-sector/#geometry_rectangle-circle-ellipse-sector](http://maptalks.org/examples/cn/geometry/rectangle-circle-ellipse-sector/#geometry_rectangle-circle-ellipse-sector)

**Comment by fuzhenn** [comment]
谢谢提issue，这个是因为图形缓存逻辑不对造成的bug。
已在[这里](https://github.com/maptalks/maptalks.js/commit/e25e6dcd115eea0670889cbd46b44febb2f04d63)解决，更新到v0.37.0-alpha.0即可

**Comment by fuzhenn** [comment]
顺提，这个bug的根本原因还是之前没有测试，这次把测试补上了，所以应该不会再次发生。
