### ISSUE TITLE
zoomable option doesn't work

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#579]
**maptalks's version and what browser you use?**
v0.36.2

**Issue description**
map's `zoomable` option doesn't work

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by 466035017** [comment]
这个是动画中鼠标缩放的bug
http://jsfiddle.net/p8w9dqz4/?utm_source=website&utm_medium=embed&utm_campaign=p8w9dqz4
