### ISSUE TITLE
设置path的smoothness参数后，click事件出现问题

### ISSUE THREAD

**Issue by ageeye-cn** [maptalks/maptalks.js#584]
**maptalks's version and what browser you use?**

**Issue description**

click响应区域总是在smoothness=0时的位置
**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
LineString和Polygon都改为通过实际像素绘制来触发事件
https://github.com/maptalks/maptalks.js/commit/76ebbf2864d7b3e6e5806df67f6a4e43b2ba7fdf
