### ISSUE TITLE
map.setZoom(number) is asynchronous？

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#589]
**maptalks's version and what browser you use?**

v0.36.2        v0.37.0

**Issue description**

```js
 var map = new maptalks.Map('map', {
        center: [-0.113049,51.498568],
        zoom: 14,
        attribution: {
          content: '&copy; <a href="http://osm.org">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/">CARTO</a>'
        },
        baseLayer: new maptalks.TileLayer('base', {
          urlTemplate: 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
          subdomains: ['a','b','c','d']
        })
      });

 //test1
      map.setZoom(6)
      console.log(map.getZoom())

      setTimeout(function() {
               console.log(map.getZoom())
      }, 1000);

   //console  result is  14  , 6


//test2
     map.setZoom(6,{animation:false})
      console.log(map.getZoom())

      setTimeout(function() {
           console.log(map.getZoom())
      }, 1000);

//console  result is  6  , 6
```
//只有手动禁用动画，获取map的zoom值才不是异步的，我所理解的是，无论是否动画，都不应该是异步的啊

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
这里主要涉及到我们怎么理解`getZoom`。
`getZoom`的含义是map **当前** 的zoom值。
`setZoom`默认是通过动画更新zoom，map **当前** 的zoom随动画更新，所以是异步的。
而`setZoom(z, { animtion : false });`因为没有动画，所以是同步的。

设计上，map的zoom变化是通过监听'zoomstart', 'zooming', 'zoomend'事件实现，事件参数的from, to会指明zoom的开始和结束值（但不绝对，滚轮缩放时，因为缩放级别根据滚轮的时间动态变化，zoomstart的to参数是没值的）

这个问题不算是bug，是api设计的范畴，我先关掉issue，但欢迎随时探讨
