### ISSUE TITLE
关于自定义瓦片底图的制作请教

### ISSUE THREAD

**Issue by 7zheng7** [maptalks/maptalks.js#595]
您好，maptalks功能很强大，我想利用您开发的maptalks自己制作瓦片底图，但是不知道如何下手，请问有什么例子吗，或者需要什么辅助工具吗？多谢！

**Comment by fuzhenn** [comment]
嗨！ 感谢提issue！

maptalks支持用node渲染静态图片，是可以基于node用maptalks来生产瓦片图片的，不过我们自己没这么干过，所以相关的基础设施不是很完善。

建议你还是看一下专业的底图生产服务，比如arcgis, 超图，或开源的mapnik等

**Comment by deyihu** [comment]
@7zheng7  这个问题我研究过，不过还没有好的解决方案

1.利用arcgis, 超图等桌面级的工具来切图，不过针对动态变化的底图（动态变更样式，动态添加底图的元素等）需要多次的切图，而且如果是切图的比例尺要求较高（比如：1:500比例尺）能切死人，尤其是范围大的，比如切一个省的，单机切片估计要一两个月；小范围的，比例尺要求不高的可以采用这种方案

2.开源的mapnik，mapbox-node可以尝试一下（其中，mapnik其我已经测试成功了，但是这个也涉及到cartocss的样式，这个要求配图人员需要基本的Css知识，所以我放弃了；mapbox-node我测试了，效率奇慢所以也放弃了）

3.矢量切片-前端渲染方案，具体的可以参考mapbox的规范，我也是采用这个方案的

--------------------------------------------------------------------------------------------------------------------------------
自己造轮子

1.mapbox的前端渲染利用webgl，我就想能不能直接用canvas2d模式来渲染（低版本的IE浏览器你懂的），然后我就自己造轮子了（你懂得），没有解决标注的问题（道路，兴趣点的标注等，不知@fuzhenn有没有研究过该问题），其他的还好我都实现了


2.百度的动态底图好像是自己手写的渲染引擎，然后我就自己又又又造轮子了，利用node.js动态的去渲染底图，然后进入死胡同了奥，[我做的列子](http://58.210.98.62:7080/TiledLayerExtendsDoor/examples/vectorTiledLayerServer.html)，也是没有解决标注的问题，不过其他的还行吧，就是利用（node-canvas)动态渲染底图，并返回给前端浏览器，不过也不是没有收获，就是这个给了我启发，大数据上图可以在后台动态切图，然后直接以切片返回给前台，
而且我已经测试了几千万的数据上图，效率也还可以


我感觉底图的动态渲染还是很难的，不过基本的业务数据渲染还是很简单的，希望对你有帮助

**Comment by fuzhenn** [comment]
哈哈！感谢 @deyihu 同学的回复！

关于底图动态渲染，我比较看好的方式是以mapbox-gl为代表的的矢量瓦片 + 前端渲染的方式。

这个路线最大的缺点是webgl开发门槛比较高，mapbox-gl的大神们基本上把原生webgl用到了极致，但问题是这么高水平的开发人员全世界也不多。

为了解决这个问题，我现在正在开发一个maptalks矢量瓦片插件，这个插件的定位不是maptalks版的mapbox-gl，而是个开发框架，主要目标是降低矢量瓦片的开发难度，让开发者能选用任意的webgl库(原生/three.js/claygl/playcanvas)甚或**canvas 2d**来轻松实现矢量瓦片的可视化/交互，且无需关心矢量瓦片的技术细节。

等我们在内部项目里实际验证以后就会把它开源出来，到时请各位同学多指正。

**Comment by fallowu** [comment]
> maptalks矢量瓦片插件

maptalks矢量瓦片插件现在有发布吗
