### ISSUE TITLE
不支持wmts吗？

### ISSUE THREAD

**Issue by sys2007** [maptalks/maptalks.js#599]
**maptalks's version and what browser you use?**

**Issue description**

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
感谢提issue！目前还不支持wmts。

你说的wmts是指ol上的这个例子吧？
https://openlayers.org/en/latest/examples/wmts.html

如果是的话，我大概看了一下，wmts和arcgis瓦片服务的支持方法差不多，通过解析wmts的xml，获得resolutions和tilesystem等设置。

* maptalks中读取arcgis瓦片服务设置的源代码 [SpatialReference.Arc.js](https://github.com/maptalks/maptalks.js/blob/master/src/map/spatial-reference/SpatialReference.Arc.js)
* maptalks[调用arcgis瓦片服务的示例](http://maptalks.org/examples/cn/tilelayer-projection/arcgis-tile/#tilelayer-projection_arcgis-tile)

因为最近事情比较多，如果急着用，你有兴趣试着开发一下，提交个PR给我们吗？

**Comment by sys2007** [comment]
感谢回复，看到你的开源项目很兴奋，wmts的使用场景还是很多的，希望我可以帮到你们，也希望这个项目可以很好的进行下去。

**Comment by fuzhenn** [comment]
谢谢反馈！期待你的工作！

WMTS的接口形式可以参考arcgis，在SpatialReference上增加一个loadWMTS方法，读取wmts中的spatial reference设置后供map或TileLayer调用，如果有任何问题请随时联系我。

**Comment by binfenshijie** [comment]
WMTS类型是把瓦片缓存起来了，每次加载会加载gwc文件夹下的切好的瓦片（我是用geoserver发布的），相比于WMS的瓦片加载要快很多，局域网（无internet）内十分有效率，请求连接如下：
http://114.115.136.50:8086/geoserver/gwc/service/wmts?
layer=bcmp_puruan:new3d_puruan
&style=
&tilematrixset=EPSG:4326
&Service=WMTS
&Request=GetTile&Version=1.0.0
&Format=image/png
&TileMatrix=EPSG:4326:17
&TileCol=219625&TileRow=42816
在OL中是用：
var wmtslayer = new ol.layer.Tile({
                    source: new ol.source.WMTS({

希望以后能增加对wmts的加载加以实现。
另外，maptalk真的是amazing的存在！！！
下个项目的地图选型已经定下用maptalk了!

**Comment by lifefriend** [comment]
遇到同样的需要加wmts类型问题，通过仿写WMSTileLayer，解决了。[wmts demo](https://github.com/lifefriend/maptalks-demo/blob/master/wmts.html)

**Comment by AllanHao** [comment]
@fuzhenn 请问maptalks可以向ol那样支持tileLoadFunction类的回调函数还重写request请求吗？例如我想在瓦片请求里加入authorization请求头信息。

**Comment by fuzhenn** [comment]
> @fuzhenn 请问maptalks可以向ol那样支持tileLoadFunction类的回调函数还重写request请求吗？例如我想在瓦片请求里加入authorization请求头信息。

覆盖renderer里的loadTileImage方法就行了。
```js
//tileImage是瓦片的image对象
layer.getRenderer().loadImage =(tileImage, url) => { ... };
```

**Comment by fuzhenn** [comment]
fixed by #1193
