### ISSUE TITLE
Map的identify优化及代码重构

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/MapTalks.js#6]
identify逻辑存在以下几个问题:

1. 代码比较啰嗦, 不够精炼
2. 性能问题比较严重, geometry一多就严重拖慢地图速度
3. 某些图形的identify逻辑存在bug.

可以考虑的改进点:

1. 对于面类型数据, 只需要判断点是否在图形中即可, 没必要判断buffer后的圆形和图形是否相交
2. 点类型数据当作面来对待
3. 线需要判断点击点和线上距离最近的点间的像素距离是否在tolerance中
4. 点包含关系判断逻辑可以分散到各个图形中去做, 而不用在util中用大段的if进行判断

**Comment by wsw0108** [comment]
except tolerance for sector
