### ISSUE TITLE
The marker with height can't be dragged normally

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [maptalks/maptalks.js#601]
有高程的marker，拖拽时，点击脚下才有效果，点击实际位置相当于拖拽地图

**Comment by fuzhenn** [comment]
There is some incorrect offset when dragging geometry due to the above commit.
Reopen this issue.

**Comment by fuzhenn** [comment]
fixed in https://github.com/maptalks/maptalks.js/commit/b6d3066c4b052e43715968a430c9d97512172d00
