### ISSUE TITLE
dragging conflicts

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#603]
**maptalks's version and what browser you use?**
v0.37.0

**Issue description**
Dragging ui markers will make other draggable dom elements undraggable. 
Suspecting it's due to event listening conflicts on **document**.

reported by @ageeye-cn

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by ageeye-cn** [comment]
demo: http://jsfiddle.net/419sqhe6/
