### ISSUE TITLE
Coordinate to Pixel慢的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#605]
**maptalks's version and what browser you use?**

**Issue description**

经纬度转屏幕坐标，当数据量大时，我测试了100万的数据，需要2-3秒，在二维地图里，当时我也遇到这个问题，解决的方法是获取当前地图的大小和经纬度范围，然后利用平均值计算，一百几十万的数据只需几百毫秒，不知这个有好的解决办法吗?

我看 插件 [bigLayer](https://github.com/maptalks/maptalks.biglayer)
里BigPointLayer.js
转换代码：
                  const cp = map.coordinateToPoint(new maptalks.Coordinate(point), targetZ);
                    vertexTexCoords.push(cp.x, cp.y, tex.idx);
                    points.push([cp.x, cp.y, tex.size, tex.offset, point]);
然后利用该方法，也是需要2秒左右

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
前几天我在master分支版本里做了一些优化，在坐标转换过程中重用而不再创建任何新的数组，或多或少应该能提高一些性能。
除此之外，能挖掘的潜力就比较有限了。

坐标转换有一些优化方式（也许你已经知道了，我再提一下）：
先把coordinate转换成point（世界二维坐标），并缓存起来。
同级别拖拽或旋转地图时，point不会有变化，不同级别之间的point只需要乘以map.getScale()即可。
需要用到containerPoint时，再把缓存的point转换为containerPoint，这样能省略掉coordToPoint的转换过程。

另外就是用webgl，webgl可以直接用point来构造数据，然后通过uniform矩阵在shader中实现point->containerPoint，从而省略坐标转换。

因为该问题不算是bug，我先关闭issue，但欢迎就此主题继续讨论。
