### ISSUE TITLE
转换成3D视角后，频繁移动会出现 this.width和this.height值为0的情况，导致 containerPointToPoint计算失败

### ISSUE THREAD

**Issue by axmand** [maptalks/maptalks.js#606]
重现操作：倾斜地图后频繁移动地图

错误堆栈：
1. _checkSize 
2. checkSize
3. _offsetCenterByPixel
4. _contanierToPrj
5. _containerToPoint,错误出现在此处，由于this.width和this.height 为0，计算移动后的点x,y出错.

示例地址：https://github.com/maptalks/maptalks.e4
因为示例带有数据和未发布的插件，请直接运行 demo/bar3d.html

**Comment by fuzhenn** [comment]
谢谢！很巧今天刚改过这个bug，因为size为0时，转换时会出现某些分母为0，导致计算出错。
下面的commit应该能解决这个问题。
https://github.com/maptalks/maptalks.js/commit/c295183211d4945b61bb360a3a5001b2bb192b07

我先关闭issue，如果仍有问题再打开。
