### ISSUE TITLE
Marker 的dblclick事件与dragend事件有冲突，同时使用的时候都跑到dragend那儿去了

### ISSUE THREAD

**Issue by daijinmaster** [maptalks/maptalks.js#610]
**maptalks's version and what browser you use?**

**Issue description**

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
你的意思是dblclick时，不应该触发dragend吗

**Comment by daijinmaster** [comment]
对的，而且不光是dblclick，单击click也触发dragend

**Comment by fuzhenn** [comment]
感谢反馈，我已经重现了这个问题，我来改一下。

**Comment by daijinmaster** [comment]
多谢

**Comment by fuzhenn** [comment]
@daijinmaster 已解决，会在下个版本(v0.38.0)中发布
