### ISSUE TITLE
fitExtent() and getFitZoom() can't contains all extent when the basemap is "baidu"

### ISSUE THREAD

**Issue by Kyokochya** [maptalks/maptalks.js#612]
**mptalks's version and what browser you use?**
0.38.1 chrome64.0.3282.119

**Issue description**
fitExtent() and getFitZoom() can't contains all extent when the basemap is "baidu"

**Please provide a reproduction URL (on any jsfiddle like site)**
https://jsfiddle.net/bougie/9ca8bdvw/

**Comment by fuzhenn** [comment]
Thank you for reporting issue!
Investigating

**Comment by fuzhenn** [comment]
Resolved in the reference commit.
It's caused by null resolutions[0] in baidu's spatial reference.
Thanks again! @Kyokochya
