### ISSUE TITLE
examples中2.11是否为bug

### ISSUE THREAD

**Issue by Wuli-Zhang** [maptalks/maptalks.js#614]
**maptalks's version and what browser you use?**

**Issue description**
在examples的2.11中，显示指定范围内的瓦片，在放大缩小地图时发生错位

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
Thanks!
Fixed in https://github.com/maptalks/maptalks.js/commit/85c98c698ff13fc59a43f676e80b70b5a6a61545

Published and fixed as v0.38.2
