### ISSUE TITLE
Polygon Pattern Fill Not working in  maptalks.ExtrudePolygonLayer

### ISSUE THREAD

**Issue by s9eenk** [maptalks/maptalks.js#616]
**maptalks's version and what browser you use?**
version - 0.38.1 and browser - chrome  

**Issue description**
I cannot fill the polygon layer with pattern or gradient. Also please provide an example providing a pop up on hovering a polygon in maptalks.ExtrudePolygonLayer

**Comment by fuzhenn** [comment]
Hi, @s9eenk , good to see u.
Yeah, ExtrudePolygonLayer doesn't support polygon pattern fill (gradient either). As [extrudePolygonLayer ](https://github.com/maptalks/maptalks.biglayer) is an experimental plugin, so I don't have a plan to add pattern fill in.
ExtrudePolygonLayer (with other big layers)  will be replaced by a new layer plugin we are working on now, extruded polygon with pattern/gradient fill will be implemented there.
