### ISSUE TITLE
几个画图问题

### ISSUE THREAD

**Issue by Wuli-Zhang** [maptalks/maptalks.js#617]
**maptalks's version and what browser you use?**

**Issue description**
 画矩形的时候，矩形角度会随着旋转地图而改变。
画椭圆时，如果椭圆过扁，椭圆的两端会有棱角的出现，大一点的矩形则没有。

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by MOLIANGWANG** [comment]
drawtool rectangle be rotated again when map rotates
V0.40.1 / V0.40.2

**Comment by fuzhenn** [comment]
@MOLIANGMAN 收到，感谢
这应该和 #629 或 #662 有关系，我晚点会改一下
