### ISSUE TITLE
添加ExtrudePolygonLayer后右键旋转视角，几何体会闪动

### ISSUE THREAD

**Issue by chenxiaoleizi** [maptalks/maptalks.js#618]
version and what browser you use?**
火狐，chrome

**Issue description**
添加ExtrudePolygonLayer后右键旋转视角，几何体的渲染有点奇怪，会有抖动的感觉。
官网的例子会有轻微的抖动，我自己加的几何体抖动比较大。

**Please provide a reproduction URL (on any jsfiddle like site)**
http://maptalks.org/gallery/extrude-buildings/index.html

**Comment by fuzhenn** [comment]
感谢报告issue

官网的例子里的插件版本已经比较老了，试过现在的biglayer插件没？
https://github.com/maptalks/maptalks.biglayer

另是怎样的抖动？ 能不能麻烦做个gif截图之类的

**Comment by chenxiaoleizi** [comment]
![pic](https://user-images.githubusercontent.com/24647177/36625347-ca2fdc96-1958-11e8-846d-0596c216d817.gif)
gif图，感觉旋转的时候有点变形。我试下新的插件。

**Comment by fuzhenn** [comment]
@chenxiaoleizi 这个问题在biglayer插件上还存在吗？

**Comment by chenxiaoleizi** [comment]
存在的。

**Comment by fuzhenn** [comment]
方便提供一份重现数据给我吗？

**Comment by chenxiaoleizi** [comment]
我们想在maptalks的基础上做一个室内室外结合的地图，这个好实现吗？能加你qq吗？

**Comment by fuzhenn** [comment]
@chenxiaoleizi 室内外结合地图做起来应该挺容易的，不过biglayer不太适合，用[three](https://github.com/maptalks/maptalks.three)插件更方便一些

qq群： 237726126

**Comment by fuzhenn** [comment]
moved to https://github.com/maptalks/maptalks.biglayer/issues/26

closing
