### ISSUE TITLE
maptalks.ui.UIMarker is Geometry or Control

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#619]
**maptalks's version and what browser you use?**
如果利用 UIMarker  自定义一个 marker ，UIMarker  会遮住map的鼠标事件（缩放，拖拽等），如果把 UIMarker  归为UI（Control）组件这个我可以理解，如果把UIMarker  归为Geometry (Marker/Point) ，其不应该影响map的操作；

我以为是 options 里 eventsToStop 设置成true的，好像不是的；

leafletjs 里也可以将dom做为 marker的icon的，其不会影响map的操作

http://maptalks.org/examples/en/style/html-marker/#style_html-marker

**Issue description**

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
目前UI和Control上的事件都会被map忽略掉

不过你说的有道理，UIMarker比较特殊，直觉上应该让事件传递给map

我会比较一下各种情况，看看能否放开

**Comment by fuzhenn** [comment]
在UIComponent增加了eventsPropagation选项，用来设置是否阻止事件冒泡
UIMarker的eventsPropagation默认设置为true，即能让事件传递给map
