### ISSUE TITLE
你们的官方API地址为什么一直打不开？

### ISSUE THREAD

**Issue by RoxanneCIA** [maptalks/maptalks.js#631]
**maptalks's version and what browser you use?**

**Issue description**

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
你是用的哪个地址？
http://maptalks.org/maptalks.js/api/0.x/Map.html

如果实在打不开，也可以从[releases里下载发布包](https://github.com/maptalks/maptalks.js/releases)，里面包含了api文档
