### ISSUE TITLE
InfoWindow调用hide或者openInfoWindow无效

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.js#632]
**maptalks's version and what browser you use?**
0.39.1

**Issue description**
点击地图上的marker，第一次显示，再次点击marker通过判断marker是否已经有了infowindow，有的话，调用hide方法无效。

**Please provide a reproduction URL (on any jsfiddle like site)**
http://jsfiddle.net/zqf02kp1/15/

**Comment by fuzhenn** [comment]
resolved by setting `autoOpenOn : null` to info window's options
