### ISSUE TITLE
(moved from maptalks.three) a gl renderer for VectorLayer

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#633]
**maptalks's version and what browser you use?**
n/a

**Issue description**
This issue is [moved from maptalks.three](https://github.com/maptalks/maptalks.three/issues/5).
Add a gl renderer to VectorLayer to improve drawing performance, e.g. with pixi.js.

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by superivaj** [comment]
Hi fuzhenn,

Fantastic work that you have done so far. Hope to be able to contribute at some point.
I am looking for a method to obtain 3d buildings from vector tiles. Similar to this: https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/

I believe this ticket will allow for it. Has there been any progress in this area?

Regards,
Francisco
