### ISSUE TITLE
能不能进行离线地图下载？

### ISSUE THREAD

**Issue by yzpopulation** [maptalks/maptalks.js#634]
maptalks 非常好，公司的环境是局域网，和互联网完全隔离，需要地图展示，我现在想用maptalks进行页面展示，但是没有瓦片数据，我尝试用博客园某人的mapdownload进行下载，可以用leaflet进行加载，但是该软件没有你例子中的4326投影的底图，请问有没有方便制作的离线接口？

**Comment by fuzhenn** [comment]
欢迎！

maptalks可以加载任意投影的地图，如果能用leaflet加载的话，maptalks也肯定能加载。
具体可以看一下它的leaflet里的瓦片参数(urlTemplate)，配置给maptalks就行了。

maptalks和leaflet一样，默认都是3857投影，加载示例：
http://maptalks.org/examples/cn/map/load/

也可以支持其他投影，例如百度的加载示例：
http://maptalks.org/examples/cn/tilelayer-projection/baidu/#tilelayer-projection_baidu

更多示例可以参考上面的示例页面

**Comment by yzpopulation** [comment]
我想问的是有没有天地图的离线下载工具啊？ @fuzhenn

**Comment by fuzhenn** [comment]
@yzpopulation sorry，我们没有离线下载工具
