### ISSUE TITLE
按照你官网的demo加载arcgis瓦片是没问题的，但是使用我们自己发布的arcgis地图服务是加载不出来的（它是可以用arcgis api加载出来的），能了解下原因么？

### ISSUE THREAD

**Issue by RoxanneCIA** [maptalks/maptalks.js#635]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可能的原因有很多，要看arcgis瓦片是怎么发布的，urlTemplate是怎么设置的

可以参考一下maptalks的arcgis config loader的示例：

http://maptalks.org/examples/cn/tilelayer-projection/arcgis-tile/#tilelayer-projection_arcgis-tile

在这个例子基础上多试几种projection。

如果你们的底图不是用3857/4326等常见投影，而是西安80之类的坐标系发布的，得用proj4js来构造自定义的projection， 示例：

http://maptalks.org/examples/cn/tilelayer-projection/proj4js/#tilelayer-projection_proj4js

**Comment by lifefriend** [comment]
官网的demo加载arcgis瓦片前会去获取一份配置
自己发布的arcgis地图服务,很多配置是不完全的，按照官网的demo是加载不出来，
我也遇见了相同的问题，写了一个 [ArcGISTileLayer](https://github.com/lifefriend/maptalks-demo/blob/master/arcgis.html) 专用于 arcgis地图服务 加载，目前项目使用中。
