### ISSUE TITLE
在做3d的地图时候，使用threejs，但是地图上字一旋转会反，有办法解决吗

### ISSUE THREAD

**Issue by maketwin** [maptalks/maptalks.js#637]
**maptalks's version and what browser you use?**
----
0.39.1

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
sorry, 没get到你的问题在哪里，能基于这个jsfiddle给个重现代码吗？
http://jsfiddle.net/cu81smp0/1/

我已经把maptalks, three.js, maptalks.three都添加到了这个jsfiddle里

**Comment by fuzhenn** [comment]
@maketwin  closing.
如果需要的话，可以随时重新打开
