### ISSUE TITLE
some mistakes in wiki

### ISSUE THREAD

**Issue by zhuang-hao-ming** [maptalks/maptalks.js#638]
https://github.com/maptalks/maptalks.js/wiki/Tile-System

I think there are some mistakes in this wiki.

1. epsg:4326 is not a projection. The projection that uses geographical coordinate directly as projected coordinate without any projection is called [plate-carre](http://desktop.arcgis.com/en/arcmap/10.3/guide-books/map-projections/plate-carr-e.htm).4326 itself is a geographical coordinate system.

2. In the tile system section.You say that the sy means order of tile,y from top to bottom .1: increse, -1 decrease.And, the osm's tile system is [1, -1, -20037508.34, 20037508.34], which means the tile,y of osm's tile system is decrease from top to down. But this is not the truth.

Thanks.

**Comment by fuzhenn** [comment]
Thanks! Appreciate very much for pointing out those mistakes!

Got them corrected.
