### ISSUE TITLE
point点三维显示？

### ISSUE THREAD

**Issue by lileialg** [maptalks/maptalks.js#643]
请问可以支持点point的三维显示吗，
现在支持了线、面、circle的三维显示，点好像不支持；
另外在添加很多circle三维显示时，拖动或者旋转地图，会不连续显示，可以解决吗？

**Comment by fuzhenn** [comment]
很高兴收到你的issue。

三维点也支持的
http://maptalks.org/examples/cn/3d/marker-draw-altitude/#3d_marker-draw-altitude
但如果你指的是三维旋转的点，那个暂时还不支持，可以用[three插件](https://github.com/maptalks/maptalks.three)来实现

关于图层不连续显示的问题，因为map的fpsOnInteracting（默认25帧）限制，在交互时为维持fps会省略一些图层的绘制，有两种办法可以强制绘制：
* 初始化地图时，在options里把`fpsOnInteracting`设为0，关闭交互帧数限制
* 初始化图层时，在options里根据需要把图层的`forceRenderOnMoving`, `forceRenderOnZooming`,  `forceRenderOnRotating` 设为true

希望以上解答了你的问题

**Comment by lileialg** [comment]
首先，非常感谢您的回复，我底下重新试试；
另外，想咨询下，maptalks对大数据量的轨迹点动画播放的支持力度有多强呢？
比方说一种场景：中国范围内4-5万量物流车实时轨迹变化

**Comment by fuzhenn** [comment]
对于4-5w辆车的实时轨迹绘制，目前VectorLayer绘制性能可以支撑，但肯定会有明显卡顿。
但如果对绘制效率要求很高，可以稍微等一段时间，我现在正在开发VectorLayer的gl renderer，应该能比现有的canvas renderer明显提升绘制性能

**Comment by lileialg** [comment]
thanks,非常期待，谢谢指导

**Comment by lileialg** [comment]
不知道maptalk能不能做成地图最终缩放成球状，类似于cesium那样，另外三维建筑能不能添加纹理？

**Comment by fuzhenn** [comment]
maptalks是二三维地图引擎，所以不能缩成球状，但可以在map的div下叠加一个地球，在需要的时候隐藏maptalks切换到地球上

用three插件载入三维建筑可以添加纹理的，具体参考three里的例子

那我先关闭这个issue，有问题欢迎随时继续讨论
