### ISSUE TITLE
可以让有纹理的线循环运动么

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [maptalks/maptalks.js#644]
**maptalks's version and what browser you use?**
----
maptalks v0.39.3    Chrome

**Issue description**
----
通过设置line的symbol做成有纹理的线 让它看起来它的纹理一直在朝一个方向移动
 symbol: [
            {
                'lineColor': '#396ce0',
                'lineWidth': 10,
                'lineDasharray': [10, 5, 10, 5]
            },
            {
                'lineColor': '#000',
                'lineWidth': 8,
                'lineDasharray': [10, 5, 10, 5]
            }
            ],

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
![gif-iloveimg-compressed](https://user-images.githubusercontent.com/13678919/38132691-b85cf00c-343e-11e8-9536-cb6445ef8f2a.gif)

```javascript
      var layer = new maptalks.VectorLayer('vector').addTo(map);

      var line = new maptalks.LineString(
        [
          map.getCenter().sub(0.1, 0),
          map.getCenter().add(0.1, 0)
        ],
        {
          symbol:{
            'linePatternFile' : 'resources/pattern2.png',
            'lineWidth' : 10,
            'linePatternDx' : 0
          }
        }
      ).addTo(layer);

      line.animate({
        symbol : {
          'linePatternDx' : 80
        }
      }, {
        repeat : true
      });
```

**Comment by liugx2018** [comment]
可不可以仅通过设置line的symbol做成有纹理的线，而不用添加图片就让它的纹理一直在朝一个方向移动？

**Comment by joric** [comment]
I need that. linePatternFile + linePatternDx works (but painfully slow), lineDasharray + lineDashOffset doesn't. It's weird that a library born for a map-centric project to help YUM! China to analyze spatial data doesn't have proper antlines.
