### ISSUE TITLE
如何解决跨域瓦片数据问题？

### ISSUE THREAD

**Issue by yzpopulation** [maptalks/maptalks.js#650]
如题，如何解决跨域瓦片数据问题？maptalks会出错，但leaflet调用不会出错。
使用调试出错 Access-Control-Allow-Origin 。

**Comment by fuzhenn** [comment]
因为瓦片图层默认用webgl渲染，webgl要求图片资源必须跨域

有两个解决方案：
* 瓦片图层的renderer改为canvas，缺点是不能三维倾斜，[示例](
http://maptalks.org/examples/cn/tilelayer-projection/canvas-renderer/#tilelayer-projection_canvas-renderer)
* 自建瓦片http代理，这里不再赘述
