### ISSUE TITLE
删除节点后无法保存位置

### ISSUE THREAD

**Issue by Ray93** [maptalks/maptalks.js#656]
**maptalks's version and what browser you use?**
----
0.39.3

**Issue description**
----
LineString和Polygon直接删除节点后，endEdit结束编辑之后无法保存编辑后的位置

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://maptalks.org/examples/en/interaction/edit-polygon/#interaction_edit-polygon
http://maptalks.org/examples/en/interaction/edit-line/#interaction_edit-line

**Comment by fuzhenn** [comment]
感谢提出issue，这个问题已在下面的commit里解决了，请稍等两天，清明节前后会发新版本

https://github.com/maptalks/maptalks.js/commit/1d59bc783f276c86029f27e4fce177a10fbfaa6a

如果急着用，可以自己编译一份maptalks.js

**Comment by fuzhenn** [comment]
嗨！ 我刚在0.39.3基础上单独修了这个问题，发布了0.39.4，可以更新一下

**Comment by Ray93** [comment]
好的，刚看到，感谢你的贡献，希望这个项目发展的更好！！
