### ISSUE TITLE
在Infowindow中加载图片时，Infowindow位置偏移

### ISSUE THREAD

**Issue by gee1k** [maptalks/maptalks.js#657]
**maptalks's version and what browser you use?**
----
- maptalks: v0.39.5
- chrome: 65.0.3325.181

**Issue description**
----
> 在Infowindow中加载图片时，图片大小设置为100%时，首次打开Infowindow会出现Infowindow位置偏移

- 首次（不是每次都会出现）：
![image](https://user-images.githubusercontent.com/12059800/38664513-7113bb62-3e6c-11e8-930f-50422205c38f.png)

- 正常：
![image](https://user-images.githubusercontent.com/12059800/38664825-4cad6e70-3e6d-11e8-91e8-bcd8effdda96.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
[http://jsfiddle.net/gee1k/zg04gnbx/](http://jsfiddle.net/gee1k/zg04gnbx/)

**Comment by fuzhenn** [comment]
嗨，很高兴收到你的issue。

我也拿不准这算不算是一个bug。

Infowindow是靠内容元素的clientHeight和clientWidth来计算位置的。

把图片高度设置为100%时，在图片载入完成之前，图片的clientHeight一直是0，所以才会出现这个问题，在引擎层面我暂时没有想到特别好的解决方案。

在应用层面，这个问题有两个解决方案：
* 把图片高度设为像素值，或者把图片放在一个容器里，给容器设置一个像素高度
* 在打开InfoWindow前，预加载图片
```js
const img = new Image();
img.onload = function () {
  //open infowindow
};
img.src = 'puppy.jpg';
```

**Comment by gee1k** [comment]
谢谢你的回复。

看样子的确是这个原因，现在是通过设置Infowindow的translate来定位的，是否可以通过设置Infowindow的bottom和left来定位呢？这样就不会因为clientHeight变化而被改变位置了。

之前用过leaflet，记得leaflet好像设置图片是没有问题的，所以刚刚又去看了一下leaflet的源码？发现leaflet就是这么做的，您可以看看是否能借鉴一下
[leaflet源码地址](https://github.com/Leaflet/Leaflet/blob/0e9797edcedbb3f10ba25f0ac3dbf4c962b08ea6/src/layer/DivOverlay.js#L194)

**Comment by fuzhenn** [comment]
哈，感谢提示，我来按这个思路改一下
