### ISSUE TITLE
只有googlemap底图才支持3d显示吗。百度地图，腾讯地图的底图能否支持3D？

### ISSUE THREAD

**Issue by petitlen** [maptalks/maptalks.js#661]
只有googlemap底图才支持3d显示吗。百度地图，腾讯地图的底图能否支持3D？

**Comment by fuzhenn** [comment]
哈， 欢迎。

百度地图和腾讯地图都能支持加载和3D展示

事实上maptalks的3D和什么底图无关，所以只要能加载的底图都能支持3D和其他所有功能

至于各种底图的加载，可以瞧一下官方例子和deyihu同学做的底图插件

https://github.com/deyihu/maptalks-tileLayercollection

**Comment by petitlen** [comment]
谢谢您的回复

现在已经可以了，我之前项目都是使用leaflet的，在考虑改成maptalks的可行性。
在leaflet中使用了全球风场的js，https://www.npmjs.com/package/wind-js-leaflet <https://www.npmjs.com/package/wind-js-leaflet>
不知道这类型js，可否支持maptalks呢。

**Comment by fuzhenn** [comment]
有一个windy图层插件：
https://github.com/fuzhenn/maptalks.windylayer

不过这个插件有个bug，在低级别上，当存在重复世界(repeatWorld)的时候，会出现绘制不正确，因为这个插件没什么人用，所以我也没有去修改这个问题。

这个bug改起来不难，如果你确定要用的话，我可以帮你把这个插件做一下修改。

**Comment by bestime** [comment]
> 

作者你好，我现在有需要使用这个插件，遇到了repeatWorld绘制错误的问题，可以帮忙修复以下吗，或者提供一个解决思路

**Comment by fuzhenn** [comment]
@bestime  可以参考一下这个插件，它也支持maptalks
https://github.com/sakitam-fdd/wind-layer
