### ISSUE TITLE
能否支持加载自定义地图？

### ISSUE THREAD

**Issue by fltjzit** [maptalks/maptalks.js#663]
**maptalks's version and what browser you use?**
----

**Issue description**
----
看了maptalks的例子，基本都是加载的互联网地图服务，能否支持加载json格式的自定义地图？
还有一个建议，baseLayer的urlTemplate属性设置在文档中最好能够有个详细说明。

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
json格式的自定义地图是指？类似arcgis的json格式的rest瓦片服务吗？可以参考这个示例：
http://maptalks.org/examples/cn/tilelayer-projection/arcgis-tile/#tilelayer-projection_arcgis-tile

另外maptalks也支持你自定义空间参考，以支持任意类型的底图服务，参考示例：
http://maptalks.org/examples/cn/tilelayer-projection/custom-tile/#tilelayer-projection_custom-tile

在这个基础上可以自定义地图投影（例如基于proj4）:
http://maptalks.org/examples/cn/tilelayer-projection/proj4js/#tilelayer-projection_proj4js

---

urlTemplate的含义比较简单，只要url里有瓦片的x, y, z参数，用{x}替代相应的参数即可，可以参考[leaflet里的说明](http://leafletjs.com/reference-1.3.0.html#tilelayer)，maptalks的含义一样。（我晚点会补充一下文档）。

另外urlTemplate也支持函数方式
```js
 urlTemplate : function (x, y, z, domain) { 
   return `http://${domain}.example.com/${z}/${x}/${y}.png`;
 }
```

**Comment by fltjzit** [comment]
可能我的问题没有描述清楚。我举个例子说明一下我所说的自定义地图。以我所从事的工作为例，我们单位是基层单位，需要经常用到以行政区域为底图各种GIS专题图，因国家法律法规限制，正规互联网地图服务都没有行政区域界线图，尤其是乡镇、行政村（社区）级别的行政区域图。但是基层单位自己是拥有这些行政区域数据的，如果将这些数据转出json格式，是否可用maptalks绘制出行政区划图呢？就像用echarts绘制自定义地图一样。

**Comment by fuzhenn** [comment]
maptalks支持geojson格式和geometry的互相转化，具体请见示例

geojson到geometry:
http://maptalks.org/examples/cn/json/geojson-to-geometry/#json_geojson-to-geometry

geometry到geojson:
http://maptalks.org/examples/cn/json/geometry-to-geojson/#json_geometry-to-geojson

另外VectorLayer也支持直接用geojson作为输入数据，通过style来设置数据样式，类似
```js
const layer = new maptalks.VectorLayer('v', geojson).addTo(map);

layer.setStyle(style);
```

相关示例：
http://maptalks.org/examples/cn/layer/vectorlayer-style/#layer_vectorlayer-style

**Comment by PasserbyFluid** [comment]
比如我有一个JSON，里面是一些坐标，怎么用这些坐标去生成地图~？
