### ISSUE TITLE
maptalks加载本机的arcgis server出现跨域问题。

### ISSUE THREAD

**Issue by GISerWang** [maptalks/maptalks.js#664]
我参考官网例子：http://maptalks.org/examples/cn/tilelayer-projection/arcgis-tile/#tilelayer-projection_arcgis-tile

然后修改了arcUrl，center，zoom，maxZoom参数，结果出现了跨域问题，我使用openlayers加载本地的arcgis server的服务，就可以成功加载，请问大佬，这个问题应该如何解决啊？？错误提示就是正常的跨域错误：Access to Image at 'http://localhost:6080/arcgis/rest/services/xc/xc/MapServer/tile/2/307/424' from origin 'http://localhost:63342' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:63342' is therefore not allowed access.

**Comment by fuzhenn** [comment]
很高兴收到你的issue

因为TileLayer默认是用webgl绘制瓦片的，所以瓦片服务必须支持跨域

有两个解决方案：
1. 给瓦片数据增加跨域代理
2. 把TileLayer的renderer换成canvas (ol是用canvas绘制瓦片，所以它默认没有跨域问题），但缺点是不支持三维

具体可以见这个demo里的说明
http://maptalks.org/examples/cn/tilelayer-projection/canvas-renderer/#tilelayer-projection_canvas-renderer
