### ISSUE TITLE
关于底图容器叠加顺序的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#665]
**maptalks's version and what browser you use?**
----
master

**Issue description**
----

如果开发的插件是插入dom标签，就是不是利用原生开放出来的CanvasRender（在maptalks-canvas-layer的canvas上进行绘制）的，而是自己自定义一个DOM元素（例如：maptalks.es插件，在maptalks-front-static插入了一个DIV来做为echarts的容器），这时maptalks-canvas-layer 上canvas绘制的图形会被自己写的插件的DOM上的内容遮盖（包括maptalks.es,和上次我写的Echarts-gl插件都存在这个问题），maptalks-canvas-layer的canvas上可能绘制点，这时点就会被覆盖，按照正常的理解，点应该在自己绘制的图形的上面（即点永远在最上面，可能是我用惯leaflet的原因，我记得leaflet里，market是单独放在一个层级更高的图层里，点永远在绘制的线，面等图形上面）

maptalks.es demo:

![2018-04-26_125630](https://user-images.githubusercontent.com/25998927/39286596-57eb58b2-4951-11e8-8d90-9583b8a5c9a7.png)

按照我的理解这个点应该在Echarts图层上面，而不是被遮盖（当然我知道这个是有层级不同导致的）

包括我写的echarts-gl demo:
![2018-04-26_130050](https://user-images.githubusercontent.com/25998927/39286692-f639e2ae-4951-11e8-8e9a-07056c3486fd.png)

如果利用CanvasRender 是不存在改问题：

我写的插件
![2018-04-26_130408](https://user-images.githubusercontent.com/25998927/39286829-a58f090a-4952-11e8-8cf1-4f75bb05303d.png)

maptalks.trhee插件

![2018-04-26_130435](https://user-images.githubusercontent.com/25998927/39286843-bb4caef0-4952-11e8-8dec-d641c4fe82bf.png)

针对该问题有好的解决方案吗？或者可以提供一些思路。或者框架层做支持呢？

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
renderer是dom时确实存在层级的问题

maptalks里的解决方案是提供了两个static div, 除了你提到的maptalks-front-static还有一个maptalks-back-static，back-static会把图层放到canvas下面

你可以代码中指定使用front static容器还是back static容器，例如e3插件是在options的container中设置front/back，renderer根据这个配置来获取图层容器：[源代码](https://github.com/maptalks/maptalks.e3/blob/master/index.js#L172)

leaflet默认的marker是用dom实现的，放置在最上层的一个div中，maptalks中也有类似的设计，不过maptalks里叫UIMarker（以和普通的Marker区分，普通Marker只会用canvas渲染）

**Comment by deyihu** [comment]
@fuzhenn  当我将 将  'container' : 'back',后，echarts 的容器直接被底图覆盖，按道理底图应该是最低的层级，如果底图的层级比 back还高，static back没有存在的意义啊
![2018-04-26_155429](https://user-images.githubusercontent.com/25998927/39293175-c5ee14a8-496a-11e8-8f4f-179fc7661826.png)

加载完瓦片的地方会直接遮盖，还没有加载完瓦片的地方还可以看到 echarts 容器的DIV

**Comment by fuzhenn** [comment]
hmmm.. 目前我没想到特别好的办法，有个不那么优雅的解决方案：
1. 还是把e3放到back static容器里
2. 在map下面叠加一个新的baseMap实例，给它只添加底图
3. 同步map和baseMap， [示例](http://maptalks.org/examples/cn/map/sync-map/#map_sync-map)

**Comment by fuzhenn** [comment]
另外ecgl和e3如果能用canvas来初始化（而非dom容器），把图层做成canvas layer的话，也能完美解决这个问题，可惜他们目前还不支持。

有个思路，在插件图层的renderer里用dom初始化，然后覆盖CanvasRenderer中的getCanvasImage方法，单独把dom中的canvas(echarts会生成好几个canvas，需要合并一下)返回给map renderer，这样就可以把图层做成canvas layer

**Comment by deyihu** [comment]
@fuzhenn  我试试，本来我想能不能将瓦片渲染的这块分离出来的，比如放在back static的下面，正常的图形渲染还是放在canvas layer里，然后插件开发的时候可以将插件放在back里，也可以用canvasRender里，也可以放在front里，这样就比较好了，不过我知道改动比较大

**Comment by fuzhenn** [comment]
@deyihu 确实可以考虑单独把baseLayer挪到一个最底层的独立canvas里，如果对性能影响不大，这样改写是最合适的。

晚点我做一下性能测试，比较一下两个canvas叠加和离屏渲染，性能上有没有区别

**Comment by fuzhenn** [comment]
这个问题还需要进一步的研究，就不包含在下个版本里了

我之后会找个专门的时间看一下这个问题
