### ISSUE TITLE
ArcCurve cannot  identify it

### ISSUE THREAD

**Issue by lifefriend** [maptalks/maptalks.js#666]
**maptalks's version and what browser you use?**

maptalks v0.39.5

**Issue description**

Draw a ArcCurve line on map use default setting,then use map.identify to identify  it,  cannot  identify it

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Thanks for your issue.

I didn't reproduce the issue you reported, this is [my jsfiddle](http://jsfiddle.net/fuzhenn/ft849muc/)

Could you please provide a minimal reproduction jsfiddle? Thanks.

**Comment by lifefriend** [comment]
[http://jsfiddle.net/sevxfqe3/](http://jsfiddle.net/sevxfqe3/)

**Comment by lifefriend** [comment]
Draw a ArcCurve line on map,then click it, click at diffent point , sometime can  identify it(middle)  sometime cannot (start or end)

[jsfiddle](http://jsfiddle.net/sevxfqe3/1/)

**Comment by fuzhenn** [comment]
I tried your fiddle, it works as expected.

What's your browser and OS?

![image](https://user-images.githubusercontent.com/13678919/39343071-8a5856ee-4a0d-11e8-999e-a74d351fa54a.png)

**Comment by lifefriend** [comment]
![image](https://user-images.githubusercontent.com/23650125/39343691-d1d98918-4a10-11e8-8ec0-56c39aa3ca50.png)

chrome Version 65.0.3325.181
windows 10

**Comment by fuzhenn** [comment]
Sorry, I still can't reproduce this bug.
I changed your fiddle a little bit: increase arc's line width to 5 px.
Could you have a recheck if it is resolved now? Thanks!

http://jsfiddle.net/sevxfqe3/2/

**Comment by fuzhenn** [comment]
Ah, I have reproduced the bug.
When the bug occurs, it seems only part of the arc can't be identified.
I'll have a check what the problem is.
