### ISSUE TITLE
高分屏下鼠标手势的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#668]
**maptalks's version and what browser you use?**
----

master

**Issue description**
----

当在高分屏下，canvasRender上绘制的图形，鼠标move上来，鼠标的手势并不会更改为小手，恰恰在该坐标的放大两倍的地方可以出现手势

![2018-04-28_130415](https://user-images.githubusercontent.com/25998927/39392224-e9f211f8-4ae4-11e8-8374-5b6b3a58fdfa.png)

应该是   
 maptalks.Browser.retina ? 2 : 1；

这个引起的吧

**Please provide a reproduction URL (on any jsfiddle like site)**
----

http://maptalks.org/examples/cn/hellolayer/drawoninteracting/

**Comment by fuzhenn** [comment]
@deyihu 这个问题我试着改掉了，不过因为手头没有高分屏的电脑（手机或chrome模拟不出这个用例）
帮忙用master分支上的代码验证一下这个问题是否改好吧

**Comment by deyihu** [comment]
@fuzhenn  ok的
