### ISSUE TITLE
About  map.getExtent()

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#669]
**maptalks's version and what browser you use?**
----

**Issue description**
----

以全球图为列，当地图缩放到小的级别时，瓦片会重复平铺渲染

![2018-04-29 13-35-55](https://user-images.githubusercontent.com/25998927/39403601-4889f6b8-4bb2-11e8-8e5f-c4ea88156149.png)

这时访问map.getExtent() 会发现获取的Extent 会出现异常，xmax居然比xmin还小（或者ymax比ymin小）
![2018-04-29 13-38-27](https://user-images.githubusercontent.com/25998927/39403625-bdaa8822-4bb2-11e8-9308-41b4ddfd9c32.png)

如果以右下角和左上角的屏幕坐标对应的经纬度值看，这个是对的，但是总感觉怪怪的；
然后我设置了 TileLayer 的 repeatWorld=false 发现问题依然存在；

接着我试了一下leaflet,虽然边界也会溢出（超过-180,90;180,90这个范围），但是没有发现maxlng<minlng这种情况；

![2018-04-29 14-27-10](https://user-images.githubusercontent.com/25998927/39403911-73f62162-4bb9-11e8-8700-d6d8f5f87b81.png)

然后我又看一下mapbox-gl.js 其也会进行边界的溢出，但是也没有发现maxlng<minlng这种情况；
发现边界会随着自己的拖动，进行线性增大；自己在上面绘制的图形会看不到了，但是如果我在拖动回来又可以看到自己添加的图形了

![2018-04-29 14-49-14](https://user-images.githubusercontent.com/25998927/39404031-8f4e24b6-4bbc-11e8-8538-9ecfe4bf9e10.png)

接着就是maptalks了，
![2018-04-29 14-45-52](https://user-images.githubusercontent.com/25998927/39404014-295f8154-4bbc-11e8-9958-e4515e23c4d7.png)

这个样子是对的，可以看见图形，但是Extent的值感觉不对
然后拖动地图

![2018-04-29 14-52-34](https://user-images.githubusercontent.com/25998927/39404050-181c1ac8-4bbd-11e8-8c8c-7459016e391b.png)

随着自己拖动地图，发现自己在地图上添加的图形不见了，但是 map.getExtent()；发现其值还是在-180,90;180,90这个范围，但是我添加的图形是在这个范围的啊

获取Extent的值，xmax比xmin还小这个有点不能理解（当然如果以屏幕对应的经纬度坐标的确是对的）

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
以最后一张图为例子，ymax为82，ymin为84，首先这个最大值比最小值还小感觉不对，而且地图明显横跨那么大的纬度区间也没有了

**Comment by fuzhenn** [comment]
真正的extent值其实是map._get2DExtent(), 它是正常的， map.getExtent()是把四个角的2d坐标转化为**正确的**经纬度，所以才会出现上面所述的情况。而在内部计算时，都是基于2d extent(2DExtent)来计算，所以不会出现错误。

leaflet和mapbox-gl的extent坐标值是线性增长的，但会出现lng或lat 超过合法值的情况（例如lng超过180或低于-180），这也会导致一些其他的bug。

这个问题感觉暂时没有**绝对正确**的做法。

另外，maptalks没有实现重复世界(repeatWorld)的重复绘制，因为世界重复绘制并不是一个**必须**实现的特性，但会明显增加插件的开发难度，所以综合考虑，就没有实现了。

**Comment by deyihu** [comment]
@fuzhenn  好的，我已经想打解决的方法了

**Comment by fuzhenn** [comment]
👍 能不能大概讲一下是怎样的解决方法？

**Comment by deyihu** [comment]
@fuzhenn  我是开发插件时需要用到这个函数，然后遇到了一些问题，不过我用其他的方法解决了，不是解决你说的这个问题，可能我没有说清楚

**Comment by fuzhenn** [comment]
既然问题已解决，先关闭此issue
