### ISSUE TITLE
关于地图动态设置坐标投影的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#670]
**maptalks's version and what browser you use?**
----

**Issue description**
----

如果Map设置了坐标投影信息（spatialReference）
  
瓦片可以正常加载   http://jsfiddle.net/j8t6171w/

**如果去掉Map的坐标投影信息，仅仅设置  TileLayer的坐标投影信息（spatialReference）**

**瓦片加载不出来，即地图没有读取TileLayer 的spatialReference 作为自己的投影信息  ，浏览器都是死掉的     http://jsfiddle.net/p08sLbnh/1/**

当然如果是加载 TileLayerGroup，TileLayerGroup里面的 TileLayer 集合的投影必须一样，否则加载坑定有问题

当使用layerSwitcherControl图层切换控件（这时TileLayerGroup里的TileLayer的投影配置可以不一样的，我认为是这样奥，因为是单选的吗，只有一个TileLayer加载到地图上），地图不设置投影信息，如果TileLayerGroup 里设置不同的投影瓦片图层，这时地图对象并不会动态的根据当前选择的TileLayer的投影配置去设置自己投影信息
http://jsfiddle.net/7mspynxy/2/

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
@fuzhenn  

地图不设置 spatialReference，TileLayer分别设置自己的spatialReference，可以加载，但是明显瓦片被缩放了或者形变了；

https://deyihu.github.io/src/html/1.html


如果动态的设置地图的spatialReference   （map.setSpatialReference(tileLayer.options.spatialReference);
这时加载就有问题了  

https://deyihu.github.io/src/html/2.html

当底图动态的添加和移除，会发生底图覆盖绘制图形要素的问题，需要手动设置VectorLayer 的zIndex或者 对 TileLayer 进行 bringToBack，这个也是上次我说的底图渲染会覆盖渲染的图形同样的问题

https://deyihu.github.io/src/html/3.html

**Comment by fuzhenn** [comment]
那个浏览器卡死的问题是瓦片图层空间参考设置的不对造成的，resolution设置的太小，导致一屏的瓦片太多，造成卡死。
单独设置瓦片图层的空间参考必须要小心，其原理是：地图根据当前的地图范围，来动态计算屏幕中应当载入的瓦片，然后按照地图当前的res和瓦片图层的res来动态调整瓦片的大小，如果瓦片图层的res和地图的res相差太大，就会出现这种情况。

GroupTileLayer里每个TileLayer目前确实不支持设置不同的SpatialReference的，我会看一下是否能实现

先回答一下今天的三个问题：

1 如果TileLayer有自己的空间参考，它的瓦片大小都是动态计算的，所以出现拉伸是正常的，但第一个google图层的空间参考与地图是相同的，不应该出现拉伸

2. 加载有什么问题？

3 是正常的，addLayer永远会把图层设置在最上层，改用setBaseLayer即可

**Comment by deyihu** [comment]
@fuzhenn
  第三个问题我知道了，我做了相关的处理；
   
 第一个问题，谷歌和高德的的确没有问题，但是天地图和百度的出现拉伸的情况，我所理解的每个底图都可以有自己的空间参考，当地图切换底图时，应该读取当前底图的空间参考作为自己的参考（如果当前地图上有多个底图，他们的空间参考必须一模一样，只要有一个不一样，就认定为出错，因为地图的空间参考不能有多个），但是可以动态的切换，可以随着加上来的TileLayer （一个或者多个）动态的切换，其实这个就是我说的第二个问题，第二个问题https://deyihu.github.io/src/html/2.html
这里动态的切换底图，我主动的设置到了地图的参考（该参考由加上来的TileLayer决定），来回切换底图，发现瓦片没有拉伸的情况



      function switchLayer(name) {
          if(currentLayer) map.removeLayer(currentLayer);
          var tileLayer=tileLayerMap[name];
          if(tileLayer){
              map.setSpatialReference(tileLayer.options.spatialReference);
              map.addLayer(tileLayer);
              currentLayer=tileLayer;
          }
        // map.addLayer(layer);
      }

这个例子运行是没有问题的，底图也没有出现拉伸的情况，可以说是非常完美了，但是当手动调整pitch>0时，在进行TileLayer的切换，然后又是卡死了，如果pitch=0则非常完美，没有任何问题，三个图层分别是Google，高德，和百度的，出问题的总是在百度那个

**Comment by fuzhenn** [comment]
明白了。

目前map是不会自动从tilelayer上读取空间参考的，原因是如果用户不需要自动处理时，会比较麻烦。

类似例子2，手动把tilelayer上的空间参考设置给map会更合理，至于pitch会卡死的问题，听上去是个bug，我会重现修改一下

**Comment by fuzhenn** [comment]
总结一下需要解决的问题：
1. GroupTileLayer考虑支持每个layer都能设置自己的空间参考
2. pitch不为0时，设置map的空间参考时会卡死地图

**Comment by deyihu** [comment]
GroupTileLayer 倒不是要考虑支持每个layer都能设置自己的空间参考，因为他是一个集合，是一起加到地图上，他们的空间参考必须一致，主要是图层切换控件的问题，图层切换控件是单选（TileLayer/GroupTileLayer）的，这个时候每个图层/图层组  是单独的加到地图上去的，他们可以有自己的空间参考，地图的参考可以随着加上去的图层来切换


比如我现在也在做一个图层切换控件，

![2018-05-04 19-47-32](https://user-images.githubusercontent.com/25998927/39626365-2cf88bc8-4fd4-11e8-8d6e-52ea0373160c.png)



![2018-05-04 19-47-05](https://user-images.githubusercontent.com/25998927/39626407-4d4bb0ee-4fd4-11e8-8511-ea80ead0e191.png)



![2018-05-04 19-47-49](https://user-images.githubusercontent.com/25998927/39626425-5f47d3a4-4fd4-11e8-9bc6-66f8132650f4.png)


![2018-05-04 19-48-03](https://user-images.githubusercontent.com/25998927/39626438-69f2903c-4fd4-11e8-9196-518d699201b4.png)


四个图层分别是谷歌，天地图，高德，百度，投影分别为EPSG:3857,EPSG:4326,EPSG:3857,BD09

四个图层的投影是三种情况，我希望自己在切换是可以动态的改变地图的投影，其中天地图有点特殊，因为是两个（一个基本底图，一个标注图层）TileLayer一起加上去（这时候可以用到GroupTileLayer了），他们两个作为一个整体加上去的

**所以问题是图层切换控件支持不同的空间参考**

**Comment by fuzhenn** [comment]
我想可以考虑给图层切换控件增加图层切换事件。
可以在事件中来手动切换地图的空间参考，类似：
```js
layerSwitcher.on('layerchanged', e => {
   const sp = e.layer.options.spatialReference;
   if (sp)  map.setSpatialReference(sp);
});
```
这样灵活性更好，你觉得如何？

**Comment by deyihu** [comment]
棒棒哒，如果TileLayer 的spatialReference 没有赋值，就给地图一个默认的spatialReference,如果TileLayer的 spatialReference赋值了，但是只给了pro没有赋值res,就默认设置一个值，比如 4326和3857通用的 分辨率的默认值，目前的问题是pitch>0卡死的问题

**Comment by fuzhenn** [comment]
已经增加了新的事件：
```js
layerControl.on('layerchange', e => {
  const layer = e.target; 
  ...
};
```
