### ISSUE TITLE
使用toDataURL打印地图的时候，文件过大会提示下载失败

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [maptalks/maptalks.js#674]
**maptalks's version and what browser you use?**
----
maptalks v0.39.8   Chrome

**Issue description**
----
使用toDataURL打印地图的时候，文件过大（宽度为浏览器宽度，若地图容器较小，不会出现类似问题）会提示下载失败

**Please provide a reproduction URL (on any jsfiddle like site)**
----
[测试地址](https://liquid-zhangliquan.github.io/zhangliquan.github.io/toDataURL.html)

**Comment by fuzhenn** [comment]
works well with even 20000 * 20000 div container

It seems more likely an enviroment related problem rather than maptalks
