### ISSUE TITLE
我成立了全球首家maptalks技术交流组织

### ISSUE THREAD

**Issue by houxieyu** [maptalks/maptalks.js#676]
群号：291020637
希望fuzhenn老大先别封这个帖子，更希望老大亲自领导组织

**Comment by fuzhenn** [comment]
首先感谢你的支持，哈哈

不过很不好意思，我还是得关闭这个issue。

这里解释一下：相较这里，qq群不太适合讨论bug或新功能，群留言凌乱也不方便组织，所以我还是倾向于github issue。当然很欢迎你为大家提供讨论场所，我目前因为主要精力在新功能开发上，现在就暂时不加入了。

等未来maptalks稳定版发布，如果那时这个qq群的人数足够多，可以就把你的群设为官方群。

再次感谢！
