### ISSUE TITLE
关于 ArcCurve 地图放大后  鼠标事件不能捕获的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#677]
**maptalks's version and what browser you use?**
----

**Issue description**
----

ArcCurve 绘制后，添加鼠标事件，捕获不到，绘制的节点处可以点击，地图缩放小的级别 弧形轨迹可以点击，当地图放大后完全捕获不到

https://deyihu.github.io/src/html/geometry_curve.html

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
谢谢！
 #666 已经报告过同样的问题，先关闭本issue
