### ISSUE TITLE
关于 infoWindow 位置的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#678]
**maptalks's version and what browser you use?**
----

**Issue description**
----

Marker 绑定  infoWindow ,如果 图片填充 infoWindow的位置是正确的，如果是Text填充infoWindow位置往上偏移，如果是矢量填充，位置偏移实在是太大了

https://deyihu.github.io/src/html/4.html

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这个问题应该是计算infowindow偏移量时，没有考虑marker的alignment造成的
