### ISSUE TITLE
how to load MapServer like export?format=png8

### ISSUE THREAD

**Issue by lifefriend** [maptalks/maptalks.js#681]
**maptalks's version and what browser you use?**
----

**Issue description**
----
How to load map like "ServiceEngine/rest/services/bncs/MapServer/export?format=png8&size=1000%2C675&f=image&dpi=96&bbox=114%2E15264446393343%2C30%2E473986893958408%2C114%2E49528057233186%2C30%2E705729752845127&transparent=true", 
thanks

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
It looks like a WMS like service.

You can write your own tilelayer class to create request url on the fly like [WMSTileLayer](https://github.com/maptalks/maptalks.js/blob/master/src/layer/tile/WMSTileLayer.js).

And you can [pack it as a plugin](https://github.com/maptalks/maptalks.js/wiki) for further reuse.

**Comment by sakitam-fdd** [comment]
@lifefriend I provide a plugin for this，you can view [TileArcGISRest](https://github.com/sakitam-gis/maptalks.esri/blob/master/demo/TileArcGISRest.html)。

**Comment by fuzhenn** [comment]
closing as lack of activity
