### ISSUE TITLE
关于隐藏地图容器，然后在显示的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#684]
**maptalks's version and what browser you use?**
----

**Issue description**
----

如果隐藏地图的容器，然后在显示地图容器，会报错

我看MapRender里有个动画函数动态的绘制Layers,最后异常抛出在绘制TileLayer里的

![2018-05-22_144857](https://user-images.githubusercontent.com/25998927/40346420-5c7877c4-5dcf-11e8-832a-425e1e40f66b.png)

应该是没有找到width和height的原因引起的，上次我测试全屏时也有这个问题

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
duplicate of #692
