### ISSUE TITLE
关于使用 ConnectorLine 连接 UIMarker 的调用问题

### ISSUE THREAD

**Issue by ymq001** [maptalks/maptalks.js#685]
请楼主写一个示例,我调用总是出错
![tim 20180525164655](https://user-images.githubusercontent.com/7494137/40535306-44fbacc4-603b-11e8-8c2d-0582a0742a8f.png)

**Comment by fuzhenn** [comment]
欢迎提issue，uimarker的连接线的示例：

http://jsfiddle.net/j9f2dLkj/

**Comment by ymq001** [comment]
是这样的 我这边需要把一个点和一个uimarker或者html结构面板连接起来 然后缩放地图后 连接线长度不变化，请问可以有什么方法做到么？
我注册了zoomend事件 然后通过 setCoordinates 改变 panel 位置 无效果

**Comment by fuzhenn** [comment]
hmm.. 

只要连接端点会根据地图变化改变位置，ConnectorLine也一定会随时发生变化的

你是想允许端点位置发生变化，但ConnectorLine一直保持不变吗？（方向，长短等）

**Comment by ymq001** [comment]
是的，原点(CoonectorLine 起点)位置不变，CoonectorLine 方向 长短 不随地图缩放而改变， 而是调整端点(CoonectorLine 终点)位置

**Comment by fuzhenn** [comment]
可以把原点和端点都设成[panel control](http://maptalks.org/examples/cn/ui-control/control-panel/#ui-control_control-panel)，Control是用像素定位的，不会跟随地图变化

**Comment by ymq001** [comment]
有没有左边转换为 屏幕像素的 或者 基于地图容器的像素偏移量的方法？
