### ISSUE TITLE
ThreeLayer和VectorLayer的图形无法按照真实三维关系渲染

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#686]
**maptalks's version and what browser you use?**
----

**Issue description**
----

ThreeLayer 进行房屋数据的渲染，
VectorLayer1进行LineString 的渲染
VectorLayer2 进行Marker的渲染

将 ThreeLayer 的zIndex 值设置大于VectorLayer1 的zIndex 可以使房屋的图形 对LineString 的图形进行遮挡

![2018-05-26 22-02-03](https://user-images.githubusercontent.com/25998927/40576943-858b7b02-6130-11e8-90c6-8408441b51d9.png)

然后就是VectorLayer2（Marker所在图层），如果 VectorLayer2的zIndex 值小于ThreeLayer  zIndex
的值，渲染效果是这个样子的

![2018-05-26 22-05-21](https://user-images.githubusercontent.com/25998927/40576979-f34ab928-6130-11e8-85be-52115b22e6dc.png)

marker会被房屋遮挡，当然这个是正常的，因为 VectorLayer2的zIndex 值小于ThreeLayer  zIndex的值

如果 VectorLayer2的zIndex 值大于ThreeLayer  zIndex的值,渲染效果是这个样子
![2018-05-26 22-07-59](https://user-images.githubusercontent.com/25998927/40577014-45ff8eaa-6131-11e8-83ed-263cd2b7ea6e.png)

marker后面的房屋不会在遮挡marker，但是marker前面的房屋也不会遮挡maker；

按照相机的概念，前面的房屋应该遮挡marker

当然我知道因为 房屋渲染和marker渲染不属于同一个场景中导致的（VectorLayer好像还是是canvas 2D渲染的不是 gl），LineString的数据和房屋数据也不在同一个场景中，但是可以手动的调整图层的zIndex的值的大小可以解决这个问题。

如果所有数据都在同一个图层中渲染效果是正常的，将 模型放到 ThreeLayer中,前面的房屋数据会遮挡 模型

![2018-05-26 22-18-45](https://user-images.githubusercontent.com/25998927/40577118-c811353c-6132-11e8-8ed0-a79fa835c04c.png)

当然如果我利用ThreeLayer渲染所有的数据可以解决这个问题，但是为了方便还是想使用VectorLayer，
这个问题不知该怎么解决？这个和上次我说的底图层级问题还是不一样的，因为没有新的dom的产生，都是在CanvasLayer里进行数据渲染的

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
你推测的没有错，目前VectorLayer是用canvas渲染的，和ThreeLayer处于不同的canvas容器， 所以他们是无法保证三维关系的。

在maptalks的设计中，不同的图层都有自己的canvas容器，所以不同图层，即使他们都是webgl渲染，也无法保证三维关系。

除非所有图层都在同一个webgl context中渲染，才能达到你想要的效果。

图层的作用就是组织图形，并能调整zindex，所以这个设计倒没有问题，但确实不同gl图层不能保证三维关系是有点麻烦的。

我们正在开发一个新库以尝试解决这个问题，这个issue我先不关闭。

**Comment by fuzhenn** [comment]
这个问题已经解决，晚些时候我们会把相关的插件和库发布出来。 😆
