### ISSUE TITLE
关于maptalks增加typescript类型文件的问题

### ISSUE THREAD

**Issue by ymq001** [maptalks/maptalks.js#687]
maptalks项目可否拉出一个分支使用Typescript写就，或者增加一个Typescript类型文件？
毕竟现在使用ts作为规范语言的越来越多了

**Comment by fuzhenn** [comment]
好主意，可以增加一个d.ts文件

不知道有没有基于注释的自动生成工具。

**Comment by ymq001** [comment]
https://blog.csdn.net/u011537073/article/details/60475636  
之前找到一个包,不过当时没有尝试转换成功,后来没那么多时间了,就没验证了, 你可以试下

https://www.npmjs.com/package/tsd-jsdoc

**Comment by fuzhenn** [comment]
duplicate of #699 , closing for now

**Comment by luo-geng** [comment]
同意，建议新建一个ts分支。后面的js可以用gulp直接生成，这样也不用维护typings了，可以直接生成
