### ISSUE TITLE
关于继承UIComponent 的UI组件 变换坐标不更新HTML内容的建议

### ISSUE THREAD

**Issue by ymq001** [maptalks/maptalks.js#688]
可否在 UIComponent 基础上增加一个 是否更新 UI (HTML)内容的 配置, 这样就可以避免 UIMarker 里面 iframe 频繁刷新的问题

**Comment by fuzhenn** [comment]
能否帮忙基于[这个jsfiddle](http://jsfiddle.net/fbyzfwmm/)来重现一下你说的这个iframe频繁刷新问题，谢谢

**Comment by ymq001** [comment]
http://jsfiddle.net/j9f2dLkj/2/

这里我只做了地图缩放后重新设置 uimarker 的位置,并没有做其他操作, 按说不应该重新加载UIMarker的内容

**Comment by zhangpeichuan001** [comment]
![image](https://user-images.githubusercontent.com/7494137/40600559-79081a0c-6284-11e8-8813-5eaf5aec0033.png)

**Comment by ymq001** [comment]
https://github.com/maptalks/maptalks.js/issues/688#event-1648729254

**Comment by ymq001** [comment]
https://jsfiddle.net/zhangpeichuan/jezq7qmg/1/

我覆写了UIMarker.setCoordinates和UIComponent.show方法解决了这个问题,但是 还是建议增加一个配置之类的

**Comment by fuzhenn** [comment]
这个建议很赞，我晚点会按你的思路实现一下
