### ISSUE TITLE
请问一下，我用绘制工具画的图形，如何给这个图形添加更多的属性，比如标题之类的属性

### ISSUE THREAD

**Issue by crstudio** [maptalks/maptalks.js#689]
drawTool 这个工具，接下来我应该用到哪些api？
没有赞助赞助链接吗？很想支持作者 :)

**Comment by liubgithub** [comment]
对绘制的要素调用setProperties()方法，geometry.setProperties({title:'标题' }), 具体可查看http://maptalks.org/maptalks.js/api/0.x/Geometry.html#setProperties

**Comment by liubgithub** [comment]
监听下drawtool的绘制完成事件
```js
drawtool.on('drawend',function(param){
   //你绘制的要素
  var geo = param.geometry;
});
```

**Comment by fuzhenn** [comment]
closing，will reopen if necessary

@crstudio 谢谢你的好意 😄
