### ISSUE TITLE
dbClickZoom失效

### ISSUE THREAD

**Issue by betseyliu** [maptalks/maptalks.js#690]
**maptalks's version and what browser you use?**
----
maptalks v0.40.1， Chrome 66
**Issue description**
----
萌新在研究API的过程中，发现示例中map option中的dbClickZoom设置为false，但是双击还是能触发zoom

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://maptalks.org/examples/cn/map/sync-map/#map_sync-map

**Comment by fuzhenn** [comment]
应该是`doubleClickZoom`

http://maptalks.org/examples/cn/interaction/map-on-off/#interaction_map-on-off
