### ISSUE TITLE
关于地图对象创建报错的问题

### ISSUE THREAD

**Issue by gee1k** [maptalks/maptalks.js#692]
**maptalks's version and what browser you use?**
----
- maptalks `v0.40.2`
- chrome `66.0.3359.181`

**Issue description**
----
在地图初始化时会报以下错误，在Vue项目环境下使用，但不影响使用。由于目前我在赶项目周期，所有没有仔细查找问题所在，先提一下issue

**Please provide a reproduction URL (on any jsfiddle like site)**
----
![http://p7wghdplg.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20180603003140.png](http://p7wghdplg.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20180603003140.png)

![http://p7wghdplg.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20180603003548.png](http://p7wghdplg.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20180603003548.png)

**Comment by gee1k** [comment]
目前猜想可能是由于Vue 组件中创建之后，地图对象的 dom 还没有显示的原因造成的，我在 Vue 组件创建完成之后延迟一段时间再进行 地图对象初始化就不会存在这个问题

**Comment by fuzhenn** [comment]
你猜的没错，我按你的思路重现了这个bug：
http://jsfiddle.net/9nkL742x/1/

我晚点改一下，加个test case保证bug不再出现

**Comment by gee1k** [comment]
好的👌。我目前的解决方案是在Vue中nextTick中初始化地图。保证dom渲染完成之后创建地图

**Comment by fuzhenn** [comment]
fix in https://github.com/maptalks/maptalks.js/commit/24f2d0b69b384b8636ed13a1e916300c57a9de5e
