### ISSUE TITLE
vue 或者 react import 后无法加载

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#693]
**maptalks's version and what browser you use?**
* maptalks `v0.40.2`
* chrome `67.0.3396.62`
**Issue description**

vue 或者 react

``` jsx
 import * as maptalks from 'maptalks'
```
![image](https://user-images.githubusercontent.com/19517451/40956428-d0d86f40-68c2-11e8-9e7a-9251e798e82a.png)

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by sakitam-fdd** [comment]
解决了，现在需要 😄 
``` jsx
import * as maptalks from 'maptalks/dist/maptalks';
```

**Comment by fuzhenn** [comment]
奇怪..
这是为啥？

**Comment by sakitam-fdd** [comment]
看着像是webpack配置的问题，因为配置是我自己配的 :joy:
![image](https://user-images.githubusercontent.com/19517451/40958549-46b5acc4-68cc-11e8-8768-a2a64deb4a50.png)

**Comment by fuzhenn** [comment]
噢，我们也先验证一下react和vue里的载入
你要是搞清楚了原因，@我一下~ 看看maptalks这边是否有什么潜在问题

**Comment by sakitam-fdd** [comment]
嗯嗯，好的

**Comment by September9** [comment]
我在用react-bmap也遇到这个问题了，然后安装了0.39.8版本就好了

**Comment by fuzhenn** [comment]
@September9 
你是用的webpack打包吗？能否告知一下webpack的版本是多少？

**Comment by September9** [comment]
webpack 4.6.0

**Comment by fuzhenn** [comment]
感谢，看来应该是对webpack 4的兼容性问题导致的，我这两天会修改一下

**Comment by fuzhenn** [comment]
ok, it looks like [a bug of webpack 4 along with ProvidePlugin](https://github.com/webpack/webpack/issues/7032)

I will fall back to original `es.js` extension, and change back to `mjs` when this bug is resolved
