### ISSUE TITLE
maptalks 渲染地图 在低版本 safri 或 chrome 下 上下左右拖动地图一会儿 js报错 程序直接崩掉了

### ISSUE THREAD

**Issue by ymq001** [maptalks/maptalks.js#694]
![image](https://user-images.githubusercontent.com/7494137/41099433-1613c18e-6a91-11e8-9ced-e9d1b59795ed.png)

看源码得知：
TileLayerCanvasRenderer.js 文件 line: 645 报错, 
暂时解决方案：
加了判断 是否safri 的判断 暂时解决了这个问题
![image](https://user-images.githubusercontent.com/7494137/41099621-a5c1bda4-6a91-11e8-8760-d93ccd8ebfd8.png)

**# 但还是建议尽早解决下这个bug, 这个严重影响了使用体验**

参考资料： https://segmentfault.com/a/1190000002502194

**Comment by fuzhenn** [comment]
可以试试改成：
```js
tile.image.onload = null;
tile.image.onerror = null;
```
如果测试可行的话，帮忙提个pull request给我吧， 谢谢！
