### ISSUE TITLE
道路面的三维渲染-立交桥-如果不使用three插件，还有其他插件可以实现吗？

### ISSUE THREAD

**Issue by lileialg** [maptalks/maptalks.js#698]
请问能支持上道路面的3D效果吗，例如立交桥，期待您的回复

**Comment by fuzhenn** [comment]
可以的，不过需要借助插件。
目前实现立交桥比较方便的是[three](https://github.com/maptalks/maptalks.three)插件

**Comment by lileialg** [comment]
如果不使用three插件，还有其他插件可以实现吗？谢谢。

**Comment by fuzhenn** [comment]
能大概说一下你的需求吗？ 立交桥什么数据？大概想画成怎样的形式？
