### ISSUE TITLE
Typings for Maptalks

### ISSUE THREAD

**Issue by praveen-238** [maptalks/maptalks.js#699]
**maptalks's version and what browser you use?**
----v0.40.2

**Issue description**
----If there is typings for maptalks. please share it.

-

**Comment by fuzhenn** [comment]
Thanks!

No typing now. But I agree that typings is important and will find some time to look into it.

It's a boring work though, wonder if there is any automatic tool to generate typings from comment etc.

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.js/issues/2235
