### ISSUE TITLE
关于maptalks图层上绘制子画布和自定义的动画

### ISSUE THREAD

**Issue by JoyTroy** [maptalks/maptalks.js#701]
**maptalks's version and what browser you use?**
----v0.40.2 Google

**Issue description**
----maptalks能否在CanvasLayer(画板图层)或其他图层上绘制子画布(或者说创建子canvas对象)，并能控制其尺寸，获取该画布对象并绘制自定义的动画？
问题来源于，我们想在底图上先批量绘制小尺寸的子画布，再在这些子画布上绘制自己书写的动画(可能不调用maptalks的API)。

此方案是否可行？

**Comment by fuzhenn** [comment]
感谢提issue

听上去应该是可行的， 能不能稍微把需求讲的详细一些，最好能举个实际例子。

**Comment by JoyTroy** [comment]
好的，详细信息已发送到邮箱fuzhen@maptalks.org，请查收

**Comment by fuzhenn** [comment]
closing as answered
