### ISSUE TITLE
Layer 新建后并加到地图上，其渲染器 _renderer 里相关要素不会立即创建的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#703]
**maptalks's version and what browser you use?**
----

**Issue description**
----

Layer 新建后并加到地图上，如果这时获取Layer的_renderer 的 canvas 或者 context,其值为空。

我看了一下CanvasRenderer的draw 方法

CanvasLayerRenderer.prototype.draw = function draw() {
        this.prepareCanvas(); //准备canvas
        this.prepareDrawContext(); //准备context||gl
        this._drawLayer(); //渲染图形
 };

如果在CanvasLayerRenderer 的draw方法里进行Layer data的绘制没有问题，（当Layer添加到地图上立即访问Layer的其他方法）如果Layer的方法有访问Renderer的相关属性或者方法将出现 Renderer null的错误。

以 ThreeLayer这个插件为例，如果不在CanvasLayer的 prepareToDraw或者draw方法里去处理three.js的scene,camera 将出现以上的问题。

这个问题我看到了，有 MapCanvasRenderer，drawLayers(layers, framestamp);用了动画引起，导致Layers的 Renderer被延迟创建

**有是么方法可以使 Layer的 Renderer 不被延迟创建吗？就是当Layer被加到地图上后可以立即拿到其Renderder来进行操作。例如ThreeLayer被创建后并加到地图上后，可以直接拿到three.js的scene，camera等直接进行mesh的添加或者删除。而不是在  prepareToDraw里去进行相关操作**

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这是特意这么设计的。
主要是renderer有时需要异步创建，例如有些图层需要先读取外部配置后才能创建。

除了`prepareToDraw`方法，还可以监听图层的`renderercreate`事件（这个事件没记录在文档里），这个事件是所有图层都有的
