### ISSUE TITLE
希望新增一个捕捉工具

### ISSUE THREAD

**Issue by gongzk** [maptalks/maptalks.js#704]
希望新增一个捕捉工具，可以控制是否步骤点，是否捕捉边；
可以和绘制和编辑工具配合，在绘制或编辑要素过程中可以捕捉点或边。

**Comment by fuzhenn** [comment]
可以看一下自动吸附插件 `maptalks.snapTo`

https://github.com/liubgithub/maptalks.snapto/

cc @liubgithub

**Comment by gongzk** [comment]
谢谢，就是类似这种功能，不过目前只有在画线时捕捉功能稳定，绘制其它图形时bug较多，还不能在正式环境下使用......

**Comment by liubgithub** [comment]
@gongzk 欢迎在这个库下面提issue
