### ISSUE TITLE
绘制工具redo无效

### ISSUE THREAD

**Issue by gongzk** [maptalks/maptalks.js#705]
drawTool工具，在undo后，执行redo无效this._historyPointer === this._clickCoords.length判断为true

**Comment by fuzhenn** [comment]
感谢提issue！
我这里没能重现出来你报的bug

能帮忙写个简单的重现代码吗？ 你可以在下面的jsfiddle基础上修改一下
http://jsfiddle.net/3px4dfqb/

**Comment by gongzk** [comment]
修改了，主要是通过地图右键菜单来使用undo和redo，感觉是右键点击引起的问题。

**Comment by fuzhenn** [comment]
收到，重现链接:
http://jsfiddle.net/3px4dfqb/3/
