### ISSUE TITLE
添加 symbol 参数 设置当 textPlacement: 'line' 时可以自定义 lineString 文字间距

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#707]
maptalks v0.40.4

chrome v67.0.3396.99

----

希望可以添加 symbol 参数 设置当 textPlacement: 'line' 时可以自定义 lineString  文字间距。

放大层级比较大的时候这个间距是合适的，但当缩小的时候，文字间距并没有相应重新计算，造成大量的文字重复堆叠在路线上。

----
zoom: 16 
![image](https://user-images.githubusercontent.com/3621846/42031286-500e92c4-7b08-11e8-80dc-8db92a11e140.png)

zoom：12
![image](https://user-images.githubusercontent.com/3621846/42031044-740e6024-7b07-11e8-8a82-5b7c8fb0d812.png)

----

**Comment by fuzhenn** [comment]
这个确实是`textPlacement : line`的优化方向，不过这个功能的工作量比较大，需要等我安排出时间后会来做一下。

**Comment by PasserbyFluid** [comment]
@wordgold 请问这个线上文字的颜色是哪个属性  ，怎么在文档没有找到，求解~~ 
是看这里的文档吧：http://maptalks.org/maptalks.js/api/0.x/LineString.html#options

**Comment by wordgold** [comment]
@FluidCui  https://github.com/maptalks/maptalks.js/wiki/Symbol-Reference#text

**Comment by FluidCui** [comment]
var aline = new maptalks.LineString(lineArr[i].geometry.coordinates, {
					arrowStyle: null, // arrow-style : now we only have classic
					arrowPlacement: 'vertex-last', 
					visible: true,
					editable: true,
					cursor: null,
					shadowBlur: 0,
					shadowColor: 'black',
					draggable: false,
					dragShadow: false, 
					drawOnAxis: null, 
					symbol: {
						'lineColor': '#00FF36',
						'lineWidth': 3,
						 'textName'  :lineArr[i].properties.t,
						 'textPlacement' : 'line',
						 'textSize'  : 16,
						 'textDy' : -10,
						 'textFill ':'#ffffff'
					}
				})
@wordgold 请问这是我写的问题吗 ，我的不起效果 最后一行这样写的

**Comment by fuzhenn** [comment]
决定增加一个新的symbol属性 `textSpacing`，用于实现这个需求
