### ISSUE TITLE
canvas绘制时，高分屏适应问题

### ISSUE THREAD

**Issue by WindyNature** [maptalks/maptalks.js#711]
如果屏幕为高分屏，devicePixelRatio为2时，导致canvas绘制的内容与地图不适应。canvas绘制的内容在初次加载是适配的，但是在进行缩放后比例会发生变化。[如热力图：](http://maptalks.org/maptalks.heatmap/demo/)

1.初次加载

![image](https://user-images.githubusercontent.com/12809143/42252252-585967c8-7f6e-11e8-9168-6efc706861b9.png)

2.做操作后
![image](https://user-images.githubusercontent.com/12809143/42252014-29585034-7f6d-11e8-8be1-d91d97e0b2ac.png)

**Comment by fuzhenn** [comment]
感谢提出issue。
你贴的两张图是一样的，没看出区别。
我刚刚也试着重现了一下，也没有发现你说的问题，请帮忙更新一下贴图，另外请提供一下你的环境信息：
* 操作系统
* 浏览器版本和位数（32位还是64位）
* 液晶屏是否是高分屏

**Comment by WindyNature** [comment]
刚才网速有点慢，没有传成功哈，我更新了下贴图。
我的环境信息如下：

- 操作系统：macos

- 浏览器版本：65.0.3325.18（正式版本）dev （64 位）

- 屏幕为mac的retina屏幕哈。

**Comment by fuzhenn** [comment]
retina + macos + 67.0.3396.99 64位

windows 10 + 2k屏 + chrome

都没出现这个问题，晚点我们再多测试一下

**Comment by WindyNature** [comment]
刚才试了safari和firefox，以及更新chrome版本为67.0.3396.99后都没有这个问题了。应该是chrome 65.0.3325.18 64位这个版本会出现这个问题哈

**Comment by fuzhenn** [comment]
我在win10上用过很长一段时间的chrome65，还没有遇到过这个问题，应该是mac os的64位 chrome 65的特定bug。
既然65+不再有这个问题，那我就不去尝试修复了。

最后表达一下感谢，如果遇到其他bug，或有feature request，欢迎随时交流。
