### ISSUE TITLE
自定义图层设置 layer options 不起作用

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#712]
maptalks v0.40.4

maptalks.e3 v0.4.5

chrome v67.0.3396.99

----

自定义图层设置 layer options 不起作用

尝试修改 maptalks.e3 图层的 zIndex 和 opacity 时，发现没有起作用

----

https://jsfiddle.net/bpzuk06j/10/

----

**Comment by fuzhenn** [comment]
收到，maptalks.e3比较特殊，是基于div dom的图层，而不是canvas，所以普通的zindex和opacity机制对它不起作用。
我把这个issue转到maptalks.e3插件上，在maptalks.e3里单独处理

**Comment by fuzhenn** [comment]
redirected to https://github.com/maptalks/maptalks.e3/issues/6

closing this issue.
