### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by XiaoYongX** [maptalks/maptalks.js#715]
**maptalks's version and what browser you use?**
----

**Issue description**
----
你好，我是现在有个项目是用到这个的，其实这个地图制作有些方面比百度的都要好的，但是我在使用这个的时候有点痛苦，我英语不是很好，而且现在技术也不是很好，这个的文档让我看起来比较痛苦，就算我找到文档里自己需要的信息了，但是我也不一定会使用，就是建议能不能更加简单明了写，详细点的信息和一些小案例那就更好了。

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
谢谢你的建议！

中文示例是个起步的好地方：
http://maptalks.org/examples/cn/map/load/

API文档中包含了每个类的方法说明，但因为API是从代码自动生成的，所以暂时没有中文，不过因为api的英文比较简单，我想应该不会有太大问题
http://maptalks.org/maptalks.js/api/0.x/Map.html

如果需要自己开发插件，大部分高级教程也有相应的中文版
https://github.com/maptalks/maptalks.js/wiki

maptalks所有的文档也都是开源的，感兴趣的话你也可以参与改进。
