### ISSUE TITLE
marker的自动旋转问题

### ISSUE THREAD

**Issue by kzfile** [maptalks/maptalks.js#717]
**maptalks's version and what browser you use?**
----
0.40.3
**Issue description**
----
三维模式下,marker不能以一种贴到地面上的形式随着拖拽而旋转.
比较明显的是例程中的"端点沿线自动旋转Marker"",一旦视角切换到接近垂直于地平线,拖拽地图时,飞机的感觉就很奇怪了.
其实如果marker能像例程"有高度的多边形"那样随着拖拽而改变自己的角度就好了(可惜多边形无法在任何比例尺下保持大小一致,否则就能完全满足需求了)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://maptalks.org/examples/cn/style/line-marker/#style_line-marker

**Comment by fuzhenn** [comment]
因为目前VectorLayer是基于canvas渲染，所以Marker暂时不支持三维旋转

这个功能会在VectorLayer的gl renderer中提供支持

**Comment by fuzhenn** [comment]
有同学正在开发[UIMarker](http://maptalks.org/examples/cn/style/html-marker/#style_html-marker)的三维旋转功能，敬请期待

**Comment by fuzhenn** [comment]
closed by #766 

add 2 new options to UIMarker (and other UIComponents):

```js
new maptalks.UIMarker([0,0], { pitchWithMap: true, rotateWithMap: true, content }
```
