### ISSUE TITLE
实现setMask, 用来实现地图遮罩

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/maptalks.js#72]
遮罩的作用域: map或layer
1. 只显示遮罩内的内容
2. 可选择遮罩以外部分的样式, 例如半透明的黑色

![image](https://cloud.githubusercontent.com/assets/13678919/12084814/4a7f44dc-b2f3-11e5-92aa-f04e9550bd3e.png)

**Comment by brucin** [comment]
效果不错，接口也挺简单。
遮盖罩部分的样式设置也是标准的面symbo的形式吗？

**Comment by FuZhenn** [comment]
对，mask就是个标准的geometry，只允许polygon, multipolygon和 vector marker作为mask图形

symbol的定义和标准一样，但因为mask只是定义了图层的显示区域而不会显示出来，所以大多数的symbol定义不起作用， 只有少数决定大小的属性有用

例如markerHeight和markerWidth

**Comment by brucin** [comment]
我指的是显示区域以外的广大黑暗区域的样式设置问题。

**Comment by FuZhenn** [comment]
那个样式不由遮罩实现，例子里我直接设的div的background
![image](https://cloud.githubusercontent.com/assets/13678919/12644526/53aed720-c5fe-11e5-977e-a3e19a6a696a.png)

layer的mask定义了显示区域， 其余部分都是透明的

**Comment by brucin** [comment]
哦，那么没有问题了。
