### ISSUE TITLE
批量绘制复杂图形时的性能问题

### ISSUE THREAD

**Issue by JoyTroy** [maptalks/maptalks.js#720]
**maptalks's version and what browser you use?**
----v0.40.2 Google

**Issue description**
----最近尝试绘制复杂图形时遇到这类性能问题，原理是通过new maptalks.Sector方式绘制了100个扇形，并通过控制其角度拼接成一个完整的圆，再通过动态控制所有扇形的半径由小到大不断循环，以实现一个圆形(被分割成100份)不断扩散的效果。

我尝试借鉴canvas离屏画布的方式，构建了离屏图层：
1、在离屏图层上绘制图形；
2、将图层转换成json(toJSON(optionsopt))；
3、将该json赋予新图层((static) fromJSON(layerJSON))；
4、将新图层添加到地图上；
但似乎并没有效果，浏览器仍旧在大量调用API，导致性能问题；

另一种方式是将扇形数量减少到20个左右，勉强流畅，但这样纯粹是逃避问题；

所以想请教有没有更好的办法？
离屏图层的方式是否具有可行性？

**Please provide a reproduction URL (on any jsfiddle like site)**
[----]
[单个](https://jsfiddle.net/fjtjintang/pc8vuLn6/1/)
[五个](https://jsfiddle.net/fjtjintang/3jgm18dq/17/)

**Comment by fuzhenn** [comment]
速度慢是因为扇形数量过多导致的

为什么不直接用圆形吗？是需要这种圆心连线效果吗？

**Comment by JoyTroy** [comment]
：D  
原本一开始只是部分的、扇形的区域扩散，现在看看......确实直接用圆心连线效果更合适啊。。。请问有示例参照不？

**Comment by fuzhenn** [comment]
这种复杂图形的绘制基于canvas貌似没有太好的解决方案，可能最终还是需要用webgl绘制来解决。

我在考虑增加一个GLLayer，把webgl的context暴露出来方便调用，到时候可以基于GLLayer来实现这个需求。
