### ISSUE TITLE
DrawTool 绘制矩形的问题？

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#722]
**maptalks's version and what browser you use?**
----

**Issue description**
----

http://maptalks.org/examples/cn/interaction/draw-tool/raw/index.html

当pitch=0,绘制 矩形没有问题；

当pitch>0 时，按正常的理解，拖拽时，应该形成一个等边梯形，类似鹰眼控件里形成的等边梯形

![2018-07-17_164933](https://user-images.githubusercontent.com/25998927/42806725-aa82e4a2-89e1-11e8-9b77-657f2e070fac.png)

目前是在地图上形成一个动态的矩形，绘制完成后，在地图上看见一个矩形（对二维平面来说是矩形，实际应该是一个等边梯形）

![2018-07-17_165330](https://user-images.githubusercontent.com/25998927/42806972-35109e84-89e2-11e8-8701-0e384280df91.png)

然后我调整pitch=0;发现不是等边梯形
![2018-07-17_165640](https://user-images.githubusercontent.com/25998927/42807179-b77dcc84-89e2-11e8-8d14-8cb704524efc.png)

然后我再调整pitch到（刚才绘制这个矩形时候的ptich值），发现也不是刚才绘制的矩形，
![2018-07-17_170057](https://user-images.githubusercontent.com/25998927/42807302-01640160-89e3-11e8-94ab-08ed5cf6a776.png)

这时期望的结果应该是这个样子的

![2018-07-17_165330](https://user-images.githubusercontent.com/25998927/42806972-35109e84-89e2-11e8-8701-0e384280df91.png)

关于这个问题是有问题的呢？还是设计如此?能说一下嘛？没看明白

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这个是刻意这么设计的，绘制的是当前viewport上的矩形。

这个是若干个项目的功能设计要求，如果你需要其他模式的Rectangle绘制，可以参考现在的rectangle，[自己扩展一下drawtool](https://github.com/maptalks/maptalks.js/blob/master/src/map/tool/DrawToolRegister.js#L94)。
