### ISSUE TITLE
ShapeFile Loading

### ISSUE THREAD

**Issue by praveen-238** [maptalks/maptalks.js#723]
**maptalks's version and what browser you use?**
--------
v0.40.2

**Issue description**
----
Is there any way to load shape files directly. I have gone through examples but didn't find a way to implement it.Please share it if there is anyway.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Thanks for submitting issue!

You can use [shapefile](https://github.com/mbostock/shapefile) to read shp files as geojson which can be added to VectorLayer directly.

```js
const layer = new maptalks.VectorLayer('v', geojson).addTo(map);
```

**Comment by fuzhenn** [comment]
closing, will reopen if you come back
