### ISSUE TITLE
map fov no more than 59 degree，when 60 degrees are set, the browser will be killed。

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#724]
**maptalks's version and what browser you use?**
----
maptalks: v0.40.4

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://jsfiddle.net/sakitamfdd/1Ldhjbou/

**Comment by fuzhenn** [comment]
这个问题现在貌似已经好了，可能是chrome后自动修正了？
