### ISSUE TITLE
使用react-native将其docs案例引入到工程中，使用webview渲染，ios正常，安卓只显示控件，没有底图，求教！！！

### ISSUE THREAD

**Issue by zhangqiang765721622** [maptalks/maptalks.js#729]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by zhangqiang765721622** [comment]
已解决，将http请求改为https即可

**Comment by fuzhenn** [comment]
👍
