### ISSUE TITLE
Request for Plugin for ESRI other services (not base tile)

### ISSUE THREAD

**Issue by satish71** [maptalks/maptalks.js#730]
**maptalks's version and what browser you use?**
Chrome, IE, Mozilla

**Issue description**
-request for ESRI feature maps (plugin) to support ESRI map services (similar) to Leaflet ESRI plug-in

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
We have a WIP plugin [maptalks.esri](https://github.com/maptalks/maptalks.esri) for ESRI services.
But we have a lot on the table, now we don't have much time to dedicate to the plugin.

I would be happy to have any PRs.

cc @praveen-238
