### ISSUE TITLE
执行 animateTo 后 其他图层无法及时显示，需要拖拽一下才会刷新

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#732]
"maptalks": "^0.40.5",

chrome last

----

在地图上叠加了多个图层，当执行 animateTo 时其他图层会消失，这里考虑到动画效率可以理解，
动画执行完后，消失的图层并没有及时显示，甚至有时 baseLayer 也会消失，需要拖拽一下才会显示

![ui-monitor-google-chrome-2018_7_31-17_22_47 1](https://user-images.githubusercontent.com/3621846/43453382-8ac8e6f0-94ec-11e8-8153-cc04b92600ce.gif)

**Comment by fuzhenn** [comment]
能麻烦提供一个重现代码吗？

**Comment by wordgold** [comment]
https://jsfiddle.net/0cmohaxk/24/

按住 ctrl 拖拽地图倾斜到一定程度，然后等待几秒执行 animateTo，会出现地图消失的情况，没有的话多试几次就出来了

还有，假如某图层数据量大的话（lines=19607），会出现 baseLayer 可以显示，图层无法及时显示的情况

抱歉由于数据涉密无法做大数据量展示，只好以 gif 做说明

**Comment by fuzhenn** [comment]
谢谢！

数据图层暂时消失可能是帧率控制造成的，可以给图层设置强制渲染来解决，具体可以参考这个issue https://github.com/maptalks/maptalks.three/issues/10

animateTo后消失的问题我重现了，这个应该是个bug，等我手头工作结束后就来对应。

**Comment by wordgold** [comment]
![image](https://user-images.githubusercontent.com/3621846/43498408-6812bfa4-9579-11e8-9a3b-f4c94eef871e.png)
设置了  forceRenderOnRotating: true, 后，当由倾斜状态执行 animateTo 时，出现图层和底图位置不匹配的状态

**Comment by wordgold** [comment]
```
map.animateTo({
          pitch: 0,
          bearing: 0,
        }, (f) => {
          rotate.style.transform = `rotateZ(${0 - map.getBearing()}deg) rotateX(${map.getPitch()}deg)`;
          if (f.state.playState === 'finished') { map.panBy([0.1, 0.1]); }
        });
```
现在是通过动画执行完后稍微位移一下来解决的
