### ISSUE TITLE
希望统合移动触发事件（囊括 moving，pitch，zoom，bearing，dragrotating 及 dragrotating 后的惯性动画）

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#733]
"maptalks": "^0.40.5",

我尝试添加一个自定义 control，希望在地图旋转，倾斜的时候使图标做相应的操作
现在监听了 dragrotating 和 viewchange

但在拖拽旋转后的惯性旋转时无法监听，使用 animateTo 触发的旋转倾斜也无法监听

希望添加一个触发器，可以监听地图任何的旋转，倾斜，移动

**Comment by fuzhenn** [comment]
viewchange 是个比较合适这个场景的事件，我会看一下为什么在你说的那几种没有抛 viewchange

**Comment by wordgold** [comment]
viewchange 是有正常触发的，但它是一次性的。
只是因为在惯性动画和 animateTo 执行过程中没有事件触发所以折衷选择了在 viewchange 时监听
还是希望在这两个执行过程中也可以有一个过程事件触发，类似于 moving 等的事件

**Comment by wordgold** [comment]
刚才查看源码 animateTo 和惯性动画里是有 animating 事件触发的，可能 API 文档没有更新还没列出来，关闭吧。
