### ISSUE TITLE
how to load an custom tile layer that was made out of an image

### ISSUE THREAD

**Issue by zhenyuan2015** [maptalks/maptalks.js#735]
**maptalks's version and what browser you use?**
----
0.40.4
**Issue description**
----
I make an tile map by using maptiler(http://www.maptiler.com/).The tile map does not contain geo info.
I found an leaflet plugin that can load this type tile layer(https://commenthol.github.io/leaflet-rastercoords/example/index.html).

how to correctly load an custom tile layer in maptalks.js?

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://commenthol.github.io/leaflet-rastercoords/example/index.html

**Comment by zhenyuan2015** [comment]
https://github.com/Leaflet/Leaflet/issues/1268

**Comment by fuzhenn** [comment]
Thanks for your issue.

It looks like it's nothing special but just a set of regular 3857 tiles.

I wrote a simple jsfiddle to load example tiles you give:
http://jsfiddle.net/o45wz0ux/14/

It uses projected mercator coordinates to lay down the image tiles per pixel.

maptalks is capable to load any tile service with arbitrary tile systems, you can refer to [this wiki doc](https://github.com/maptalks/maptalks.js/wiki/Tile-System) for further information.

**Comment by fuzhenn** [comment]
closing now, will reopen if you come back.
