### ISSUE TITLE
使用鹰眼功能时，浏览器窗口改变时鹰眼中的多边形框无法移动。

### ISSUE THREAD

**Issue by Crush1013** [maptalks/maptalks.js#736]
**maptalks's version and what browser you use?**
----version 0.40.4         任意浏览器

**Issue description**
----在使用鹰眼功能时，当窗口发生改变时，鹰眼中的多边形框无法拖动。
      调试发现，getEventContainerPoint 这个函数获取容器点时，取了缓存中的点位置，浏览器窗口改变时没有重新获取位置。

**Comment by fuzhenn** [comment]
感谢提issue。

确实有这个问题，overview map应该监听主map的resize事件，调用checkSize方法

有兴趣提个PR给我吗？

**Comment by Crush1013** [comment]
额，我还不是很会玩github

**Comment by alex2wong** [comment]
小伙子接单了吗？不接我就去接这个pr了

**Comment by Crush1013** [comment]
你接吧，我还不是很会玩。。。

**Comment by alex2wong** [comment]
看起来最近的一个commit 已经fix 了，很棒。
