### ISSUE TITLE
希望 Marker 添加 rotation-alignment 可以选择根据屏幕或者地图做为旋转基准

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#737]
![image](https://user-images.githubusercontent.com/3621846/43674184-23b54b48-9802-11e8-9284-2af4d39e833c.png)
![image](https://user-images.githubusercontent.com/3621846/43674220-ede8aed2-9802-11e8-92dd-dacd90cae485.png)

我尝试添加 Marker ，希望可以根据地图做基准来调整方向，类似 mapbox 的以下代码：

```
layout: {
	'icon-rotation-alignment': 'map', // map or view
	'icon-rotate': rotate,
}
```

类似 http://maptalks.org/examples/cn/style/line-marker/#style_line-marker 此例中飞机的绘制效果

**Comment by fuzhenn** [comment]
这个功能可以用function type来支持：

http://jsfiddle.net/9xmhe8fu/3/

回头在example加个示例

**Comment by wordgold** [comment]
@fuzhenn 

```
          const rotate = bearing(point(this.task.Coordinate[0]), point(this.task.Coordinate[1]));
          car.updateSymbol({
            markerRotation: {
              property: '{bearing}',
              stops: [
                [-180, -180 - rotate],
                [180, 180 - rotate],
              ],
            },
          });
```

**Comment by fuzhenn** [comment]
你是想图标随地图旋转时，本身还有个rotation，达到 bearing + rotation 的效果吗？

**Comment by wordgold** [comment]
@fuzhenn
对，不过经你提醒，现在使用楼上的代码已经完全满足需求，不需要修改了。
