### ISSUE TITLE
TileLayer mask 不支持 MultiPolygon

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#741]
**maptalks's version and what browser you use?**
----

**Issue description**
----

Polygon 是可以的
  http://jsfiddle.net/cdghpjky/9/

切换到MultiPolygon,就不可以了
http://jsfiddle.net/cdghpjky/10/

我看文档里是支持

mask geometry, can only be a Marker with vector symbol, a Polygon or a MultiPolygon

当然用Polygon 来挖洞是可以做的
![2018-08-04 23-47-51](https://user-images.githubusercontent.com/25998927/43678176-d9ac7adc-9840-11e8-8202-e6c2930d06b7.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
目前的确不支持，文档里有误。

>> 当然用Polygon 来挖洞是可以做的

这个是指？

**Comment by fuzhenn** [comment]
@deyihu 截图中好几个polygon mask的效果是怎么做到的，指导下哈。
我把它实现一下发到下个版本里

**Comment by deyihu** [comment]
@fuzhenn  哈哈，TileLayer的mask怎么做的我没看源码，多个Polygon的这个我偷懒的（抖了个机灵），内部用了一个VectorLayer，然后画了一个大面，MultiPolygon作为其Holes来实现的，利用VectorLayer来对TileLayer遮盖

例如mask为 MultiPolygon,
[polygon,polygon,polygon.....],


然后内部
var polygon=[
 [[-180,-90],[-180,90],[180,90],[180,-90]],
polygon，
polygon，
polygon,
.......

]；

就是从全球的范围把这几个Polygon挖掉，让底图漏出来。

如果MultiPolygon的polygon中如果有带holes的就把holes拿出来，与全球范围的这个Polygon一样也加到VectorLayer上；

如果MultiPolygon中Polygon 不含有 hole的话，效果是上面的截图，如果MultiPolygon中Polygon 含有 hole的话，如下图

![2018-09-02 13-51-56](https://user-images.githubusercontent.com/25998927/44952669-b133a480-aeb7-11e8-869a-8692f116d1aa.png)


**不过这样做纯粹抖机灵，如果有多个TileLayer的话，当一个TileLayer设置了Mask，其他的TileLayer也会被遮盖**


至于目前maptalks中TileLayer自带的 mask 测试 是支持Polygon的，不过我没有测试含有hole的Polygon是否也正常

**Comment by fuzhenn** [comment]
哈哈，很天才

这个问题我尝试了一下，一些技术贴上提到canvas 支持 multiple clip， 但我还没试出来。 过两天找时间来看一下

**Comment by deyihu** [comment]
@fuzhenn  至于你说的  multiple clip，我刚才尝试了一下，进行多个path绘制后进行统一剪裁，然后能达到MultiPolygon 多个区域被剪裁的效果

http://jsfiddle.net/x18y6ajh/27/


不知道是不是你说的效果

**Comment by fuzhenn** [comment]
谢谢！@deyihu
我研究一下

**Comment by deyihu** [comment]
@fuzhenn   这个问题我刚才尝试了一下，基本上已经解决了

https://deyihu.github.io/src/html/mask.html

不过代码方面涉及到了 底层的Canvas(src/core/Canvas.js)

而且我认为这个解决方法不是太好，在Canvas.polygon方法中判断是否MultiClip,
**相关标志绑定在Canvas 的context的（这个认为不好的地方）**

**主要是因为我对maptalks.js整个项目代码不是很熟悉，所以不好对这块的重构,你看看怎样进行整合一下**

MultiPolygon多边形中含有holes的没有处理，
我看了下即使是Polygon时，如果含有洞，进行Clip也是只剪裁洞的内容（应该是有问题的），这里我没有做处理(没有想到好的对多个Polygon且含有洞的clip方法)

我待会给个PR,代码变动不多

**还有setMask时，如果多次设置同一个（Polygon/MultiPolygon），会报 (Geometry cannot be added to two or more layers at the same time.),这个应该是个bug**  :smile:

**Comment by fuzhenn** [comment]
closed by #801
