### ISSUE TITLE
关于官网首页3D demo，建筑物的点击事件

### ISSUE THREAD

**Issue by julyking0** [maptalks/maptalks.js#742]
您好，我想问下官网首页提供的3D demo，http://maptalks.org/gallery/extrude-buildings/index.html

3d建筑物怎么增加点击事件，我看使用的是maptalks.webgl.js，我没有找到有关maptalks.webgl.js的api说明。
看maptalks.webgl.js，也没发现可以增加点击事件的方法。

**Comment by fuzhenn** [comment]
maptalks.webgl.js是实验性的插件，改为了 [maptalks.biglayer](https://github.com/maptalks/maptalks.biglayer) 

这个插件已经停止维护，也没实现3d建筑的点击事件，后面会用新的gl插件代替。
