### ISSUE TITLE
点击 infoWindow 的默认关闭按钮不会触发 hide 事件

### ISSUE THREAD

**Issue by wordgold** [maptalks/maptalks.js#744]
虽然可以在创建完后重置下事件，或者使用定制 infoWindow，但每次都这么搞实在是有点麻烦。
希望修改关闭按钮触发 hide 事件。

**Comment by fuzhenn** [comment]
收到，你的pr就是解决这个问题的吧？ https://github.com/maptalks/maptalks.js/pull/740
我最近事情比较多，还没来得及看，等下周我会找个时间对应issue的。
