### ISSUE TITLE
Examples例子中的BUG

### ISSUE THREAD

**Issue by zhangboxi** [maptalks/maptalks.js#745]
5.22 Polygon gradient fill中的 rect3 初始化并没有渐变色，只有在移动地图后，才会变为渐变色。试了下，发现是浏览器的问题，别的效果都能支持，就这个出现了问题。

**Comment by zhangboxi** [comment]
试了下，发现是浏览器的问题

**Comment by fuzhenn** [comment]
你用是什么版本的浏览器，什么操作系统？
我这里最新的chrome没有重现这个问题

**Comment by fuzhenn** [comment]
closing，will reopen if you come back
