### ISSUE TITLE
Cannot read property 'zoom' of null

### ISSUE THREAD

**Issue by NinaMuaMua** [maptalks/maptalks.js#749]
用dwz的框架，页面跳转时出现了以上的错误

**Comment by fuzhenn** [comment]
谢谢提出issue。
不过你给的信息太少，无法定位错误，请提供一个重现代码：
http://maptalks.org/examples/cn/map/load/
打开页面后，点击右上角的编辑按钮，在jsfiddle中编辑好重现代码后，把url贴在这里即可。

谢谢！

**Comment by fuzhenn** [comment]
closing, will reopen if you come back
