### ISSUE TITLE
有高度的marker 设置信息框，随地图倾斜信息框位置变化遮挡标注

### ISSUE THREAD

**Issue by hixfang** [maptalks/maptalks.js#750]
**maptalks's version and what browser you use?**
----
maptalks v0.40.5  Google
**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
sorry，没有get到你的意思，能更详细的描述一下你的问题吗？
最好能提供一个jsfiddle的运行demo

http://maptalks.org/examples/cn/map/load/
打开链接，点击右上角的"编辑"即可

**Comment by hixfang** [comment]
http://jsfiddle.net/69es1vo7/10/
可能更详细的说法是 缩放地图 信息框位置和图标位置不对应

**Comment by terry8204** [comment]
我把marker图标旋转角度之后，信息框就不在marker的正中央，总是偏移了，图片是35x35的箭头。
创建symbol 如下
==============================================
                    'markerFile': this.getCarMarkerImgSrc(track),
                    'markerWidth': 35,
                    'markerHeight': 35,
                    'markerRotation': 360 - (track.course || 0),
                    "markerHorizontalAlignment": "middle",
                    "markerVerticalAlignment":"middle",
                    'online': track.online,
                    'moving': track.moving,

**Comment by terry8204** [comment]
效果如图：
图标的中心点和infowindow的中心点垂直不在一条线上，如果不旋转就是正常。
<img width="494" alt="WX20210305-230714@2x" src="https://user-images.githubusercontent.com/59051601/110133711-92575580-7e07-11eb-9274-c6bdaf8bc674.png">

**Comment by deyihu** [comment]
@fuzhenn 这个问题应该被fix了
