### ISSUE TITLE
编辑多边形时，中心处的原点如何去掉？顶点的symbol样式最好能支持自定义。

### ISSUE THREAD

**Issue by cooljser** [maptalks/maptalks.js#751]
RT

**Comment by fuzhenn** [comment]
可以通过给 startEdit 方法设置参数来修改样式：
```js
polygon.startEdit({
   centerHandleSymbol, //中心编辑手柄的symbol
   vertexHandleSymbol, //已有端点编辑手柄的symbol
   newVertexHandleSymbol, //新端点手柄的symbol
});
```

**Comment by cooljser** [comment]
非常感谢！！！

**Comment by jingyebuchen** [comment]
@fuzhenn 
您好，我想追问一下
polygon.startEdit({
   centerHandleSymbol, //中心编辑手柄的symbol
   vertexHandleSymbol, //已有端点编辑手柄的symbol
   newVertexHandleSymbol, //新端点手柄的symbol
});
手柄或者端点的详细样式参数我可以参考哪里呢？在官网我没有找到相应的答案

**Comment by fuzhenn** [comment]
@jingyebuchen 
这个设置和Geometry用的是一样的symbol系统：
https://github.com/maptalks/maptalks.js/wiki/Symbol-Reference

**Comment by jingyebuchen** [comment]
嗯嗯好的，非常感谢！！！
