### ISSUE TITLE
How call geojson tile layer with pitch

### ISSUE THREAD

**Issue by chakravarthi-vl** [maptalks/maptalks.js#752]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Hi, thanks.

Could you be a bit more specific?
* what do you mean of `geojson tilelayer`
* how do you display `geojson tilelayer` now

**Comment by chakravarthi-vl** [comment]
Hi, thanks for reply,

I want call  geojson as tile layer with pitch for three.js,
can you please base example code for this.

**Comment by fuzhenn** [comment]
Hi, @chakravarthi-vl , this is a question with an epic answer: there is no easy way to load geojson tile layer with three.js.

You need to extend TileLayer to create your own `GeoJSONTileLayer` to load geojson as tiles (and you need a proper server to serve geojson as tiles), and render them with three.js in your layer layer renderer. It is not quite an easy task, but can be done. Extending `TileLayer` and `TileLayerGLRenderer` should be a good start point.

So if any thought, don't hesitate to share with us.

**Comment by chakravarthi-vl** [comment]
Thanks thanks for reply
