### ISSUE TITLE
在拖动改变 polygon 形状结束时，会触发什么事件？只能使用 shapeChange 吗？

### ISSUE THREAD

**Issue by cooljser** [maptalks/maptalks.js#753]
RT

**Comment by fuzhenn** [comment]
还有`shapechange`(形状改变)或`positionchange`(位置改变)事件，另外结束编辑有`editedit`
http://maptalks.org/maptalks.js/api/0.x/Polygon.html#event:shapechange

编辑端点拖动结束暂时没有事件，需要的话可以增加一下，'handledragend`之类

**Comment by cooljser** [comment]
如果方便的话，最好能增加一个 dragend 的事件。因为在拖动的过程中，shapeChange 会被触发多次，需要做 debounce 处理。

**Comment by fuzhenn** [comment]
👍  有兴趣帮忙提个pr给我吗？

https://github.com/maptalks/maptalks.js/blob/master/src/geometry/editor/GeometryEditor.js#L299

在`createHandle`方法里的`onHandleStart`等事件回调里，增加一下事件fire方法就行了，类似：
```js
this._geometry.fire('handledragstart');
```

**Comment by cooljser** [comment]
好的，我看一下。

**Comment by fuzhenn** [comment]
closed by #754
