### ISSUE TITLE
map tiles are blank when pitching on chrome

### ISSUE THREAD

**Issue by muka** [maptalks/maptalks.js#757]
**maptalks's version and what browser you use?**
----
maptalks v0.40.5
chrome 68.0.3440.106 (Ubuntu 18.04)

**Issue description**
----
When changing the pitch the tiles become white

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://maptalks.org/examples/en/map/load/

![image](https://user-images.githubusercontent.com/1021269/44520521-58eaee80-a6d0-11e8-9eeb-01708fd50d8d.png)

In firefox instead the rendering is correct

**Comment by fuzhenn** [comment]
Thanks for reporting!
Will install a ubuntu and investigate on it.

**Comment by muka** [comment]
Let me know if I can help somehow, thanks

**Comment by wsw0108** [comment]
I saw same problem using Firefox 61.0.2 under Linux(Manjaro).
The console shows: 
![image](https://user-images.githubusercontent.com/4977975/44525499-af2d5100-a713-11e8-9fe8-840c7bef9bd0.png)

The default renderer of `TileLayer` is `gl`, if the browser does not support webgl, it will fallback to `canvas`.

On my Manjaro, Chrome 68.0.3440.106 works fine.

Please check the webgl support of your Chrome browser. (ex, check URL `chrome://gpu`)

**Comment by wsw0108** [comment]
@muka Or, access https://get.webgl.org/

**Comment by muka** [comment]
Thanks @wsw0108 
my gpu support seems fine. I had some work with three.js too and visualization was smooth

![image](https://user-images.githubusercontent.com/1021269/44527431-1254be80-a6e7-11e8-9ce5-f57762039009.png)

**Comment by wsw0108** [comment]
@muka Could you show the console output when changing the pitch?

**Comment by muka** [comment]
Sure, I see just those 2 lines in the log  (debug level is enabled )

```
info: maptalks v0.40.5
warn: [Violation] 'requestAnimationFrame' handler took 130ms
```
The second warn happens once while starting the pitch

**Comment by wsw0108** [comment]
@fuzhenn

**Comment by fuzhenn** [comment]
Thanks @wsw0108 !

This is confusing.

TileLayer with gl renderer still renders tiles with canvas renderer (which is a little bit smoother) when pitch = 0 and will switch to gl renderer once pitch changes, The problem may come from the switch.

@muka could you help test this url out to see if it's still blank. Pitch is set at the first place to avoid switch from canvas to gl renderer.

http://jsfiddle.net/vfo8zj6n/

**Comment by muka** [comment]
__UPDATE:__

Works when explicitly enabling the HW GPU features in chrome. Here the steps for future reference:

1. Visit `chrome://gpu/` it may say `software only` on many options
2. Visit `chrome://flags/`, search for `gpu` and enable `Override software rendering list` and restart.
3. Visit `chrome://gpu/` it says now `HW accelerated` on many features
4. map are rendered perfectly when pitching!

I think the issue can be closed.

Maybe worth to be mentioned in the docs?

Thank you for your time

---

Still no luck, while setting pitch to 0 render the plain map as expected

![image](https://user-images.githubusercontent.com/1021269/44567980-09123300-a775-11e8-8517-9719ec87086f.png)

Thanks!
