### ISSUE TITLE
改变地图的pitch再还原，地图成空白

### ISSUE THREAD

**Issue by MrSasuke** [maptalks/maptalks.js#762]
**maptalks's version and what browser you use?**
----
version:maptalks v0.40.5 browser:firefox

**Issue description**
----
设置pitch再还原pitch为0变空白，拖动才出现地图

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://jsfiddle.net/Ljcmz391/11/

**Comment by fuzhenn** [comment]
感谢提issue

我这里没有重现这个问题
我的firefox版本是61.0b5 (64-bit) developer edition， os 是win10 64位

请问一下你的操作系统和firefox的具体版本

**Comment by SimpleYong** [comment]
firefox 61.0.2(64bit) ,os win10-64
________________________________
lwysimple@outlook.com

发件人： Fu Zhen<mailto:notifications@github.com>
发送时间： 2018-08-29 19:16
收件人： maptalks/maptalks.js<mailto:maptalks.js@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： Re: [maptalks/maptalks.js] 改变地图的pitch再还原，地图成空白 (#762)

感谢提issue

我这里没有重现这个问题
我的firefox版本是61.0b5 (64-bit) developer edition， os 是win10 64位

请问一下你的操作系统和firefox的具体版本

**Comment by fuzhenn** [comment]
还是没能重现.. 不过这个问题也许和 #732 有关

那个bug是能重现的，我先把它改掉，也许这个问题就随之解决了
