### ISSUE TITLE
能否添加VectorTileLayer图层的支持？

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#763]
**maptalks's version and what browser you use?**
----

**Issue description**
----

针对 VectorLayer  希望加上TileLayer的瓦片属性，可以像TileLayer那样分层，分行列好取请求业务数据（可以是切好的json,geojson,pbf,mvt,甚至自己手写的后台的restful json服务）

分层按需来加载业务数据，数据加载和数据的格式化可以开放出来自定义，同时希望其具有VectorLayer管理Geometry的能力

数据格式化函数中我们可以将相关业务数据格式化成Geometry,让VectorTileLayer这图层自动管理

我做的一个例子  https://deyihu.github.io/src/maptalks-vectorTileLayer-test/
我现在是利用TileLayer 在其瓦片请求函数中动态的请求  mapbox的 pbf服务，将数据利用canvas渲染成图片作为TileLayer的图片使用的。

希望VectorTileLayer 只是针对业务的数据加载和移除（缩放，移动等操作自动加载业务数据或者移除相关数据），不是像mapbox那样动态的进行底图的动态渲染，只是针对业务数据的加载

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
👍 你做的这个矢量瓦片的例子真心赞！ 感觉很平滑！

我们正在开发一系列基于webgl的三维插件，其中包括了基于maptalks symbol系统的矢量瓦片图层。

你要是有兴趣，到时候我可以先发给你做一下内部测试。

不过新的三维插件是否全部开源，目前我们还有些争议，可能会初步保守一点，先以闭源免费或部分开源的形式发布，待到合适的时机再全部开源。

就这个主题，如果你（或其他同学）有什么想法或建议，欢迎探讨。

**Comment by kzfile** [comment]
现在的maptalks是不是是纯CPU运算啊,我在控制台查看发现显存占用一直是0

**Comment by fuzhenn** [comment]
@kzfile 
技术实现要分图层，基于gl renderer的都是webgl实现的（比如三维时的TileLayer）
其他有canvas实现，也有基于dom的

至于为啥显存占用是0就不清楚了

**Comment by deyihu** [comment]
This has been realized by maptalks.three
