### ISSUE TITLE
LineString在设置smoothness参数的情况调用animateShow方法，播放时间和速度不正确

### ISSUE THREAD

**Issue by ageeye-cn** [maptalks/maptalks.js#765]
**maptalks's version and what browser you use?**
----

**Issue description**
----

播放完成的时间总是比设定时间提前，曲线的播放速度不一致

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
这个问题我尝试解决了下，以前的处理逻辑是不对的，为了smoothness求控制点，会将坐标多两个，导致markerPlacement 的数量比线的实际长度多两个，现在我是吧动画的实时点，重复两次，可以控制markerPlacement 的数量和线的当前长度吻合，但是因为smoothness绘制的问题，但是线的绘制总是比markerPlacement 慢点
