### ISSUE TITLE
加载自定义切图服务，如何禁止找不到的瓦片报404错误

### ISSUE THREAD

**Issue by davidweining2333** [maptalks/maptalks.js#768]
**maptalks's version and what browser you use?**
----
0.40.5 chrome 68.0.3440.106
**Issue description**
----
![image](https://user-images.githubusercontent.com/28379395/45015823-75364600-b055-11e8-97b5-b417c96afc0a.png)
因为是自定义切图，所以只有部分瓦片，导致控制有大量404，openlayers有类似的not found img，就是找不到瓦片以自定义图片替代，maptalks是否有类似的配置项呢，或者是否可以再urlTemplate的回调中改写瓦片请求实现类似的功能呢（主要是x y取值范围是否可计算）

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://jsfiddle.net/u9f4kjcw/57/

**Comment by fuzhenn** [comment]
closed by #778
