### ISSUE TITLE
使用Proj4自定义投影底图时，spatialReference 会缺失一些属性

### ISSUE THREAD

**Issue by gee1k** [maptalks/maptalks.js#774]
**maptalks's version and what browser you use?**
----
- maptalks:`v0.41.1`
- browser: `Chorme 69`

**Issue description**
----
使用Proj4自定义投影底图时，spatialReference 会缺失一些属性。
在使用官方例子里的自定义投影底图时，我在其中绘制线，想尝试线的动画，发现报错如下：

![输入图片说明](https://images.gitee.com/uploads/images/2018/0909/135641_240b5dfc_1401522.png "屏幕截图.png")

由于是自定义的`Projection`，所以里面没有`measurer`对象。请问这个要怎么解决
![输入图片说明](https://images.gitee.com/uploads/images/2018/0909/135834_8c89c712_1401522.png "屏幕截图.png")

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by signhuwei** [comment]
给自定义的投影赋个椭球呗
`Object.assign(youPrj,maptalks.measurer.WGS84Sphere)`

**Comment by fuzhenn** [comment]
可以参考一下源代码里的处理方法，如楼上所说，根据需要添加Sphere或Identity的相关方法计算逻辑就行了。(源代码里的Common方法不用添加，maptalks会自动给自定义proj对象添加common方法的)
https://github.com/maptalks/maptalks.js/blob/master/src/geo/projection/Projection.EPSG3857.js

自定义投影的示例代码需要修改一下，我晚点去改一下
