### ISSUE TITLE
Edge浏览器下为Marker设置svg图标样式时，渲染样式不正确

### ISSUE THREAD

**Issue by ageeye-cn** [maptalks/maptalks.js#782]
**maptalks's version and what browser you use?**
----

**Issue description**
----

同时设置svg图标样式和shadow样式时，svg图标被阴影挡住
颜色不正确，始终和shadow同色

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by deyihu** [comment]
因为edge已经换成了chromium内核，所以这个问题应该不用fix了
