### ISSUE TITLE
How to animate a marker through a LineString?

### ISSUE THREAD

**Issue by jgauna** [maptalks/maptalks.js#783]
Chrome 64 - Maptalks lastest version
----

I want to animate a marker (just as the LineString example: 

http://maptalks.org/examples/en/animation/line-animateshow/#animation_line-animateshow

and I can't figure out how to do it
----

- First the line should be rendered just like here http://maptalks.org/examples/en/animation/line-animateshow/#animation_line-animateshow

- The marker should appear and follow the exact same LineString coordinates

- Should be possible to stop the marker in multiple points (like courier stops)

- Extra example: Draw a new line from the previous one and continue the marker movment.

Thanks!
----

**Comment by fuzhenn** [comment]
Hi!
You could take a look at this plugin, which may help:
https://github.com/maptalks/maptalks.routeplayer/

**Comment by deyihu** [comment]
fixed by https://github.com/maptalks/maptalks.routeplayer
