### ISSUE TITLE
Marker 处于编辑状态时的边框控制点在视角倾斜时的位置不是预期效果

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#784]
**maptalks's version and what browser you use?**

version:  0.41.1

**Issue description**

Marker 处于编辑状态时的边框控制点在视角倾斜时的位置不是预期效果，预期控制点还应该处于Marker周边。

![image](https://user-images.githubusercontent.com/19517451/45614058-ce14ce00-ba9a-11e8-8a9a-1b5a65e027f9.png)

**Please provide a reproduction URL (on any jsfiddle like site)**

http://jsfiddle.net/sakitamfdd/tn6Lfv54/4/

**Comment by deyihu** [comment]
这个问题已经fix
