### ISSUE TITLE
在3D视角下，vector图层的覆盖物盖在了fog上，导致感官与实际不一致，可能导致误解

### ISSUE THREAD

**Issue by davidweining2333** [maptalks/maptalks.js#788]
**maptalks's version and what browser you use?**
----
0.40.5 chrome 68.0.3440.106
**Issue description**
----
在3D视角下，vector图层的覆盖物盖在了fog上，导致感官与实际不一致，可能导致误解
![image](https://user-images.githubusercontent.com/28379395/45739613-f846c700-bc25-11e8-814a-d26a2586aab4.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://jsfiddle.net/u9f4kjcw/81/
基于官方demo写了一个类似的例子

**Comment by davidweining2333** [comment]
看了一下大概是因为fog的绘制比vectorlayer的绘制先，这里是否有方法能解决呢

**Comment by fuzhenn** [comment]
原因确实如你所说。但fog如果画在所有图层上，效果也很怪。
这个没什么很好的解决方案，可以这么改一下试试：
* fog设为false
* 把map的maxVisualPitch设大一点(默认60)，这样底图会延伸的远一些（性能会下降，需小心调整）
* 调整容器背景

**Comment by davidweining2333** [comment]
fog是需要的，干脆我就设置一下maxPitch减少vector图层的展示好了
