### ISSUE TITLE
Polygon对象为什么只有mouseenter事件没有mouseleave事件呢

### ISSUE THREAD

**Issue by davidweining2333** [maptalks/maptalks.js#789]
**maptalks's version and what browser you use?**
----
***
**Issue description**
----
![image](https://user-images.githubusercontent.com/28379395/45745893-74e0a200-bc34-11e8-80d6-cf48a097786e.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://maptalks.org/maptalks.js/api/0.x/Polygon.html#event:mouseenter

**Comment by fuzhenn** [comment]
不同于dom，Geometry上mouseout和mouseleave的行为是一样的，所以就没有新增一个mouseleave事件了

mouseenter（不会重复fire）和mouseover行为不同，所以就增加了一个mouseenter
