### ISSUE TITLE
这个怎么加载离线地图啊？

### ISSUE THREAD

**Issue by qg1994** [maptalks/maptalks.js#793]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

    <script>
      var map = new maptalks.Map('map', {
        center: [-0.113049,51.498568],
        zoom: 14,
        baseLayer: new maptalks.TileLayer('base', {
          urlTemplate: 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
          subdomains: ['a','b','c','d'],
          attribution: '&copy; <a href="http://osm.org">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/">CARTO</a>'
        })
      });

    </script>
demo里面用的是在线的 怎么引用离线的？

**Comment by fuzhenn** [comment]
需要自己生成瓦片数据并发布为服务，按照与在线服务类似的方式加载就行。

具体可以搜索下，相关教程和文章很多

**Comment by tiosan** [comment]
> 需要自己生成瓦片数据并发布为服务，按照与在线服务类似的方式加载就行。
> 
> 具体可以搜索下，相关教程和文章很多
大哥能推荐一篇不？我门外汉，找到的感觉都不太像。
