### ISSUE TITLE
setView中的判断是否合适

### ISSUE THREAD

**Issue by zzcyrus** [maptalks/maptalks.js#794]
https://github.com/maptalks/maptalks.js/blob/b479fa0b1419b5ca54c7f4160e909cfeeacc0160/src/map/Map.js#L802

```js
if (view['pitch'])
```

这样判断，如果view中的pitch和bearing想要刻意设置成0，就只能采取setPitch的方法了，是不是不太合适

**Comment by fuzhenn** [comment]
确实，zoom, pitch, bearing都有这个问题

有兴趣帮忙提个pr给我不？
