### ISSUE TITLE
GroupTileLayer 移除后不能再次添加到地图上

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#796]
**maptalks's version and what browser you use?**
----

**Issue description**
----

TileLayer 从地图上移除后可以再次添加。
GroupTileLayer 从地图上移除不能再次添加到地图上

http://jsfiddle.net/1on8gu95/

老版本是可以的（我用0.39.0是可以的），目前新的版本不可以的

[引用的issue](https://github.com/deyihu/maptalks-tileLayercollection/issues/1)  @binfenshijie 

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
closed by #800
