### ISSUE TITLE
绘制图形自动闭合

### ISSUE THREAD

**Issue by artskin** [maptalks/maptalks.js#797]
**new?**
想问下maptalk在绘制多边形的时候，能不能设置首尾坐标接近时自动吸附，点击后，图形闭合。
目前没看到接口和例子里有相关内容

**Comment by fuzhenn** [comment]
目前绘制多边形时已经是自动闭合的，只是没有你提到的自动吸附闭合的过程，而是在双击结束后，自动添加一个闭合点。

**Comment by artskin** [comment]
> 目前绘制多边形时已经是自动闭合的，只是没有你提到的自动吸附闭合的过程，而是在双击结束后，自动添加一个闭合点。

目前这种绘制多边形，闭合的地方不太精确，经常多出个拐点。
建议后续加个自动吸附。还有个就是绘制过程中线段是否交叉的判断，以前用其他框架有这些设置，感觉体验比较不错。

**Comment by fuzhenn** [comment]
闭合的地方不精确和多个拐点是指？请稍微讲的详细一些

对于自相交的判断，目前有个插件可以实现这个功能：

https://github.com/maptalks/maptalks.isects

绘制过程中检查是否自相交确实是个好主意

**Comment by artskin** [comment]
> 闭合的地方不精确和多个拐点是指？请稍微讲的详细一些
就是说绘制多边形，最后想闭合时，回到起始点双击，由于目测误差经常不准确。双击后会自动绘制双击的点与起始点的线段，这样就会多出一段。虽然很小，但是会多生成一个坐标

**Comment by artskin** [comment]
> 闭合的地方不精确和多个拐点是指？请稍微讲的详细一些
> 

就是说绘制多边形，最后想闭合时，回到起始点双击，由于目测误差经常不准确。双击后会自动绘制双击的点与起始点的线段，这样就会多出一段。虽然很小，但是会多生成一个坐标

**Comment by cooljser** [comment]
这个问题我也碰到了，是这样处理的：
在每次点击时，在拐点处都会绘制一个 marker 的小圆点，把第一个小圆点的 hover 属性设置为 pointer，并且绑定 click 事件。当要终止绘制时，移动到第一个小圆点上，鼠标手势会变化，所以不易误操作。

**Comment by fuzhenn** [comment]
drawtool应该会自动闭合的，不用特意回到起始点去双击

**Comment by cooljser** [comment]
嗯，drawtool 是可以自动闭合。但是产品需求就是这个鸟样，需要点击起始点也实现闭合功能(心里mmp...)。

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.snap
