### ISSUE TITLE
ui.UIMarker 添加 ToolTip支持

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#798]
**maptalks's version and what browser you use?**
----

**Issue description**
----
复杂的点（图表等之类的东西）需要ui.UIMarker来支持

需要ui.UIMarker进行消息提示，ui.UIMarker好像不支持ToolTip

我看了一下ToolTip限制了 owner只能为Geometry实例，希望加个判断ui.UIMarker来支持ToolTip

我试了一下，放开就可以了

<pre>

      if (owner instanceof Geometry) {
            owner.on('mousemove', this.onMouseMove, this);
            owner.on('mouseout', this.onMouseOut, this);
            return super.addTo(owner);
        } else {
            throw new Error('Invalid geometry the tooltip is added to.');
        }
</pre>

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
赞！ 提个pr给我吧，判断一下Geometry或者UIMarker就展示

**Comment by fuzhenn** [comment]
closed by #799
