### ISSUE TITLE
完善地图的CRS和Projection设置

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/maptalks.js#80]
总的原则是尽量简单, 能覆盖大多数常用场景即可, 以下是一些初步的想法:

* tileInfo设置换到Map上, 不再放在baseTileLayer里.
* tileInfo换一个更恰当的名称
* projection的设置, 我们只提供三种projection<br>
    优点: 使用简单, 能覆盖大多数场景.<br>
    缺点: 无法像[d3js利用投影实现更丰富的地图表现形式](https://github.com/mbostock/d3/wiki/Geo-Projections)
    * EPSG:3857 或 web-mercator
    * BAIDU
    * ~~NULL~~ IDENTITY (无投影转换, 类似leaflet的[EPSG:4326](https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.EPSG4326.js)), 不叫EPSG:4326的原因是它还适用于室内地图, 像素坐标, 输入和输出均为3857坐标的场景使用, 并不仅仅适用于经纬度坐标
   
* 去掉map和geometry的CRS方法, geometry数据中不再提供CRS, 由外部调用方法来指定坐标转换
* 默认只支持欧几里德坐标或经纬度坐标两种坐标, 考虑在map和geometry上增加euclidean属性, 默认为false<br>
   如果是true, 表示坐标是个欧几里德坐标<br>
   如果是false, 表示坐标是wgs84经纬度坐标<br>
   要支持别的坐标系, 得自己构造自定义的projection类来实现

**Comment by FuZhenn** [comment]
地图初始化时所需的设置

* projection, 即投影转换算法, 目前有两种流行定义
     * proj4定义法
     * leaflet和openlayers都采用形似[EPSG4326](http://openlayers.org/en/v3.12.1/examples/epsg-4326.html), EPSG3857的形式定义
* map CRS(可选), 即地图所使用的坐标类型, 定义了地图上坐标及VectorLayer的数据的CRS, 默认为EPSG4326

**Comment by FuZhenn** [comment]
中国的三种流行坐标系, 均为EPSG4326的变种

* BD09
* GCJ02
* CGCS2000

它们均没有国际公认的CRS定义(EPSG编号等), 如何用恰当的GeoJSON CRS定义它们?
目前采用的是自定义的CRS, 例如

        {
         "type:"cnCoordinateType",
         "properties" : {
            "name" : "bd09"
         }
        }

**Comment by wsw0108** [comment]
我觉得需要两个设置就可以了，CRS/SRS与TileSystem

### 1. CRS/SRS
- proj4的str表达
```
+proj=longlat +ellps=WGS84 +datum=WGS84 +units=degrees
+proj=gnom +lat_0=90 +lon_0=0 +x_0=6300000 +y_0=6300000 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
```

- Leaflet的CRS对象
  - [CRS.EPSG4326](https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.EPSG4326.js)
  - [CRS.EPSG3857](https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.EPSG3857.js)

#### Leaflet的CRS支持(以proj4的方式来看)
支持的投影(+proj)：
- LonLat
- Mercator
- SphericalMercator

支持的基准面(+datum)：
- WGS84

支持的椭球模型(+ellps)：
- WGS84

这三者可以认为是proj4的三个主要参数。

在Leaflet中，只有投影是明显的，其他两个都是隐含的。
且Leaflet对CRS的支持只是proj4所支持的小部分。

#### 对于国内的情况
需要支持的投影(+proj)：
- LonLat
- SphericalMercator
- BaiduMercator
- CGCS2000
- Identity(其实与[LonLat](https://github.com/wsw0108/proj4js/blob/master/lib/projections/longlat.js#L10)一样)

其中Identity就可以适用于室内地图/像素坐标等。
(FIXME) CGCS2000放在这里不知道合适不合适。

需要支持的基准面(+datum)：
- WGS84
- GCJ02
- BD09LL
- CGS2000

需要支持的椭球模型(+ellps)：
- N/A

因为对于基准面GCJ02和BD09LL来说，椭球参数无法得知。

#### 示例
- 对于map来说，一般的CRS可能长这样：
```
  +proj=merc +datum=WGS84 +units=m
  +proj=merc +datum=GCJ02 +units=m
  +proj=bmerc +datum=BD09LL +units=m
```
对于layer上的数据来说，CRS可能长这样：
```
  +proj=lonlat +datum=WGS84 +units=degrees
  +proj=merc +datum=WGS84 +units=m
  +proj=lonlat +datum=GCJ02 +units=degrees
  +proj=lonlat +datum=BD09LL +units=degrees
```
对于一般查询数据来说：
```
  { in_srs: +proj=lonlat +datum=GCJ02 }
  { out_srs: +proj=lonlat +datum=BD09LL }
```
对于现有动态图层实现查询数据来说：
```
  { in_srs: +proj=lonlat +datum=GCJ02 }
  { out_srs: +proj=bmerc +datum=BD09LL }
```

### TileSystem
瓦片规则大概有以下几种：
- Google/WebMercator，以投影左上角为编号原点
- TMS/GlobalMercator，以投影左下角为编号原点
- Baidu，以投影原点(经纬度原点投影后所在位置)为编号原点
- ArcGIS的以某种奇特的位置为原点的编号规则

**Comment by FuZhenn** [comment]
太赞了~

**Comment by brucin** [comment]
整理的太详细了。科普贴。

**Comment by FuZhenn** [comment]
进一步总结下,.
实践中, 涉及地理计算的有两个地方, 所以我们的地理设置参数只能要准确明白的定义这两个方面即可

* Projection, 投影转换, 即把数据坐标转换为投影坐标的算法, 在proj4中用proj参数指定. GIS中通常指将球体转换为平面, 常用的有三种:
      * CRS3857: 谷歌, 高德等大多数图商支持的投影方式, 事实上的互联网地图发布标准
      * Baidu: 百度地图特有的投影转换, 只用于百度地图服务
      * Identity: 无投影转换, 适用于室内地图, 像素坐标等.
* Measurement, 即测量体系. 决定测距, 测面等算法, 由采用的世界模型决定, 在proj4中用ellps参数指定, 例如wgs84椭球是一个半径约为6378137的球体, 目前常用的有两个:
      * 基于WGS84椭球的测量体系, 适用于WGS84, BAIDU, GCJ02, CGCS2000等WGS84类似坐标系
      * 基于欧几里德坐标系的测量体系, 适用于室内地图, 像素坐标等简单平面坐标使用场景.

**Comment by FuZhenn** [comment]
关于数据的CRS

我现在倾向于在数据中不再附上CRS属性, 按照[GeoJSON的推荐方式](https://github.com/geojson/draft-geojson/pull/6), 统一数据的默认CRS坐标系为WGS84, 投影坐标为3857.

有两个原因:
1. 实践中无CRS也不会引起困扰, 因为数据的CRS是人为指定的, 数据上图前一般都会根据底图和应用提前转换好, 很少动态转换, 效率低也没必要
2. GCJ02, BAIDU等都不是国际公认的坐标类型, 没有合理的crs表示法, 按照伟伟举例的proj4表示法:+proj=lonlat +datum=GCJ02 +units=degrees, 也只有我们自己认识, 其他系统都不认识

**Comment by FuZhenn** [comment]
关于查询时的CRS转换

我觉得伟伟的提议非常好, 因为CRS转换是我们系统内部使用的, 用proj4的形式来指定用起来确实很方便.

- 对于一般查询数据来说：
```
  { in_srs: +proj=lonlat +datum=GCJ02 }
  { out_srs: +proj=lonlat +datum=BD09LL }
```

- 对于现有动态图层实现查询数据来说：
```
  { in_srs: +proj=lonlat +datum=GCJ02 }
  { out_srs: +proj=bmerc +datum=BD09LL }
```

**Comment by FuZhenn** [comment]
关于地图的地理体系定义

可以参照 openlayers3 和 leaflet的做法, 用简单的值来定义projection和measurement
 * EPSG:3857 (CRS3857投影转换和WGS84测量体系)
 * EPSG:4326 (无投影转换和WGS84测量体系)
 * BAIDU (baidu投影转换和WGS84测量体系)
 * IDENTITY (无投影转换和欧几里德测量体系)

用户也可以继承Projection类来定义自定义的Projection

Geometry中增加measure属性, 默认为WGS84测量, 如果为euclidean, 则是欧几里德测量, 用来定义Geometry的getCenter, getLength和getArea的计算算法. 也允许用户继承Measurement类定义其他的测量算法.

**Comment by wsw0108** [comment]
数据中不附上CRS是没有问题的。

数据也一定得有CRS，不管默认值也好，非默认值也好，都必须有。
只是对于GCJ02等类似来说，GeoJSON等规范肯定是不支持的，不管采用哪种CRS表达方式，都无法(或不方便?)与其他系统一致

**Comment by wsw0108** [comment]
@FuZhenn 我觉得“无投影转换”这个表达有些不妥，最好还是有个值，如
https://github.com/wsw0108/proj4js/blob/master/lib/projections/longlat.js#L10

**Comment by FuZhenn** [comment]
https://github.com/MapTalks/maptalks.js/tree/master/src/Geo/Measurer
新增了measurer包, 用来表示测量模型
