### ISSUE TITLE
只显示指定范围内的瓦片-BUG

### ISSUE THREAD

**Issue by davidweining2333** [maptalks/maptalks.js#803]
**maptalks's version and what browser you use?**
----0.40.5 chrome 68.0.3440.106

**Issue description**
----使用mask，显示范围内地图功能时，将地图倾斜至最大角度，在将地图向北平移，到达地平线时报错，程序阻塞
![image](https://user-images.githubusercontent.com/28379395/47007980-f52ef000-d16b-11e8-994f-a0cae53a687a.png)
![image](https://user-images.githubusercontent.com/28379395/47007998-fbbd6780-d16b-11e8-9402-4ba7cde2f53e.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----http://maptalks.org/examples/cn/tilelayer-projection/tile-mask/#tilelayer-projection_tile-mask
官网的例子可以复现

**Comment by fuzhenn** [comment]
fixed in https://github.com/maptalks/maptalks.js/commit/38752c15e5d663d49e4f6ba9da08e6320f27a6ab
