### ISSUE TITLE
关于InfoWindow位置问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#805]
**maptalks's version and what browser you use?**
----

**Issue description**
----
点和面绑定InfoWindow时没有问题

但是当线 绑定InfoWindow，zoom小时候手动点击打开InfoWindow，地图放大后，InfoWindow位置就不准确了

http://jsfiddle.net/qc4021br/

**我知道这个是由精度问题导致（这时InfoWindow的位置应该是点击地图对象获取的经纬度），地图zoom小的时候，一个像素对应的经纬度值误差很大，当地图放大后InfoWindow还是保存的刚才点击的经纬度值，所以显示不准确了**

UIMarker也是存在这个问题的，我的做法是在InfoWindow不要自动打开，在UIMarkr的click事件中手动的设置 InfoWindow的位置为
UIMarker的 coordinate,如果不手动的取修正位置，也会存在像线那样的问题，地图放大后InfoWindow的位置不准确

**另外线InfoWindow的默认位置绑定在center这样是否合理？如果线不是直线，而是曲线，InfoWindow的位置就不在线上了**

![2018-10-17 22-48-12](https://user-images.githubusercontent.com/25998927/47094955-cb0a2a80-d25e-11e8-933f-9134c1e09360.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
fixed by #1197

**Comment by fuzhenn** [comment]
我想到一个效率也许更高的解决方案。
如你所说，问题的根源是第一次打开的坐标没有（精确的）定位在线上，放大地图后就会出现差异。
#1197 的解决方案是计算infowindow位置时，对坐标进行校正，找到离线上最精确的点。
那如果第一次打开infowindow时，做一次校正定位，找到LineString上距离鼠标事件坐标距离最近的那个坐标作为infowindow坐标，就不需要在计算infowindow位置时，每次都校正了。

**Comment by deyihu** [comment]
> 我想到一个效率也许更高的解决方案。
> 如你所说，问题的根源是第一次打开的坐标没有（精确的）定位在线上，放大地图后就会出现差异。
> #1197 的解决方案是计算infowindow位置时，对坐标进行校正，找到离线上最精确的点。
> 那如果第一次打开infowindow时，做一次校正定位，找到LineString上距离鼠标事件坐标距离最近的那个坐标作为infowindow坐标，就不需要在计算infowindow位置时，每次都校正了。

没怎么明白，我这个是每次打开时才计算的，因为每次打开时鼠标的位置都是不一样的，所有要再次计算

**Comment by fuzhenn** [comment]
sorry，我刚仔细看了一下，是我理解错了，现在的实现没问题
