### ISSUE TITLE
Add infowindow for UIMarker

### ISSUE THREAD

**Issue by jingyebuchen** [maptalks/maptalks.js#806]
**maptalks's version and what browser you use?**
----
版本^0.40.5  浏览器：谷歌浏览器  

**Issue description**
----
图片标注里面不支持gif图吗？我想加载一个gif格式的图片标注，但是他到页面上之后就不是动图了。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://maptalks.org/examples/cn/style/image-marker/#style_image-marker

**Comment by fuzhenn** [comment]
因为受canvas限制，普通的marker不支持gif，需要gif的可以改用UIMarker

**Comment by jingyebuchen** [comment]
> 因为受canvas限制，普通的marker不支持gif，需要gif的可以改用UIMarker
用了UIMarker确实可以显示出来了，可是我还要用marker的setInfoWindow方法，打开窗口，这种情况我看UIMarker好像没有这个方法。

**Comment by fuzhenn** [comment]
reopen，changed title

**Comment by deyihu** [comment]
@jingyebuchen  可以将InfoWindow手动的绑定到UIMarker，相比Geoemtry的直接绑定，稍显繁琐一点。

http://jsfiddle.net/hxvagkqc/1/

不过不能自动的打开，需要手动的打开，否则位置在地图放大后就不准确了

上个问题 [#805](https://github.com/maptalks/maptalks.js/issues/805)我也提到了

**Comment by jingyebuchen** [comment]
> @jingyebuchen 可以将InfoWindow手动的绑定到UIMarker，相比Geoemtry的直接绑定，稍显繁琐一点。
> 
> http://jsfiddle.net/hxvagkqc/1/
> 
> 不过不能自动的打开，需要手动的打开，否则位置在地图放大后就不准确了
> 
> 上个问题 [#805](https://github.com/maptalks/maptalks.js/issues/805)我也提到了

多谢，我也正在尝试，您的这个例子来的太及时了，我先试试

**Comment by jingyebuchen** [comment]
@deyihu 是不是用您的这种写法了之后？必须加上可以拖动的这个属性？因为我去掉这个属性之后好像打开不了窗口。
![9cf12c76a12ed9d66680dc7a3a6a900](https://user-images.githubusercontent.com/41276803/47191677-49f48580-d37b-11e8-8d94-f6d8f556263c.png)

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/oNRBKZz
