### ISSUE TITLE
兩個問題，分別關於GeoJSON和縮放級別

### ISSUE THREAD

**Issue by Wujidadi** [maptalks/maptalks.js#809]
請教兩個問題：
1. 使用 maptalks.GeoJSON.toGeometry() 創建的 geometry，要如何修改其 cursor？setCursor() 似乎只能用在 Map，無法用於 geometry。
2. zoomIn、zoomOut 的縮放級別都是 1，用 maptalks-zoom-zoomin 和 maptalks-zoom-zoomout 按鈕好像能藉由修改 zoomIn() 和 zoomOut() 來實現小數點等級的縮放，那麼滾輪和雙擊的部分，要怎麼達到相同的效果呢？

**Comment by fuzhenn** [comment]
嗨，@Wujidadi
1.  Geometry可以通過 geometry.config('cursor', cursorStyle); 來設置cursor
2.  因為圖片底圖在非整數級別上不清晰，所以目前滾輪和雙擊都只支持整數縮放級別，但這個功能已經在我們的開發計劃中了，會在近期實現的。

**Comment by fuzhenn** [comment]
嗨, @Wujidadi 
1.  可以通過 geometry.config('cursor', cursorStyle); 來設置cursor
2.  因為圖片底圖在小數級別上會模糊，目前雙擊和滾輪只支持整數級別，但這個功能已經在計劃中，會在近期實現的

**Comment by Wujidadi** [comment]
感謝回覆！
