### ISSUE TITLE
目前有辦法「繪製多邊形的高度面」嗎？

### ISSUE THREAD

**Issue by Wujidadi** [maptalks/maptalks.js#812]
示例 4.2、4.4 分別是「繪製Marker的高度線」和「繪製線的高度面」，卻沒有「繪製多邊形的高度面」，只有如示例 4.5 的「有高度的多邊形」，想請問目前是不是還不能做出 3D 立體多邊形的效果？

如下圖：
![image](https://user-images.githubusercontent.com/10349431/47635849-5655bb00-db91-11e8-8bd3-bdc8618c7217.png)

**Comment by fuzhenn** [comment]
这个可以用three插件绘制： [maptalks.three](https://github.com/maptalks/maptalks.three/)

相关issue: https://github.com/maptalks/maptalks.js/issues/807

**Comment by Wujidadi** [comment]
謝謝回覆……Orz

其實發問後不久自己就找到了，正想上來close……真是貽笑大方了。
