### ISSUE TITLE
maptalks website is down

### ISSUE THREAD

**Issue by anakein** [maptalks/maptalks.js#816]
antivirus say me: there is trojan html:redirME-inf

**Comment by fuzhenn** [comment]
Really? 

[maptalks.org](https://maptalks.org) is hosted on github pages and served through cloudflare's CDN.

It's OK for me here and it sounds like a problem of cloudflare's service in your place.

Do you mind telling me where are you?

**Comment by anakein** [comment]
![captura](https://user-images.githubusercontent.com/1563663/47967248-b9e15c00-e05b-11e8-87ca-751aca2da2ce.PNG)
spain

**Comment by cornelius-agrippa** [comment]
It looks like the kind of error you get when your computer's clock is wrong. Make sure your time is set correctly.

**Comment by anakein** [comment]
my clock is fine. the problem is tls.
![captura](https://user-images.githubusercontent.com/1563663/48249479-91f74d00-e3fb-11e8-84cd-8fc276f9253b.PNG)
![captura](https://user-images.githubusercontent.com/1563663/48249536-b4896600-e3fb-11e8-9037-2b90cdd6346e.PNG)

**Comment by fuzhenn** [comment]
maptalks.org's front page contains codes from [google analytics](https://analytics.google.com) for visitor statics.

You can have a try of [API doc](https://maptalks.org/maptalks.js/api/0.x/Map.html), it doesn't have the google codes. If that is OK, then it should be the problem between AVG and google analytics.

By the way, have you tried http://maptalks.org (without https)?
