### ISSUE TITLE
Three.js 建立的 3D features 可以綁定 InfoWindow 嗎？

### ISSUE THREAD

**Issue by Wujidadi** [maptalks/maptalks.js#817]
請問：3D Features 可以像 2D Geometry 一樣綁定 infowindow 嗎？以 3D 建築物為例，目前我是通過在該建築物的「頂樓」高度加上一層 2D 的 polygon geometry，再綁定 infowindow 給它。但若不是 3D Feature 不是這種等高的形狀，那就穿梆了。或是有時也需要 hover 到 3D feature 的側面「身體」上跳出 infowindow。
![share](https://user-images.githubusercontent.com/10349431/47992415-cc28cc00-e127-11e8-882f-9267d8aecb94.png)

**Comment by deyihu** [comment]
@Wujidadi   默认不支持的，我用的时候也遇到相同的问题，不过可以可以通过 three.js 碰撞检测，然后动态绑定 Infowindow

http://jsfiddle.net/910hnjqb/2/

**Comment by Wujidadi** [comment]
@deyihu 就是這個效果！感謝您的指點！
