### ISSUE TITLE
曲线使用linePattern样式问题

### ISSUE THREAD

**Issue by XiangLiLiang** [maptalks/maptalks.js#819]
环境：maptalks v0.42.0 和谷歌浏览器中 

当 CubicBezierCurve、QuadBezierCurve、ArcCurve使用linePattern时，曲线样式会随地图方位角和俯仰角( Pitch&Bearing )变化

http://jsfiddle.net/XiangLiLiang/nuphz0m6/28/

**Comment by fuzhenn** [comment]
这个问题不是很好解决，pattern的角度是按照当前线段的直线角度来设置的，但曲线偏离了原有的直线，所以会出现这个现象。

要完美解决，必须把曲线做切割，切成很多小的直线线段，但这样会急剧提升绘制成本。

一时半会还找不到特别好的解决思路

**Comment by XiangLiLiang** [comment]
好滴
