### ISSUE TITLE
if possible please provide working example of CanvasTileLayer

### ISSUE THREAD

**Issue by chakravarthi-vl** [maptalks/maptalks.js#821]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
The example is down because mapzen is out of service now.

They are now moved to [nextzen](https://www.nextzen.org/)， I think you may fix the example by redirecting mapzen's url to nextzen.
