### ISSUE TITLE
关于在echatrs GL中使用mapTakls的一些marker事件问题

### ISSUE THREAD

**Issue by monkey65535** [maptalks/maptalks.js#823]
环境：
Chrome  mapTalk@0.42.0  

问题：
当在echarts gl的环境下基于geojson渲染城市之后，使用mapTalk的API添加了一些marker，然后依照文档绑定了相关的事件，但是事件完全无法触发= = 暂时无法找到解决方案T  T

重现代码： 
http://gallery.echartsjs.com/editor.html?c=xMVnfn3hla&v=6

**Comment by fuzhenn** [comment]
这个应该是因为echarts接管了容器事件，maptalks的容器无法接收到事件导致的。

可以试试一个有点hack的方法：
通过echarts捕捉容器事件，然后手动调用map的事件处理方法：
对于geometry事件：
```js
map._identifyGeometryEvents(event);
```
对于map本身的dom事件：
```js
map._handleDOMEvent(event);
```

**Comment by monkey65535** [comment]
刚刚去修改了下代码，发现echarts容器的事件也无法获取

http://gallery.echartsjs.com/editor.html?c=xMVnfn3hla&v=7

然后查看dom发现，如果把echarts生成的canvas设置为display:none的话，地图的事件就可以正常的去执行=  = 忧伤。

这样就没办法按照您的方法去实现了 T T

**Comment by fuzhenn** [comment]
可以试着去echarts的官方仓库问问看：
https://github.com/apache/incubator-echarts

**Comment by deyihu** [comment]
@monkey65535  这个问题我有深入的研究过,回答一下希望帮到你

*  echarts-gl 不能触发事件的问题，你的代码我看了，需要设置支持事件交互，需要将silent:false, silent表示是否关闭鼠标事件（当数据量大时候，关闭事件可以大大提高渲染速度）

![2018-11-21_194617](https://user-images.githubusercontent.com/25998927/48839391-5169dd00-edc6-11e8-81d8-85bdc6963e2d.png)

![2018-11-21_194705](https://user-images.githubusercontent.com/25998927/48839490-a86fb200-edc6-11e8-8495-19f7d10d620e.png)

*  echarts-gl 目前在事件交互是存在bug的，碰撞精度有问题
https://github.com/ecomfe/echarts-gl/issues/229  建筑物的这个例子不是所有的建筑物都可以触发事件，有的数据是可以的

*   echarts-gl 中使用maptalks3D组件从而导致maptalks的事件失效的原因为 echarts生成的canvas元素会遮盖地图的容器
![2018-11-21_195929](https://user-images.githubusercontent.com/25998927/48839938-14064f00-edc8-11e8-9c5a-e4a3ee4e6250.png)


=======================================================
解决方法：

*  将 echarts生成的canvas 支持鼠标穿透 
![2018-11-21_200416](https://user-images.githubusercontent.com/25998927/48840110-adcdfc00-edc8-11e8-8777-3e03430cdf84.png)



![2018-11-21_200546](https://user-images.githubusercontent.com/25998927/48840181-e077f480-edc8-11e8-937b-73832d9df0ec.png)


这样就可以了触发maptalks相关的事件了，但是这样有一些弊端，因为maptalks地图容器和echarts-gl的canvas 处于同一层级会导致maptalks的所有东西都在echarts 的下面（包括控件，UIMarker等元素）


* 如果能将echarts-gl以图层的方式加到maptalks中就好了，这个插件可以帮到你[maptalks.e4](https://github.com/maptalks/maptalks.e4),   但是这个插件也有一些问题，就是maptalks在缩放时和echarts-gl中maptalks3D组件同步有问题，这也用到了这个插件，但是我有更改echarts-gl的源码来解决这个问题


*  如果你是基于maptalks来做建筑物展示，可以用maptalks.three这个插件试一下   https://github.com/maptalks/maptalks.three


* 上次我也遇到相同问题，使用了https://github.com/maptalks/maptalks.e4 这个插件，并且通过更改echarts-gl的源码解决了地图同步的问题，但是因为 echarts-gl 鼠标bug的原因，所以没有在项目中使用echarts-gl，然后我做了一个deck.gl和maptalks结合的插件[maptalks.deckgl](https://github.com/deyihu/maptalks-deckgl),用deck.gl替代了echarts-gl

**Comment by monkey65535** [comment]
@deyihu  非常感谢 ！！
