### ISSUE TITLE
Ignore tiles out of tile service's extent

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#825]
An unfinished work refering to #778

**Comment by davidweining2333** [comment]
@fuzhenn 老哥，紧急求助一下，我现在的项目需要在大屏上展示，由于我的地图服务时自己切的，所以在大屏上会有大量的404，而且拖动时卡顿现象严重，甚至导致浏览器崩溃
tileLayer中的spatialReference的fullExtent属性是否可以设置超出范围的瓦片就不在加载呢，
或者这个ISSUE解决后是不是也可以解决这个问题呢

**Comment by davidweining2333** [comment]
@fuzhenn 并且在大屏下（15360*4320）,只加载vectorLayer（水工绘制的矢量图形，数量也不多，大概30个多边形），进行图形的交互与拖动地图也很卡，有哪些配置项可以提高性能呢，我只看到这个好像可以layerCanvasLimitOnInteracting，很惭愧英文不好其他属性看不太明白，还望老哥提点一下。

**Comment by fuzhenn** [comment]
看上性能比较慢，可能单纯因为canvas太大造成的。
* 减少图层数量
* 降低屏幕分辨率，缩小地图canvas长宽
* 在效果允许的条件下，通过放大div(设置scale)，来减小地图canvas的长宽
* 升级电脑配置

如果功能不多，改起来快的话，可以改用leaflet，它是基于dom渲染的，在这种超大屏上，性能要比基于canvas的地图库要快。

**Comment by davidweining2333** [comment]
@fuzhenn 换框架是来不及了，renderer 换成gl会好点吗，如果不行确实用scale应该会好点

**Comment by davidweining2333** [comment]
电脑配置应该会好点吧

**Comment by fuzhenn** [comment]
canvas和gl的性能区别不大，推荐先试试scale。

**Comment by davidweining2333** [comment]
@fuzhenn 老哥，项目要转测了，404太多会有问题，能帮忙看下不，我自己改的那个getTileUrl出来效果有问题，过着指导一下我先改下

**Comment by fuzhenn** [comment]
@davidweining2333 周末我会改一下这个问题，并发个新版本

**Comment by davidweining2333** [comment]
@fuzhenn 非常感谢!

**Comment by fuzhenn** [comment]
@davidweining2333 新版本v0.42.2已经发布，请测试一下这个issue是否解决，如有问题可以随时@我。

**Comment by davidweining2333** [comment]
@fuzhenn 感谢，我试试看

**Comment by fuzhenn** [comment]
seems it still has some bug in it
