### ISSUE TITLE
批量添加一个自定义Html 的 Marker时的错误问题

### ISSUE THREAD

**Issue by monkey65535** [maptalks/maptalks.js#827]
**maptalks's version and what browser you use?**
----
Chome@70.0 maptalks's@0.42.0
**Issue description**
----
创建多个UI Marker然后批量添加到一个新创建的layer中的时候，添加失败，浏览器报错：
```
Uncaught TypeError: Cannot read property 'getZIndex' of null
```  
然后去文档中查找UI Marker的配置项，发现并没有zIndex的配置，  
虽然Marker的配置项中有zIndex的配置，但是配置了option之后发现依然没有效果 报错依然是：  
```
maptalks.min.js:6 Uncaught TypeError: Cannot read property 'getZIndex' of null
```  

另：如果不clear或者removeLayer的方法，有办法一次性清空地图上的所有物体么？ 

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://jsfiddle.net/dilidili/r4suc2g9/

**Comment by fuzhenn** [comment]
UIMarker不是用来添加到图层上的，它是个UI Component，类似InfoWindow或右键菜单，是直接添加到地图上的：
http://jsfiddle.net/fuzhenn/bfw0Lx2u/
