### ISSUE TITLE
polygon 的 text symbol是否支持自动避让？

### ISSUE THREAD

**Issue by AllanHao** [maptalks/maptalks.js#828]
maptalks 0.42.1

hi，Polygon的text symbol内容是否支持自动避让？例如当文字长度超过Polygon大小时不予显示，现在默认情况下显示比较乱。
![image](https://user-images.githubusercontent.com/3953310/48965605-6085a080-effb-11e8-86e9-4dac0d4b2af7.png)

谢谢。

**Comment by fuzhenn** [comment]
https://github.com/ageeye-cn/maptalks.collisionLayer
maptalks.js核心库没有避让功能，可以看一下上面的图层插件

另外polygon的中心文字可以用polylabel库来计算，能保证文字在多边形内部

**Comment by AllanHao** [comment]
好的，了解了，谢谢~
