### ISSUE TITLE
设置infoWindow autoPan属性为true时，顶部无法全部显示

### ISSUE THREAD

**Issue by AllanHao** [maptalks/maptalks.js#830]
**maptalks 0.42.1**

Hi，我将ui.InfoWindow的autoPan属性设置为true时，发现顶部气泡还是无法显示，如下图所示：
![image](https://user-images.githubusercontent.com/3953310/48968750-ee2eb380-f02e-11e8-8338-f1e631890d79.png)

通过查看源码发现判断时没有将clientHeight计算在内，不知道是Author故意为之呢，还是怎样。下面是我改的记录：
![image](https://user-images.githubusercontent.com/3953310/48968809-e15e8f80-f02f-11e8-8b14-0b8ee53731ec.png)

demo地址：
http://jsfiddle.net/api/post/library/pure/

**Comment by fuzhenn** [comment]
看上去有点像是个bug，提个pr给我吧

另外demo地址还是原始的编辑地址，没有保存下来 🤣

**Comment by AllanHao** [comment]
ok 长这么大，人生第一次提pr啊，有点小激动

**Comment by fuzhenn** [comment]
Thanks!
下周会发个新版本 => v0.42.2
