### ISSUE TITLE
未来是否会添加适量瓦片支持？

### ISSUE THREAD

**Issue by gee1k** [maptalks/maptalks.js#836]
**maptalks's version and what browser you use?**
----

**Issue description**
----
未来是否会添加适量瓦片支持？
看到目前 maptalks 中的适量瓦片是用得 mapbox 写的插件，这种方式会有很多局限性，比如只能用 mapbox 在线的图，坐标系限制等
请问是否有计划之后会自己支持自定义适量瓦片呢，比如 pbf，geojson 等规范

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
已在开发中，过段时间就会发布的

**Comment by gee1k** [comment]
👍 好的，会包含文字沿路旋转折叠嘛

**Comment by fuzhenn** [comment]
包含的~

**Comment by gee1k** [comment]
666 ~

**Comment by gee1k** [comment]
麻烦问一下，矢量瓦片什么时候能发布了呀 ❤️

**Comment by fuzhenn** [comment]
总算能尝试着回答一下，争取年中能发布第一个版本

**Comment by gee1k** [comment]
好的！
目前公司用的是基于 Leaflet 进行封装的框架，然后我也在次基础上做了基于 pbf 的矢量瓦片的实现。不过目前也还存在一些问题，例如：文字注记的问题

现在又想要地图支持2.5D倾斜➕旋转➕房屋高程

房屋高程还可以通过webgl实现，要想在目前的引擎上实现2.5D，就非常复杂了。🤥

所以目前在选型，看有没有什么更好的替代品。MapBox、Maptalks。
Mapbox 的坐标系局限性➕其封装到骨子里的API让人望而止步。
Maptalks 的功能、API 用来做项目真的是棒👍。期待你的矢量瓦片

**Comment by exotfboy** [comment]
Does maptalks support vector layer now?
