### ISSUE TITLE
Is there any plugin for vector tile layer ?

### ISSUE THREAD

**Issue by chakravarthi-vl** [maptalks/maptalks.js#838]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
not now.

There is one under development, but it's still in early stage and hard to say when to publish.

**Comment by chakravarthi-vl** [comment]
> not now.
> 
> There is one under development, but it's still in early stage and hard to say when to publish.
 can I get any sample code ?

**Comment by fuzhenn** [comment]
It's still under development, messy and all in chaos.

Will keep you updated once it's ready, hope not long.

**Comment by chakravarthi-vl** [comment]
> It's still under development, messy and all in chaos.
> 
> Will keep you updated once it's ready, hope not long.
thanks for reply, i am closing this issue
