### ISSUE TITLE
新手小白有个问题请教一下

### ISSUE THREAD

**Issue by duanhongfei** [maptalks/maptalks.js#840]
这个是否可以绘制室内地图，如果使用自己制作的地图，有什么要求吗？要用什么具体有要求的工具吗？期待您的回答，谢谢！

**Comment by fuzhenn** [comment]
感谢提issue。
室内地图是可以基于[identity投影](http://maptalks.org/examples/cn/tilelayer-projection/identity/#tilelayer-projection_identity)来绘制的，但制作工具并不在maptalks.js的未来计划中，你需要自己开发。
