### ISSUE TITLE
关于min包的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#842]
**maptalks's version and what browser you use?**
----

**Issue description**
----

我在使用 maptalks.markercluster 插件时，使用了自己编译的包（**所有代码和原始仓库完全同步了，代码未做任何改动，所有依赖都更新过了）**，如果使用 min包，会报异常
https://deyihu.github.io/src//bugdisplay/markerClusterMin.html

![2018-12-25_144622](https://user-images.githubusercontent.com/25998927/50415056-ee031d00-0853-11e9-9ea7-61128f1f88bc.png)

好像是feature-filter过滤的问题

```js
   var clusterLayer = new maptalks.ClusterLayer('cluster', markers, {
            'noClusterWithOneMarker': false,
            'maxClusterZoom': 18,
            //"count" is an internal variable: marker count in the cluster.
            'symbol': {
                'markerType': 'ellipse',
                'markerFill': { property: 'count', type: 'interval', stops: [[0, 'rgb(135, 196, 240)'], [9, '#1bbc9b'], [99, 'rgb(216, 115, 149)']] },
                'markerFillOpacity': 0.7,
                'markerLineOpacity': 1,
                'markerLineWidth': 3,
                'markerLineColor': '#fff',
                'markerWidth': { property: 'count', type: 'interval', stops: [[0, 40], [9, 60], [99, 80]] },
                'markerHeight': { property: 'count', type: 'interval', stops: [[0, 40], [9, 60], [99, 80]] }
            },
            'drawClusterText': true,
            'geometryEvents': true,
            'single': true
        });

```

然后我debug了一下，其中markerFill，markerWidth，markerHeight三个取值有问题。

**然后我切换了到了 自己编译的非min包，
https://deyihu.github.io/src//bugdisplay/markerCluster.html
却没有任何问题，至此我确定为 uglify-js 压缩的问题，**

然后我使用
cdn的min编译包
```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks/dist/maptalks.min.js"></script>

```
https://deyihu.github.io/src//bugdisplay/markerClusterCdn.html
**居然是没有问题的？**

**按理说我这边编译有问题，你那边也应该是有问题的啊，好奇怪？**

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by AirWinger** [comment]
@deyihu  可能是打包的机制不一样，最好是将FuntionType.js 里的createFunction函数里面对fun的属性isFeatureConstant和isZoomConstant增加是否为undefined的判断

**Comment by deyihu** [comment]
@AirWinger  我是完全clone maptalks的仓库，代码未做任何修改，然后直接编译的；
比较纳闷的是为是么 @fuzhenn  那边打包没有问题，而我这里是有问题的。

rollup+babel 打包后没有任何问题， 问题出在 uglify-js 压缩这里

**Comment by fuzhenn** [comment]
可能是uglifyjs版本的问题，我之前也遇到过高版本uglifyjs打包后会出错的问题，后[回退到老版本](https://github.com/maptalks/maptalks.js/commit/73b82d74d2028f999adab61eebfe6370c4a95b44)才解决
可以试试maptalks.js的uglifyjs版本

**Comment by deyihu** [comment]
的确是uglifyjs版本的问题，直接 npm  i  默认会安装 3.4.9


![2018-12-25 22-13-52](https://user-images.githubusercontent.com/25998927/50423596-8b7d4180-0892-11e9-9e07-ce584eace021.png)
强制安装 3.3.28 可以解决这个这个问题

 :joy:
