### ISSUE TITLE
同一个mapdiv，不同范围，图层重复

### ISSUE THREAD

**Issue by JackBaoL** [maptalks/maptalks.js#844]
**maptalks's version and what browser you use?**
----
   maptalks v0.42.2 ，chrome: 71.0.3578.98
**Issue description**
----
HI，加载切片图层时，图层在不同区域存在重复渲染的情况，官网示例也是如此，在大范围的情况还好，在显示小范围区域时效果很不好。
有没有方法和属性可以规避这种情况。
![image](https://user-images.githubusercontent.com/24949781/50509561-5c004c00-0ac1-11e9-9055-6ebb8a97abc7.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
TileLayer options里的repeatWorld设为false即可
