### ISSUE TITLE
line doesn't respond to click event

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#847]
**maptalks's version and what browser you use?**
----
v0.42.2 chrome 71.x

**Issue description**
----
The wall drawn by line with `drawAltitude`  doesn't respond to click event in some certain angle and point.

![image](https://user-images.githubusercontent.com/13678919/50622631-a82c1000-0f49-11e9-8944-995e7b3a8d2c.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://jsfiddle.net/xchLfrbp/8/

**Comment by binfenshijie** [comment]
The test passes as expected。bangbang da good
