### ISSUE TITLE
maptalks支持切换视角到地下

### ISSUE THREAD

**Issue by dxiuxiu** [maptalks/maptalks.js#848]
**maptalks's version and what browser you use?**
----0.42.2

**Issue description**
----有这样一个需求：需要加载地下三维管线模型，我知道目前maptalks可以借助threejs加载外部模型但是加载的模型都在地面上方并且没有发现maptalks允许切换视角到地下的功能。我想能在地面模式下像往常一样使用二维的东西又想可以切换成地下模式查看我加载的地下管线。这样的需求目前maptalks支持吗？

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
感谢提issue。
地下模式是指？从下方往上看头顶的管线吗？

**Comment by dxiuxiu** [comment]
> 感谢提issue。
> 地下模式是指？从下方往上看头顶的管线吗？

 嗯嗯~和您描述的差不多

**Comment by fuzhenn** [comment]
这个目前不行，暂时也没有计划支持..
