### ISSUE TITLE
设置marker的位置时未对dom进行判空处理

### ISSUE THREAD

**Issue by helloworldcyj** [maptalks/maptalks.js#849]
v0.39.3
----
点击摄像头的聚簇让其展开的时候，我遇见了这个问题．查看报错，发现是在设置style的时候未对dom进行判空处理
----
` UIComponent.prototype._setPosition = function _setPosition() {
            var dom = this.getDOM(),
                p = this.getPosition();
            this._pos = p;
            dom.style[TRANSITION] = null;
            dom.style[TRANSFORM] = toCSSTranslate(p) + ' scale(1)';
        };
`
----

**Comment by fuzhenn** [comment]
👍 能不能提个pull request给我？

**Comment by helloworldcyj** [comment]
Set animationOnHide to false to make setting marker's dom display none synchronously
animationOnHide is a hidden option which you will only find in maptalks's code, here is the link
https://github.com/maptalks/maptalks.js/blob/master/src/ui/UIComponent.js#L44
