### ISSUE TITLE
带 hole 的 polygon 重叠后轮廓显示不全

### ISSUE THREAD

**Issue by cooljser** [maptalks/maptalks.js#850]
**maptalks's version and what browser you use?**
----
maptalks: 0.41.1
chrome: 71

**Issue description**
----
polygon 重叠后轮廓显示不全，期望两个 polygon 都能正常显示

**Please provide a reproduction URL (on any jsfiddle like site)**
----
jsfiddle: http://jsfiddle.net/cooljser/75fkb618/

**Comment by deyihu** [comment]
@cooljser  这个是么有问题的，你的polygon，外环和内环（hole）经纬度差值太小，在地图支持的最大精度下，根本反应不出来，其实你把polygon的 lineWidth设置成不为0还是能看出来的

http://jsfiddle.net/73oqhngy/

![2019-01-09 22-47-23](https://user-images.githubusercontent.com/25998927/50906889-0cc2ff80-1461-11e9-9602-7b51131145b5.png)



然后我把你的数据放到mapbox-gl中渲染一下，开启无极缩放，是可以明显看出来的，就是精度误差太小导致导致在地图的最高精度下肉眼看不出来导致的
http://jsfiddle.net/fh4rvpgk/
![2019-01-09 22-50-19](https://user-images.githubusercontent.com/25998927/50906910-177d9480-1461-11e9-850b-03cc93a90945.png)


如果你有超高精度的底图，将地图zoom放到特别大的情况下是可以反应出来的

你们这个数据精度太牛逼了，感觉这是要造导弹的标准啊

**Comment by cooljser** [comment]
@deyihu 哈哈哈，应该是我没说清楚，现在的情况是两个 A、B，A 和 B 叠加的地方只能看到 B 的轮廓，A 被盖在底下的那部分轮廓就看不到了，希望和一般的 polygon 一样也能显示出来。
