### ISSUE TITLE
AnimationTo can create bearing changes of almost a full circle when changing around 180 and -180 degrees.

### ISSUE THREAD

**Issue by 31415tertje** [maptalks/maptalks.js#851]
**maptalks's version used: 0.42.2, browser firefox or chrome**
----

**AnimationTo can create bearing changes of almost a full circle when changing around 180 and -180 degrees.**

When I try to animate a route which goes from north to south, the bearing can change from around 180 to -180. e.g. a change from -178 to 177 is required which means a change of 5 degrees.
The animation is generating frames which go from -178 to 177 by positive increments of the bearing  leading to a delta angle of 355 degrees instead of 5.

Please have a look of my proposed changes in Map.Anim.js which make sure the bearing change is always below 180 degrees,
Please have a look at my test html script which demonstrates the behaviour and works as expected after applying the proposed change.

Apart from this small bug, the library works extremely well and is easy to use. Thanks.

[Map_Anim_js.zip](https://github.com/maptalks/maptalks.js/files/2740576/Map_Anim_js.zip)

----

----

**Comment by fuzhenn** [comment]
Thanks!
I'll have a look into this later

**Comment by fuzhenn** [comment]
~LGTM 👍  , could you submit a pull request?~

**Comment by fuzhenn** [comment]
I have carefully reviewed your demo,  the main concern of this proposal is:

If users want to intentionally rotate map with the angle diff > 180, they can **never** achieve it.

I think we should not change the `bearing` inside `animateTo` automatically which leads to ambiguousness, and should stick to a fixed logic, and let user decide bearing's value on the application level.

Get back to your demo, you can adjust bearings before passing to `map.animateTo`, this should be able to make it work rightly too.

**Comment by 31415tertje** [comment]
The problem of rotating almost 360 degrees only occurs when flipping from -180 to 180 or vice versa. In all other cases the rotation is always the shortest angle (< 180).
Can you really animate more than 180 degrees anywhere else?

Perhaps adding an extra option to animateTo would help:
    direction: clockwise or anti clockwise.

Adjusting the bearings before passing to map.animateTo does not work (or I am doing it in a wrong way) since I start the next animation before the current one in ended. Doing this makes the route animation very fluent.

**Comment by fuzhenn** [comment]
Yes, a `rotationDirection` option is definitely a good idea. You can set this option to keep map's rotation direction right. 

Could you have a test to see if it works?

**Comment by 31415tertje** [comment]
I'm not sure what you mean with 'Could you have a test to see if it works'.
1) Adapt the code myself and test it.
2) You adapt (or adapted) the code and I test it.

As far as I'm concerned rotationDirection would be:
clockwise, anticlockwise, shortestAngle
or
left, right, shortestAngle.

**Comment by fuzhenn** [comment]
1 will be great!

I prefer `clockwise, anticlockwise, shortestAngle`.

**Comment by 31415tertje** [comment]
Okay,

Please give me some time.
