### ISSUE TITLE
地图交互时无法渲染 Marker 等元素

### ISSUE THREAD

**Issue by chenyuan8059** [maptalks/maptalks.js#852]
**maptalks's version and what browser you use?**
----

**Issue description**
----
如何设置在地图进行移动，缩放时渲染 Marker 等元素

**Please provide a reproduction URL (on any jsfiddle like site)**
----
http://jsfiddle.net/chenyuan8059/Lcmh7ov5/2/

**Comment by fuzhenn** [comment]
这是地图的帧率控制导致的
可以在options里设置VectorLayer的强制渲染：
```js
forceRenderOnMoving : true,
forceRenderOnZooming : true,
forceRenderOnRotating : true
```
参考：
http://maptalks.org/maptalks.js/api/0.x/VectorLayer.html#options
