### ISSUE TITLE
tianditu api was changed

### ISSUE THREAD

**Issue by lifefriend** [maptalks/maptalks.js#853]
chrome71 , maptalks v0.42.2

tianditu api was changed, the example of epsg4326(http://maptalks.org/examples/en/tilelayer-projection/epsg4326/#tilelayer-projection_epsg4326) is blank

old: http://t{s}.tianditu.com/DataServer?T=vec_c&x={x}&y={y}&l={z}
new: http://t{s}.tianditu.gov.cn/DataServer?T=vec_c&tk=YOUR_KEY&x={x}&y={y}&l={z}

in the new api,random white patches appear on the map

![default](https://user-images.githubusercontent.com/23650125/51235283-1214d280-19aa-11e9-96a0-c84635ab93c9.png)

Here's the amendment I've tried.

```
_proto.loadTileImage = function loadTileImage(tileImage, url) {
        var crossOrigin = this.layer.options['crossOrigin'];
        tileImage.crossOrigin = crossOrigin !== null ? crossOrigin : '';
       
       // add  +++++
        tileImage.onerror = function(){
          tileImage.src = url;
          tileImage.onerrorTick = tileImage.onerrorTick || 0;
          tileImage.onerrorTick = tileImage.onerrorTick + 1;
          if(tileImage.onerrorTick > 9){
            tileImage.onerror = null;
          }
        };

        tileImage.src = url;
        return;
};
```

white patches disappear

**Comment by gee1k** [comment]
天地图现在已经全部服务需要申请 key 才可以使用，瓦片服务只需在 tileUrl 后加一个 tk 参数即可
![image](https://user-images.githubusercontent.com/12059800/51362743-cda34700-1b0f-11e9-87ec-c99ae93493cf.png)

![image](https://user-images.githubusercontent.com/12059800/51362758-d98f0900-1b0f-11e9-9ba6-5a3317b16685.png)

**Comment by gee1k** [comment]
@lifefriend 你可以看看你的瓦片请求错误，状态码应该是 418

**Comment by fuzhenn** [comment]
@lifefriend 
adding a retry strategy to TileLayer is definitely a good idea.
Could you submit a pull request to me?
* add a new option `tileRetryCount` to TileLayer's options
* move the code in your comment to `TileLayerCanvasRenderer`'s `onTileError` method

Thanks!

**Comment by lifefriend** [comment]
@fuzhenn
A pull request has been made in the hope that it does not break your code structure
