### ISSUE TITLE
How to join in your development team

### ISSUE THREAD

**Issue by chakravarthi-vl** [maptalks/maptalks.js#858]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Thanks for your interests to this project.

You are welcome to be aboard any time, please [email me](mailto:fuzhen@maptalks.org) for further discussion.

Closing this issue for now, thanks again.
