### ISSUE TITLE
3D features 重疊但高度不同時顏色會互相交錯

### ISSUE THREAD

**Issue by Wujidadi** [maptalks/maptalks.js#859]
我故意設定幾個座標完全相同的geojson，但令其高度不同，打算製造出分層的效果
出來的畫面會有顏色互相穿透、重疊、交錯的問題，如附圖
請問如何讓分層的顏色正常顯示？

![color_problem_1](https://user-images.githubusercontent.com/10349431/52778938-1bb15900-3082-11e9-8391-2441f964d632.png)
![color_problem_2](https://user-images.githubusercontent.com/10349431/52778960-24a22a80-3082-11e9-9eec-cfedc253ee9b.png)
![color_problem_3](https://user-images.githubusercontent.com/10349431/52779406-07219080-3083-11e9-941b-3a430b73f8f6.png)

理想的效果應該是這樣（沒錯，在特定角度下顏色可以正常顯示）：
![ideal_color](https://user-images.githubusercontent.com/10349431/52779692-a21a6a80-3083-11e9-8f03-833ad521ce17.png)

**Comment by Wujidadi** [comment]
我想藉機再請教一下，有沒有辦法製造出一個懸空的feature，例如上面3層不同顏色的大樓，上面兩層其實是不接地面的？

**Comment by deyihu** [comment]
@Wujidadi   http://jsfiddle.net/xbamdkc6/2/

**Comment by Wujidadi** [comment]
@deyihu 原來是translateZ()
大神請受我一拜

**Comment by deyihu** [comment]
@Wujidadi  哈哈 ，我只是一个普普通通的码农，能帮到你这是最好的了

**Comment by fuzhenn** [comment]
感谢 @deyihu !

**Comment by fuzhenn** [comment]
忘记提了，正文中提到的问题是 深度冲突([z-fighting](https://www.youtube.com/watch?v=9AcCrF_nX-I)) 导致的，解决方法根据不同情况比较复杂，这里就不再赘述。

**Comment by Wujidadi** [comment]
看起來 z-fighting 最好的解決方法大概就是改變不同物體的 z 值使不重疊了，哪怕差 0.1 也好？

**Comment by fuzhenn** [comment]
z-fighting的实质是webgl 深度缓冲 里的深度值，深度值相同时会出现z-fighting。
深度缓冲是个24位的浮点数，很多因素会影响深度值，比如你说的z值，还有物体和相机的距离，相机的近视面的值等。
有时候相机近视面设的太小时，就算z值相差很大，也会出现z-fighting。

我晓得的解决方法：
1. 调整模型的z值
2. 在情况允许下，把相机近视面尽量设得大一些
3. 调整polygonOffset
