### ISSUE TITLE
DrawTool中能否添加一个是否允许绘制Geometry随鼠标移动更新的参数

### ISSUE THREAD

**Issue by AllanHao** [maptalks/maptalks.js#860]
**maptalks's version and what browser you use?**
0.43.0

**Issue description**
实际开发使用DrawTool，需要添加右键菜单，当右键菜单弹出时，不希望geometry随鼠标移动更新，是否可以加入这个参数？

**Comment by AllanHao** [comment]
如果 @fuzhenn 觉得有必要我可以提一个pr，如果觉得没有必要就算了

**Comment by fuzhenn** [comment]
谢谢！请提个pr给我。
我觉得不用增加额外的设置，默认在右键菜单展开时不更新图形就行
