### ISSUE TITLE
ImageLayer 更新Extent后没有效果

### ISSUE THREAD

**Issue by fallowu** [maptalks/maptalks.js#861]
**maptalks's version and what browser you use?**
----
0.43.0
**Issue description**
----
准备图片铺满整个地图，缩放时仍然铺满。使用滚轮缩放地图，监听事件，更新imageLayer extent为map.getExtent()，事件触发了， console出来的imageLayer里的extent也更新了，但是没有效果。
不知道是不是哪里错了。还请看下。
```
      map.on('zooming zoomend', function(e) {
        var images=imageLayer.getImages()
        images[0].extent = map.getExtent()
        imageLayer.setImages(images)
        console.log(imageLayer)
      })    
```

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/fallowu/pen/ErGoba

**Comment by fuzhenn** [comment]
谢谢提issue，我这里重现了这个问题，确实不太正常，我会找时间看一下。

**Comment by deyihu** [comment]
初步确定因为图片的url一样（每个图片被加载后会缓存在ImageLayer实例里），导致重置ImageLayer的images（这时图片的url和上一次一样）的时候会从缓存中直接提取image（而image如被gl render后会绑定 glBuffer的值）导致；

解决方案为每次渲染时删除 image 的 glBuffer就可以了

我待会把代码提交过来

@fallowu  https://deyihu.github.io/src/html/imagelayer.html

**Comment by fallowu** [comment]
感谢对应。

**Comment by fallowu** [comment]
请问pitch与map.getExtent()之间是否存在必要的关联？
若pitch为60时，能否通过map的extent区域，计算出pitch为0时，map的extent区域？
谢谢。
