### ISSUE TITLE
pitch 与map.getExtent()关联

### ISSUE THREAD

**Issue by fallowu** [maptalks/maptalks.js#867]
**maptalks's version and what browser you use?**
----
0.43.0
**Issue description**
----
请问pitch与map.getExtent()之间是否存在必要的关联？
若pitch>0时，能否通过map.getExtent()计算出pitch为0时的extent.
谢谢。

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
很遗憾没什么关联，具体可以参考一下Map.js中的实现
