### ISSUE TITLE
是否支持地形数据的加载?

### ISSUE THREAD

**Issue by wsw87201326** [maptalks/maptalks.js#868]
maptalks是否支持DEM数据的地形加载?实现3d地图的效果?

**Comment by fuzhenn** [comment]
目前暂时不支持，不过地形的支持目前在我们的开发计划中。

**Comment by deyihu** [comment]
@wsw87201326 

今天我正好做了一个地形渲染的效果
利用 http://turfjs.org/docs/#tin 对等高线的数据进行三角拆分（至于tin方法里的相关算法我没有去研究一下）

拆好的数据利用 maptalks.three插件可以渲染，将经纬度数据转化为 three.js的 mesh就可以了

如果你急着用可以尝试一下

![2019-03-17_142753](https://user-images.githubusercontent.com/25998927/54486437-66153800-48c3-11e9-8be7-93bef15d84ab.png)
![2019-03-17_142904](https://user-images.githubusercontent.com/25998927/54486450-7e855280-48c3-11e9-9946-e8b7c955ea8e.png)
