### ISSUE TITLE
请问如何使threejs获取相机控制权

### ISSUE THREAD

**Issue by rindybo** [maptalks/maptalks.js#870]
@fuzhenn 您好，我现在想做的功能是点击模型能够切换全景图浏览，但是不知道如何把相机控制权转给threelayer

**Comment by fuzhenn** [comment]
感谢提issue。
目前没办法把map的相机控制权交给threelayer，只能通过计算map的center, bearing, pitch来调整map的相机。

因为这个issue和核心库无关，先关闭，后续讨论可以继续在这个issue里留言。

**Comment by rindybo** [comment]
好的，谢谢
