### ISSUE TITLE
3D Feature 顏色變換

### ISSUE THREAD

**Issue by Wujidadi** [maptalks/maptalks.js#871]
請問：已渲染完成的 3D features，有辦法隨時變色嗎？

我的 code 如下（`layer3D` 是已渲染完成的 3D 圖層）：
```
layer3D._renderer.scene.add.apply(layer3D._renderer.scene, machines.map(d => {
    let mf = layer3D.toExtrudeMesh(d.geometry, d.height, material('#f70', d.opacity));
    return mf;
}));

function material(color, opacity) {
    return new THREE.MeshPhongMaterial({
        color: color,
        opacity: opacity
    });
}
```
這樣只能做到地圖移動、旋轉或縮放時變色，無法在未改變 view 的情況下靜態地改變顏色。

**Comment by fuzhenn** [comment]
调用一下renderer的setToRedraw应该就行了
```js
layer3D.getRenderer().setToRedraw();
```

**Comment by Wujidadi** [comment]
確實可以了！

不過，又發現一個問題，這樣變色 2～3 次以上時，似乎因為先前的顏色沒有被清掉，又會出現 z-fighting 的狀況，是否有可以清除原有顏色或渲染的方法？

又或者，當前我有多個 3D features，但我只想更改其中 1 個的顏色，有無像 2D features `setSymbol()` 這樣的方法呢？

感謝付兄這麼快回覆，受寵若驚！

**Comment by fuzhenn** [comment]
8客气，哈哈

看上去每次都是创建了新的mesh，设置颜色后加入scene，mesh越加越多就出现了z-fighting.

可以试试只创建一次mesh，之后每次更新mesh的material
```js
mesh.material = material('#f70', d.opacity);
```

**Comment by Wujidadi** [comment]
感謝付兄，問題解決了！

一點小心得：
修改單一 feature 的顏色，只要在創建 mesh 時依原 feature 帶入屬性，後面就能很方便地通過屬性來 filter 要修改的 mesh 了！

**Comment by Wujidadi** [comment]
借串再請教一下，如何取得 mesh 的高度並改變它？

我們設置 mesh 時，藉由 toExtrudeMesh 方法給了一個 height 值，然而渲染完成後，要怎麼從 mesh 對象中取出來……？Three.js 官方有一個 mesh.geometry.parameters.height，然而在 maptalks.three 中好像沒有看到這樣的屬性……

有看到一個 mesh.geometry.parameters.options.depth，但改之無效。直接改每一個 vertices 的 z 值也不起作用。

**Comment by Wujidadi** [comment]
自己找到了，原來是 mesh.scale.z 😂
（不過這個值好像仍然要依賴 toExtrudeMesh 所設定的 height，是用這個 height 去乘以 scale.z？初始值為 0 時就怎麼樣都是 0 ……）
