### ISSUE TITLE
3d模型在近视角下调整角度时发生移动

### ISSUE THREAD

**Issue by rindybo** [maptalks/maptalks.js#872]
![screen](https://user-images.githubusercontent.com/7138939/53779767-66651900-3f3c-11e9-8f64-3e15120e4527.gif)

**Comment by binfenshijie** [comment]
如果是使用了three插件，主要原因可能是模型的水平高度设置问题，主要是模型问题高度属性

**Comment by rindybo** [comment]
已解决

**Comment by wuhandamowang** [comment]
> 如果是使用了three插件，主要原因可能是模型的水平高度设置问题，主要是模型问题高度属性
请问模型的高度有什么要求

> 已解决

请问这个问题是如何解决的？是由模型高度导致的吗？
