### ISSUE TITLE
建筑模型数据在哪下载或者在哪

### ISSUE THREAD

**Issue by wmn1525** [maptalks/maptalks.js#874]
**maptalks's version and what browser you use?**
----
![image](https://user-images.githubusercontent.com/31503298/53941507-37dd6e80-40f3-11e9-88cd-ed4665edf521.png)

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by wmn1525** [comment]
在哪转换

**Comment by fuzhenn** [comment]
sorry，这个问题超纲了，issue只用于maptalks库相关bug和feature request的讨论。
