### ISSUE TITLE
3dBuildings layer 在iOS Safari中异常

### ISSUE THREAD

**Issue by chunjil** [maptalks/maptalks.js#875]
3dBuildings layer 在iOS Safari中看不到立体建筑，在Mac Safari中正常。
[Esri的3dbuildings](https://developers.arcgis.com/javascript/latest/sample-code/layers-scenelayer-edges/live/index.html)在iOS Safari中正常。

**Comment by chunjil** [comment]
这个bug作者有修复计划么，有的话，大概是在什么时候呢~
:-）

**Comment by fuzhenn** [comment]
sorry，正如readme里声明的，biglayer是个实验性的库，后续会有新的图层替代它，所以我们没有再维护它了。
您可以试试用[three.js 插件](https://github.com/maptalks/maptalks.three)绘制三维建筑，这个图层会一直维护
