### ISSUE TITLE
绘制工具边缘检测

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#876]
**maptalks's version and what browser you use?**
----

**Issue description**
当地图放大后，绘制大的图形还是比较麻烦，绘制的过程中还要移动地图；
绘制图形时希望自动检测鼠标位置是否接近地图容器的边缘，当接近容器边缘时自动的对地图向反的方向平移一定的距离

https://codepen.io/deyihu/pen/BbdZxB?editors=0110

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
👍 
这个功能可以通过增加一个新的[map handler](https://github.com/maptalks/maptalks.js/tree/master/src/map/handler)来实现。
通过检测鼠标位置到屏幕边缘，调用panBy即可，实现应该还比较容易。

有兴趣提个pr给我吗？ 😆

**Comment by deyihu** [comment]
@fuzhenn  我这边已经做好了一个，直接写在DrawTool里（因为我目前只想到在绘制图形需要检测边界的问题，其他的地方没想到），我把代码提交过来，你先看一下

另外 panBy 方法，动画和禁止动画，移动的方向好像是反的

https://codepen.io/deyihu/pen/qvXVOX?editors=0010

**Comment by fuzhenn** [comment]
确实是反的，帮忙提个pr过来吧（你太棒了！） 😆
