### ISSUE TITLE
多点文本显示时，text值可不可以加上当前坐标在坐标数组中的索引值

### ISSUE THREAD

**Issue by geminird** [maptalks/maptalks.js#882]
**maptalks's version and what browser you use?**
----

**Issue description**
----
多点文本显示时，text值可不可以加上当前坐标在坐标数组中的索引值，以实现点的数字展示

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
目前没有这个功能，如果需要显示不同的内容，可以把它分开为不同的marker
