### ISSUE TITLE
自定义地图以及缩放尺度的问题

### ISSUE THREAD

**Issue by Saong** [maptalks/maptalks.js#884]
我想把地图的底图换成自己的图片
默认是重复平铺的效果，请问能否去除掉这种效果？改成只显示单张图片

还有就是自定义图片的坐标是如何进行规定的？

**Comment by fuzhenn** [comment]
不要重复平铺： TileLayer里把repeatWorld设为false即可

坐标规定和你选择的投影系统有关，如果是默认的identity([示例](http://maptalks.org/examples/cn/tilelayer-projection/identity/#tilelayer-projection_identity))，则投影系统的中心点是[0, 0]
上下左右的边界如下：
```js
'top': 10000,
'left': -10000,
'bottom': -10000,
'right': 10000
```

你也可以参考示例中的代码自己指定坐标系参数
