### ISSUE TITLE
InfoWindow 在地图移动和缩放时，会移动位置

### ISSUE THREAD

**Issue by ryry886** [maptalks/maptalks.js#886]
**maptalks's version and what browser you use?**
----v0.42.1

**Issue description**
---- 在地图移动和缩放时，InfoWindow会稍微移动一下位置, 然后马上恢复到指定位置，但是我看官网例子（v0.38.2）上的 InfoWindow在移动地图时，infowindow窗口不会移动。v0.43一样的会移动

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
谢谢提issue！我会来看一下这个问题

**Comment by ryry886** [comment]
可以对比下 v0.38.2 和v0.43版本下的 examples里面 9.5图形信息框的例子。移动缩放地图下，InfoWindow表现不同。

**Comment by lifefriend** [comment]
v0.38.2
UIComponent.prototype._measureSize = function _measureSize(dom) {
     ...
    dom.style.top = '0px';
}

v0.43
_proto._measureSize = function _measureSize(dom) {
   ...
   // anchor default is bottom
    dom.style[anchor] = '0px';
}

use css can fix it 

.maptalks-msgBox {
  position: unset !important;
}
