### ISSUE TITLE
How to load terrain data?

### ISSUE THREAD

**Issue by ok958726** [maptalks/maptalks.js#890]
I have saw the demos and read the document,but I'm not find solutions to load terrain data. 
Thanks.

**Comment by fuzhenn** [comment]
Thanks for this issue!

It doesn't support terrain directly now, but you can draw terrain via [maptalks.three](https://github.com/maptalks/maptalks.three) by yourself as described in #868 .

Of course we are planning to add terrain support, but having too many works in the plate, we will turn to this feature later for sure.
