### ISSUE TITLE
polygon能否考虑显示HTMLElement

### ISSUE THREAD

**Issue by ryry886** [maptalks/maptalks.js#891]
**maptalks's version and what browser you use?**
----

**Issue description**
可以绘制带高度的多边形，但是只能是水平面，能否绘制竖直面的多边形。
例子里有个绘制line的高度面，虽然是竖直面的，但是必须接地。
另外polygon里能否像infowindow一样显示HTMLElement，主要是infowindow会随着地图放大旋转而变化，在有些场景不适用。

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
目前VectorLayer无法直接支持带高度的多边形，但用[maptalks.three](https://github.com/maptalks/maptalks.three)是肯定可以的。

在Polygon中绘制HTMLElement目前无法支持。
