### ISSUE TITLE
你好！ 请问怎么加载arcgis动态图层？

### ISSUE THREAD

**Issue by Xyyue221** [maptalks/maptalks.js#892]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
核心库目前不支持，但可以参考[esri.leaflet](https://esri.github.io/esri-leaflet/)加载arcgis动态图层

之前我们有做过esri图层的兼容，但是个半成品: [maptalks.esri](https://github.com/maptalks/maptalks.esri)

目前暂时还没有计划提供对arcgis图层的支持，但如果需要的用户比较多，我们会加到开发计划里的

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.esri
