### ISSUE TITLE
为什么没有图层组LayerGroup

### ISSUE THREAD

**Issue by zhengtan2003** [maptalks/maptalks.js#893]
因为用习惯了leaflet     只是想知道  为什么没有LayerGroup类似的东西

**Comment by fuzhenn** [comment]
leaflet里的LayerGroup是用来添加多个图形的，和maptalks中的VectorLayer作用其实一样
而且VectorLayer功能更多，比如支持identify方法，能整体设置样式等。

**Comment by zhengtan2003** [comment]
非常感谢
