### ISSUE TITLE
关于图形绘制

### ISSUE THREAD

**Issue by joli007** [maptalks/maptalks.js#894]
既然对标leaflet和openlayer，能不能在绘制图形时也加入捕捉的效果，就是能够自动吸附到临近的节点或线上。

**Comment by fuzhenn** [comment]
您可以看一下这个插件：
https://github.com/liubgithub/maptalks.snapto

**Comment by fuzhenn** [comment]
另外提一下，maptalks并没有对标 openlayers 和 leaflet  :)

**Comment by joli007** [comment]
> 您可以看一下这个插件：
> https://github.com/liubgithub/maptalks.snapto

谢谢，确实解决了绘制时的捕捉，遗憾的就是在编辑状态下不行。
