### ISSUE TITLE
maptalks默认是PerspectiveView还是OrthographicView？

### ISSUE THREAD

**Issue by dytmh** [maptalks/maptalks.js#895]
maptalks默认是PerspectiveView还是OrthographicView？ 支持设置Perspective或者Orthographic吗？

**Comment by fuzhenn** [comment]
固定为PerspectiveView，不支持Orthographic
map的相机矩阵在这里：
https://github.com/maptalks/maptalks.js/blob/master/src/map/Map.Camera.js#L294
