### ISSUE TITLE
wkt格式转换

### ISSUE THREAD

**Issue by ybtsdst** [maptalks/maptalks.js#897]
**maptalks's version and what browser you use?**
----
0.44.0

**Issue description**
----
Geometry是否支持wkt格式？序列化和反序列化等

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
可以通过 [maptalks.formats](https://github.com/maptalks/maptalks.formats) 插件转换

**Comment by ybtsdst** [comment]
我看只有wkt转成Geometry? 有Geometry转成wkt的示例么

**Comment by fuzhenn** [comment]
这个没有，您可以直接用 [wellknown](https://github.com/mapbox/wellknown) 
maptalks.Geometry提供了和geojson的互转方法。
```js
//geometry => geojson
geometry.toGeoJSON();
//geojson => geometry
maptalks.GeoJSON.toGeometry(geojson);
```
然后通过wellknown来把geojson与wkt互转即可。
