### ISSUE TITLE
热力图显示问题

### ISSUE THREAD

**Issue by ybtsdst** [maptalks/maptalks.js#900]
**maptalks's version and what browser you use?**
----
0.44.0

**Issue description**
----
https://github.com/maptalks/maptalks.heatmap/issues/38

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
具体的原理其实我也没有仔细研究过 😳 
maptalks.heatmap 里的热力图是完全基于[simpleheat](https://github.com/mourner/simpleheat)生成的，你可以看一下它的原理。

**Comment by ybtsdst** [comment]
好吧，我试下simpleheat

**Comment by ybtsdst** [comment]
> 具体的原理其实我也没有仔细研究过 
> maptalks.heatmap 里的热力图是完全基于[simpleheat](https://github.com/mourner/simpleheat)生成的，你可以看一下它的原理。

好吧，我试下simpleheat

**Comment by fuzhenn** [comment]
嗯嗯，heatmap里的热力图是基于simpleheat绘制的。
所以你可以看一下simpleheat里的参数一般如何设置，然后设置到heatmap图层里即可。
simpleheat也提供了一个交互式页面用于测试不同的参数。

**Comment by ybtsdst** [comment]
> 嗯嗯，heatmap里的热力图是基于simpleheat绘制的。
> 所以你可以看一下simpleheat里的参数一般如何设置，然后设置到heatmap图层里即可。
> simpleheat也提供了一个交互式页面用于测试不同的参数。

[这行](https://github.com/maptalks/maptalks.heatmap/blob/90688057c556099f1fc57890b591d0e7688090aa/index.js#L178)，会把原始数组的第三个值改掉，但是修改后的值貌似不太正常.

下图是debug的截图:
![Screenshot from 2019-05-09 16-04-13](https://user-images.githubusercontent.com/3139535/57437766-09a41880-7275-11e9-9662-3a14d8aae1df.png)
这个是`_heatData`返回后的数据.

![Screenshot from 2019-05-09 16-03-53](https://user-images.githubusercontent.com/3139535/57437767-0a3caf00-7275-11e9-9969-13c83832fea4.png)
这个是原始数据.

@fuzhenn 请问，这个能怎么快速修复一下？比较急

**Comment by fuzhenn** [comment]
收到，能否用jsfiddle或者codepen整理一个重现demo？

**Comment by ybtsdst** [comment]
好的，==

**Comment by ybtsdst** [comment]
> 收到，能否用jsfiddle或者codepen整理一个重现demo？

https://codepen.io/ybtsdst/pen/Ybwqjq

**Comment by fuzhenn** [comment]
请看一下这个版本是否解决了该问题:

[maptalks.heatmap.zip](https://github.com/maptalks/maptalks.js/files/3161117/maptalks.heatmap.zip)

**Comment by ybtsdst** [comment]
> 请看一下这个版本是否解决了该问题:
> 
> [maptalks.heatmap.zip](https://github.com/maptalks/maptalks.js/files/3161117/maptalks.heatmap.zip)

我试下

**Comment by ybtsdst** [comment]
![Screenshot from 2019-05-09 16-55-38](https://user-images.githubusercontent.com/3139535/57440848-51c63980-727b-11e9-969d-0cd3a5caf132.png)

目测能出来了，不过比openlayers的略丑:smile:

**Comment by fuzhenn** [comment]
😓  可以调整radius和blur参数，看看是否能改善显示效果。

那我先关闭这个issue，等会我会发布一下maptalks.heatmap的新版本

**Comment by ybtsdst** [comment]
嗯嗯，多谢支持:thumbsup:

**Comment by fuzhenn** [comment]
已经发布新版本 v0.6.0
增加了一个新的option: `heatValueScale`(热力值的乘数因子)，用于在绘制前动态调整热力值。
heatValueScale设得越大，热力图就越深，越小，则越浅
