### ISSUE TITLE
marker能否随图层倾斜？

### ISSUE THREAD

**Issue by hceasy** [maptalks/maptalks.js#903]
做了一个导航功能，marker用了自定义图片，地图倾斜和旋转的时候这个marker一直是竖起来的，角度还可以根据地图旋转大小加补偿，倾斜视角没办法搞定。大家都是怎么解决这个问题的？想做成类似高德导航那种效果。

**Comment by hceasy** [comment]
明天开工先试试这个
https://github.com/maptalks/maptalks.js/issues/717

**Comment by adevin** [comment]
我也遇到同样的问题 这个现在可以了吗

**Comment by hceasy** [comment]
> 我也遇到同样的问题 这个现在可以了吗

用UIMarker,缺点是不能弹出信息框
