### ISSUE TITLE
Document Error

### ISSUE THREAD

**Issue by ghost** [maptalks/maptalks.js#904]
**maptalks's version and what browser you use?**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.27 Safari/537.36

**Issue description**
Word misspelling in example code, Layerswither -> LayerSwitcher .

**Please provide a reproduction URL (on any jsfiddle like site)**
http://maptalks.org/maptalks.js/api/0.x/control.LayerSwitcher.html

**Comment by fuzhenn** [comment]
Good catch 😄  

Could you create a PR?
The API document is generated from comments, so you can fix the typo in this line:

https://github.com/maptalks/maptalks.js/blob/master/src/control/Control.LayerSwitcher.js#L31

**Comment by ghost** [comment]
ok, but contributing guide https://github.com/maptalks/maptalks.js/blob/master/CONTRIBUTING.md is not found in master README.md...

**Comment by ghost** [comment]
Pull request: #905

**Comment by fuzhenn** [comment]
Thanks! closed by #905
