### ISSUE TITLE
为什么会出现多个图

### ISSUE THREAD

**Issue by huishuohuadeTT** [maptalks/maptalks.js#907]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by huishuohuadeTT** [comment]
![Uploading 16570202286218.jpg…]()

**Comment by fuzhenn** [comment]
不好意思，请在jsfiddle或者codepen上提供一个重现代码
