### ISSUE TITLE
imagelayer在设置option{renderer:'gl'}的情况，设置mask，图片会消失

### ISSUE THREAD

**Issue by whydontyoufly** [maptalks/maptalks.js#909]
**maptalks's version and what browser you use?**
----
0.44.0
**Issue description**
----
imagelayer在设置option{renderer:'gl'}的情况，设置mask，图片会消失

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/accountli/pen/MdQeaE

**Comment by Liquid-Zhangliquan** [comment]
您好，我试着重现你说的问题，但是没发现错误
这是我的代码和效果截图
![image](https://user-images.githubusercontent.com/23397455/58066461-ff124900-7bbb-11e9-944f-d28f2db32c1e.png)

**Comment by fuzhenn** [comment]
谢谢提出issue，@whydontyoufly 你提供的重现代码地址访问不了啦，能否用codepen或者jsfiddle提供一个最小重现代码
