### ISSUE TITLE
底图切换导致三维元素不显示问题

### ISSUE THREAD

**Issue by airoba** [maptalks/maptalks.js#911]
加载arcgis瓦片服务后，三维带高度的所有元素就不显示了。
如果将底图切换成其它的就没出现此问题。
不知道是BUG还是什么其它问题导致的。

**Comment by fuzhenn** [comment]
我们还没有遇到过这个问题，是否能提供一个最小重现代码？

**Comment by airoba** [comment]
json文件是建筑轮廓数据，
iot是写的测试代码，里边有注释。
重现代码可能需要您稍微调整下文件请求路径（ps:还差个jquery）


------------------ 原始邮件 ------------------
发件人: "Fu Zhen"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 下午4:30
收件人: "maptalks/maptalks.js"<maptalks.js@noreply.github.com>;
抄送: "尽享此时此刻"<535125065@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [maptalks/maptalks.js] 底图切换导致三维元素不显示问题 (#911)




我们还没有遇到过这个问题，是否能提供一个最小重现代码？
