### ISSUE TITLE
请问是否能够在echarts-gl上展示maptalks图层

### ISSUE THREAD

**Issue by wangpinyuan** [maptalks/maptalks.js#913]
比如 https://gallery.echartsjs.com/editor.html?c=xeap3hI0rs 这样geo3D的地图。
我希望地图上配上maptalks元素，比如 http://maptalks.org/examples/cn/geometry/textbox/#geometry_textbox 文本框。
我的理解是以echarts-gl作为maptalks的图层，在另一个maptalks图层上渲染文本框。现有的插件似乎不支持这点。请问思路是什么？

**Comment by fuzhenn** [comment]
https://github.com/deyihu/maptalks-echarts-gl

您可以看一下这个库，它可以把echarts当做maptalks的图层使用，看一下是否满足您的要求

**Comment by wangpinyuan** [comment]
感谢回答。
用这种方式实现了echarts-gl坐标系贴合。
又使用new maptalks.ui.UIMaker将自定义组件附上。

**Comment by wangpinyuan** [comment]
另，不过这种方式在添加border时出现不贴合的情况。https://gallery.echartsjs.com/editor.html?c=xxwuivnLAL&v=4

**Comment by deyihu** [comment]
@wangpinyuan  

出现这个问题的原因为 echarts-gl里 extrude 的方向为 Y 轴，maptalks3D 和 mapbox3D的组件的 extrude 方向为Z 轴，

我刚才尝试修复了一下,在内部做了 coordinateSystem的适配

example  https://gallery.echartsjs.com/editor.html?c=xC9KzCXX59&v=1

fix code  https://github.com/deyihu/echarts-gl/commit/8d2f6032502737d6e7d9c83bdc2d792555aa08c8

ps: echarts-gl里的bug 还是有点多的，使用时请注意

**Comment by fuzhenn** [comment]
感谢 @deyihu ，那我先关闭这个issue

**Comment by wangpinyuan** [comment]
感谢回答，问题已解决。
