### ISSUE TITLE
VectorLayer的渲染完成事件触发后，toDataURL下载图片结果不对

### ISSUE THREAD

**Issue by whydontyoufly** [maptalks/maptalks.js#914]
**maptalks's version and what browser you use?**
----
0.44.0
**Issue description**
----
VectorLayer的渲染完成事件触发后，toDataURL下载图片结果不对。设置定时器延迟截图就是正确的结果。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/anon/pen/LoJNqG

**Comment by sakitam-fdd** [comment]
@whydontyoufly 试试 layerload 事件：
```js
layer.on('layerload',function(){
    map.toDataURL({
      'mimeType' : 'image/png', // or 'image/png'
      'save' : true,             // to pop a save dialog
      'fileName' : '000'         // file name
    });
  });
  layer.addGeometry(multipoint);
  map.addLayer(layer);
```

**Comment by whydontyoufly** [comment]
layerload可以诶！但是怎么官网的api里面没看见这个事件呢
