### ISSUE TITLE
请问maptalk可以集成在小程序里吗

### ISSUE THREAD

**Issue by yangyang158** [maptalks/maptalks.js#916]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by liubgithub** [comment]
完全可以啊

**Comment by yangyang158** [comment]
小程序里没有document和window，maptalks.js脚本里调用了 var ua = navigator.userAgent.toLowerCase(),
            doc = document.documentElement,就报错了

**Comment by liubgithub** [comment]
可以用web-view标签嵌套

**Comment by yangyang158** [comment]
是的，最后就是这样处理的

**Comment by yangyang158** [comment]
在小程序端 支持离线使用吗

**Comment by fuzhenn** [comment]
感谢 @liubgithub 的解答，那暂时关闭此issue。
maptalks现在还不能原生支持小程序，如果未来用户的需求量大，会考虑做一下适配。
