### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by dr-vadim** [maptalks/maptalks.js#918]
**maptalks's version and what browser you use?**
0.44.2

**Issue description**
Hello! When I trying to cover my React components (wich are contains MapTalks lib) with unit tests I'm facing with error "Invalid container when creating map: ". For mounting components I use Enzyme framework. Do you have any ideas, how to overcome it? :cheers:

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Without reproduction codes, we aren't able to investigate the exact cause. Below are our guesses:

It looks like you haven't provided a valid container when creating map instance in your unit test.

```js
new Map(container, options);
```
container can be id or dom element of the html container you want to load map in.

It can also be the reason of asyn loading, the dom is not ready when you calling map constructor. 

Maybe worth to mention, usually map is initiated in `componentDidMount` method of React component.

**Comment by Arnack** [comment]
Hi! Here is the way how we use maptalks:

A simplified component which contains map: 
```
import * as React from "react";
import * as maptalks from "maptalks";
.....
class Map extends React.Component<IMapProps, IMapState> {
...
    initMap = () => {
        const {id} = this.props;
        let map = new maptalks.Map(id, {
            center: center,
           ....
            baseLayer: new maptalks.TileLayer('base', {
                urlTemplate: 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
                subdomains: ['a', 'b', 'c', 'd']
            })
        });
        return map;
    };

    componentDidMount () {
        this.setState({map: this.initMap()}, () => {
            .....
        });
    }

    render () {
        const {id} = this.props;
        ...
        return (
            <div id={id} className="..." />
        )
    }
};
```

Then we just place it other components

````
<div>
     <Map id="map" ... />
</div>
````

It works great in normal usage, but not in Enzyme tests

**Comment by fuzhenn** [comment]
It looks like, Enzyme depends on [jsdom](https://github.com/jsdom/jsdom) to mock the browser enviroment, which may be the cause of failing to get container element.

My colleague said you can try to pass [react ref](https://reactjs.org/docs/refs-and-the-dom.html) to Map's constructor to solve this problem.

**Comment by mankeheaven** [comment]
when you test, document.getElementById("map") in componentDidMount is null, but it's ok when you delelop.
The enviroments of test and dev is diffirent.
use ref like this can resolve your question:
```
myRef = React.createRef() as any;

  render() {
    return <div ref={this.myRef}  style={{height: "800px", width: "1000px"}}>

    </div>
  }

  componentDidMount(){

    // const mymap = document.getElementById("mymap")

    // console.log(mymap)

    let map = new maptalks.Map(this.myRef.current, {
      center: [114.31, 30.52],
      minZoom: 1,
      zoom: 6,
      zoomControl: {
        position: { bottom: "76", right: "10" },
        slider: false,
        zoomLevel: true
      }
    });

    const layer = new VectorTileLayer("vt", {
      urlTemplate:
        "https://api.mapbox.com/v4/mapbox.mapbox-streets-v7/{z}/{x}/{y}.vector.pbf?access_token=pk.eyJ1IjoidGFuZ21pbmd5YW5nIiwiYSI6ImNqczVqZmw2eTBnOW0zem96OHN4Zm41bTgifQ.0EPVaDmwmlr8iXf9cT34Kg",
      background: [0, 0, 0, 1]
    }).addTo(map);

    console.log(map, layer)
  }
```

**Comment by fuzhenn** [comment]
close due to lack of activity
