### ISSUE TITLE
请问一下付老师，maptalks现在支不支持一些buffer的计算，例如绘制一条线之后，提供一个长度值沿着线绘制辐射范围。其实跟绘制Circle有点类似。谢谢。

### ISSUE THREAD

**Issue by wuhandamowang** [maptalks/maptalks.js#921]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
你好！
maptalks不直接支持buffer计算，可以直接调用第三方库，例如[turf.js](https://turfjs.org/)来计算。
基于turf.js的大概调用示例：
```js
const geojson = geometry.toGeoJSON();
const buffered = turf.buffer(geojson , 0.5, {units: 'kilometers'});
const bufferedGeometry = maptalks.GeoJSON.toGeometry(buffered);
```

**Comment by wuhandamowang** [comment]
收到，谢谢付老师
