### ISSUE TITLE
关于阴影shadowBlur 引发的事件问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#922]
**maptalks's version and what browser you use?**
----

**Issue description**
----

如果 geometry symbol 设置了阴影

```js
           shadowColor: 'black',
            shadowBlur: 50
```

https://codepen.io/deyihu/pen/pXvdyp?editors=0110

会导致事件触发有点问题（我还不确定这是不是一个bug）,事件检测的时候会把shadowBlur算进去，以我给这个例子为例，当鼠标还没有移动到线上就触发了鼠标手势了（当然这时鼠标已经在线的阴影里），**就是阴影到底算不算线宽度的问题，我认为阴影这个应该算线的效果，而不是线的宽度**

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
有道理，我会去掉shadow的事件监听
