### ISSUE TITLE
请问付老师，WMSTileLayer支持切片原点这个属性吗，类似openlayer里面的tilesOrigin属性

### ISSUE THREAD

**Issue by wuhandamowang** [maptalks/maptalks.js#923]
**maptalks's version and what browser you use?**
----

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
支持的，不过maptalks是通过设置TileLayer(WMSTileLayer的父类)的tileSystem来设置tilesOrigin的
tileSystem是一个四位数组： [sx, sy, ox, oy]
sx,sy是瓦片序号的增长方向，ox和oy就是tilesOrigin的x,y值了。
* sx为1时，从左到右序号增大，-1则反之
* sy为1时，从上到下序号增大，-1则反之

用这个TileSystem能描述所有的地图瓦片系统。

例如 3857 的 TileSystem：`[1, -1, -6378137 * Math.PI, 6378137 * Math.PI]`

```js
const layer = new TileLayer('t', {
  urlTemplate: '..',
  tileSystem: [1, -1, -6378137 * Math.PI, 6378137 * Math.PI]
});
```

这里有更多引擎内置的 [tileSystem 示例](https://github.com/maptalks/maptalks.js/blob/master/src/layer/tile/tileinfo/TileSystem.js#L64)和TileSystem的[说明文档](https://github.com/maptalks/maptalks.js/wiki/Tile-System)

希望能解决你的问题。
