### ISSUE TITLE
LineWidth between the starting point and the endpoint

### ISSUE THREAD

**Issue by jmerlinz** [maptalks/maptalks.js#924]
**maptalks's version and what browser you use?**
---- 
Maptalks 0.44.2 & google Chrome

**Issue description**
----
Is it possible to draw a lineString that has difference LineWidth between starting point and endpoint. I've been trying to use stops to determine, but it didn't work for me.

Thank you!

**Comment by fuzhenn** [comment]
duplicate of #925
