### ISSUE TITLE
请问一下是否支持geoJson作为底图？

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.js#926]
**maptalks's version and what browser you use?**
----

**Issue description**
如果图所示，该效果是以eachrts加载深圳geoJson数据作为底图，请问maptalks能不能做这样的效果？
![image](https://user-images.githubusercontent.com/24503453/59730237-2d934a80-9274-11e9-9277-d4b7276efb64.png)

----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
支持的，用VectorLayer加载geojson，设为map的baseLayer即可

map的baseLayer并没有要求必须用TileLayer，什么图层都可以

**Comment by MaJiaXuan** [comment]
@fuzhenn 请问有没有例子？谢谢

**Comment by fuzhenn** [comment]
https://codepen.io/fuzhenn-the-decoder/pen/wLzxwm
```js
var json = {
  'type': 'Feature',
  'geometry': {
    'type': 'Polygon',
    'coordinates': [
      [
          [-0.123049, 51.503568],
          [-0.136049, 51.503568],
          [-0.136049, 51.488568],
          [-0.123049, 51.488568]
       ]
    ]
  },
  'properties': {
    'type': 1
  }
};
var map = new maptalks.Map('map', {
  center: [-0.113049, 51.498568],
  zoom: 14,
  baseLayer: new maptalks.VectorLayer('v', json, {
    style: [
      {
        filter: ['=', 'type', 1],
        symbol: {
          polygonFill: '#f00',
          polygonOpacity: 0.5
        }
      }
    ]
  })
});

```

**Comment by MaJiaXuan** [comment]
@fuzhenn 非常感谢！
