### ISSUE TITLE
line设置smoothness后，缩放和拖动地图，line变形

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [maptalks/maptalks.js#930]
**maptalks's version and what browser you use?**
----0.44.2

**Issue description**
----当我设置smoothness=0.1时，缩放和拖动地图出现line的轨迹变形的情况；具体操作是当你的line在你视图下方时会重现

**Please provide a reproduction URL (on any jsfiddle like site)**
----https://codepen.io/liquid-zhangliquan/pen/wLzZVG

**Comment by Liquid-Zhangliquan** [comment]
正常情况下：![image](https://user-images.githubusercontent.com/23397455/59748577-fc377080-92ad-11e9-8f54-499169b58de7.png)
异常：
![image](https://user-images.githubusercontent.com/23397455/59748617-11ac9a80-92ae-11e9-9f03-87dd97a5711a.png)

**Comment by fuzhenn** [comment]
another reproduction:
https://liquid-zhangliquan.github.io/maptalks-weather-demo/weather_demo/weather_line1.html?tdsourcetag=s_pctim_aiomsg
