### ISSUE TITLE
Map listens for context events, context menu cannot be displayed

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#932]
**maptalks's version and what browser you use?**
----

**Issue description**
----
Map listens for context events, context menu cannot be displayed

地图对象监听了 contextmenu 事件，导致 上下文菜单不能显示了

```js

      var options = {
        'items'  : [
              {item: 'item1', click: function () { alert('Click item1'); }},
          '-',
              {item: 'item2', click: function () { alert('Click item2'); }}
        ]
      };
      map.setMenu(options);//.openMenu();


      map.on('contextmenu',function(e){
        console.log(e);
      });

```

https://codepen.io/deyihu/pen/WqoBJO

希望地图既可以触发contextmenu，当setMenu了后也希望菜单能被显示，不知道这个需求是否合理，我看了一下内部做了次数限制

```js

 /**
     * If contextmenu is not listened, open the menu in default.<br>
     * Otherwise, do nothing here.
     * @param  {Object} param - event parameter
     * @return {Boolean} true | false to stop event propagation
     * @private
     */
    _defaultOpenMenu(param) {
        if (this.listens('contextmenu') > 1) {
            return true;
        } else {
            this.openMenu(param['coordinate']);
            return false;
        }
    }

```

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
大多数情况下，用户监听contextmenu事件后，是不希望默认显示menu的。
如果需要，可以手动调用 map.openMenu(e.coordinate);

感觉这样设计会更合理，因为如果默认就显示menu，当客户不需要时，目前是无法禁用menu显示的。

所以感觉目前的设计更合理。

**Comment by deyihu** [comment]
@fuzhenn 

我平时如果不用map自带的menu,需要自己自定义的话，会在contextmenu事件里去展示自己手写的menu,根本不会进行map.setMenu的，既然我设置了就希望其显示的，否则我就不会设置map的menu，这样就显得多此一举了 :smile:



**对了了目前类似于markerFile这样的配置项能否添加
blob,image对象，canvas等的支持，我试了一下目前好像只支持 url, base64**

今天我做文件上传的时候，直接在前端URL.createObjectURL(file)的时候，发现 markerFile不支持blob这样的方式，由此想到更多的对象支持，比如:Image,canvas等对象


[test url](https://codepen.io/deyihu/pen/MMpMGB)

**Comment by fuzhenn** [comment]
目前maptalks的symbol属性有个强制要求，就是所有属性都应该支持JSON序列化（这个是maptalks的核心特性）。

因为blob, image和canvas都不支持序列化，所以markerFile不会直接提供对这些类型的支持，可以把它们转化成base64后再设置~

**Comment by deyihu** [comment]
close by https://github.com/maptalks/maptalks.js/commit/3889e298108abc8457716da5dc321b9ec9c189aa
