### ISSUE TITLE
現在能讀取OSM文件嗎？

### ISSUE THREAD

**Issue by Wujidadi** [maptalks/maptalks.js#933]
有時候數據來源都是OSM，必須先轉為GeoJSON才能讀取，目前能像OpenLayers那樣直接讀取OSM XML文件嗎？剛剛看了maptalks.formats，好像也沒有OSM格式。

**Comment by fuzhenn** [comment]
目前不直接支持osm xml，不过可以扩展maptalks.formats来做支持。
但因为目前手头事情较多，暂时腾不出时间来实现这个特性，不知道 @Wujidadi 兄有兴趣吗？

**Comment by Wujidadi** [comment]
好啊，有空來研究研究，不過最近我也比較忙就是了……😂

**Comment by deyihu** [comment]
@Wujidadi @fuzhenn   

https://github.com/maptalks/maptalks.formats/pull/2

**Comment by fuzhenn** [comment]
谢谢 @deyihu 
maptalks.formats 插件已经增加了OSM的支持并发布到npm上了 (v0.3.0)

**Comment by Wujidadi** [comment]
感謝 @deyihu 大佬，慚愧我一直擠不出時間研究……
