### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.js#934]
**maptalks's version and what browser you use?**
----

**Issue description**
有一个场景：marker很多，而且每个marker都单独绑定一个或者多个事件，这样会比较耗性能。
能不能使用最外层也就是
var map = new maptalks.Map('map', ...)
使用map绑定事件，然后通过代理的方式，代理到每个market的事件，这样是否可以？
![image](https://user-images.githubusercontent.com/24503453/59893534-c6120200-940f-11e9-91a6-87fb52bfcea3.png)
![image](https://user-images.githubusercontent.com/24503453/59893546-d7f3a500-940f-11e9-87ab-4d8549ddaeba.png)
![image](https://user-images.githubusercontent.com/24503453/59893559-e215a380-940f-11e9-970e-9d8489a30d17.png)
如上三图所示，目前好像没在map点击回调中拿到marker的点
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by liubgithub** [comment]
如果不想在marker上绑定事件，可以考虑用map.identify的方式
http://maptalks.org/maptalks.js/api/0.x/Map.html#identify

**Comment by MaJiaXuan** [comment]
@liubgithub 我试了下，回调函数中没拿任何东西
![image](https://user-images.githubusercontent.com/24503453/59903244-1058aa80-9433-11e9-93ab-46e6302628da.png)

**Comment by liubgithub** [comment]
确定你设置coordinate:[0, 0]这个地方有marker吗，如果没有marker，返回的是拿不到东西的，比较正确的做法应该是coordinate:e.coordinate, 即用你鼠标点的地方作为识别点

**Comment by MaJiaXuan** [comment]
@liubgithub 谢谢 ，可以了

**Comment by fuzhenn** [comment]
谢谢 @liubgithub !
