### ISSUE TITLE
地图 wrap-y 方向平铺添加可配置选项

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#935]
现状：
目前地图视图默认平铺Y 轴方向；
期望：
有些时候可能不需要 Y 方向的平铺，希望可以增加可配置项来定义是否开启 Y 轴方向的平铺。

**Comment by fuzhenn** [comment]
repeatWorld 可以设为 true, x 或者 y，来控制 repeat world 的方向
