### ISSUE TITLE
问题：关于栅格瓦片层级变化时的更新问题

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#936]
**maptalks's version and what browser you use?**
----
 V0.44.2
**Issue description**
----
1、如果我的栅格瓦片服务只提供了前五级，在第六级时地图上将不会显示任何瓦块，这是 maptalks 的处理，当然我们在预先知道切片层级时可以指定maxAvailableZoom参数（缺陷是如果预先不知道层级时就没办法进行设置）。
2、openlayer 和 mapbox 存在另外一种处理方式，当下一级瓦片不存在或者加载失败后，默认使用上一级瓦片，这样也会存在一个弊端就是有些情况下地图呈现会有部分区域模糊。

这种情况是否有更好的处理方式？

**Comment by fuzhenn** [comment]
我对这个问题也想不出什么更好的办法 😞
