### ISSUE TITLE
希望文档能完善一下

### ISSUE THREAD

**Issue by adevin** [maptalks/maptalks.js#938]
我一般是按这个逻辑来使用的 。 比如我想画一个粒子层，我会看demo。demo中主要可以看到
`      particles.getParticles = function (t) {
        var point = map.coordinateToContainerPoint(center);
        // particle's angle at current time
        var angle = (t / 16 % 360) * Math.PI / 180;
        // convert distance in meter to pixel length
        var pxLen = map.distanceToPixel(radius, radius);
        var r = pxLen.width;
        // caculate pixel offset from circle's center
        var x = r * Math.cos(angle),
          y = r * Math.sin(angle);
        return [
          {
            point : point.add(x, y),
            r : 4,
            color : 'rgb(135,196,240)'
          }
        ];
      };`

getParticles  主要是这个方法。 然后就去找API 但API基本什么没说啊。 只说了个入参 t。 然后定位到源码。 这样我就不太知道 这个return回来的数组都要包含什么。需要返回什么。只能猜测一下。

**Comment by adevin** [comment]
还有希望能多吸收一些人加入维护框架。 一两个人维护这么大的框架和文档真的很难。也感谢开发组的付出。

**Comment by fuzhenn** [comment]
感谢你的建议！

我们的API文档都是从源代码中的注释中自动生成的，如果你发现API中有待改善点，很欢迎直接修改相应的注释帮我们改善API文档。 😆
