### ISSUE TITLE
maptalk加载百度地图切片比百度的api模糊

### ISSUE THREAD

**Issue by whydontyoufly** [maptalks/maptalks.js#941]
**maptalks's version and what browser you use?**
----
0.44.0
**Issue description**
----
加载百度地图在线瓦片，底图看起来比百度自己原生的api记载的模糊一些。

**Please provide a reproduction URL (on any jsfiddle like site)**
----
maptalks加载
https://codepen.io/accountli/pen/VJdJNL
百度官网例子（地图层级需要设置一样的）
http://lbsyun.baidu.com/jsdemo.htm#a1_2

**Comment by fuzhenn** [comment]
从你给的例子里，没看出来两者有什么不同，是不是缺了别的什么设置？

## maptalks
![image](https://user-images.githubusercontent.com/13678919/60648115-dd220c80-9e71-11e9-80fd-f89ad0eb65d7.png)

## baidu
![image](https://user-images.githubusercontent.com/13678919/60648068-bc59b700-9e71-11e9-9d89-6a866e22ffa0.png)

**Comment by whydontyoufly** [comment]
[map.zip](https://github.com/maptalks/maptalks.js/files/3358482/map.zip)
包含一个maptalks的是实现和百度的实现，百度的要添加自己的key。
在浏览器里打开两个html，左右切换会发现模糊的情况。同时还会看到切换两个页面的时候，地图有拉伸的情况。

**Comment by fuzhenn** [comment]
刚试了一下，实在没看出来maptalks的比baidu 的模糊
https://codepen.io/fuzhenn-the-decoder/pen/qzyQKg

另外相同中心点，左右切换地图有点小晃动是正常的，应该是百度的坐标转换和maptalks转换策略（比如是否取整）不同造成的，但标注的位置一般都是准确的

**Comment by fuzhenn** [comment]
最后经过沟通，发现是retina屏下，百度地图会根据devicePixelRatio自动切换底图的原因。
maptalks中也可以根据dpr自动切换底图，达到同样的效果。
https://codepen.io/fuzhenn-the-decoder/pen/qzyQKg
```js
     var map = new maptalks.Map('map', {
          center: [106.569849,29.561211],
          zoom: 18,
          minZoom:1,
          maxZoom:19,
          draggable:true,
          zoomable:true,
          scaleControl:true,
          dragRotate:false,
          dragPitch:false,
          dragRotatePitch:false,
          spatialReference:{
            projection : 'baidu'
          }
      });
      const dpr = map.getDevicePixelRatio();
      const scaler = dpr > 1 ? 2 : 1;
      map.setBaseLayer(new maptalks.TileLayer('base', {
        'urlTemplate': `http://online2.map.bdimg.com/tile/?qt=vtile&x={x}&y={y}&z={z}&styles=pl&scaler=${scaler}&udt=20190704`,
        'subdomains'  : [0,1,2,3,4,5,6,7,8,9],
        'attribution' :  '&copy; <a target="_blank" href="http://map.baidu.com">Baidu</a>'
      }));
```
