### ISSUE TITLE
我用canvas画的一些动图，怎么通过坐标 像Marker那样定位到地图上面呢

### ISSUE THREAD

**Issue by adevin** [maptalks/maptalks.js#942]
**maptalks's version and what browser you use?**
----最新版

**Issue description**
----我用canvas画的一些动图，怎么通过坐标 想Marker那样定位到地图上面呢
好像canvas只是覆盖的表面了 并没有坐标可以定位啊

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by liubgithub** [comment]
可以自己实现一个继承自canvaslayer的插件

**Comment by fuzhenn** [comment]
@adevin 你可以参考文档中的插件开发指南，自己开发一个基于canvas的插件，你的问题在指南里都有解答。
https://github.com/maptalks/maptalks.js/wiki/%E5%88%9B%E5%BB%BA%E6%96%B0%E5%9B%BE%E5%B1%82

我先关闭这个issue，有进一步的问题欢迎随时讨论。
