### ISSUE TITLE
能不能在视野内显示所有的标记点(Marker)

### ISSUE THREAD

**Issue by yangyang158** [maptalks/maptalks.js#944]

**Comment by fuzhenn** [comment]
sorry，不是很明白你的需求

**Comment by liubgithub** [comment]
1、先获取当前marker所在图层的范围：var extent = layer.getExtent();
2、然后获取最合适的地图缩放级别，就可以看到所有marker了：var zoom = map.getFitZoom(extent);

**Comment by yangyang158** [comment]
作者您好，现在页面上有几十个marker，并且位置比较分散，想要在页面渲染完后，视野内能看到所有的marker，getFitZoom可以获取到合适的缩放级别，但是还需要一个合适的中心坐标点，有没有方法 获取呢？

**Comment by liubgithub** [comment]
extent获取后，extent的中心就是你这几十个marker的外接矩形的中心，应该是你想要的比较合适的中心，即var center = extent.getCenter();

**Comment by liubgithub** [comment]
参考官方文档：http://maptalks.org/maptalks.js/api/0.x/Extent.html#getCenter
