### ISSUE TITLE
请问能这种图形吗？

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.js#945]
**maptalks's version and what browser you use?**
----

**Issue description**
请问能做这种3D图形吗
![TIM截图20190705120238](https://user-images.githubusercontent.com/24503453/60698748-70ffe100-9f23-11e9-8155-90ce2ad59564.png)
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
这个可以用 maptalks.three 插件做

**Comment by wefiy** [comment]
@MaJiaXuan 你这个2.5D的效果实现出来了吗？
