### ISSUE TITLE
Load tiles with base64 encoding,Page performance is very poor

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#946]
**maptalks's version and what browser you use?**
----

**Issue description**
----

用base64的方式载入瓦片，整个页面的性能下降的特别厉害，无论是移动还是缩放都非常卡
,我本认为是base64序列化的问题，测试了render一下时间，好像不是的

https://codepen.io/deyihu/pen/MMPXgz

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
看上去应该是canvas处理base64占用率比较高，每个瓦片的处理时间都在10ms左右，对主线程cpu占用还是挺大的，毕竟地图要流畅交互，每帧只有16ms

**Comment by deyihu** [comment]
@fuzhenn  
问题已经找到了，**图片质量的问题**
canvas.toDataURL('image/png');
序列化后的base64会将原始的图片质量放大 7-8倍 （16kb=> 112kb），**图片质量大导致maptalks.js内部 Canvas.image(ctx, img, x, y, width, height) 绘制消耗大量的时间，**

**只需要在 canvas.toDataURL 时控制一下图片质量即可，**
https://codepen.io/deyihu/pen/MMPXgz

```js
canvas.toDataURL('image/jpeg', 0.6)
```

虽然canvas.toDataURL => base64的处理时间会影响相关性能，但不是最主要的原因，我尝试了将 image的src写死了（相比较原始瓦片，这时的base64图片质量有被放大了7-8倍，而不是动态的去格式化base64,所有的image.src的都是相同，这时的base64序列化时间是可以忽略的），性能表现的还是不是很好
