### ISSUE TITLE
如何加载ArcGis的影像混合图(带中文标注)

### ISSUE THREAD

**Issue by yangyang158** [maptalks/maptalks.js#947]
[ArcGis地图](http://handfile.nandcloud.cn/group1/M00/00/1F/rBEC4l0i_-KACRKVAA-_INuYsvQ567.png)
影像图已经加载出来了， 但是获取矢量图的请求是这种格式的https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/10/404/828.pbf，应该怎么实现呢

**Comment by yangyang158** [comment]
利用 maptalks.mapboxgl 可以实现吗? 我试了有问题

**Comment by fuzhenn** [comment]
嗯对，mapboxgl插件应该能支持pbf瓦片的渲染，有什么问题？

**Comment by fuzhenn** [comment]
先关闭，如有后续问题，可以随时reopen
