### ISSUE TITLE
能做2.5D的geoJson吗

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.js#948]
**maptalks's version and what browser you use?**
----

**Issue description**
能做2.5D的geoJson吗
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
2.5D的geojson是指？

**Comment by MaJiaXuan** [comment]
@fuzhenn 
![image](https://user-images.githubusercontent.com/24503453/60935698-5e0f5700-a2fd-11e9-9b24-100c64ae7435.png)

**Comment by fuzhenn** [comment]
duplicate of #945
