### ISSUE TITLE
地图渲染和实时获取地图的json数据

### ISSUE THREAD

**Issue by YealZoy** [maptalks/maptalks.js#951]
**maptalks's version and what browser you use?**
v0.44.2

**Issue description**
# 第一个问题
我在geoserver上使用openlayer预览结果
![image](https://user-images.githubusercontent.com/10301073/61032298-be80c000-a3f3-11e9-9899-c8028aa03bf1.png)

我使用maptalk之后渲染的地图效果
![image](https://user-images.githubusercontent.com/10301073/61032404-f5ef6c80-a3f3-11e9-99c7-e2c5a624ea20.png)

地图上的label多了

# 第二个问题
我现在准备使用maptalks + maptalks.three 实现建筑物三维效果，有没有方法可以实时获取相关图层的json数据，然后进行创建3d建筑物。maptalk.three的例子 是一次性加载所有的建筑物数据，如果数据小还行，数据大的话就。。。。。。

# 第三个问题
有没有交流的qq群 微信群 钉钉群。。。。。。

god bless you

**Comment by fuzhenn** [comment]
您好！
* 第一个问题
是加载的geoserver的什么服务？是否有重现代码？
* 第二个问题
如果有大量数据加载，比较合适的是用矢量瓦片，但目前maptalks.three不直接支持矢量瓦片。矢量瓦片渲染插件正在开发中，过段时间会发布的。
* 第三个问题
qq群： 237726126

**Comment by YealZoy** [comment]
谢谢回复！
+ 第一个问题
加载的是wms服务;重现代码
```javascript
import * as THREE from 'three';
import * as maptalks from 'maptalks';
import 'maptalks/dist/maptalks.css';
import './styles/page.css';
let map = new maptalks.Map('map', {
  center: [116.3912822800,39.9074647400],
  //center:     [-0.113049,51.498568],
  zoom:  15,
  pitch : 45,
  zoomControl : true, // add zoom control
  scaleControl : true, // add scale control
  overviewControl : true, // add overview control
  baseLayer : new maptalks.WMSTileLayer('wms', {
    'urlTemplate' : 'http://192.168.130.64:8080/geoserver/china/wms',
    'crs' : 'EPSG:3857',
    'layers' : 'china:china_group',
    'styles' : '',
    'version' : '1.3.0',
    'format': 'image/png',
    'transparent' : true,
    'uppercase' : true
  }
});
```
+ 第二个问题
矢量瓦片渲染的插件可以说下大概的发布时间吗？

**Comment by fuzhenn** [comment]
* 关于第一个问题
看上去像是wms参数的问题，能否将同样的瓦片openlayers请求的参数，和maptalks请求的参数发在这里？谢谢！

**Comment by YealZoy** [comment]
+  geoserver 中的openlayer访问地址是  http://192.168.130.64:8080/geoserver/china/wms?service=WMS&version=1.1.0&request=GetMap&layers=china:china_group&bbox=73.4997347,8.8619574,134.7754563,53.5608154&width=768&height=560&srs=EPSG:4326&format=application/openlayers

+ maptalk的请求
```javascript
import * as THREE from 'three';
import * as maptalks from 'maptalks';
import 'maptalks/dist/maptalks.css';
import './styles/page.css';
let map = new maptalks.Map('map', {
  center: [116.3912822800,39.9074647400],
  //center:     [-0.113049,51.498568],
  zoom:  15,
  pitch : 45,
  zoomControl : true, // add zoom control
  scaleControl : true, // add scale control
  overviewControl : true, // add overview control
  baseLayer : new maptalks.WMSTileLayer('wms', {
    'urlTemplate' : 'http://192.168.130.64:8080/geoserver/china/wms',
    'crs' : 'EPSG:3857',
    'layers' : 'china:china_group',
    'styles' : '',
    'version' : '1.3.0',
    'format': 'image/png',
    'transparent' : true,
    'uppercase' : true
  }
});
```

难道是maptalk里的`format` 参数改为`application/openlayers`?

**Comment by fuzhenn** [comment]
maptalks请求的url是？能不能也帮忙打印一下，看看又没有什么不同

**Comment by fuzhenn** [comment]
http://192.168.130.64:8080/geoserver/china/wms?SERVICE=WMS&REQUEST=GetMap&LAYERS=china%3Achina_group&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&VERSION=1.3.0&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&BBOX=12956382.042450517,4855280.036674395,12958828.027355641,4857726.021579521

我这里打印的maptalks的请求url， 看上去version和crs不同，不知道这个有没有影响

**Comment by YealZoy** [comment]
我修改了一下我的参数配置如下,
添加了`spatialReference.projection`为`EPSG:4326`,
修改了`crs为EPSG:4326`,
`version为1.1.1`
```javascript
let map = new maptalks.Map('map', {
  center: [116.13493,39.91861],
  //center:     [-0.113049,51.498568],
  spatialReference:{
    projection: "EPSG:4326"
  },
  zoom:  14,
  pitch : 45,
  zoomControl : true,
  scaleControl : true,
  overviewControl : true,
  baseLayer : new maptalks.WMSTileLayer('wms', {
    'urlTemplate' : 'http://192.168.130.64:8080/geoserver/china/wms',
    'crs' : 'EPSG:4326',
    'layers' : 'china:china_group',
    'styles' : '',
    'version' : '1.1.1',
    'format': 'image/png',
    'transparent' : true,
    'uppercase' : true,
  })
});
```
我查看了一下请求参数
geoserver的openlayers请求参数为
![image](https://user-images.githubusercontent.com/10301073/62273547-64ae6b80-b470-11e9-95a0-48ca27031445.png)

maptalks的请求参数为
![image](https://user-images.githubusercontent.com/10301073/62273589-77c13b80-b470-11e9-8ca0-7f91b2da3f35.png)

但还是没有解决问题

@fuzhenn

**Comment by YealZoy** [comment]
是geoserver的问题
可以通过
+ 将瓦片的大小修改更大
+ 修改SLD，将标注改为以面的中心点进行标注  
[地址](https://www.jianshu.com/p/157f4d257ee9)
