### ISSUE TITLE
ImageLayer如何获取跨域图片

### ISSUE THREAD

**Issue by jerry000lin** [maptalks/maptalks.js#954]
maptalk 0.44.2

imageLayer中从argis获取了一张图片（另一个域），报错：

WebGl Failed to execute 'texImage2D' on 'WebGLRenderingContext'：the image element contains cross-origin data, and may not be loaded.

文档中imageLayer 有 api ：crossOrigin，但没有说明如何使用。

请问：除了直接将图片保存下来，我如何在maptalks里使用不同域名里的图片。

**Comment by fuzhenn** [comment]
crossOrigin只是用来设置image的[crossOrigin属性](https://developer.mozilla.org/zh-CN/docs/Web/HTML/CORS_enabled_image)的，需要服务器支持。
如果不需要三维功能，可以把 ImageLayer 的renderer设为canvas，它支持跨域。
如果需要三维，因为 webgl 的限制，目前ImageLayer无法直接支持跨域数据，一般需要从服务端想办法，例如创建CORS代理服务等。
