### ISSUE TITLE
imageLayer加载SVG图片失真

### ISSUE THREAD

**Issue by jerry000lin** [maptalks/maptalks.js#955]
maptalks0.44.2

作者你好，这边需要实现一个这样的需求：
在地图上足够大的区域（深圳市）上加载一个图片图层
通过的imageLayer实现该功能时，出现问题：
imageLayer加载SVG图片会失真严重，
通过修改svg的宽高改变svg图片的大小，得到的改变也不明显
当改到6144pt*3456pt时，加载的图层直接为全黑色

目前想到的解决方法是将svg上的形状用maptalks提供的接口重新绘制一次，这样做挺麻烦的。
是否有更好的解决方案。

**Comment by fuzhenn** [comment]
您好！
是否能提供一个重现代码？

**Comment by deyihu** [comment]
需要提供个复现代码
