### ISSUE TITLE
markerFile使用网络资源时报警告

### ISSUE THREAD

**Issue by yangyang158** [maptalks/maptalks.js#956]
markerFile使用网络地址时报警告
警告如下：
maptalks.es.js?ec60:5819 hit detect failed with tainted canvas, some geometries have external resources in another domain:
 DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at VectorLayerRenderer.hitDetect (webpack-internal:///./node_modules/maptalks/dist/maptalks.es.js:5886:34)
    at MapCanvasRenderer.hitDetect (webpack-internal:///./node_modules/maptalks/dist/maptalks.es.js:29856:61)
    at eval (webpack-internal:///./node_modules/maptalks/dist/maptalks.es.js:30246:14)

**Comment by fuzhenn** [comment]
如警告所示，markerFile资源跨域，造成 hit detect （设置鼠标样式）时，调用 canvas的getImageData 方法时失败。
这个问题会造成鼠标移动到图形上时，样式无法正常设置为pointer，如果不介意这个问题的话，可以不用处理。
如果要解决，修改服务端资源，允许跨域即可。

**Comment by yangyang158** [comment]
好的呢，谢谢，markerFile的图片是正方形的，有属性 可以设置成圆角吗

**Comment by fuzhenn** [comment]
目前没有这个设置，需要自己修改图片

**Comment by yangyang158** [comment]
好的，谢谢

**Comment by yangyang158** [comment]
作者您好，对于上面的警告，已经在服务器端设置了access-control-allow-origin:*，警告还存在
[如图](http://handfile.nandcloud.cn/group1/M00/00/1F/rBEC4l0xO1iAZbBuAAASyE6Pzgo340.png)
查了说要 设置 img.crossOrigin = ''

**Comment by fuzhenn** [comment]
在VectorLayer图层的options里设置一下 crossOrigin 即可
