### ISSUE TITLE
Render distance

### ISSUE THREAD

**Issue by markvex20** [maptalks/maptalks.js#957]
**maptalks's version and what browser you use?**
---- Chrome : Versión 75.0.3770.142 (Build oficial) (64 bits)
----maptalks: 0.44.2

**Issue description**
---- Its there a way to extent the field of view when the pitch is high and the zoom its high?
 i.e: When my zoom its 20 and the pitch 80 or near, i can extent the field of vision, the render distance or something?

**Please provide a reproduction URL (on any jsfiddle like site)**
----
I mean how to use this space to render more map and not only white space (the red line space)
![image](https://user-images.githubusercontent.com/52195645/61635197-4c319a80-ac93-11e9-9031-3edd45684397.png)

**Comment by fuzhenn** [comment]
Hi!
You can extend render distance by setting higher map's `maxVisualPitch` (default is 60) option.
However, you need to be careful with it which will increase tilelayer's tiles count dramatically.

**Comment by markvex20** [comment]
Thank you!
You are rigth, if i use a high number in "maxVisualPitch" value the tiles count its being affected as  the performance as well, wich one could be a good value to use the map in a mobile to get a good experience?
 Now im getting some visual problems not only performance ones...
How i can avoid that things?
![image](https://user-images.githubusercontent.com/52195645/61687582-11774300-ad23-11e9-86a4-76e805f218d6.png)

**Comment by fuzhenn** [comment]
That is an intended artifact. 

Because when map is tilted, to decrease the tile count to render, `TileLayer` uses a technique called cascaded tiles to render tiles of parent zoom (much less to cover the same area) in far distance.

You can turn off this feature by setting TileLayer's `cascadeTiles` option to `false`. You can also extend current's zoom's tiles' distance by increasing TileLayer's `minPitchToCascade` (default is 35).

**Comment by markvex20** [comment]
Thank  you for all, you helped a lot , i reopened it to ask a last question.
Its posible to set a maxpitch or limit it? Or you can only use "dragPitch" to disable/enable it? It would be nice if you could limit the pitch because if pitch is too high some layers lose the vision

**Comment by fuzhenn** [comment]
You are welcome.
To limit map's max pitch, you can simply set map's `maxPitch` option to a favored value (default is 80).

**Comment by markvexiza** [comment]
Hello again! I'll reuse this post to ask something again. Its possible to increase the max zoom of the map more than 20?
