### ISSUE TITLE
[Feature request] Class: Coordinate  add class parameter data format

### ISSUE THREAD

**Issue by ghost** [maptalks/maptalks.js#958]
**maptalks's version and what browser you use?**
----
0.44.2

**Issue description**
----
add class parameter data format , eg: `{ lng: 0 , lat: 0 }` `{ latitude: 0, longitude: 0 }`. If you confirm this feature , I can create a pull request, include code and document.

**Please provide a reproduction URL (on any jsfiddle like site)**
----
Coordinate class document:   https://maptalks.org/maptalks.js/api/0.x/Coordinate.html

**Comment by deyihu** [comment]
你可以自定义函数来实现这个功能，Coordinate是底层的类，不可太灵活，目前Coordinate的构造函数已经挺复杂了，加更多格式的支持容易出bug,且ts type也不好定义（越灵活，type越复杂）

在我看来一个Util的事情，这个感觉不需要做到标准库里

```js
function toCoordinate(obj){
   return new Coordinate(obj.lng,obj.lat);
}

function toObject(coordinate){
  return {
        lng:coordinate.x,
       lat:coordinate.y
   }
}

```
