### ISSUE TITLE
[feature] 支持自定义svg图标集

### ISSUE THREAD

**Issue by ageeye-cn** [maptalks/maptalks.js#960]
目前symbol使用svg图标时，需要将很长的svg代码设置为参数，希望能在地图初始化和运行过程中，自定义管理svg图标集，这样支持直接使用图标名称添加svg图标。

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.js/pull/1860

**Comment by deyihu** [comment]
close by https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/releases/1_0_0_rc_34.html#%E5%8A%A0%E8%BD%BDiconfont%E5%9B%BE%E6%A0%87%E5%BA%93
