### ISSUE TITLE
地图大级别抖动问题

### ISSUE THREAD

**Issue by Phlicess** [maptalks/maptalks.js#964]
**maptalks's version and what browser you use?**
----
最新版本，Chrome 最新版本浏览器

**Issue description**
----
投影坐标：
在 WebGL 里面只支持 Float32 类型的精度，据我了解，这个精度对于墨卡托投影来说是远远不够的，
也看了很多业界的文章，比如：https://zhuanlan.zhihu.com/p/57469121 等等，我想找一种更简单的方案处理这种问题，因此就看到了 Maptalk 的源码。我看到了 getGLScale 在 ImageGLRenderable 文件和 TileLayerGLRender 文件里面，但是没有弄懂您怎么能做到在地图的大级别下（zoom: 18，19）的时候，没有因为精度丢失问题导致的平移或者旋转等造成的抖动问题。
**Please provide a reproduction URL (on any jsfiddle like site)**
----
 ```drawTile(tileInfo, tileImage) {
        const map = this.getMap();
        if (!tileInfo || !map) {
            return;
        }
        if (tileImage.src === emptyImageUrl) {
            return;
        }
        console.log('tileInfo', tileInfo);

        const scale = map.getGLScale(tileInfo.z),
            w = tileInfo.size[0] * scale,
            h = tileInfo.size[1] * scale;
        if (tileInfo.cache !== false) {
            this._bindGLBuffer(tileImage, w, h);
        }
        if (!this._gl()) {
            // fall back to canvas 2D
            super.drawTile(tileInfo, tileImage);
            return;
        }
        const point = tileInfo.point;
        const x = point.x * scale,
            y = point.y * scale;
        const opacity = this.getTileOpacity(tileImage);
        this.drawGLImage(tileImage, x, y, w, h, opacity);

        if (opacity < 1) {
            this.setToRedraw();
        } else {
            this.setCanvasUpdated();
        }
    }
```

**Comment by fuzhenn** [comment]
您好，很开心有同行讨论技术问题。

直接采用墨卡托坐标，它的值范围较大，所以float32会有精度问题。

maptalks里是采用 maxNativeZoom / 2 的墨卡托坐标作为世界坐标，这个值一般变化范围很小，再用float32(甚至int16)都不存在精度问题了。

瓦片的坐标因为本身比较特殊，它的顶点值在pow(2, n)的瓦片体系中永远都是整数，所以直接按照比例缩小它再还原是不会存在误差的，所以不会存在误差导致的抖动。

这个问题并不是maptalks的bug，我就先关闭了。

**Comment by Phlicess** [comment]
多谢，可能我还需要找新的方案，因为我需要绘制矢量瓦片，只有每个瓦片级别的 P10 坐标，精度应该是不够的。
