### ISSUE TITLE
polygon gradient fill 设置在图形将要移出视野时失效（或者与预期不符）

### ISSUE THREAD

**Issue by sakitam-fdd** [maptalks/maptalks.js#967]
**maptalks's version and what browser you use?**
----
maptalks: v0.44.2
Chrome: 75.0.3770.142
**Issue description**
----
![image](https://user-images.githubusercontent.com/19517451/61928096-e3effb00-afa9-11e9-8405-e066f92f21ae.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/sakitam-fdd/pen/dxpVLm

**Comment by fuzhenn** [comment]
这个问题目前暂时无法解决，因为VectorLayer是通过转换，把三维图形用二维api来绘制的，所以无法准确的计算gradient的参数。
等webgl图层发布后，就能准确实现了。
