### ISSUE TITLE
定义了很多marker在地图上 有很多分类 怎么根据分类进行显隐呢

### ISSUE THREAD

**Issue by adevin** [maptalks/maptalks.js#968]
**maptalks's version and what browser you use?**
----

**Issue description**
----
单独显示一个分类 或者 几个分类。 怎么拿到地图上面的marker呢

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by SimpleYong** [comment]
layer.filter(marker => marker.getProperties().type == 1).forEach(marker => marker.hide())
你描述的是这个意思吗

**Comment by adevin** [comment]
> layer.filter(marker => marker.getProperties().type == 1).forEach(marker => marker.hide())
> 你描述的是这个意思吗

厉害 老哥

**Comment by adevin** [comment]
> layer.filter(marker => marker.getProperties().type == 1).forEach(marker => marker.hide())
> 你描述的是这个意思吗

还有就是怎么显示出来呢 把隐藏的

**Comment by SimpleYong** [comment]
marker.show()
