### ISSUE TITLE
在聚合的效果下，如果Marker设置为hide，聚合怎么设置只计算show的数量

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.js#969]
**maptalks's version and what browser you use?**
----

**Issue description**
在聚合的效果下，如果Marker设置为hide，聚合怎么设置只计算show的数量？
比如把一个marker隐藏了，那么这个时候聚合就不需要计算被隐藏的marker；反则计算显示的marker
![image](https://user-images.githubusercontent.com/24503453/62106142-0437f680-b2d7-11e9-91bb-22e207137e51.png)

----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
您好，这个问题属于cluster插件的问题，我转到那边去了

https://github.com/maptalks/maptalks.markercluster/issues/18

**Comment by fuzhenn** [comment]
该问题已经解决，marker show hide后，会重新计算cluster数量并重新绘制

把maptalks.cluster插件更新到 `0.8.3` 版即可
