### ISSUE TITLE
Bouncing back at world level

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.js#970]
**maptalks's version and what browser you use?**
----
v0.44.2

**Issue description**
----
Bouncing back seems to have some problem at world level.
Sometimes map will be bounced back to a position like below:
![image](https://user-images.githubusercontent.com/13678919/62271169-886eb300-b46a-11e9-80a3-51ca37e9f221.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by treasureMoment** [comment]
在地图低级别下。开启repeat y, 上下回弹会出现错误的位置

**Comment by fuzhenn** [comment]
should be fixed by #985 

修改了bouncing back的实现逻辑
