### ISSUE TITLE
Zoom higher than 20

### ISSUE THREAD

**Issue by markvex20** [maptalks/maptalks.js#971]
**maptalks's version and what browser you use?**
---- Chrome : Versión 75.0.3770.142 (Build oficial) (64 bits)
----maptalks: 0.44.2

**Issue description**
Its there a possibility to increase the zoom more than 20? Im using maptalks with maptalks three and i need to increase the zoom to place the camera near the obj loaded. Its there a posibility to increase to 21 more or less?

**Comment by fuzhenn** [comment]
Sure you can, you need to create a customized spatial reference to set any zoom system you need.
[example](https://maptalks.org/examples/en/tilelayer-projection/custom-tile/)
