### ISSUE TITLE
怎么在地图上删除自定义的UI

### ISSUE THREAD

**Issue by adevin** [maptalks/maptalks.js#974]
```javascript
let options = {
	'autoOpenOn' : 'null',  //set to null if not to open window when clicking on map
	'single' : false,
	'width'  : 150,
	'height' : 90,
	'custom' : true,
	'dx' : 0,
	'dy' : 0,
	'content':
		'<div x="'+ item.coor.x +'"  y="'+ item.coor.y +'" districtCode="'+ item.districtCode +'"  class="person-card-container animated  rubberBand delay-1s">' +
			'<div class="left">' +
				'<span>'+ item.district +'</span>' +
				'<i>在线人员</i>' +
			'</div>' +
			'<div class="right">' +
			'	<span>'+ item.streetPersonCount +'</span>' +
			'</div>' +
		'</div>'
};

let infoWindow = new maptalks.ui.InfoWindow(options);
infoWindow.addTo(map).show(item.coor);
```

**Comment by adevin** [comment]
把自定义的提示框放到一个层。 然后删掉这个层 不管用。 layer.remove() 方法 没反应

**Comment by liubgithub** [comment]
看你的代码，infoWindow是加到map上了,不是加到layer图层上。建议不管加到哪，直接调用infowindow的remove方法。https://maptalks.org/maptalks.js/api/0.x/ui.InfoWindow.html#remove

**Comment by fuzhenn** [comment]
如 @liubgithub 所说，InfoWindow和layer没有关系，直接调用它本身的remove方法即可

**Comment by adevin** [comment]
> 看你的代码，infoWindow是加到map上了,不是加到layer图层上。建议不管加到哪，直接调用infowindow的remove方法。https://maptalks.org/maptalks.js/api/0.x/ui.InfoWindow.html#remove

我的意思是我已经尝试过 加在map上 调动remove方法 和加入layer上调用layer.remove 方法 都不管用。 而且我建的threeLayer层 调用threelayer.remove() 也不管用。但方法确实执行了

**Comment by adevin** [comment]
> 看你的代码，infoWindow是加到map上了,不是加到layer图层上。建议不管加到哪，直接调用infowindow的remove方法。https://maptalks.org/maptalks.js/api/0.x/ui.InfoWindow.html#remove
这个我直接找到DOM元素 然后直接清空里面的DOM解决了。调remove无效。但threelayer层怎么删除？？
```
let layer = new ThreeLayer('problemRegionLayer', {
					forceRenderOnMoving: true,
					orceRenderOnRotating: true,
					animation: true
				})
layer.addTo(this.map)
this.mapLayer = layer;

******

this.mapLayer.remove() // 这个失效 不管用
this.map.removeLayer(this.mapLayer) // 这个也失效 不管用
```

**Comment by liubgithub** [comment]
我已经跟你说的很清楚了，调用infoWindow的remove方法，infoWindow.remove().  为什么你要调用图层的remove. this.mapLayer.remove(),this.mapLayer.remove(). 不太理解？

**Comment by fuzhenn** [comment]
@adevin 

我这里没能重现ThreeLayer无法用remove删除的问题，方便提供一个重现代码吗？

发现bug后可以基于example中的编辑功能提供重现代码，方便我们快速定位问题，大部分时候光靠用户的文字描述， 我们很难准确的理解和重现bug，谢谢！
