### ISSUE TITLE
Distorted Image Layer

### ISSUE THREAD

**Issue by dploeger** [maptalks/maptalks.js#980]
Maptalks version: maptalks v0.44.2
Codepen-Example: https://codepen.io/anon/pen/ZgaMaP

We'd like to use Maptalks to navigate a building based on image layers. Maybe I don't understand the concept here.

I tried to add an Imagelayer with the image with the extents set to the image's original dimensions.

However, this shows a highly distorted image (please see [this Pen](https://codepen.io/anon/pen/ZgaMaP))

Do I need to change an option for this to work or am I getting something wrong here?

**Comment by fuzhenn** [comment]
Hi, @dploeger , welcome for submiting issue.

It's because the extent's unit is not `pixel` but geographic `degree`.

You can see [this pen](https://codepen.io/fuzhenn-the-decoder/pen/VorRbR).

**Comment by fuzhenn** [comment]
May be useful to mention:

If you don't want to use longtitude/latitude to position your data, you can change map's spatial reference to plain `identity` which uses a simple cartesian coordinate system. It's should be much more easier for positioning data in a local coordinate system like inside a building.

You can see [the example](https://maptalks.org/examples/en/tilelayer-projection/identity/) for more details.

**Comment by dploeger** [comment]
Hey, thanks so much. I knew I didn't get that right. I'm just missing all the geographical theory background. 😄 

I will go with the mapping to `identity` now.
