### ISSUE TITLE
百度底图设置下，集成deck.gl

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/maptalks.js#981]
spatialReference:{
            projection : 'baidu'
          }
设置下，是否无法集成deck.gl？目前会出现偏移不同步，缩放偏大等问题
![image](https://user-images.githubusercontent.com/19590233/62523028-83907180-b865-11e9-99ce-3bde2db56156.png)

相关的一个issue https://github.com/uber/deck.gl/issues/745

**Comment by fuzhenn** [comment]
参考那个issue中ibgreen的回复。
因为deck.gl的坐标偏转算法是写在shader中的，所以按我的理解，deckgl目前很难和百度地图集成

**Comment by deyihu** [comment]
@The-End-Hero 

**这个问题我刚才试了一下，百度地图和deckgl是可以结合的**

首先WGS84（mapbox,bing,cartodb,天地图等）的和deckgl结合，就像@fuzhenn说的那样，zoom差值为1，

高德等（tencent,google.cn ....）的和deckgl需要将 WGS84的坐标转化为火星,zoom差值也是为1，

**百度的结合稍微有点特殊，首先将WGS84转为 BD09,我测试了一下 zoom的差值为 1.75左右**

我用maptalks和deckg.gl结合分别测试了 高德和百度都是可以的

https://deyihu.github.io/src/maptalks-deckgl/examples/amap.html

https://deyihu.github.io/src/maptalks-deckgl/examples/baidu.html


为了验证正确性，而后我用百度地图sdk和deck.gl结合测试了一下，zoom的差值也为1.75左右

https://codepen.io/deyihu/pen/RXeJWB

另外 坐标互转 这个库
https://github.com/hujiulong/gcoord
应该可以帮到你

https://github.com/uber/deck.gl/issues/745

**Comment by fuzhenn** [comment]
感谢 @deyihu 的解答！ 既然问题已得到解答，关闭该issue
