### ISSUE TITLE
鼠标双击事件

### ISSUE THREAD

**Issue by zhangming2266** [maptalks/maptalks.js#982]
**maptalks's version and what browser you use?**
version 0.44.2

**Issue description**
//地图双击事件
map.on('dblclick', function(param) {
    console.log('dblclick', param);
});
//地图单击事件
map.on('click', function(param) {
    console.log('click', param);
});
地图同时注册双击和单击事件，但是鼠标双击两次，每次还是会先触发单击事件两次，在触发双击事件。
正确情况应该是当鼠标双击的时候只应该响应双击事件，不应该响应单击事件了。

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by sakitam-fdd** [comment]
@zhangming2266 双击时响应两次单击事件是符合预期的，如果不想响应的话处理一下：
```js
getClickHandler(onClick, onDblClick, delay) {
        let timeoutID = null;
        delay = delay || 250;
        return function (event) {
          stopPropagation(event && event.domEvent);
          if (!timeoutID) {
            timeoutID = setTimeout(() => {
              onClick(event);
              timeoutID = null;
            }, delay);
          } else {
            timeoutID = clearTimeout(timeoutID);
            onDblClick(event);
          }
        };
      }

xxx.on('click', getClickHandler(handleClick, handleDBClick), this)
```

**Comment by zhangming2266** [comment]
@sakitam-fdd   嗯，知道了，这个的方式可以。

**Comment by fuzhenn** [comment]
感谢 @sakitam-fdd 的解答！
已解决，关闭issue。
