### ISSUE TITLE
请问ExtrudePolygonLayer图层是否支持点击获取geojson对象

### ISSUE THREAD

**Issue by zhuli0905** [maptalks/maptalks.js#983]
你好，我现在使用geojson格式渲染出楼宇，是否可以点击获取单个楼宇对象。
   谢谢

**Comment by fuzhenn** [comment]
sorry，目前ExtrudePolygonLayer没有提供该功能，另外ExtrudePolygonLayer是一个实验性插件，已经停止开发。

您可以转用 [maptalks.three](https://github.com/maptalks/maptalks.three) 插件实现该功能

**Comment by zhuli0905** [comment]
好的，谢谢
