### ISSUE TITLE
TileLayer 在大分辨下刷新问题

### ISSUE THREAD

**Issue by zhangming2266** [maptalks/maptalks.js#984]
**maptalks's version and what browser you use?**
0.44.2

**Issue description**
TileLayer 在大分辨下刷新，总是将图层先清空，然后在慢慢加载。
高德，百度等其它地图是不会将现有的地图清空，只是不断刷新需要加载的地图。

**Please provide a reproduction URL (on any jsfiddle like site)**
可以通过改变浏览器的缩放比例重现。
将浏览器的缩放比更改为25%， maptalk地图TileLayer图层就会出现将图层先清空，然后在慢慢加载。

也可以在大分辨的屏幕上复现，例如8k屏幕或更大。

**Comment by fuzhenn** [comment]
首先谢谢提issue。

不过我还没有完全get到，具体是怎样一种现象？ 

如果具体描述不方便的话，可以加qq群(237726126)发个录屏

**Comment by wang2lang** [comment]
有可能跟这个情况一样 [1262](https://github.com/maptalks/maptalks.js/issues/1262)
