### ISSUE TITLE
墨卡托坐标系在2层级地图时。因为不想拖动到180度以外的范围，但是是限制不了地图范围。 

### ISSUE THREAD

**Issue by gy001302** [maptalks/maptalks.js#985]
墨卡托坐标系在2层级地图时。因为不想拖动到180度以外的范围，但是发现限制不了地图范围。 var map = new maptalks.Map('map', {
    center: [-0.113049, 51.498568],
    zoom: 3.2,
    minZoom: 3,
    centerCross: false,
    dragPitch: false,
    dragRotate: false,
    ....
})

map.setMaxExtent(new maptalks.Extent(-160, -75, 160, 75));

**Comment by fuzhenn** [comment]
这是因为地图有repeatWorld机制，拖动地图时，中心点会在相邻的repeatWorld里的坐标是在你设置的合法范围内的，就不做限制了。

我想你需要的是只要中心点超出当前world的给定范围，就应该做限制，这也更合理，我会修改一下这个问题。
