### ISSUE TITLE
支持蚂蚁金服的L7吗？

### ISSUE THREAD

**Issue by wefiy** [maptalks/maptalks.js#986]
https://antv.alipay.com/zh-cn/l7/1.x/index.html

**Comment by fuzhenn** [comment]
谢谢提issue。

L7本身只支持高德地图，要支持maptalks上需要fork一份做些修改。

后续如果我们做了适配会更新这个issue的，目前先关闭，谢谢。

**Comment by yanyu510** [comment]
https://github.com/yanyu510/L7/tree/maptalks

**Comment by yanyu510** [comment]
我做了maptalks适配，可以看看。
