### ISSUE TITLE
marker setTimeout animation

### ISSUE THREAD

**Issue by Leijiawei** [maptalks/maptalks.js#989]
I want to set many markers animate in turn.

![QQ图片20190906154107](https://user-images.githubusercontent.com/11434308/64410084-d8b9e000-d0bc-11e9-916e-bf5b9caec7d0.png)

Is the attribute startTime to resolve this problem?

thanks

**Comment by fuzhenn** [comment]
reproduction code：

https://codepen.io/leijiawei/pen/bGbaLap?&editable=true

**Comment by fuzhenn** [comment]
Yes, startTime is the option you need.

By setting proper `startTime`, you can animate markers one by one:
```js
const now = Date.now();
const startTime = now + 1000; //1 second later
```
