### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by liuxinqiong** [maptalks/maptalks.js#991]
技术选择：maptalks + maptalks.three

需求：在现有场景上，加上地图作为底图

想请教的问题
1. 现有项目使用米字坐标进行 3d 渲染，要加上地图是否只能选择转成经纬度坐标吗？可否通过设置一个经纬度中心点，然后继续使用米字坐标呢
2. 相机只能是透视相机吗？可否在透视和正交中做选择
3. 使用 LightHelper、AxesHelper、CameraHelper 查看位置，我蒙圈了，能介绍一下这三个东西的 Position 么？

感谢

**Comment by fuzhenn** [comment]
已在群里得到解答，先关闭
