### ISSUE TITLE
cesium scene default mode is Cesium.SceneMode.COLUMBUS_VIEW

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#994]
**maptalks's version and what browser you use?**
----

**Issue description**
----

rep: https://github.com/fuzhenn/maptalks.cesium

I think that when Cesium's Scene mode is Cesium.SceneMode.COLUMBUS_VIEW, it is more similar to the current maptalksde 2.5d mode.

When the map is zoomed out instead of a ball

![20190909173345](https://user-images.githubusercontent.com/25998927/64520114-08205500-d328-11e9-8e7f-11fb0bb84b2a.png)

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
Thanks!

Could you make a PR to [maptalks.cesium plugin](https://github.com/fuzhenn/maptalks.cesium)?

**Comment by deyihu** [comment]
I want

But COLUMBUS_VIEW has some problems in camera synchronization at present.

Of course, at present SCENE3D, camera synchronization is also a problem.



![20190911150654](https://user-images.githubusercontent.com/25998927/64676951-37aa9b00-d4a9-11e9-9d86-c39e3ee332b2.png)
![20190911150735](https://user-images.githubusercontent.com/25998927/64676952-39745e80-d4a9-11e9-828f-755ce3c9b62f.png)

**Comment by fuzhenn** [comment]
COLUMBUS_VIEW  seems to be promising, I'll find some time window to have a look at this.

另外，你有兴趣参与maptalks.three插件的维护吗？有兴趣的话我把你加到maptalks.three的collaborator里。

**Comment by deyihu** [comment]
目前的SCENE3D 也是有问题的

可以啊 :smile: 
maptalks.three插件，我可以参与维护一下，不过我不是每天都有很充裕的时间。

另外如果我参与维护three.js插件的话，我可能主要侧重添加更多的功能，比如 柱子，线，点，动画等

**Comment by fuzhenn** [comment]
👍 给你发邀请了~
只要不影响原有功能，什么新功能都可以 😆 
另外我给master设了分支保护，新的代码都需要用pr来提交，我们相互之间做一下审核后再合并。
