### ISSUE TITLE
绘制工具和测距、测面工具结合使用时，出现的问题

### ISSUE THREAD

**Issue by Evenssi** [maptalks/maptalks.js#995]
**maptalks's version and what browser you use?**
----
maptalks v0.44.2

**Issue description**
----
把绘制工具和测距等工具一起作为工具栏的时候，如果先测距/测面，后面再使用画点、线......的时候，也会有距离/面积的显示。想知道怎么在标记点的时候，测距等被禁用呢？

**Comment by fuzhenn** [comment]
调用 drawTool.disable() 就行了

**Comment by Evenssi** [comment]
> 调用 drawTool.disable() 就行了

调用这个的画，不是就

> 调用 drawTool.disable() 就行了

谢谢，调整了一下，已经解决了~

**Comment by Evenssi** [comment]
> 调用 drawTool.disable() 就行了

谢谢，已经解决了。
