### ISSUE TITLE
polygon在编辑状态下无法响应dblclick事件

### ISSUE THREAD

**Issue by zhouzhili** [maptalks/maptalks.js#996]
**maptalks's version and what browser you use?**
----
maptalks's version：v0.44.2
browser ：Google Chrome：76.0.3809.132

**Issue description**
----
polygon在startEdit状态下无法响应dblclick事件，无法在双击后结束编辑

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://codepen.io/zhili124/pen/WNezRJE?editors=0111

**Comment by sakitam-fdd** [comment]
@zhouzhili 这个问题在于你先开启的 `startEdit` 后绑定的事件，默认 Geometry 在开启 `startEdit` 后会 [copy 事件](https://github.com/maptalks/maptalks.js/blob/master/src/geometry/editor/GeometryEditor.js#L122), 但此时你还没有绑定事件，所以处于编辑态的图形并没有绑定事件。

暂时解决方案：可以将 `geo.startEdit();` 放到事件绑定完毕后执行。

BTW: 是否需要考虑在原图形事件、属性、空间信息变化后进行同步 @fuzhenn ，感觉这样操作流好像被打破了

**Comment by fuzhenn** [comment]
确实，事件绑定应该在startEdit前完成。

为了提升编辑时的性能，geometry会在编辑时，克隆一个shadow单独添加到一个内部图层上用于编辑，所以编辑开始后的事件注册，shadow就无法获取到了。

两相取舍的话，这个问题应该不会带来太大的困扰，我觉得先暂时保持现有的模式。
