### ISSUE TITLE
Map zoom center point is incorrect after the map is set to the maximum range（maxExent）

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#997]
**maptalks's version and what browser you use?**
----

**Issue description**
----

Map zoom center point is incorrect after the map is set to the maximum range（maxExent）

https://codepen.io/deyihu/pen/gJbVeM

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
sorry，没有发现有什么异常，能否再详细说明一下？

**Comment by fuzhenn** [comment]
另外我们有个qq群，欢迎来加：237726126

**Comment by deyihu** [comment]
可以左右拖拽地图试试，当地图在动画平移的过程ing,立刻缩放地图这时就会出现问题了

**Comment by fuzhenn** [comment]
should be closed with #1000
