### ISSUE TITLE
获取 rotate 旋转参数

### ISSUE THREAD

**Issue by luosijie** [maptalks/maptalks.js#998]
请问maptalks如何获取旋转参数呢
或者 有没有开放 类似指南针的控件

**Comment by fuzhenn** [comment]
旋转参数可以用下面的方法获取。
`map.getBearing()`
`map.getPitch()`

目前还没有指南针控件，有兴趣一起做一个吗？

**Comment by deyihu** [comment]
@luosijie 

https://github.com/cXiaof/maptalks.control.compass
