### ISSUE TITLE
Disable map Interaction Not Working on Mobile Device

### ISSUE THREAD

**Issue by markvex20** [maptalks/maptalks.js#999]
**Issue description**
Disable map interaction not working:
`  draggable: false, //disable drag
  dragPan: false, //disable drag panning
  dragRotate: false, //disable drag rotation
  dragPitch: false, //disable drag pitch
  scrollWheelZoom: false, //disable wheel zoom
  touchZoom: false, //disable touchzoom
  doubleClickZoom: false, //disable doubleclick zoom` 
This all options are set to false but when you open it in a mobile browser map stills being able to  dragPitch and zoomed with two fingers.

Tested phone: Samsung s8 plus (Android 9) | Xiaomi mi5s (Android 6.0.1)

**Please provide a reproduction URL (on any jsfiddle like site)**
Just open this on any mobile device -> [https://maptalks.org/examples/en/interaction/map-off/#interaction_map-off](url)
and try to intenteract with the map with two fingers

**Comment by fuzhenn** [comment]
Thanks! Will fix this in the next release

**Comment by fuzhenn** [comment]
This is not a bug, you need to disable `touchRotate` and `touchPitch` instead.
```js
touchRotate: false,
touchPitch: false
```
